### ISSUE TITLE
gpgkeys: key 8B3981E7A6852F782CC4951600A6F0A3C300EE8C can't be retrieved

### ISSUE THREAD

**Issue by rasekar2000** [nginxinc/docker-nginx#100]
Step 4 : RUN add-apt-repository -y ppa:nginx/stable &&   apt-get update &&   apt-get install -y nginx &&   rm -rf /var/lib/apt/lists/*
 ---> Running in 826679b8d073
gpg: keyring `/tmp/tmp8s8y1j0i/secring.gpg' created
gpg: keyring `/tmp/tmp8s8y1j0i/pubring.gpg' created
gpg: requesting key C300EE8C from hkp server keyserver.ubuntu.com
**gpgkeys: key 8B3981E7A6852F782CC4951600A6F0A3C300EE8C can't be retrieved**
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Can you please suggest a resolution?

Regards,
Raj

**Comment by thresheek** [comment]
No, this is not our key nor this is our code.
