### ISSUE TITLE
unmet dependencies:      nginx-module-geoip : Depends: nginx (= 1.11.1-1~jessie)

### ISSUE THREAD

**Issue by mattqs** [nginxinc/docker-nginx#102]
See detail at http://stackoverflow.com/questions/38083191/docker-build-nginx-unmet-dependencies

**Comment by mattqs** [comment]
Used wrong dockerfile.

**Comment by andrewmclagan** [comment]
Hmm elaborate? sorry, just experiencing the same issue...

**Comment by mattqs** [comment]
I used a previous version of the dockerfile. This one [https://github.com/nginxinc/docker-nginx/blob/master/stable/jessie/Dockerfile](https://github.com/nginxinc/docker-nginx/blob/master/stable/jessie/Dockerfile) worked fine.
