### ISSUE TITLE
nginx hangs due to weird state of access/error logs

### ISSUE THREAD

**Issue by whitlockjc** [nginxinc/docker-nginx#107]
I apologize for the wording of the issue subject but I have no better way to describe it.  I am currently trying to rebuild [k8s-router](https://github.com/30x/k8s-router/blob/master/Dockerfile) using `nginx:stable-alpine` instead of `gcr.io/google_containers/nginx`.  _(The issue seems to happen with `nginx:stable` as well.)_  Building the Docker image works fine but when I run my application, once I start `nginx` the application halts without an error or anything.  My first thought was to `cat /var/log/nginx/error.log` on the running container but it hangs too.  For grins I tried `cat /etc/nginx/nginx.conf` on the running container and it ran fine.  Something seemed off with the log files in `/var/log/nginx` so I tried one more thing.  I ran my container with `sh` as the entry point, deleted the log files, recreated them using `touch` and fired up my application.  This time, the application ran as expected and did not hang after `nginx` was ran.  All my application does is run `nginx` at startup and then uses `nginx -s reload` to reload the configuration whenever necessary.

I'm not sure what the real cause is but you can reproduce this using `docker run --name nginx-stable -it --rm cat /var/log/nginx/access.log`.  Instead of `cat` returning, it just hangs.  Run `docker run --name nginx-stable -it --rm cat /etc/nginx/nginx.conf` and it runs just fine.

Also, for posterity, here is the `Dockerfile` I'm building with:

```
FROM nginx:stable-alpine

MAINTAINER Jeremy Whitlock <jwhitlock@apache.org>

LABEL Description="A general purpose router for Kubernetes."

# Install CA Certificates
RUN apk add --update --no-cache ca-certificates
RUN update-ca-certificates

COPY k8s-router /

CMD ["/k8s-router"]
```

**Comment by thresheek** [comment]
/var/log/nginx/access.log and error.log are symlinks to /dev/stdout and /dev/stderr respectively.  cat does not "hang", it just waits for some output.

**Comment by whitlockjc** [comment]
That makes sense.  I guess when Go is trying to spawn `nginx`, it just appears to hang because of this.  Do you have any suggestions on handling this?  I could just handle this in my `Dockerfile` but as that being the naive approach, I'd welcome any suggestions.

**Comment by whitlockjc** [comment]
I could also handle this in code by using `Command#Start` instead of `Command#CombinedOutput`.  This looks like it's not necessarily a container issue so I will close this myself.  Thanks for helping me out.

**Comment by whitlockjc** [comment]
For those that run into this later, here is how I modified my code to use `exec.Command#Start` and `exec.Command#Wait` in place of `exec.Command#CombinedOutput` to work around this:

```diff
diff --git a/nginx/server.go b/nginx/server.go
index a89d95d..15b35ed 100644
--- a/nginx/server.go
+++ b/nginx/server.go
@@ -8,16 +8,18 @@ import (
 	"os/exec"
 )
 
-func shellOut(cmd string, exitOnFailure bool) {
+func shellOut(cmdStr string, exitOnFailure bool) {
 	// If we are running outside of Kubenetes, KUBE_HOST will be set in which case we do not want to start nginx
 	if os.Getenv("KUBE_HOST") != "" {
 		return
 	}
 
-	out, err := exec.Command("sh", "-c", cmd).CombinedOutput()
+	cmd := exec.Command("sh", "-c", cmdStr)
+	err := cmd.Start()
 
 	if err != nil {
-		msg := fmt.Sprintf("Failed to execute (%v): %v, err: %v", cmd, string(out), err)
+		out := cmd.Wait()
+		msg := fmt.Sprintf("Failed to execute (%v): %v, err: %v", cmdStr, out, err)
 
 		if exitOnFailure {
 			log.Fatal(msg)
```

Now I just need to figure out the best way to allow me to get real log files and we'll be set, but that isn't you problem.  Thanks again.

**Comment by thresheek** [comment]
Thanks Jeremy!
