### ISSUE TITLE
Lua Image

### ISSUE THREAD

**Issue by ahawkins** [nginxinc/docker-nginx#11]
Any possibility of providing an image with lua support? I've got a `Dockerfile` if interested.

**Comment by mattbailey** [comment]
:+1:

Would be really handy, even if just for injecting env vars into a custom nginx.conf

**Comment by hacfi** [comment]
@ahawkins Can you please create a gist so other can use it if this issue is rejected?

**Comment by thresheek** [comment]
Closing as a duplicate for https://github.com/nginxinc/docker-nginx/issues/14
