### ISSUE TITLE
nginx:alpine has a core dump embedded in it

### ISSUE THREAD

**Issue by oogali** [nginxinc/docker-nginx#119]
I was examining the Docker image for mainline, and it seems there's an 8MB core file in the image.

![image](https://cloud.githubusercontent.com/assets/232224/17857248/fdf47350-684e-11e6-85fb-ee9aff6f9ebf.png)

In addition to deleting it, I'm assuming "core" and any other relevant patterns should be added to `.dockerignore`.

**Comment by thresheek** [comment]
It looks like an artifact produced by the builds of the image on Docker inc side.

Not sure how .dockerignore will help in this case - there is no core file ADDed from the context of the git repo.

**Comment by oogali** [comment]
Oof. Maybe `ulimit -Sc 0` should be added at the start of the build process to avoid emitting a core file?

Or if someone wants to examine it, during build, change the sysctl variable `kernel.core_pattern`, to point to a volume where it's emitted without being stored in the image?

**Comment by thresheek** [comment]
Maybe.  Paging @tianon!

**Comment by yosifkit** [comment]
This is the same issue as https://github.com/tianon/docker-brew-ubuntu-core/issues/55.  The core file appeared on the `addgroup` layer, so it should go away once we rebuild the image off of alpine:3.4 (since that will bust any build cache on the server).

**Comment by thresheek** [comment]
Fixed by https://github.com/docker-library/official-images/pull/2084
