### ISSUE TITLE
install ca-certificates

### ISSUE THREAD

**Issue by mathroc** [nginxinc/docker-nginx#12]
I've seen a few images (eg: https://github.com/jwilder/nginx-proxy) having to install ca-certificates on their images to configure SSL/ this means they have to `apt-get update && apt-get install ... && rm -rf /var/lib/apt/lists/*`.

it would simplify things if ca-certificates was installed by default as it seems it's a useful package for nginx

would you consider adding it into the image?

**Comment by thresheek** [comment]
Thank you @mathroc, this makes sense indeed.

Fixed and pushed.

**Comment by hacfi** [comment]
:+1: cool

**Comment by wesm-outreach** [comment]
Did this change get dropped? I don't see this in stable or mainline as of recent.

https://github.com/nginxinc/docker-nginx/blob/1d2e2ccae2f6e478f628f4091d8a5c36a122a157/stable/stretch/Dockerfile

**Comment by ghostsquad** [comment]
Did this change get dropped? I don't see it in current mainline or stable.

https://github.com/nginxinc/docker-nginx/blob/1d2e2ccae2f6e478f628f4091d8a5c36a122a157/stable/stretch/Dockerfile

**Comment by thresheek** [comment]
Yes, dropped in https://github.com/nginxinc/docker-nginx/commit/ec7ff8c0a3d58aba0e812598c2a7b7869aba985d#diff-2aaa25af4e5df3dd6c91b501b3d9c630

**Comment by ghostsquad** [comment]
Is it expected then to install ca-certificates if it's desired on downstream images?

**Comment by thresheek** [comment]
Yep.
