### ISSUE TITLE
Rebuild docker hub images to include new nginx signing key

### ISSUE THREAD

**Issue by timstallmann** [nginxinc/docker-nginx#120]
I'm seeing some errors locally on the docker hub `nginx` image which seem to be related to https://www.nginx.com/blog/updating-gpg-key-nginx-products/

I think the solution might be as easy as rebuilding the images which are on Docker hub so that the new nginx key is pulled during the `apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62` step?

**Comment by thresheek** [comment]
Done by https://github.com/docker-library/official-images/pull/2084
