### ISSUE TITLE
What means mainline vs stable ?

### ISSUE THREAD

**Issue by pascalandy** [nginxinc/docker-nginx#121]
What is the definition of mainline ?
Is it like a version from a sprint ?

Thanks for the clarification :)

**Comment by tianon** [comment]
https://www.nginx.com/blog/nginx-1-6-1-7-released/ has some good
description of the two IMO

**Comment by thresheek** [comment]
Indeed.

**Comment by pascalandy** [comment]
tl:dr We recommend that in general you deploy the NGINX mainline branch at all times.

Thank you guys! cc @tianon @thresheek
