### ISSUE TITLE
PID-1 dumb-init

### ISSUE THREAD

**Issue by wernight** [nginxinc/docker-nginx#123]
Nginx spawn processes as far as I know. Unless it reaps processes in all cases, it'd be useful to use [dumb-init](https://github.com/Yelp/dumb-init) to fix those issues. It's meant for Docker and works also on Alpine.

Just need 2 lines to add it, then change entrypoint from:

    ENTRYPOINT ["/entrypoint.sh"]

to:

    ENTRYPOINT ["dumb-init", "/entrypoint.sh"]

**Comment by thresheek** [comment]
NGINX is supposed to launch and stop it's own proccesses on its own.  If you observe that it's not the case, please file a bug with a description on how to achieve that.

Right now this looks like an unnecessary change.

Thanks!
