### ISSUE TITLE
Perl module not enabled with alpine Dockerfile?

### ISSUE THREAD

**Issue by hasancansaral** [nginxinc/docker-nginx#124]
I am using `nginx:alpine` and trying to set my environment variables with:

`perl_set $SOME_KEY 'sub { return $ENV{"SOME_KEY"}; }';`

in my `nginx.conf` file. As far as I know (from the Dockerfile) alpine version comes with `--with-http_perl_module`, but I am getting nginx: [emerg] unknown directive `"perl_set" in /etc/nginx/nginx.conf:36`. What am I doing wrong?

**Comment by hasancansaral** [comment]
Loading the module with command `nginx -g 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;'` resolved the issue.

**Comment by woto** [comment]
Cool, that's what i'm searched. Its would be cool if this tip was present in docker hub nginx main page. Thanks!

**Comment by c4m4** [comment]
using centos and nginx repo, install package nginx-module-perl and load the module

**Comment by eleftrik** [comment]
> Loading the module with command `nginx -g 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;'` resolved the issue.

Thanks! You made my day.
After hours of searching, I got a Docker container with Nginx and nginx-module-perl.

**Comment by thresheek** [comment]
@eleftrik Hi, you can also use `nginx:alpine-perl` image, and use the `load_module` directive in your `nginx.conf` file, instead of re-defining the CMD.

**Comment by eleftrik** [comment]
> @eleftrik Hi, you can also use `nginx:alpine-perl` image, and use the `load_module` directive in your `nginx.conf` file, instead of re-defining the CMD.

Thanks for your feedback. During my attempts, I tried different solutions and each one gave me a different error. Redefining the CMD was the only one that worked for me, but maybe I did some mistakes while trying to find a solution.

**Comment by Crisesm** [comment]
> Loading the module with command `nginx -g 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;'` resolved the issue.

when I do that I get the following error when lifting the container 
nginx: invalid option: "load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;"

in dockerfile
FROM nginx:alpine
CMD ["nginx", "-g", "daemon off;", "load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;"]

**Comment by typoworx-de** [comment]
Bug still present in 2022 even through the docs say it's possible with docker build-arg ENABLED_MODULES="..." :-(
