### ISSUE TITLE
curl: (7) Failed to connect to localhost port 8080: Connection refused

### ISSUE THREAD

**Issue by gengu** [nginxinc/docker-nginx#125]
I was a novice docker

I have done according to the document，but I can not connect to the host:port , please help me . 

![image](https://cloud.githubusercontent.com/assets/6317176/18809009/1bdabd9c-82a4-11e6-9787-155e3c00aa0b.png)

**Comment by gengu** [comment]
> docker version 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

> Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        2016-08-18T17:52:38.255390991+00:00
 OS/Arch:      linux/amd64

**Comment by gengu** [comment]
![image](https://cloud.githubusercontent.com/assets/6317176/18809040/e5ad2ff6-82a4-11e6-81dc-57ad35540332.png)

**Comment by gengu** [comment]
sorry...

I ssh to the machine "default" , then execute "curl http://localhost:8080" 

that is the right way ....

**Comment by ashishd751** [comment]
@gengu 
I am facing the same issue, can you please tell me what solution you implemented?

**Comment by gengu** [comment]
if you are using a MacBook
Do not use 'localhost' to interview your server.
use '127.0.0.1' or network en0 ...

**Comment by swethaiyappan** [comment]
I am facing the same problem in windows 10 Home. Can any one help me solve the issue?
