### ISSUE TITLE
-v causes container to not run

### ISSUE THREAD

**Issue by RobertDiebels** [nginxinc/docker-nginx#126]
Hi guys,

I have an issue with the image.
I altered the command from the documentation to:

`docker run --name reverse-proxy -v ~/settings/nginx/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx`
Which is basically:
`docker run --name some-nginx -v /some/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx`
with different naming.
However my container does not show when executing:
`docker ps`

I read that this has something to do with the `daemon off;` which I included in my nginx.conf file.
Which looks like this:

```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;
daemon off; **<--here** 

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
```

I have no idea what I'm doing wrong as I'm only using the simplest configuration possible.
Might be that it has something to do with me using the docker toolbox on windows 10.

If someone could enlighten me. Please do.

**Comment by yosifkit** [comment]
Maybe there is something in `docker logs reverse-proxy` that would help?

**Comment by RobertDiebels** [comment]
@yosifkit thanks for the hint! I got this error: "daemon" directive is duplicate in /etc/nginx/nginx.conf
solved it by removing the `daemon off;` from the config file.

However, the documentation on the docker hub specifically states the following:
> Be sure to include daemon off; in your custom configuration to ensure that Nginx stays in the foreground so that Docker can track the process properly (otherwise your container will stop immediately after starting)!

Which would not be correct assuming I made no other mistakes.

Either way docker ps is now showing the container! Thank you!

**Comment by Dominik-K** [comment]
@RobertDiebels, just for clarification:
If you run the Nginx Docker image without an added command, the usual command `CMD ["nginx", "-g", "daemon off;"]` in the [Dockerfile of the nginx image](https://github.com/nginxinc/docker-nginx/blob/master/mainline/jessie/Dockerfile) is used. Obviously, it adds the `daemon off` flag to the configuration.

**Comment by RobertDiebels** [comment]
@Dominik-K I highly doubt this is obvious. The documentation states that it is required to add the `deamon off;` configuration. I don't read the Dockerfile of each library I want to use. I usually assume that reading the documentation and following it means it will work.

Unless this:

> Be sure to include daemon off; in your custom configuration to ensure that Nginx stays in the foreground so that Docker can track the process properly (otherwise your container will stop immediately after starting)!

Means I should put it in my own "Docker" configuration. I would say it's not obvious.

**Comment by Dominik-K** [comment]
@RobertDiebels You're right the Docker hub documentation with `daemon off` is wrong. I added my comment that you and all the readers can understand why they see the message you got.
Does someone know where the source file of the Docker hub documentation is located?

**Comment by yosifkit** [comment]
The Docker Hub documentation is generated from the `docker-library/docs` repo; you'd want to update the `content.md` file for nginx: https://github.com/docker-library/docs/blob/master/nginx/content.md.

**Comment by RobertDiebels** [comment]
@Dominik-K thanks for fixing it guys :D !

**Comment by Dominik-K** [comment]
@RobertDiebels You're welcome. If you're ok with the new doc, then please close this issue. 

(Sorry for the many commit references. I thought they will only show up if I do a pull request. Did you receive an email for all of them?)

**Comment by RobertDiebels** [comment]
@Dominik-K seems clear to me! I'll close the issue. My late reaction was because I have no email notifications haha.

Again, thanks for the quick action!
