### ISSUE TITLE
Nginx rewrite to proxy_pass server/path

### ISSUE THREAD

**Issue by rajkumar49** [nginxinc/docker-nginx#128]
is it possible to use Nginx proxy_pass to rewrite URL as below:

location /foo {

             proxy_pass http://external-server-IP:8080/some/path/;

                            }

**Comment by thresheek** [comment]
Please use nginx mailing list for questions like that, as github is not an appropriate place to receive general nginx support.

http://mailman.nginx.org/mailman/listinfo/nginx
