### ISSUE TITLE
Current images use OpenSSL 1.0.1e

### ISSUE THREAD

**Issue by keunwoo** [nginxinc/docker-nginx#13]
'''
$ docker pull nginx:latest
$ docker run -d --name nginx nginx:latest
$ docker cp nginx:/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 .
$ strings libssl.so.1.0.0 |grep '^OpenSSL'
OpenSSLDie
OpenSSL 1.0.1e 11 Feb 2013
'''

OpenSSL needs to be updated to at least 1.0.1g.

FYI I reported this on the nginx trax by accident:
http://trac.nginx.org/nginx/ticket/703
but now I see from the Docker Hub page that it should be reported here:

**Comment by thresheek** [comment]
It is not a correct way to check if openssl vulnerabilities are fixed in that particular library. Debian Wheezy (which is what nginx official image is based on) has it fixed long ago by backporting a patch without changing the library version.

For more information, please refer to:

    Debian/Wheezy? openssl package: ​https://packages.debian.org/wheezy/openssl
    NGINX official Dockerfile: ​https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile
