### ISSUE TITLE
Add support for libatomic and aio libs for atomic memory and asynic io

### ISSUE THREAD

**Issue by virtuman** [nginxinc/docker-nginx#132]
These require a couple of system packages and a couple of configure flags:

https://books.google.com/books?id=qScxCgAAQBAJ&pg=PA5&lpg=PA5&dq=nginx+with-libatomic&source=bl&ots=RM-UAdOiv7&sig=eiMyokRX0GKpqlLTd_KEQNSVioU&hl=en&sa=X&ved=0ahUKEwiS9tPP7M7QAhWKjlQKHVF9DAkQ6AEIUDAH#v=onepage&q=nginx%20with-libatomic&f=false

Thank you for consideration

**Comment by thresheek** [comment]
It's not needed on amd64.
