### ISSUE TITLE
Minimize nginx.conf

### ISSUE THREAD

**Issue by JensPiegsa** [nginxinc/docker-nginx#138]
Hi folks,

In my opinion this docker image would largely benefit from a minimal `nginx.conf` in terms of flexibility. A minimal version of this file would only contain `include` declarations inside the `http` block pointing to `conf.d/*.conf`. The `conf.d` sub-folder then could be replaced with a (pre-existing) Docker volume at runtime and the main `nginx.conf` does not need to be touched in most cases.

Cheers,
Jens

**Comment by tianon** [comment]
This is already the case, isn't it?  (I usually only `COPY` into / bind-mount `/etc/nginx/conf.d`)

```console
$ docker run --rm nginx grep include /etc/nginx/nginx.conf
    include       /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
$ docker run --rm nginx:alpine grep include /etc/nginx/nginx.conf
    include       /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;
```

**Comment by alaz** [comment]
I would say `nginx.conf` needs to be touched in most practical cases, because (a) modules need to be loaded; (b) `worker_connections` increased; (c) `worker_processes` tuned up to the task.

So the current `nginx.conf` provides a good minimal default IMO.

**Comment by JensPiegsa** [comment]
Thanks for your replies!

@tianon 
yes, but it also has other "default" declarations.

@alaz 
The cases you've mentioned even seem to raise the urge to make substitution of configuration more convenient.

The current directory structure allows for three ways to alter the main configuration, each comes with certain disadvantages:

1. a **single-file docker volume for nginx.conf** makes it harder to replace the container / stay independent from the host file system
2. a **derived docker image**: adds the need to deal with updates / images
3. a **docker volume** for the whole `/etc/nginx` folder makes it necessary to copy all other files there, too.

Did I miss something?

**Comment by alaz** [comment]
Everything seems to me so convenient already: there is a single small `nginx.conf` suitable for simple configurations. And I'm providing my own `nginx.conf` for anything above that.

Frankly I don't want another Debian-like convention w/ lots of includes at different levels and me looking at this for an hour only to realize I need to throw the whole alien config out of my way.

**Comment by thresheek** [comment]
@JensPiegsa which "default" declarations are getting in your way?  nginx.conf we ship is the one that worked for years for all other purposes, and it's quite concise and, well, sane. I agree with @alaz that there isnt much to fix, and I'd rather ship the defaults instead of having them fixed for Docker only, which means there will be more deviations of the standard way we package things at nginx.org.  That might sound like I'm being lazy (and I surely am), but the principle of least astonishment still stands - and I'd like to stick to it.

**Comment by JensPiegsa** [comment]
@alaz @thresheek 
Thanks for the discussion. I understand that packaging for docker and non-docker environments somehow compete and users switching from one to another should not be faced with unpleasant surprises.

Maybe instead of forcing applications to restructure their whole configurations to be optimized for Docker, their support for single-file volumes should be enhanced..
