### ISSUE TITLE
How to install the nginx_ajp_moudle to docker-nginx ?

### ISSUE THREAD

**Issue by huyilong0516** [nginxinc/docker-nginx#139]
how can I install the ajp moudle to the image that does not contain ?

**Comment by thresheek** [comment]
If this module supports dynamic loading, you can compile it on top of the provided nginx image.  If it does not, you should not use this image and create one on your own instead.

**Comment by huyilong0516** [comment]
have this docker image contain nginx src code? how can I recompile nginx using [configure] to install this moudle?

**Comment by thresheek** [comment]
No, there is no source code included in this image.  If the module can be compiled dynamically, you can download appropriate nginx source code, and use ./configure --add-dynamic-module=path-to-ajp/ && make modules to build this module.  Then, use load_module directive to load it in nginx.conf.

**Comment by huyilong0516** [comment]
Thx Anyway !
