### ISSUE TITLE
apt-key call is failing hitting pgp.mit.edu - alternatives?

### ISSUE THREAD

**Issue by eric-tucker** [nginxinc/docker-nginx#140]
```
gpg: requesting key 7BD9BF62 from hkp server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

Currently cannot build the nginx container from the Dockerfile.

**Comment by eric-tucker** [comment]
Seems to be back up now.  Disregard.

**Comment by thresheek** [comment]
The alternative is to fetch the key from https://nginx.org/packages/keys/ .

**Comment by eric-tucker** [comment]
Curious - why isn't that the one used by this Dockerfile?

**Comment by thresheek** [comment]
Because it will suffer from the same problem if it's unreachable.
