### ISSUE TITLE
proxy_bind requires root

### ISSUE THREAD

**Issue by jonarmani** [nginxinc/docker-nginx#143]
I'm using nginx as a load balancer in front of syslog servers, so here is my nginx.conf:

```
events {
   worker_connections 1024;
}
stream {
   upstream logstash_servers {
      server logstash-collector-01:514 max_fails=2 fail_timeout=5;
      server logstash-collector-02:514 max_fails=2 fail_timeout=5;
      server logstash-collector-03:514 max_fails=2 fail_timeout=5;
   }
   server {
      listen 514/udp;
      proxy_pass logstash_servers;
      proxy_bind $remote_addr transparent;
   }
}
```
Without the "proxy_bind" line, my syslog servers see all events as sourced from the IP of this load balancer.  However, with that line I get this error every time nginx tries to forward to a upstream server:
`2017/02/02 04:57:42 [alert] 7#7: *1 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: 172.26.0.6, server: 0.0.0.0:514, upstream: "172.26.0.3:514", bytes from/to client:35/0, bytes from/to upstream:0/0
`

I've tried doing `docker run` with --user=root, setcap in a docker-entrypoint, etc and keep running into this issue.  Is it impossible to run nginx as a root user so that `proxy_bind` works?

**Comment by jonarmani** [comment]
Disregard; adding `user root;` as the first line of nginx.conf allowed this to work.

**Comment by yegle** [comment]
@jonarmani Would you be able to share any extra configs you did to make this work? I don't even see the `IP_TRANSPARENT` error message while running `proxy_bind` with `transparent` using `nobody` user and am unsure what I did wrong...

**Comment by jonarmani** [comment]
Sorry, I don't even work at the company that I was doing this for years
ago.  I'm also positive the equipment I was working on has since been
decommissioned.  Sorry.
