### ISSUE TITLE
vts module

### ISSUE THREAD

**Issue by kfox1111** [nginxinc/docker-nginx#144]
Could the vts plugin be added to the images? I'd like to be able to integrate this image with a monitoring system and being able to gather metrics about how the web server is performing would be very useful.

**Comment by thresheek** [comment]
No, third party modules will not be added to this image because we cannot guarantee the quality of the code, nor fix any issues with them.

I guess the best way to act is to use your own separate image if you need modules compiled from source.

**Comment by kfox1111** [comment]
Ok. Thanks.
