### ISSUE TITLE
often see these flags in nginx build examples, is there any benefit from them?

### ISSUE THREAD

**Issue by virtuman** [nginxinc/docker-nginx#146]
Often see these:

`--with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2'  `
and 
`--with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed' `

in numerous examples on how to build nginx. is there any benefit from settings these options?

Thank you

**Comment by thresheek** [comment]
Check https://wiki.debian.org/Hardening.

**Comment by virtuman** [comment]
I guess I should have been more direct in the original question - Is there any benefit from setting these options in the nginx official image itself?
