### ISSUE TITLE
-e TZ=Europe/Moscow

### ISSUE THREAD

**Issue by bscheshirwork** [nginxinc/docker-nginx#149]
I can't configure the `nginx` service throw environment `TZ`

Another service in the composition can set timezone with
```
    environment:
      TZ: Europe/Moscow
```
```
$ date
Ср фев 15 18:16:52 MSK 2017
$ docker-compose run --rm php date
Wed Feb 15 18:17:05 MSK 2017
$ docker-compose run --rm db date
Wed Feb 15 18:17:47 MSK 2017
```

but nginx-alpine has strange effect:
```
$ docker-compose run --rm nginx date
Wed Feb 15 15:18:20 GMT 2017
```
without pass -e 
```
$ docker-compose run --rm nginx date
Wed Feb 15 15:18:44 UTC 2017
```

UTC -> GMT

may be this 
https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-217809326

**Comment by thresheek** [comment]
That looks like a problem in the alpine image, not nginx related.

**Comment by bscheshirwork** [comment]
The nginx use it... Write time, for exp, in log file. So... Can may be need expand alpine for nginx and resolve problem?

**Comment by bscheshirwork** [comment]
yes, its resolve problem.
```
$ docker-compose run --rm nginx date
Wed Feb 15 15:55:29 GMT 2017
$ docker-compose run --rm nginx date
Wed Feb 15 18:55:55 MSK 2017
```

**Comment by thresheek** [comment]
Please provide a PR for it, then.

**Comment by khs1994** [comment]
You can add 

```docker
FROM nginx:1.13.6-alpine

RUN apk add --no-cache tzdata
```

in Dockerfile ,rebuild docker image

**Comment by bscheshirwork** [comment]
@khs1994 https://github.com/nginxinc/docker-nginx/pull/150/files#diff-2803676de07439b8d816bd56f7e53776R70

**Comment by khs1994** [comment]
other based alpine Docker Image (redis,memcached,etc) is not include tzdata!

**Comment by khs1994** [comment]
@bscheshirwork I got it.

**Comment by bscheshirwork** [comment]
> other based alpine Docker Image (redis,memcached,etc) is not include tzdata!
Thank you! I will propose this changes into redis image too...

**Comment by khs1994** [comment]
Add tzdata use `1.3MB` size.
