### ISSUE TITLE
Headers More module

### ISSUE THREAD

**Issue by sourcerer-mike** [nginxinc/docker-nginx#153]
Hello. I wonder how to bring in other modules like the "Headers More module".
Will it be done in the package repo some day?
Can it be compiled within the container? (like in the php-fpm container).

**Comment by thresheek** [comment]
No, they won't be shipped in this container as they are third-party and nginx cannot guarantee the code quality of those modules.

I guess you can compile them if you install gcc and everything needed to build it.

**Comment by sourcerer-mike** [comment]
I am okay with the fact that this is some third party dependency.
But I was hoping for some more enthusiasm about making it easier to bring in those modules.

Imagine a not so experienced developer / sysop working with your solution.
They won't know how to use gcc and add the missing library.

The php docker do it quiet well as they give away a command to easily build additional modules. I hope nginx docker does that too some day.

**Comment by raphaklaus** [comment]
@sourcerer-mike You can link third party modules into nginx easily using Docker. You can use volumes for example to share the built module with nginx container and include it in your config file.

**Comment by sourcerer-mike** [comment]
Thanks for offering a solution. I am good with this. Was hoping for some gcc ready container from your side. Not shipping the compiled solution as @thresheek might have understood.
Just offering the ability to do this. Like people who want to use 3rd party modules, not knowing how but having a command like `docker-php-ext-install bcmath` which handles the compiling for them.

Anyways I can live without and my awareness for other peoples problems drops here too. Thanks for discussing this a bit! :)

**Comment by ish1301** [comment]
I think having somthing like 'docker-nginx-module-install headers-more-nginx-module` would be great idea and simply this process of installing additional modules.

**Comment by milliephanillie** [comment]
Does anyone have an example docker file that simply just adds the headers module?

**Comment by thresheek** [comment]
@milliephanillie check out https://github.com/nginxinc/docker-nginx/tree/master/modules#docker-compose-with-pre-packaged-modules
