### ISSUE TITLE
Potentially provide a version without perl module

### ISSUE THREAD

**Issue by M-SIGMA** [nginxinc/docker-nginx#154]
Hi, 

I was doing a little digging around with regards to the images provided as standard and was looking for the smallest provided image of a local NGINX container for development purposes. Upon inspection I noticed that the downloading and use of the NGINX perl module is included in docker build process for all versions of these images.

Upon creating my own version of the provided Alpine (tagged 1.11-alpine) image without the Perl module I noticed a significant saving in container size. 

| Repository  | Tag | Image ID | Created | Size |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| nginx-noperl | 1.11-alpine-noperl | affa9237547c | Omitted | 13.2 MB |
| nginx | 1.11-alpine | 0ae090dba3ab | Omitted | 54.28 MB |
| nginx | latest | 6b914bbcb89e | Omitted | 181.8 MB |

I think for those who simply want an NGINX container for development purposes, or potentially also for those that are trying to reduce storage, a separate tagged version without perl would be very useful, as many don't require the Perl module or the additional functionalities/capabilities it provide and the addition of it merely inflates the size of the image.

As you can see the difference between the Alpine version of the image WITH Perl and the that of the Alpine version of the image WITHOUT Perl is a huge difference in size. (Around ~75% saved)

**Comment by thresheek** [comment]
Yeah possibly.  I'm thinking about removing perl module from the default images for the upcoming switch in stable/mainline (1.12/1.13), which will happen sometime mid-april.

**Comment by andreif** [comment]
Yes, please

**Comment by thresheek** [comment]
Done starting with nginx:1.13.0 / mainline and nginx:1.12.0 / stable.

-perl tag variants are added for those willing to use perl module.
