### ISSUE TITLE
Edit nginx.conf

### ISSUE THREAD

**Issue by ebuildy** [nginxinc/docker-nginx#16]
Really sorry to post this as an issue, I think I just misunderstood something ^^

In the documentation I can read

    docker run --name some-nginx -v /some/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx

I tried this but when I browse the container, I am still seeing the default nginx page instead of my content. 

Am i wrong or the documentation is outdated?

Thanks for your help,

**Comment by hacfi** [comment]
@ebuildy How did you add your content to the container?

**Comment by thresheek** [comment]
@ebuildy it seems to work just fine here:
docker@boot2docker:~$ cat /home/docker/conf/nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    access_log  /var/log/nginx/access.log combined;
server {
listen 80;
location / {
    return 200 'OK - this is a new configuration file!\n';
}
}
}
docker@boot2docker:~$ docker run -v /home/docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx:latest
6ddb3a977eb7d3ba337e54fad9b867a115eb8c85aa2b8723b20f593f4c965b19
docker@boot2docker:~$ docker inspect 6ddb | grep -i ipaddr
        "IPAddress": "172.17.0.6",
docker@boot2docker:~$ curl http://172.17.0.6:80/
OK - this is a new configuration file!

**Comment by ebuildy** [comment]
Thanks you very much for a so detailed response!

As I use nginx so often with "sites-enabled" folder I didn't notice that I let 

    include /etc/nginx/conf.d/*.conf;

In the configuration file I tried ;-(
