### ISSUE TITLE
Google PageSpeed Module (Alpine)

### ISSUE THREAD

**Issue by argollo** [nginxinc/docker-nginx#162]
Anyone has ever tried this with the [PageSpeed Module](https://modpagespeed.com/doc/build_ngx_pagespeed_from_source)? It could increase performance and maybe could be worked into the reverse proxy as an optional feature.

**Comment by thresheek** [comment]
In my opinion pagespeed creates more problems than it solves.  Anyway, we will not distribute official images with third-party modules, so it will not be included.

**Comment by argollo** [comment]
I understand. Thanks for the reply.
