### ISSUE TITLE
URL rewriting for AngularJS app not working

### ISSUE THREAD

**Issue by piyuaryan** [nginxinc/docker-nginx#164]
app-nginx.conf
server {
listen 80;
server_name my-app;

location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    expires -1;
    add_header Pragma "no-cache";
    add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
    try_files $uri$args $uri$args/ $uri $uri/ /index.html =404;
}
}

Tried without add_header and expires as well. (didn't work)

Dockerfile
FROM nginx
MAINTAINER Piyush Ramavat
COPY ./docker/qb-nginx.conf /etc/nginx/conf.d/qb-nginx.conf
COPY ./ /usr/share/nginx/html

Please help, everything is working fine, but when Page is refreshed, 404 is thrown.

**Comment by thresheek** [comment]
It's not an appropriate place to get general nginx support.  Please consider mailing lists instead: http://mailman.nginx.org/mailman/listinfo/nginx

**Comment by piyuaryan** [comment]
Actually this is working fine with Normal Nginx. It's not working only in case of Docker.
Hence added here.

**Comment by thresheek** [comment]
Check error logs for nginx running on Docker, then.
