### ISSUE TITLE
SIGQUIT stopsignal causes unclean shutdown; use SIGTERM

### ISSUE THREAD

**Issue by bluefoxicy** [nginxinc/docker-nginx#167]
The `SIGQUIT` stop signal in newer nginx images causes an unclean shutdown.  This causes nginx to fail to start after shutting down if it uses any UNIX domain sockets.

Upon starting, nginx creates UNIX domain sockets.  If a UNIX domain socket exists at the path specified, nginx will throw an error and fail to start.

Upon a `SIGQUIT`, nginx will fail to remove these UNIX domain sockets.  This means `docker restart` causes the container to fail until the user manually removes the socket file.

Upon a `SIGTERM`, nginx removes any UNIX domain sockets used by the current nginx configuration.  This allows for a clean shutdown and restart.

Earlier releases of Ubuntu also issued a `SIGQUIT` in the nginx `init.d` script; this was replaced with `SIGTERM` for the above reasons.

**Comment by bluefoxicy** [comment]
This issue rolls back #46.  That is on-purpose and by-design.  #46 was ill-conceived and should have never been done.

**Comment by thresheek** [comment]
I guess for the sake of clarity we should define STOPSIGNAL as SIGTERM instead and not rely on defaults?

**Comment by bluefoxicy** [comment]
Perhaps.  The default in Docker has always been `SIGTERM`, and most images don't define it explicitly.  I'm just trying to unbreak nginx so it stops failing on container restart.

**Comment by gsf** [comment]
This appears to be the nginx issue @bluefoxicy is referring to:
https://trac.nginx.org/nginx/ticket/753

**Comment by robsonpeixoto** [comment]
News about it?

**Comment by taylorb-syd** [comment]
As per #377 the incorrect behaviour with `SIGQUIT` and UNIX sockets has been fixed since 1.19.1. Therefore we can proceed, but we're using #377 to track this issue.
