### ISSUE TITLE
Install php5-fpm problem since stretch

### ISSUE THREAD

**Issue by yoyos** [nginxinc/docker-nginx#169]
I get this with new stretch based version.

> user@ec9596a8d917:/# apt-get update && apt-get install php5-fpm
Hit:1 http://security.debian.org stretch/updates InRelease
Get:2 http://deb.debian.org/debian stretch InRelease [186 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [88.5 kB]
Hit:4 http://nginx.org/packages/debian stretch InRelease
Fetched 275 kB in 0s (634 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php5-fpm
root@ec9596a8d917:/#

Do you know the new way to install php5-fpm like it was on jessie ? Thanks !

**Comment by thresheek** [comment]
php-fpm maybe? https://packages.debian.org/search?keywords=php-fpm

**Comment by yoyos** [comment]
No, it's php 7.0 dependent. 

I found what to do for ppl interested:

RUN apt-get update && apt-get install -y apt-transport-https lsb-release ca-certificates wget
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
RUN apt-get update && apt-get install -y php5.6-fpm
