### ISSUE TITLE
need help with GPG key

### ISSUE THREAD

**Issue by kleuf** [nginxinc/docker-nginx#170]
when i build a image from the apline Dockerfile, it takes forever when i get to 

Fetching GPG key B0F4253373F8F6F510D42178520A9993A1C052F8 from ha.pool.sks-keyservers.net
gpg: keybox '/tmp/tmp.kgBAgm/pubring.kbx' created

any way to fix this?

**Comment by thresheek** [comment]
Fix your connection / firewalls.
