### ISSUE TITLE
Alpine image does not include sites-enabled

### ISSUE THREAD

**Issue by jmcollin78** [nginxinc/docker-nginx#171]
Hi there,

When migrating to Alpine Docker images, our tests are KO because the default nginx.conf doesn't include the sites-enabled conf.
Is it normal ?

**Comment by thresheek** [comment]
Yes, it is normal.  If you need special directory configuration, just mkdir and include them in nginx.conf.

**Comment by jmcollin78** [comment]
but it breaks compatibiity with non docker Nginx installation which automatically includes sites-enabled/*
