### ISSUE TITLE
rc-service is missing 

### ISSUE THREAD

**Issue by 6ecuk** [nginxinc/docker-nginx#172]
Please add in image the rc-service for nginx start,stop,restart etc.
Thanks

**Comment by thresheek** [comment]
Which image?

**Comment by 6ecuk** [comment]
> Which image?
mainline-alpine

**Comment by yosifkit** [comment]
There is no init system in containers; the only thing running in the container is the nginx process  You can just use docker to manage the lifecycle:

- `docker stop nginx-container`
- `docker start nginx-container`
- `docker restart nginx-container`
- `docker kill -s HUP nginx-container`
- `docker kill -s [some-other-signal] nginx-container`
