### ISSUE TITLE
You broke perl for NginX

### ISSUE THREAD

**Issue by diamantn** [nginxinc/docker-nginx#174]
`emerg] 7239#7239: dlopen() "/usr/lib/nginx/modules/ngx_http_perl_module.so" failed (libperl.so.5.20: cannot open shared object file: No such file or directory)`

The new debian version is using 5.24
So you basically broke your own container by switching to a perl version that the NginX perl module does no support.

**Comment by alaz** [comment]
You didn't specify which Docker image you see this in.

Note that images w/ Perl are now packaged separately and have `-perl` suffix in image tag: #154.

For example, I have a `Dockerfile` that depends on `nginx:stable-alpine-perl` and it successfully loads Perl module:

```
/ # nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
/ # grep load_m /etc/nginx/nginx.conf
load_module /etc/nginx/modules/ngx_http_image_filter_module.so;
load_module /etc/nginx/modules/ngx_http_perl_module.so;
/ # nginx -v
nginx version: nginx/1.12.0
```

**Comment by thresheek** [comment]
It also works fine with nginx:1.13.1-perl, so please @diamantn tell us more.

**Comment by diamantn** [comment]
Hello,
You are correct.
I've been using the 'nginx' version before the change to stretch.
That image did not require the 'perl' tag.
I've tested with that tag and everything looks fine.
Thank you.
