### ISSUE TITLE
Nginx responds with 403 if mounted volume doesn't have 0755 permissions

### ISSUE THREAD

**Issue by maxkueng** [nginxinc/docker-nginx#177]
The content mounted to `/usr/share/nginx/html` can not be served by Nginx despite the container having read access to it, unless _"other"_ is given read access too.

Given the following directory structure:

```
/tmp/webs:
total 0
drwxr-x--- 2 root root 60 Jun 26 09:40 my-website

/tmp/webs/my-website:
total 8
-rw-r----- 1 root root 32 Jun 26 00:18 index.html
```

And running the container like this:

```sh
docker run --rm -it \
           --name my-website \
           -p 9999:80 \
           -v /tmp/webs/my-website:/usr/share/nginx/html \
           nginx:latest

```

Nginx will return a 403 error:

```sh
curl -X HEAD -I http://localhost:9999

HTTP/1.1 403 Forbidden
Server: nginx/1.13.1
Date: Mon, 26 Jun 2017 07:51:24 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
```

But checking the permissions from inside the container shows correct permissions:

```sh
docker exec my-website ls -lR /usr/share/nginx/ 

/usr/share/nginx/:
total 0
drwxr-x--- 2 root root 60 Jun 26 07:40 html

/usr/share/nginx/html:
total 4
-rw-r----- 1 root root 32 Jun 26 07:47 index.html
```

And the HTML file is readable from inside the container:

```sh
docker exec my-website cat /usr/share/nginx/html/index.html

<!DOCTYPE html>
<p>It works</p>
```

To fix this I have to make the mounted directory and its contents publicly readable:

```sh
chmod -R o+rX /tmp/webs/my-website
```

```sh
/tmp/webs:
total 0
drwxr-xr-x 2 root root 60 Jun 26 09:40 my-website

/tmp/webs/my-website:
total 4
-rw-r--r-- 1 root root 32 Jun 26 09:47 index.html
```

Now Nginx can serve the files:

```sh
curl -X HEAD -I http://localhost:9999

HTTP/1.1 200 OK
Server: nginx/1.13.1
Date: Mon, 26 Jun 2017 07:57:12 GMT
Content-Type: text/html
Content-Length: 32
Last-Modified: Mon, 26 Jun 2017 07:47:56 GMT
Connection: keep-alive
ETag: "5950bc2c-20"
Accept-Ranges: bytes
```

I think it's pretty weird since the directory belongs to root, the docker daemon runs as root and Nginx inside the container runs as root too (at lease I didn't see a user change in the Dockerfile). Shouldn't Nginx be able to serve the files it it has read access to them?  
I can't recall having a similar issue with other containered software.

### Versions

Docker: 17.05.0-ce
Nginx: nginx/1.13.1 (image: nginx:latest)
Host OS: Debian 9

**Comment by thresheek** [comment]
nginx drops privileged to the user supplied in the configuration file, which is nginx by default; therefore it has no access to index.html.

**Comment by maxkueng** [comment]
Oh, alright. Then how can I set the permissions of my files without making them readable for everyone?  
Is it common practice to make a new image based on the nginx image that `chown`s the files?

**Comment by thresheek** [comment]
you set them as readable for nginx group

**Comment by maxkueng** [comment]
But my host OS doesn't have an nginx group. Also it's likely that my local nginx group (if I had one) would have a different ID than the one inside the container.

**Comment by thresheek** [comment]
Then chown in the dockerfile is your only semi-sane option, I guess.

What's the issue with index.html being non-world-readable if you're serving it on the interwebs anyway?

**Comment by maxkueng** [comment]
> What's the issue with index.html being non-world-readable if you're serving it on the interwebs anyway?

Fair enough :) I just wanted the permissions to be as strict as possible.

I'm closing this as the current behavior is intentional and expected. Thanks for helping with the issue!
