### ISSUE TITLE
Please provide subs-filter as a module that can be installed

### ISSUE THREAD

**Issue by eigood** [nginxinc/docker-nginx#178]
I'm using the debian-stretched based version of nginx(1.13).  It does not have the same set of available extra modules for me to install.  Debian Buster has many more available.

Something like the following should be available:

libnginx-mod-http-auth-pam - PAM authentication module for Nginx
libnginx-mod-http-cache-purge - Purge content from Nginx caches
libnginx-mod-http-dav-ext - WebDAV missing commands support for Nginx
libnginx-mod-http-echo - Bring echo and more shell style goodies to Nginx
libnginx-mod-http-fancyindex - Fancy indexes module for the Nginx
libnginx-mod-http-geoip - GeoIP HTTP module for Nginx
libnginx-mod-http-headers-more-filter - Set and clear input and output headers for Nginx
libnginx-mod-http-image-filter - HTTP image filter module for Nginx
libnginx-mod-http-lua - Lua module for Nginx
libnginx-mod-http-ndk - Nginx Development Kit module
libnginx-mod-http-perl - Perl module for Nginx
libnginx-mod-http-subs-filter - Substitution filter module for Nginx
libnginx-mod-http-uploadprogress - Upload progress system for Nginx
libnginx-mod-http-upstream-fair - Nginx Upstream Fair Proxy Load Balancer
libnginx-mod-http-xslt-filter - XSLT Transformation module for Nginx
libnginx-mod-mail - Mail module for Nginx
libnginx-mod-nchan - Fast, flexible pub/sub server for Nginx
libnginx-mod-stream - Stream module for Nginx

The previous list are the debian package names.  Some of those are already available as nginx-module-*.  But most aren't.

**Comment by thresheek** [comment]
No third-party modules can be provided with this image, see #116, #162.

In you case, maybe http://nginx.org/r/sub_filter will help? It's almost on par with subs-filter feature-wise.

**Comment by eigood** [comment]
Then perhaps add an entry about this to a FAQ or something?  Since 3 separate issues have been filed about added more modules, it would seem to be a missed opportunity.

**Comment by amingilani** [comment]
@thresheek how do I enable `sub_filter`?

**Comment by amingilani** [comment]
To clarify: The docs only point to recompiling with the `-with-http_sub_module`

>This module is not built by default, it should be enabled with the --with-http_sub_module configuration parameter.

@thresheek is there a way for me to drop in a few lines in my own Dockerfile based off of this image and have this module available?

**Comment by amingilani** [comment]
It's definitely not in the image:

```
s -lah /usr/lib/nginx/modules
total 1.2M
drwxr-xr-x 2 root root 4.0K Jul 26 07:33 .
drwxr-xr-x 3 root root 4.0K Jul 26 07:33 ..
-rw-r--r-- 1 root root  20K Jul 11 13:07 ngx_http_geoip_module-debug.so
-rw-r--r-- 1 root root  20K Jul 11 13:07 ngx_http_geoip_module.so
-rw-r--r-- 1 root root  23K Jul 11 13:09 ngx_http_image_filter_module-debug.so
-rw-r--r-- 1 root root  23K Jul 11 13:09 ngx_http_image_filter_module.so
-rw-r--r-- 1 root root 256K Jul 11 13:15 ngx_http_js_module-debug.so
-rw-r--r-- 1 root root 256K Jul 11 13:15 ngx_http_js_module.so
-rw-r--r-- 1 root root  19K Jul 11 13:16 ngx_http_xslt_filter_module-debug.so
-rw-r--r-- 1 root root  19K Jul 11 13:16 ngx_http_xslt_filter_module.so
-rw-r--r-- 1 root root  16K Jul 11 13:07 ngx_stream_geoip_module-debug.so
-rw-r--r-- 1 root root  16K Jul 11 13:07 ngx_stream_geoip_module.so
-rw-r--r-- 1 root root 255K Jul 11 13:15 ngx_stream_js_module-debug.so
-rw-r--r-- 1 root root 251K Jul 11 13:15 ngx_stream_js_module.so
```

**Comment by thresheek** [comment]
It's not a dynamic module, check nginx -V

**Comment by amingilani** [comment]
Yes, I realize that now. Sorry, new to nginx. Thanks @thresheek

**Comment by fanyinghao** [comment]
@amingilani finally, how do you enable -with-http_sub_module with docker?

**Comment by amingilani** [comment]
@fanyinghao this was a while ago, so I can't remember exactly, but I think this was always enabled 😁

**Comment by fanyinghao** [comment]
@amingilani yes, you are right. I confirmed it was always enabled. thank you.
