### ISSUE TITLE
For IPV6, $remote_addr shows docker0 interface instead of client's ip

### ISSUE THREAD

**Issue by nsymms** [nginxinc/docker-nginx#18]
In the logs, and anything else that uses $remote_addr, why do I [mostly] always see the IP address of the docker0 interface instead of the client's remote IP?

The strange thing is that when Google's web crawler hits my server, or the hackers from China take their shot, I see their remote IP with no problems. But every other hit to the website gives me 172.17.42.1 as the client's address. This IP is the default private address for the docker0 interface. That is, the default gateway for every docker container.

**Comment by nsymms** [comment]
Okay so it's related to Ipv6. Any connections on Ipv4 get their correct address into nginx. Any Ipv6 connections coming in gets the Ipv4 address of the docker0 interface passed to nginx. So maybe this is a docker issue?

**Comment by nsymms** [comment]
Ok, I think I've figured this one out. It's by design. As @MalteJ mentions in https://github.com/docker/docker/issues/11518, docker does not support proxy or NAT of IPv6 to containers. In his words, docker does not "support publishing container ports on the host's IPv6 address." Which is, in effect, what I'm trying to do.

And if I look at the ip6tables on my container host, I can clearly see that there are no FORWARD or other entries set up by docker that would accommodate anything like I want, even when the docker daemon is run with the *--ipv6* option.

So, in the end, if you want to have proper IPv6 addresses passed to your containers, you need to run them with **--net host**. I've tried this with the nginx container (and @jwilder's nginx-proxy container) and of course it solves my problem. The only issue now is that I'm a little uncomfortable opening up the entire host's network to a container.

Any ideas would be appreciated.

**Comment by MalteJ** [comment]
How many IPv6 addresses do you have? Just one?

**Comment by nsymms** [comment]
I have a subnet for IPv6, but I think you already knew that. I'm not sure how that really matters, unless you're suggesting I expose the nginx container's IPv6 address? And, possibly, each container's IPv6? That would work in theory, assuming my containers are all set up as virtual hosts in nginx. Then IPv6 would simply bypass the nginx proxy container and hit the web apps directly.

But it doesn't work well if I have one server hostname with containers running web apps that are on paths instead of virtual hosts. That is, https://myserver.com/gitlab and https://myserver.com/other-app. In that case my main server has its hostname for some services and the nginx container has a separate hostname (and IPv6 address) for web apps.

Or maybe I'm trying to use this container and docker in ways that it is not intended. In any case, the issue is clearly not with this container or nginx. It's a docker thing, so this issue should be closed.

**Comment by MalteJ** [comment]
Then I would use an nginx as reverse proxy serving the domain https://myserver.com
This nginx will forward traffic to your apps `gitlab` and `other-app` via IPv6. You would set up your firewall rules to allow only traffic from the reverse proxy to your apps.

**Comment by rs-development** [comment]
Regarding this issue i would like to ask if there is any kind of logging in place? Having the above mentioned setup, we received suspicious requests and the nginx logging only shows the docker host ip address. Any docker internal logs whoing the orginal ip address?
