### ISSUE TITLE
OpenSSL no longer included in image

### ISSUE THREAD

**Issue by tdpearson** [nginxinc/docker-nginx#182]
It appears that the switch from base image Jessie to strech-slim has removed openssl from the container image. Any plans to add openssl back into the nginx image?

**Comment by thresheek** [comment]
That's correct - the idea is to keep nginx image as minimal as it can be, without shipping things not directly used by nginx.  What's the case for openssl in your setup?

**Comment by tdpearson** [comment]
We were using it to generate self-signed certs directly in the container.

**Comment by thresheek** [comment]
Right, so a plain apt install openssl will work right after FROM: nginx. I'll keep this issue open to collect the feedback from the users that might want to +1 it and we'll see if it makes sense to provide openssl in the base image. Thanks!

**Comment by tdpearson** [comment]
@thresheek Thanks for your quick responses. We have moved openssl into its own container and this is no longer an issue for us.

**Comment by eigood** [comment]
My vote would be to never add it to the nginx container; it's simple enough to mount a volume from $HOST or elsewhere, and isolate certification creation away from the network-exposed service.  You can(should) even mount said volume as read-only in nginx, for further security/protection.
