### ISSUE TITLE
Alpine release old/insecure

### ISSUE THREAD

**Issue by jmellor** [nginxinc/docker-nginx#185]
The latest nginx/alpine image is based off Alpine 3.5, which is old and insecure.
Alpine 3.6 was released several months ago.
Please release a new version with an updated base image.

**Comment by skyzyx** [comment]
https://github.com/nginxinc/docker-nginx/issues/184#issuecomment-315833599

**Comment by xanview** [comment]
+1

**Comment by thresheek** [comment]
Looks like alpine:3.5 was updated to cover the mentioned issue; see also https://hub.docker.com/r/library/nginx/tags/1.13.3-alpine/.
