### ISSUE TITLE
Why is /var/cache/nginx a volume?

### ISSUE THREAD

**Issue by dpwspoon** [nginxinc/docker-nginx#19]
I would like to know the reasoning on why /var/cache/nginx is a volume.  

As an administrator of docker-nginx is this a folder I should archive by default?

**Comment by sherter** [comment]
I guess this is just for better performance. By declaring an explicit volume you bypass docker's copy-on-write backend (e.g. aufs) and bind-mount the data directly from the host filesystem. 
Images like [mysql](https://github.com/docker-library/mysql/blob/master/5.7/Dockerfile) do this for the same reason.

**Comment by thresheek** [comment]
It is there so you could re-use caches (if any) between nginx upgrades.

**Comment by dpwspoon** [comment]
I discovered this when I was trying to learn docker and I noticed I was unintentionally [orphaning docker volumes](http://container-solutions.com/2014/12/understanding-volumes-docker/).  

It seems to me that there are several files you may want to keep between updates such as the conf directories.  I've found [this issue](https://github.com/nginxinc/docker-nginx/issues/5) on why for nginx most of those are not included in the volume.

Other then the potential performance reasons mentioned by @sherter, I can't see why the cache would be a special case.  As such perhaps it may be better to remove it for consistency, or have it documented on [docker hub/_/nginx readme](https://registry.hub.docker.com/_/nginx/) so people don't make the mistake of orphaning volumes.

**Comment by booyaa** [comment]
isn't the cache used for static assets?

**Comment by Siilwyn** [comment]
> Other then the potential performance reasons mentioned by @sherter, I can't see why the cache would be a special case. As such perhaps it may be better to remove it for consistency, or have it documented on docker hub/_/nginx readme so people don't make the mistake of orphaning volumes.

I agree with this, at least document it in the readme.

**Comment by dpwspoon** [comment]
updated the dockerfile with the reasoning provided by @sherter

**Comment by Siilwyn** [comment]
:+1: Nice!
