### ISSUE TITLE
Proxy_Pass with variable throwing: invalid URL prefix in "http://"

### ISSUE THREAD

**Issue by Vacant0mens** [nginxinc/docker-nginx#191]
I have nginx running in Docker swarm using the `docker stack deploy` command, I have a `xconf` folder mapped to the host to be able to modify the conf file on the fly. I have the nginx image start with the `-c` option to use the custom conf file.
I have the host port mapped using the "long syntax" with `mode: host` to avoid the ingress/mesh routing port binding (I hear it's not quite ready yet).

I have multiple networks in my system, including a few public IP addresses. I also have an external load balancer which is programmed to add the header `X-SERVER-SELECT` with the docker-dns hostname of the service being requested from the web.

When the web request hits nginx, it throws multiple errors: `[error] 7688#1972: *13 invalid URL prefix in "http://", client: 10.0.230.160, server: , request: "GET /"`
If the web page ever comes up (rather than a `504 Gateway Timeout` error), it takes around 2 minutes!

Here's my config file:
```
#multiple worker default :  auto
worker_processes  auto;
events {
    worker_connections 2048;
}
http {
    proxy_buffering off;
    include       ../conf/mime.types;   
    keepalive_timeout  15;
    server {
        listen 80;
        resolver 10.254.0.1;
        error_log server_error.log info;
        location / {
            proxy_redirect off;
            proxy_read_timeout 10;
            error_log proxy_error.log info;
            set $server $http_x_server_select ;
            proxy_pass http://$server ;
        }
    }
    # HTTPS server
    #include ssl.conf;
}
```
The `resolver` line is referencing the stack's custom network. the x.x.x.1 address is Docker's DNS server for that stack.

output of `nginx -v`:
```
nginx version: nginx/1.12.0
```
``
``
what am I doing wrong? Or is this even possible?

**Comment by thresheek** [comment]
It should work, provided the header contains valid hostnames.  Enable debug logging and launch nginx-debug binary to take a look on what's really going on.

**Comment by thresheek** [comment]
Closing due to the lack of response.
