### ISSUE TITLE
STOPSIGNAL incompatible with restart policy "always"

### ISSUE THREAD

**Issue by jbq** [nginxinc/docker-nginx#192]
Hi, thanks for providing the nginx image.  I ran into trouble in my production setup.  I always set `restart: always` on my production containers to make sure the various production services are started on server boot.  However for the first time I came across an unexpected problem, while using the `nginx` image.  I believe the `STOPSIGNAL` instruction is somewhat incompatible with the afore-mentioned restart policy.  When I do a `docker kill` on the `nginx` container, instead of killing the container, the `nginx` process is restarted and thus the `docker kill` command hangs forever, stuck waiting for termination.

I believe the safest option is to remove the `STOPSIGNAL` altogether, but I admit this may be more a Docker issue than a nginx-Docker-image issue?

WDYT?

**Comment by thresheek** [comment]
I don't think I can reproduce with current images.  Care to provide a minimal working example?

**Comment by thresheek** [comment]
Closing due to lack of response for two months.

**Comment by jbq** [comment]
Can't reproduce either with new version 1.13.8
