### ISSUE TITLE
Add include directory to support new dynamic module.

### ISSUE THREAD

**Issue by kevin-lot** [nginxinc/docker-nginx#194]
In https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/nginx.conf, can we add a new include directory, like "include /etc/nginx/modules.d/*.conf;"

All configuration files in "nginx/modules.d" directory would add dynamic modules.
Example /etc/nginx/modules.d/ngx_http_image_filter_module.conf: 
```
load_module "modules/ngx_http_image_filter_module.so";
```
This allows to add dynamic modules without editing nginx main configuration file, just matching volumes in docker-compose for example to add some configurations.

Best regards.

**Comment by thresheek** [comment]
No, please edit the main nginx configuration file for that.
