### ISSUE TITLE
How to increase max body size

### ISSUE THREAD

**Issue by hugohil** [nginxinc/docker-nginx#195]
Hi,
I cannot find any working solution to avoid having a `client intended to send too large body` error when I upload a 12Mo file to my server.

I tried `./uploads.ini:/etc/php/conf.d/uploads.ini`, where `uploads.ini` is : 

```yml
memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 1200
```

But this didn't solve my issue.

Any idea ?

**Comment by thresheek** [comment]
Try tuning http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size. Furthermore, please use nginx mailing lists or forums for questions unrelated to docker usage of nginx. Thanks.
