### ISSUE TITLE
/etc/nginx/nginx.conf can not mount？

### ISSUE THREAD

**Issue by jay763190097** [nginxinc/docker-nginx#197]
```
#docker run -p 80:80 --name mynginx -v $PWD/html:/www -v $PWD/nginx.conf:/etc/nginx/nginx.conf -v $PWD/logs:/wwwlogs  -d nginx
```
```
#docker logs mynginx 
```
open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)

**Comment by thresheek** [comment]
Check the permissions on your nginx.conf file.

**Comment by jay763190097** [comment]
@thresheek the file of "/etc/nginx/nginx.conf' is in nginx image.
```
[root@oracledb nginx]#  docker run -i -t nginx /bin/bash
root@2c21f58950df:/# cd /etc/nginx/
root@2c21f58950df:/etc/nginx# ls -l
total 32
drwxr-xr-x. 2 root root   25 Jul 26 07:33 conf.d
-rw-r--r--. 1 root root 1007 Jul 11 13:06 fastcgi_params
-rw-r--r--. 1 root root 2837 Jul 11 13:06 koi-utf
-rw-r--r--. 1 root root 2223 Jul 11 13:06 koi-win
-rw-r--r--. 1 root root 3957 Jul 11 13:06 mime.types
lrwxrwxrwx. 1 root root   22 Jul 11 13:06 modules -> /usr/lib/nginx/modules
-rw-r--r--. 1 root root  643 Jul 11 13:06 nginx.conf
-rw-r--r--. 1 root root  636 Jul 11 13:06 scgi_params
-rw-r--r--. 1 root root  664 Jul 11 13:06 uwsgi_params
-rw-r--r--. 1 root root 3610 Jul 11 13:06 win-utf
```

**Comment by thresheek** [comment]
could be a selinux or similar issue then.

**Comment by khs1994** [comment]
Your OS?

**Comment by thresheek** [comment]
Closing due to lack of response.

**Comment by abusayem955** [comment]
You may need to change SELinux mode with "Permissive"
# setenforce [Permissive|0]
To make changes persistent through a system reboot, edit the 'SELINUX=' line in  /etc/selinux/config  for either 'enforcing', 'permissive', or 'disabled'. For example: 'SELINUX=permissive'

**Comment by dolevhadad** [comment]
it happened to you because the SElinux is in Enforcing state.
you can check it by execute `getenforce` and see if the output is `Enforcing`, to change it to `Permissive` mode you can run  `setenforce 0` or disable the SELinux itself.

or my preferred method you can add in the docker-compose privileged: true or --privileged in the docker run and it will fix the problem.
