### ISSUE TITLE
Please add nginx-unitd docker images

### ISSUE THREAD

**Issue by netroby** [nginxinc/docker-nginx#198]
Please add nginx-unitd docker images

**Comment by thresheek** [comment]
It's in the works. They won't be published in the nginx repo, though, as it's not really nginx.

**Comment by thresheek** [comment]
You can now fetch them from https://hub.docker.com/r/nginx/unit/tags/ . See https://www.nginx.com/blog/unit-0-6-beta-release-available-now/ for more info.
