### ISSUE TITLE
1.13.6 miss?

### ISSUE THREAD

**Issue by khs1994** [nginxinc/docker-nginx#207]

**Comment by khs1994** [comment]
In Dcoker Hub  1.13.6.

**Comment by mrcasablr** [comment]
I do not see a 1.13.6 in official docker nginx registry

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/3566, especially https://github.com/docker-library/official-images/pull/3566#issuecomment-337353975:

> Let's scrap this PR then; I'll provide another one to bump nginx versions.

**Comment by soulne4ny** [comment]
And 1.12.2 as well.

**Comment by thresheek** [comment]
See https://github.com/docker-library/official-images/pull/3644
