### ISSUE TITLE
Could not run additional service (consul-template) along with nginx

### ISSUE THREAD

**Issue by bboyz269** [nginxinc/docker-nginx#212]
Hi, I tried to run consul-template to fetch info from Consul server to setting up upstream for nginx.

I create 2 scripts as

/etc/service/nginx/run
```groovy
#!/bin/bash

/usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"

````

/etc/service/consul-template/run
```groovy
#!/bin/bash

/usr/local/bin/consul-template -config "/etc/consul-template/conf"

```

In Dockerfile, I change the CMD to `CMD ["/usr/bin/runsvdir", "/etc/service"]`. When I tried to start the container, I got the message repeatedly:
```
runsv /etc/service/nginx: fatal: unable to start ./run: file does not exist
runsv /etc/service/consul-template: fatal: unable to start ./run: file does not exist
```
I already made sure that the files were there and have executable rights. Connected to the container, I could run each commands successfully (commands in the scripts). But running the script using `runsv` or `runsvdir` always yield the same error as above.
If it helps, I'm trying to integrate, register the nginx server to the Consul server for service discovery and load balancing.

// File permission
```
root@71077dcf4a7a:/etc/service/consul-template# ls -l
total 4
-rwxr-xr-x 1 root root 83 Nov 24 00:40 run
root@71077dcf4a7a:/etc/service/nginx# ls -l
total 8
-rwxr-xr-x 1 root root   79 Nov 24 00:40 run
drwx------ 2 root root 4096 Nov 24 01:26 supervise
```

Thanks in advance.

**Comment by thresheek** [comment]
Sorry, we can't provide technical support for consul.
