### ISSUE TITLE
LUA version like perl version?

### ISSUE THREAD

**Issue by Schnitzel** [nginxinc/docker-nginx#213]
As many people where showing interested for a LUA version (like the perl version) of nginx, would a pull request for that be even considered to be merged? I would love to have lua part of the regular nginx Docker Images.

**Comment by thresheek** [comment]
No, we won't ship third-party modules in the official images since we cant ensure the quality of those.

**Comment by TigerC10** [comment]
If I want to use this image as a base and add Lua to it, how might I do that?  Can that be documented, at least?  The typical method I would use results in:

```
[emerg] module "/etc/nginx/modules/ndk_http_module.so" version 1016001 instead of 1018000 in /etc/nginx/modules/devel_kit.conf:1
```

Or if I get the _same_ version installed, it results in:
```
nginx: [emerg] module "/etc/nginx/modules/ndk_http_module.so" is not binary compatible in /etc/nginx/modules/devel_kit.conf:1
```

Not having much luck, I'm afraid. 😅
