### ISSUE TITLE
Add a note about http2 not available on the default tag but available on alpine

### ISSUE THREAD

**Issue by jareddlc** [nginxinc/docker-nginx#214]
I just attempted to add http2 support to my nginx and took me a while to figure out why my site wasnt loading with the http2 protocol. turns out `openssl 1.0.2` is needed and the image that ships with `nginx` tag ships with `openssl 1.0.1`

I think it would be very helpful to include a portion in the hub readme about http2.

**Comment by jareddlc** [comment]
https://github.com/docker-library/docs/pull/1081

**Comment by thresheek** [comment]
Uhm, current nginx:latest (since 1.13.0 and 1.12.0) ship with http2 enabled due to usage of debian stretch base image, so this statement is not correct. You are likely using something outdated.

**Comment by jareddlc** [comment]
@thresheek  you are correct, I didnt catch that. look like im not using latest which explains why my alpine image worked as it was a fresh pull.

```
root@17f751848a24:/# nginx -V
nginx version: nginx/1.11.3
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.1t  3 May 2016
TLS SNI support enabled
```
