### ISSUE TITLE
add architectures to alpine

### ISSUE THREAD

**Issue by Evaw** [nginxinc/docker-nginx#219]
was reviewing the code and it seems the issue mentioned here https://github.com/nginxinc/docker-nginx/blob/master/generate-stackbrew-library.sh#L94 has been closed.

**Comment by thresheek** [comment]
Thanks, I will happily accept a PR fixing this one - I wont be able to work on this at the moment.

**Comment by FibreFoX** [comment]
@Evaw @thresheek One of you should close this issue, as this is already merged, or did I miss something?

**Comment by thresheek** [comment]
Yep, it's merged and fixed - thanks!
