### ISSUE TITLE
nginx packages for Debian 8

### ISSUE THREAD

**Issue by nikolas** [nginxinc/docker-nginx#22]
Debian 8 has been released (https://www.debian.org/News/2015/20150426)

I don't know if this is the right place to bring this up, but at some point it would be good to
get nginx mainline packages for debian 8 "jessie" here: http://nginx.org/packages/mainline/debian/dists/
and then update this repo.

The debian 8 package for nginx is at 1.6: https://packages.debian.org/jessie/nginx

**Comment by thresheek** [comment]
Thank you @nikolas. I have published 1.9.0 and Jessie in https://github.com/nginxinc/docker-nginx/commit/2d9dbca5d2a916b90227863bb8f1a6458e5083c5. Once the PR is merged, it will be available through the docker hub.
