### ISSUE TITLE
static website using docker nginx doesn't update automatically after rebuilding image

### ISSUE THREAD

**Issue by gqoew** [nginxinc/docker-nginx#223]
I am a beginner with nginx. I am using the docker nginx image to build a static website.

Here is my Dockerfile:

```
FROM nginx
COPY . /usr/share/nginx/html
```

The files copied in the container are a simple `index.html` with some css/js.

Here is what I did on my laptop:

I built a first webiste image and executed the container on my laptop. I could see the website by hitting `http://localhost:port`.
I changed the `index.html`, rebuilt the image and executed again the container on my laptop. I could see the changes added in `index.html` on the website by hitting `http://localhost:port`.

I did exactly the same process on a remote virtual machine by using the images created from my laptop, but this time, I cannot see directly the changes I made `index.html` after rebuilding the image (step 2), when I hit `http://host-ip:port`. People using other laptops may be able to see the latest changes when accessing `http://host-ip:port`.

I also noticed that if I kill the container, sometimes I can still see the website when reloading the page, but not others people accessing the same page. Also, if I shut down the laptop and open it some hours later and hit `http://host-ip:port` again, this time I see the latest change. Really weird issue 😛 

Here are my environments details:

Laptop:

```
MacOS High Serria 10.13.1
Docker version 17.12.0-ce, build c97c6d6
```

Virtual Machine:

```
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Docker version 1.12.5, build 047e51b/1.12.5
```

Any idea what could made this happen? Do I have to fine-tune something in nginx config files? Or is it a docker/OS version issue? Browser cache?

Thanks for your help.

**Comment by thresheek** [comment]
Don't trust your browser, check with curl.

**Comment by thresheek** [comment]
Closing due to the lack of response for two weeks.

**Comment by gqoew** [comment]
I confirm that it is probably due to the browser that for whatever reason doesn't update the content live; `curl` works. Thanks.
