### ISSUE TITLE
Autostart issue

### ISSUE THREAD

**Issue by liminspace** [nginxinc/docker-nginx#229]
I have several docker-compose.yml files.
Nginx is in one of them. Another ones have some web-sites.
They are here: https://github.com/liminspace/team-backoffice
After server reboot all docker-compose start but nginx doesn't serve requests.
It works only after restart docker-compose with nginx. But it is a solution.
What I can do to fix it?

**Comment by thresheek** [comment]
What are the logs on nginx side?

**Comment by liminspace** [comment]
Nothing. Nginx even doesn't start.
And I found that it works only after `docker-compose down && docker-compose up -d`.
Maybe after server's booted, docker-compose starts, but docker-gen can't generate nginx configs as other docker-composes weren't started yet. But `conf.d/default.conf` is correct.

**Comment by code-chris** [comment]
The nginx configs are the only container configs without the "restart always" policy... Maybe this is the reason.

**Comment by liminspace** [comment]
I tried, it didn't help me =(

**Comment by liminspace** [comment]
I repeated and it works now, thanks @code-chris.
I'm starting to like docker =)
