### ISSUE TITLE
No dockerfile is present for building nginx container on Ubuntu for power8 architecture

### ISSUE THREAD

**Issue by abhishek-work** [nginxinc/docker-nginx#23]
I have ported nginx to power8 architecture (ppc64le) and have also dockerized it on Ubuntu. I want to contribute docker files back to nginx community.

I would like to know more about,
1. What is the correct way/procedure to commit/submit dockerfile to repository?
2. Is there any preference about naming convention of dockerfiles and their place in repository?

**Comment by thresheek** [comment]
This is the repository for the official nginx image for docker hub, which officially only supports amd64 architecture.   I will only accept patches to this repo fixing issues on ppc64le when docker, hub and registry will support it as a first-class citizen.

If you wish to make your dockerfile work public, I guess uploading it to the github and then publishing on docker hub under your account will do the trick.  I can not comment on the naming convention for ppc64le images, but for the sake of searching I guess a suffix of -ppc64le will be fine.
