### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by kelaductor** [nginxinc/docker-nginx#230]
in Dockerfile 
```
FROM nginx:alpine
```

```
$ docker-compose build
Building nginx
Step 1/5 : FROM nginx:alpine
alpine: Pulling from library/nginx
ERROR: Service 'nginx' failed to build: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by uLan08** [comment]
same here
`docker pull nginx:1.13-alpine`

```
1.13-alpine: Pulling from library/nginx
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by uLan08** [comment]
I saw in other related issues that this should fix itself after a few mins but it has been an hour since then. 
Is it possible to trigger a manual build right now? @tianon 

Tagging for future reference 
https://github.com/docker-library/official-images/issues/3835

**Comment by kb10uy** [comment]
Same here too.
```yaml
web:
  image: nginx:mainline-alpine
```
I got
```
Pulling web (nginx:mainline-alpine)...
mainline-alpine: Pulling from library/nginx
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```
Like @uLan08 said, this image seems to be down for long time than other cases.
I hope this recover asap. 🙏

**Comment by mattjegan** [comment]
While the image is down you can possibly get around this issue temporarily using an older image, e.g. `nginx:1.12-alpine`

**Comment by TopFuel** [comment]
Until this is fixed you can use `nginx:stable-alpine`, it has an older version of nginx, but it's working fine for me at the moment.

**Comment by uLan08** [comment]
A better approach would probably be too specifically pull an old sha256 digest of nginx:1.13-alpine or whatever tag you're using. This way you won't be pulling an old version of nginx rather just an old build. It is also the recommended workaround in the issue I have linked. 
What I did was I viewed the history of the [nginx alpine readme](https://github.com/docker-library/repo-info/blob/master/repos/nginx/remote/1.13-alpine.md) copied and pulled the old digest and tagged it as `nginx:1.13-alpine`

**Comment by rawpixel-vincent** [comment]
you can also use the previous build directly 
`FROM nginx:1.13.8-alpine`

**Comment by kennyrulez** [comment]
@rawpixel-vincent your snippet did the trick for me. Thanks

**Comment by ebernard** [comment]
See also https://github.com/docker-library/official-images/issues/3835

**Comment by thresheek** [comment]
And this is why you should never use non-specific versions in your dependent images.

**Comment by greuff** [comment]
I deemed `1.13.9-alpine` to be specific enough.

**Comment by akamustang** [comment]
`1.13.9-alpine` is specific enough, but it's still the version that hasn't finished building yet, hence why it's not working.

As rawpixel-vincent said, use `1.13.8-alpine` until the new build is ready.

**Comment by bscheshirwork** [comment]
Pulling nginx (nginx:1.13.9-alpine)...
1.13.9-alpine: Pulling from library/nginx
ERROR: no matching manifest for linux/amd64 in the manifest list entries
d

**Comment by bscheshirwork** [comment]
same situation on mysql 8.0.4
%) 
is this illuminati real

**Comment by rolandjitsu** [comment]
For me only `stable-alpine` works.

**Comment by bscheshirwork** [comment]
but I wish latest-fresh-hot versions of my favorite tools :cry: I can see `2 hours ago`. I cant pull it. It's terrible...

**Comment by bscheshirwork** [comment]
docker pull nginx:1.13.9
1.13.9: Pulling from library/nginx
8176e34d5d92: Pull complete 
5b19c1bdd74b: Pull complete 
4e9f6296fa34: Pull complete 
Digest: sha256:4771d09578c7c6a65299e110b3ee1c0a2592f5ea2618d23e4ffe7a4cab1ce5de
Status: Downloaded newer image for nginx:1.13.9

:horse_racing:

**Comment by dedsm** [comment]
not yet nginx:alpine though

**Comment by TopFuel** [comment]
Seems like it's building: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/nginx/

**Comment by joekiller** [comment]
looks like the build is "unstable" so best to lock dependencies for now.

**Comment by bndw** [comment]
As @ebernard alluded to, this appears to be due to Dockerhub's library build and release process.

> Sometimes, we'll have non-amd64 image build jobs finish before their amd64 counterparts, and due to the way we push the manifest list objects to the library namespace on the Docker Hub, that results in amd64-using folks (our primary target users) getting errors of the form "no supported platform found in manifest list" or "no matching manifest for XXX in the manifest list entries" (see linked issues below for several reports from users of this variety).
>
> Thus, manifest lists under the library are "eventually consistent" -- once all arches complete successfully, the manifest lists get updated to include all the relevant sub-architectures.

https://github.com/docker-library/official-images/issues/3835

A workaround is to use a specific version of a particular tag, e.g. `nginx:1.13.8-alpine` instead of `nginx:alpine`

**Comment by drpaneas** [comment]
Same problem here

**Comment by schmunk42** [comment]
I have an automated build depending on `nginx` (rebuilds on updates) - and getting a failed email now every few hours.

I bet this affects a ton of people depending on `nginx`.

Failed build: https://hub.docker.com/r/schmunk42/nginx-redirect/builds/bpwpbjrbqc7svxkyx8ygxlo/

**Comment by pzelnip** [comment]
```nginx:alpine``` now working for me.

**Comment by kelaductor** [comment]
Works now!
I'll close this issue.

**Comment by TarCode** [comment]
It's happening for me too :(

**Comment by RancherEdimia** [comment]
docker pull nginx:alpine
alpine: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries

**Comment by scalp** [comment]
Same problem here with `nginx:1.15-alpine`.
Switch on `nginx:stable-alpine` works for me.

**Comment by mageekguy** [comment]
Same here with `nginx:1.15-alpine`, used by https://github.com/api-platform/api-platform.

**Comment by alter** [comment]
I've switched from nginx:alpine to nginx:stable-alpine too, looks like shit happened

**Comment by artem-sabitov** [comment]
same here
`nginx:latest`

**Comment by pejkosz94** [comment]
same here.
Change to `nginx:stable-alpine` and everything works fine.
