### ISSUE TITLE
Keep the default index.html page as simple and small as possible

### ISSUE THREAD

**Issue by KamranAzeem** [nginxinc/docker-nginx#234]
Hi, 
Thank you for a great product and a great docker image. We - and probably else in the container world - loves to run nginx to see if what we are trying to get to work, actually works! Nginx is great for that small little test, and of-course for bigger tasks too.

I see that curling any default nginx setup shows a large html page with styling and all that fancy stuff. e.g: 
![screenshot from 2018-03-12 17-07-54](https://user-images.githubusercontent.com/4216369/37337418-8622d756-26b4-11e8-9552-05a9cbee5167.png)

No matter how trivial or silly it may sound, I think, a simple one-liner saying "Welcome to nginx!" - as a default html page - is good enough. It does get the job done without filling up the screen.

The Apache httpd image, for example shows minimal output, which gets the job done! 
![screenshot from 2018-03-13 11-54-24](https://user-images.githubusercontent.com/4216369/37337682-5217ebb2-26b5-11e8-9152-3ae55c6cc571.png)

Hope it makes sense to the maintainers!

**Comment by thresheek** [comment]
I don't think I see a problem here, to be honest.

**Comment by KostyaEsmukov** [comment]
If the problem is long output, then you can just invoke curl slightly differently:

```
$ curl -s http://localhost | grep h1
<h1>Welcome to nginx!</h1>

$ curl -I http://localhost
HTTP/1.1 200 OK
Server: nginx/1.13.9
Date: Wed, 14 Mar 2018 09:14:43 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 20 Feb 2018 12:21:20 GMT
Connection: keep-alive
ETag: "5a8c12c0-264"
Accept-Ranges: bytes
```

**Comment by KamranAzeem** [comment]
Hi.
It is **not** a problem, I certify that.
Its just a request for minor improvement in output, making it  slick and to
the point.

Yes. I could always grep, I am aware of that .

Sometimes one simply wants to know that 'it works', without really wishing
to know what styling was uses so 'it works'!

When demo-ing to certain audiences (new comers) , especially from windows
background, one wants to focus more on showing that curl works and shows a
web page, and not let it fill the entire screen with styling code. Using
grep is always an option but that - from a student perspective - is little
complicated, and takes away focus from curl to grep.

That is why I pointed to apache/httpd.

Regards,
Kamran

**Comment by thresheek** [comment]
I don't think that justifies the change for the index.html, as we will lose the marketing part of that message, especially the nginx.com one.

**Comment by KamranAzeem** [comment]
IMHO, the marketing part of the image is just one line, which can be abbreviated to something like: 
```
<h1>Welcome to Nginx!<h1>
For commercial support, please visit https://nginx.com
```
Besides, in my opinion, people don't visit your commercial support website just because they see the advertisement on the container image's default webpage! They reach through other marketing efforts yb nginx.com . Besides, above I suggested a slick way of keeping your "marketing part" of the message.
Thanks!
