### ISSUE TITLE
Document that lua is not included and will not be supported on docker hub

### ISSUE THREAD

**Issue by alexanderkjeldaas** [nginxinc/docker-nginx#235]
It is very difficult to figure out if lua is included or not in this image.

The situation should be documented reasonably prominently on docker hub.

**Comment by williamgueiros** [comment]
I have the same problem.
i'm try fix the problem, if i go to www.test.com/index.php , OK but if try that www.test.com/index.PHp , you can see the php source code.

I'm try using, all the possible, you can see in 
https://dodwell.us/rewrite-uri-to-lowercase-using-nginxperl-nginxlua-or-apache.html

**Comment by thresheek** [comment]
@alexanderkjeldaas this build does not contain any third party module, I don't think it makes sense to document lua explicitely.  You may open a PR to document it at https://github.com/docker-library/docs/tree/master/nginx.

@williamgueiros I don't think you're in the right place to post that comment.

**Comment by alexanderkjeldaas** [comment]
@thresheek done

**Comment by TigerC10** [comment]
If I want to use this image as a base and add Lua to it, how might I do that?  Can that be documented, at least?  The typical method I would use results in:

```
[emerg] module "/etc/nginx/modules/ndk_http_module.so" version 1016001 instead of 1018000 in /etc/nginx/modules/devel_kit.conf:1
```

Or if I get the _same_ version installed, it results in:
```
nginx: [emerg] module "/etc/nginx/modules/ndk_http_module.so" is not binary compatible in /etc/nginx/modules/devel_kit.conf:1
```

Not having much luck, I'm afraid. 😅
