### ISSUE TITLE
Publish a "build" image to support custom module development

### ISSUE THREAD

**Issue by AnthonyMastrean** [nginxinc/docker-nginx#239]
I'm just getting started with custom module development and I'm having a hard time getting the exact correct prerequisites and sources downloaded properly. Would it make sense to publish a "build" image Looks like it should be something like the first ~50 lines of [this image](https://github.com/nginxinc/docker-nginx/blob/72ac2226580ee73c170163dbe6e4436373b6ece9/stable/stretch/Dockerfile#L58), except without compiling and without cleaning up.

**Comment by thresheek** [comment]
All the prerequisites are in `apt-get build-dep nginx`.

Regarding the "build" image, it might make sense yes, if it includes:
- a script to build modules from http://hg.nginx.org/pkg-oss/file/tip/build_module.sh
- a way to inject additional build depends (as third party modules might need some)
- documentation on how to use it.

PR are welcome!

**Comment by AnthonyMastrean** [comment]
Would you need a "build image" per distribution? Like, what's the `apt-get build-dep nginx` equivalent on Alpine w/ `apk`?

**Comment by dr-madatsin** [comment]
it's possible in vidual studio blend to combine multiple syntaxes try import settings under tools

**Comment by thresheek** [comment]
You'd need the binaries to be compatible to the actual tag/nginx version you're building against, so indeed, you need to build on the same distribution. For apk, we've recently introduced nginx.org prebuilt packages, so you might want to re-use those to create new module packages. See http://hg.nginx.org/pkg-oss/file/tip/alpine for more details on that.

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
