### ISSUE TITLE
Can't fetch nginx:alpine with recent push as of 27 minutes ago

### ISSUE THREAD

**Issue by eigood** [nginxinc/docker-nginx#240]
```
14:13:25 -0500 adam@tooz(master):~$ docker pull nginx:alpine
alpine: Pulling from library/nginx
no matching manifest for linux/amd64 in the manifest list entries
```

I don't know what I can do now to fix this.

**Comment by gaiaz-iusipov** [comment]
Use `nginx:stable-alpine`

Again same thing I guess https://github.com/nginxinc/docker-nginx/issues/230

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/issues/3835

**Comment by brandonfancher** [comment]
Seems like it was just a blip. Working again for me all of a sudden.

**Comment by thresheek** [comment]
Closing this one, since it's a docker infrastructure issue, and not this image issue.
