### ISSUE TITLE
Alpine Nginx does not start

### ISSUE THREAD

**Issue by ptahchiev** [nginxinc/docker-nginx#242]
When I use the `nginx:1.13.12-alpine` with docker-compose (version `docker-compose version 1.7.0, build 0d7bf73`) I get this error:
````
ERROR: for nginx  OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
````
and the container does not start. However, when I se 1.13.12 it works fine. I am on Ubuntu Linux 16.04

**Comment by thresheek** [comment]
This image does not have /bin/bash, and you probably define something else in docker-compose configuration as a cmd/entrypoint for this container. Please post it.
