### ISSUE TITLE
hwo to process two nginx to process websocket requests

### ISSUE THREAD

**Issue by moskiGithub** [nginxinc/docker-nginx#243]
Hi ,nginx team
I have a problem about two ngingx to proxy websocket request, when I use a nginx to proxy ws requests, it work correct, but when I add new nginx to process, it retuan 110 connect fail error to me .
I hope the request process is wss -> nginx -> nginx -> ws.
how I to configure two nginx for process my requests.

**Comment by thresheek** [comment]
For general support, please use mailing lists: http://nginx.org/en/support.html
