### ISSUE TITLE
status 304

### ISSUE THREAD

**Issue by geomen888** [nginxinc/docker-nginx#244]
Hi, I have problem 
172.17.0.1 - - [26/Apr/2018:12:38:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0" "-"
by command: docker run --rm -p 8000:80 nginx
OS: Ubuntu 16
Need advice. Thank U

**Comment by thresheek** [comment]
What is the problem?

**Comment by thresheek** [comment]
Closing due to response timeout.
