### ISSUE TITLE
Release image for 1.14.x?

### ISSUE THREAD

**Issue by goodspark** [nginxinc/docker-nginx#245]
nginx 1.14.0 was released recently. It would be nice to have this version released as an image as well so our local dev environments can match prod.

Thanks!

**Comment by pedrofurtado** [comment]
@thresheek Could you release the version 1.14 and publish it in Docker Hub? 👍

**Comment by thresheek** [comment]
Sorry, was on a vacation.  Filled the PR now: https://github.com/docker-library/official-images/pull/4324

**Comment by thresheek** [comment]
That seems to be another instance of https://github.com/docker-library/official-images/issues/3835
paging @tianon @yosifkit

**Comment by tianon** [comment]
Sorry about that -- our trigger server got stuck last night.  It's up now. :+1:

**Comment by goodspark** [comment]
Confirmed downloads and runs for me now. Thanks!

**Comment by shojibMahabub** [comment]
how to install 1.14.0 in base image of ubuntu 16.04
Command
`RUN apt-get install -y nginx1.14.0 `
gives this error 
`Unable to locate package nginx1.14.0`
