### ISSUE TITLE
Using envsubst in Dockerfile

### ISSUE THREAD

**Issue by jrock2004** [nginxinc/docker-nginx#248]
Looking at documentation I get `envsubst` to work when using docker-compose. On azure I cannot use that so I am trying in my dockerfile to specify a command like

```
CMD "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```

But getting this error

```
nginx | /bin/sh: envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;': not found
```

*Image Used:*: nginx:1.12.1-alpine

**Comment by yosifkit** [comment]
Since you are using the non-json syntax, drop the quotes and you should be good to go:

```dockerfile
CMD envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'
```

**Comment by learner0811** [comment]
`FROM nginx:alpine
COPY /build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx/nginx.conf /etc/nginx/conf.d
COPY nginx/nginx.template /etc/nginx/conf.d
EXPOSE 80
CMD envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'
`

Here is my dockerfile. After starting, I've checked the folder config.d and didn't find any nginx.conf file. Seem like it didn't generate any file by using envsubt. But then I jumped to interactive mode after starting and run envsubt command it did generate the file. What seem to problem in my case
