### ISSUE TITLE
TLS 1.3 not working?

### ISSUE THREAD

**Issue by dankawka** [nginxinc/docker-nginx#251]
I tried everything but I can't make TLS 1.3 work. My config:

```
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
ssl_session_timeout  10m;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off; # Requires nginx >= 1.5.9
ssl_stapling on; # Requires nginx >= 1.3.7
ssl_stapling_verify on; # Requires nginx => 1.3.7
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

Nginx container works fine but it does not accept any request, all are reset for some reason. They are not logged either. I tried with newest versions of Chrome, Firefox, curl, mobile Chrome.

Also, I was able to visit other TLS 1.3 page and Chrome confirmed it's TLS 1.3.

**Comment by thresheek** [comment]
tls v1.3 support is only available with openssl 1.1.1 (unreleased yet), so nginx in official images does not support it yet. See http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols.
