### ISSUE TITLE
NGINX doesn't start in CentOS 7.4 Docker EE 2.0, need help creating a debug build

### ISSUE THREAD

**Issue by pedrobmorales** [nginxinc/docker-nginx#253]
Hi,

I am creating an nginx docker image to host my static website.  Dockerfile below:
I can get this application's nginx instance to start in one of my deployment environments, but it does not start in my QA environment.  NGINX does not start, it just gives an error.

nginx -t gives OK in DEV and FAIL in QA.

Can you help me create a Dockerfile similar to nginx:latest (using NGINX 1.15) but with Debug information?  I would like to be able to run a Debug-binary of NGINX so that I can upload more logs and see what's going on.

----- Dockerfile -----
FROM nginx:latest

COPY ./dist/production /usr/share/nginx/html
COPY ./dist/timestamp.txt /usr/share/nginx/html/timestamp.txt
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./docker/docker-entrypoint.sh /entrypoint.sh
COPY ./docker/nginx-start.sh /nginx-start.sh
COPY ./docker/init-alp.sh /etc/init.d/nginx

RUN chmod -v +x /entrypoint.sh
RUN chmod -v +x /nginx-start.sh
RUN chmod -v +x /etc/init.d/nginx

ENTRYPOINT ["/entrypoint.sh"]

CMD /nginx-start.sh

---- Logs -----
myapp.1.omvjpg9ag81d@ip-10-212-55-140.qa.domain.com    | 2018/06/19 13:51:48 [warn] 15#15: duplicate MIME type "text/html" in /etc/nginx/conf.d/default.conf:14
myapp.1.mnujufzu2xs5@ip-10-212-55-140.qa.domain.com    | 2018/06/19 18:47:12 [warn] 15#15: duplicate MIME type "text/html" in /etc/nginx/conf.d/default.conf:14

**Comment by pedrobmorales** [comment]
This is our nginx.conf

server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # gzip compression
    gzip on;
    gzip_comp_level 6;
    gzip_vary on;
    gzip_min_length  1000;
    gzip_proxied any;
    gzip_types text/plain text/html text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_buffers 16 8k;

    location / {
        try_files $uri $uri/ /?$request_uri;
    }
}

**Comment by thresheek** [comment]
the debug binary is available under /usr/sbin/nginx-debug

**Comment by pedrobmorales** [comment]
hi,

I am getting this output still:

root@e9758317729f:/usr/sbin# ./nginx-debug -t                                                                            
nginx: configuration file /etc/nginx/nginx.conf test failed     

Also nginx-debug -V

root@e9758317729f:/usr/sbin# nginx-debug -t                                                                              
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/conf.d/default.conf:14                                       
nginx: configuration file /etc/nginx/nginx.conf test failed                                                              
root@e9758317729f:/usr/sbin# nginx-debug -V                                                                              
nginx version: nginx/1.15.0                                                                                              
built by gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)                                                                     
built with OpenSSL 1.1.0f  25 May 2017                                                                                   
TLS SNI support enabled                                                                                                  
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/e
tc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/r
un/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-
path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache
/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-a
io --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_modu
le --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with
-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_statu
s_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_real
ip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builde
r/debuild/nginx-1.15.0/debian/debuild-base/nginx-1.15.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-s
trong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-specs=/usr/share/dpkg/no-pie-link.s
pecs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' --with-debug

**Comment by thresheek** [comment]
You should check /etc/nginx.conf and everything included from it manually.

**Comment by pedrobmorales** [comment]
hi @thresheek thanks we are looking.  the nginx.conf and default.conf work perfectly well in another of our environments.

**Comment by pedrobmorales** [comment]
unfortunately /usr/sbin/nginx-debug does not emit any more log output than /usr/sbin/nginx.

Is there anything that we can put in nginx.conf to make sure it logs absolutely everything?

**Comment by thresheek** [comment]
No. I suggest you check your startup scripts, differences between the environments this runs on, etc.  Does not look like a nginx-docker issue to me.
