### ISSUE TITLE
Upgrade to alpine 3.8

### ISSUE THREAD

**Issue by mrcasablr** [nginxinc/docker-nginx#254]

**Comment by thresheek** [comment]
No. There is no alpine:3.8 tag on https://github.com/docker-library/official-images/blob/master/library/alpine afaict.  Also, what real problem does it solve?

**Comment by mrcasablr** [comment]
This issue was a placeholder for 3.8 upgrade. https://alpinelinux.org/posts/Alpine-3.8.0-released.html
It is now tagged for 3.8

**Comment by tburschka** [comment]
Any chance to switch to Alpine 3.8?

A real problem: merging multiple images (like php and nginx) into one container seems to require same alpine version.

**Comment by m9rco** [comment]
+1
