### ISSUE TITLE
Difference between stable and mainline '400 Bad Request - The plain HTTP request was sent to HTTPS port'

### ISSUE THREAD

**Issue by TheWolfNL** [nginxinc/docker-nginx#256]
Okay so I've got a setup where want to move to the stable branch.
I changed `FROM nginx:1.13.12-alpine` to `FROM nginx:1.14.0-alpine` and things stopped working.

I then get `400 Bad Request - The plain HTTP request was sent to HTTPS port` where previously I got the desired content with the `1.13.12` version.

When I changed it to `FROM nginx:1.15.1-alpine` It works again.

Between changing these versions and testing it, I changed nothing.
This leads me to a conclusion that there are some differences between the `stable` and `mainline` branch. I think these differences are unintended and undesirable, so I'd like to help in getting rid of this  behaviour.

**Comment by thresheek** [comment]
Please provide full logs and example requests output, so we could try to reproduce.

**Comment by TheWolfNL** [comment]
After some more investigation I found that there was a misconfiguration in the docker image I was using.
