### ISSUE TITLE
Using templates is broken

### ISSUE THREAD

**Issue by youroff** [nginxinc/docker-nginx#258]
Alpine image (not sure about other images) uses envsubst to replace ENV variables in config template on run. This unfortunately affects runtime variables as well. Here's the example from documentation:

```
command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
```

Here's the example of template that breaks:
```
 location @app {
      proxy_redirect off;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://backend;
}
```

And this is what it ends up with: 
```
location @app {
       proxy_redirect off;
       proxy_set_header X-Forwarded-For ;
       proxy_set_header Host ;
       proxy_set_header X-Forwarded-Proto ;
       proxy_pass http://backend;
 }
```

Not sure how this can be fixed, since these vars are pretty common in nginx configs and they are being vanished by envsubst.

**Comment by youroff** [comment]
After a bit of research I ended up using `esh`, ruby-style templating engine for shell, instead of `envsubst`. Only explicitly marked snippets get evaluated, so that if `SOME_VAR=5` then `<%= $SOME_VAR %> $runtime_var` will be evaluated into `5 $runtime_var`.

**Comment by thresheek** [comment]
You can actually use the same trick by specyfing only the variables you need replacing with envsubst as well.  See https://github.com/docker-library/docs/issues/496 for more details.
