### ISSUE TITLE
latest: Pulling from library/nginx no matching manifest for unknown in the manifest list entries

### ISSUE THREAD

**Issue by techhounds2015** [nginxinc/docker-nginx#266]
Getting error 
latest: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries

**Comment by tianon** [comment]
Sounds like a broken Docker installation (it doesn't know what platform it
should pull).

**Comment by techhounds2015** [comment]
Any idea how to fix this? I did reinstallation many times and nothing works. 
tried: 
docker pull ngix:stable too but it doesnt work

**Comment by tianon** [comment]
Are you able to successfully pull any other images?  I'd recommend trying
the Docker forums or community slack for more help debugging your install.

**Comment by techhounds2015** [comment]
not i tried ubuntu mysql nothinng works. 

I am on slack as tarun.mahajan@puresoftware.com we can connect there

**Comment by thresheek** [comment]
Closing as it's not an nginx image issue.

**Comment by mansetaashok** [comment]
I have a same error : "Pulling from library/node
no matching manifest for unknown in the manifest list entries"

I am building Azure Pipeline for my Nodejs application using Host VS2017 agent. My application is working fine in my local system, However while doing DevOps pipeline setup the error encountered.

I have also tried different versions of node as base image in my docker file. But no luck.

![image](https://user-images.githubusercontent.com/40860482/57123451-31314780-6d82-11e9-92c5-ac89884a04ac.png)


Can anyone please help for the same.
