### ISSUE TITLE
How to set which libstdc++.so.6.* version to load within docker container? 

### ISSUE THREAD

**Issue by sulabhaP** [nginxinc/docker-nginx#267]
src/lda: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by src/lda)

please help me

**Comment by sulabhaP** [comment]
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIB 
I got following result for above command:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.18
GLIBC_2.3.4
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by sulabhaP** [comment]
Added LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu" to my Dockerfile also. then freshly build the image, still not working. please help me.

thanks in advance....

**Comment by thresheek** [comment]
Closing as not nginx related. You can try https://forums.docker.com/ for questions like that.
