### ISSUE TITLE
How to make it support accept-language module

### ISSUE THREAD

**Issue by daoudi5** [nginxinc/docker-nginx#268]
Hi,
I'm trying to use Accept-Language header to give the most suitable locale for the user from a list of supported locales from your website.
Is this version support it? 
How to install : https://www.nginx.com/resources/wiki/modules/accept_language/#accept-language-installation
Where to found Nginx folder?
Thanks

**Comment by thresheek** [comment]
No, this module is not included in this image since it's a third-party one. You can use a workaround as described in https://www.nginx.com/resources/wiki/modules/accept_language/#alternative

**Comment by daoudi5** [comment]
Ok, thanks for your answer. I tried to change Nginx.conf but I got this error : [emerg] 1#1: "set" directive is not allowed here in /etc/nginx/nginx.conf:32
nginx: [emerg] "set" directive is not allowed here in /etc/nginx/nginx.conf:32
Do you know how to use the alternative method described in : https://www.nginx.com/resources/wiki/modules/accept_language/#alternative

Thank you for your help

**Comment by thresheek** [comment]
You need to use "set" in the server context instead of http.

**Comment by daoudi5** [comment]
OKay thank you vey much :)

**Comment by anirbandas18** [comment]
this link seems to not be valid anymore
https://www.nginx.com/resources/wiki/modules/accept_language/#alternative
