### ISSUE TITLE
Change user?

### ISSUE THREAD

**Issue by amouat** [nginxinc/docker-nginx#27]
Does nginx have to run as root? It would be much better for security if it set-up a separate user. 

Note that users with volumes will have a short-term problem if you make this change.

**Comment by thresheek** [comment]
nginx master proccess has to run as root as it has to bind to port 80, worker proccesses are run as the user specified in the configuration.

If you are aware of security issues with this approach, please share.

**Comment by amouat** [comment]
Ah, I should have realised that.

The main problem is that if the container gets hacked and a breakout occurs, the attacker will have root privileges on the host. Similarly, they can do whatever they like to any mounted volumes (unless locked down with SELinux, --read-only or similar).

In a lot of cases, users don't actually need to bind port 80 in the container as it often gets forwarded or is only used internally. I wonder if a secondary image that doesn't run as root would be useful.

**Comment by thresheek** [comment]
I think this is out of scope and should be fixed by the docker project by using user namespaces instead of patching every image and introducing weird setup tricks.

**Comment by amouat** [comment]
I just had a poke around; in case anyone is wondering, the user is defined in nginx.conf to be nginx by default.

Currently, the nginx user has UID 101 and GID 102, www-data has UID 33 and GID 33. It might be useful to document this in the readme.

Closing is fine, I don't think there's much that can be done without confusing users. I also hadn't realised worker processes had a different user (it showed up as "syslog" in docker top which threw me - this was because  UID 101 is different on my host)

**Comment by iszak** [comment]
Sorry for commenting on an old ticket, but I thought it might be useful for those who want to run nginx as non-root.

This in theory should be possible, as you can give the capability [NET_BIND_SERVICE](http://man7.org/linux/man-pages/man7/capabilities.7.html) which allows the binary to "Bind a socket to Internet domain privileged ports (portnumbers less than 1024)." unfortunately I could not get this to work with docker.

I was able to however in my Dockerfile set the nginx binary to have this capability by setting it as effective and permitted e.g. `setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx` this allows me to bind to ports < 1024 such as 80 irrespective of whether I set NET_BIND_SERVICE or not in docker.

**Comment by amouat** [comment]
iszak: The Docker capabilities affect the container, not the user. By default, a container does have the NET_BIND_SERVICE capability. If you remove it (--cap-drop NET_BIND_SERVICE iirc), you should find that your container doesn't work regardless of setcap etc.

What you could do is create a container that drops most privileges except NET_BIND_SERVICE and whichever other privileges are essential to it's operation.

I was being stupid when I opened this ticket, but I like the setcap suggestion.

**Comment by iszak** [comment]
@amouat That explains it, an alternative to my setcap solution is to just use a higher port than 1024, this will allow us to run nginx as non-root and then just give the container NET_BIND_SERVICE (which as you stated is default) to bind it to the host machine and forward for >1024 port on the container to < 1024 on the host.

**Comment by amouat** [comment]
Yes, and I don't think you'd even need NET_BIND_SERVICE for that.
