### ISSUE TITLE
unable to docker cp alpine:/etc/nginx .

### ISSUE THREAD

**Issue by chaiguifeng007** [nginxinc/docker-nginx#276]
system:centos7.5 Docker version 18.06.1-ce, build e68fc7a docker image:nginx:1.14.0-alpine

i want to cp /etc/nginx to host,i get the following err

docker cp alpine:/etc/nginx . invalid symlink "/tmp/nginx/modules" -> "../../usr/lib/nginx/modules"

**Comment by thresheek** [comment]
It looks like a docker cp problem, not an nginx image one.
