### ISSUE TITLE
Dash application opens with http instead of https

### ISSUE THREAD

**Issue by Anusha2605** [nginxinc/docker-nginx#278]
Dash application loads properly with http but page does not load with https.
Docker logs of the web application tells that application is running as expected. But logs of Ngnix tells something like below:

2018/09/29 06:41:17 [error] 43#0: 4741 open() "/usr/share/nginx/html/_dash-component-suites/dash_renderer/react@15.4.2.min.js" failed (2: No such file or directory), client: 172.31.135.12, server: ~^[0-9], request: "GET /_dash-component-suites/dash_renderer/react@15.4.2.min.js?v=0.14.1&m=1538144648 HTTP/1.1", host: "xxxx", referrer: "https://xxxx/rdh"

2018/09/29 06:41:17 [error] 43#0: 4735 open() "/usr/share/nginx/html/_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js" failed (2: No such file or directory), client: 172.31.135.12, server: ~^[0-9], request: "GET /_dash-component-suites/dash_renderer/react-dom@15.4.2.min.js?v=0.14.1&m=1538144648 HTTP/1.1", host: "xxxx", referrer: "https://xxxx/rdh"

Dockerfile of Dash Application is as below:
FROM python:2.7.15

WORKDIR /usr/src/rdh

ENV PATH /usr/src/rdh:$PATH
#RUN yum -y install python-pip
RUN pip install dash \
                dash_core_components \
                dash_html_components \
                datetime \
                pymongo \
                Flask \
                gunicorn \
                dash-renderer

COPY . .

CMD [ "gunicorn", "--bind", "0.0.0.0:3005", "wsgi:server" ]

ngnix configuration

location ^~ /rdh {

    proxy_pass  http://rdh:3005;
    proxy_set_header Connection "upgrade";
    proxy_set_header  X-Forwarded-Ssl on;
    proxy_set_header  X-Forwarded-For $remote_addr;
    proxy_set_header  Host $host;
}
please let me know where am going wrong

**Comment by thresheek** [comment]
Please consult the support of "dash application".
