### ISSUE TITLE
Error 502 Bad Gateway when upgrade host container

### ISSUE THREAD

**Issue by Arsmn1996** [nginxinc/docker-nginx#283]
nginx shows Bad Gateway error for a while time when i upgrade other host containers.
I know it is cache problem but  i don't know how to resolve it.
Error log:

> connect() failed (111: Connection refused) while connecting to upstream

**Comment by thresheek** [comment]
That error means that nginx was not able to connect to the backend server.  Check why that backend server fails.

**Comment by Arsmn1996** [comment]
backend server works properly right after update is done.
I use curl from inside of docker and all backend servers are working correctly
but nginx does not work for about 2 or 3 minutes.

**Comment by thresheek** [comment]
You can configure max_fails and/or fail_timeout to minimize that time: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server . I suggest reading https://docs.nginx.com/nginx/admin-guide/ too.
