### ISSUE TITLE
nginx container unable to pick the container's /etc/hosts file

### ISSUE THREAD

**Issue by princejha95** [nginxinc/docker-nginx#284]
I am running the nginx container and i want that the container should perform the DNS mapping by using the container's /etc/hosts file. But instead of that, the container is using the host's machine /etc/hosts file for DNS mapping.

Can anyone provide a solution for this ? I am using nginx v1.15.5

**Comment by tlc** [comment]
nginx does not use /etc/hosts for proxy_pass.  The standard answer for (non-docker) nginx is to run dnsmasq, which is not a good solution for the docker image.

Also, the docker-compose.yml element 'extra_hosts' works by writing /etc/hosts.  So 'extra_hosts' does not work for docker-nginx.

**Comment by silencej** [comment]
For docker-compose, using an extra dnsmasq container may be a solution.

**Comment by thresheek** [comment]
I'm not sure where the idea that `/etc/hosts` doesnt work for nginx comes from. nginx will use information from there when starting up, so maybe your `/etc/hosts` in the container isnt populated when nginx starts?

Anyhow, the following works fine here:
```
$ cat docker-compose.yml
nginx:
  image: 'nginx:1.19.7-alpine'
  volumes:
  - ./configs/proxy.conf:/etc/nginx/conf.d/default.conf:ro
  extra_hosts:
    - "somehost:127.0.0.1"
    - "otherhost:127.0.0.2"
  ports:
    - '80:80'
```
```
$ cat configs/proxy.conf
upstream backends {
        server somehost:8888;
        server otherhost:8888;
}

server {
    listen 80;
    location / {
        proxy_connect_timeout 1s;
        proxy_pass http://backends;
    }
}

server {
    listen 8888;
    location / { return 200 '$server_addr\n'; }
}
```
After `docker-compose up -d`:
```
$ curl http://127.0.0.1/asdfasdf  
127.0.0.1
$ curl http://127.0.0.1/asdfasdf
127.0.0.2
```
```
$ docker exec -ti myapp_nginx_1 cat /etc/hosts 
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1       somehost
127.0.0.2       otherhost
172.17.0.3      5395310df226
```
