### ISSUE TITLE
nginx-dav-ext module missing in alpine image

### ISSUE THREAD

**Issue by richardbrinkman** [nginxinc/docker-nginx#286]
The Debian based image provides the [nginx-dav-ext module](https://github.com/arut/nginx-dav-ext-module). The Alpine version version lacks this module, which in my view is inconsistent. Can this module be included in the Alpine version as well?

**Comment by thresheek** [comment]
Hello, I believe you are wrong - the stretch-based image does not have the dav-ext module.

**Comment by richardbrinkman** [comment]
You are right. But with a simple `apt-get install libnginx-mod-http-dav-ext` or `apt-get install nginx-extras` it's easy to extent the debian based image. For example:

```
FROM nginx:latest
RUN apt-get update && apt-get install -y nginx-extras
```

For the nginx:alpine version this is impossible since Alpine does not have an nginx-dav-ext like module (nor does the nginx:alpine version pull in the nginx package from apk but compiles from scratch). Therefore I still think that the addition of my pull request is useful. It's only marginally bigger in size and I see no other disadvantages.

**Comment by thresheek** [comment]
I doubt libnginx-mod-http-dav-ext from Debian will work with nginx.org-provided nginx packages and binaries.  What that command does is it effectively replaces nginx.org binaries with Debian ones, and that is not something supported by this image.  Therefore, there is no reason to support it in alpine builds.

**Comment by KostyaEsmukov** [comment]
@richardbrinkman

> I see no other disadvantages.

I see a dozen. To name a few:
1. https://github.com/arut/nginx-dav-ext-module.git module (as proposed in #287) is provided by a third party which nginx inc cannot be responsible for, yet it is possible for them to break the official nginx docker image with an erroneous/malicious code pushed to that repo.
2. That PR being merged in would set a precedent which would be an excuse for adding more and more other third party modules. I can't help it but compare this to the [Broken windows theory](https://en.wikipedia.org/wiki/Broken_windows_theory).
3. Each module is a subject for maintenance, i.e. watching for compatibility, interoperability, security issues and updates. Handing this liability over to this docker image maintainers is rather unfair.

Your specific issue could be easily resolved by forking this repo, introducing required changes (the ones you did in #287) and setting up an [automated] build on docker hub. Of course you will have to maintain that image by yourself.

@thresheek I believe that adding custom modules to this image is a quite common issue, yet I cannot find any documentation on the supposed/endorsed way of handling this. Am I missing it, or it doesn't actually exist?

**Comment by thresheek** [comment]
The documentation is at https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/ - maybe we should link it from the docs to the image.

Basically you need to fetch nginx source codes, and run the configure & make and copy the module to the resulting image. 

I thought about providing something like a "build env" image tag, but then again there is no guarantee this image holds anything you'd need to build a new custom module - e.g. third party modules can depend on third-party libraries...  Even then, after you built the module you would need to copy/add the file to a new image, and then recompile the module every time the base image is updated.  In my book, that's not much different than just forking the repo and the image, and is actually more work to do.

**Comment by KostyaEsmukov** [comment]
> The documentation is at https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/ - maybe we should link it from the docs to the image.

This page is definitely helpful, however, it doesn't cover the aspects of packaging nginx with docker.

> I thought about providing something like a "build env" image tag, but then again there is no guarantee this image holds anything you'd need to build a new custom module - e.g. third party modules can depend on third-party libraries...

I don't think that running apt/apk/etc for adding extra deps in a separate `RUN` stage is an issue. What really seems to be the issue, IMO, is the layout of the Dockerfiles in this repo. 
1. Would the current nginx image depend on that `build` image using `FROM`? If so, then all the build stuff would be preserved in the docker image layers, which would significantly increase the resulting image size.
2. Would the new `build` image Dockerfile contain the copy-pasted beginning of the current `nginx` image Dockerfile? That will be quite error-prone from the maintenance point of view, I believe.

Perhaps there's another (better) layout I didn't think of?
(#239 seems to be a better place for this discussion -- we can move it there if you prefer).

> In my book, that's not much different than just forking the repo and the image, and is actually more work to do.

I'd agree that forking seems to be the easiest solution as for now, hovewer, this is definitely not an obvious one for the newcomers, and also is more complex in terms of maintenance for them.

I think that having at least a little section at https://hub.docker.com/_/nginx/ discussing the available approaches for adding custom modules would be very helpful. Do you think you could add that, or you'd prefer to consider accepting a PR from someone instead?

**Comment by thresheek** [comment]
> > I thought about providing something like a "build env" image tag, but then again there is no guarantee this image holds anything you'd need to build a new custom module - e.g. third party modules can depend on third-party libraries...
> 
> I don't think that running apt/apk/etc for adding extra deps in a separate `RUN` stage is an issue. What really seems to be the issue, IMO, is the layout of the Dockerfiles in this repo.
> 
>     1. Would the current nginx image depend on that `build` image using `FROM`? If so, then all the build stuff would be preserved in the docker image layers, which would significantly increase the resulting image size.

It will definitely not depend on the build image exactly for the reason you mentioned.
 
>     2. Would the new `build` image Dockerfile contain the copy-pasted beginning of the current `nginx` image Dockerfile? That will be quite error-prone from the maintenance point of view, I believe.

 Indeed, error-prone, but what other choices do we have? I don't really see other options here.

> I'd agree that forking seems to be the easiest solution as for now, hovewer, this is definitely not an obvious one for the newcomers, and also is more complex in terms of maintenance for them.
> 
> I think that having at least a little section at https://hub.docker.com/_/nginx/ discussing the available approaches for adding custom modules would be very helpful. Do you think you could add that, or you'd prefer to consider accepting a PR from someone instead?

Please do a PR.

**Comment by J0WI** [comment]
Here is what the PHP image does to prevent overwriting binaries:
https://github.com/docker-library/php/blob/master/Dockerfile-debian.template#L3-L10

**Comment by vizshrc** [comment]
You can try it.This is my nginx.I make it today.
https://github.com/vizshrc/Full-WebDAV-Nginx-Docker

**Comment by mcarbonneaux** [comment]
alpine has this package: 
https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx-mod-http-dav-ext

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
