### ISSUE TITLE
directory index of "/usr/share/nginx/html/ is forbidden

### ISSUE THREAD

**Issue by karthik11c** [nginxinc/docker-nginx#289]
Currently I am Running nginx container inside docker in windows.when i mount a volume to container
it show directory index of "/usr/share/nginx/html/ is forbidden

**Comment by thresheek** [comment]
Enable http://nginx.org/r/autoindex for that directory.

**Comment by patrolez** [comment]
Hello,
I wonder if it would be possible to make minimal effort simple one-liner docker container invocation to serve:
`/usr/share/nginx/html` with `autoindex on`

I think it would be good idea to configure it via environment variable.

**Comment by cleveritcz** [comment]
This is not good settings for production servers
