### ISSUE TITLE
no --with-ipv6 module in nginx image

### ISSUE THREAD

**Issue by 404xiaochaochao** [nginxinc/docker-nginx#293]
I couldn't find "--with-ipv6" flag in nginx configure arguments after starting nginx container.  As a result, ipv6 request cannot be handled by nginx in container even though i set "listen [::]80;" ....   I try to add this flag to official Dockerfile and build it 。 “--with-ipv6” flag occures, but nginx still ignores ipv6 request.   
Can anyone provide a solution for this ? I am using latest nginx.

**Comment by thresheek** [comment]
ipv6 is always enabled these days, check with ss -ln or netstat if nginx listens on ipv6 address.

**Comment by 404xiaochaochao** [comment]
Thanks your reply,  it does listen ipv6 address like "tcp6     0   0 :::9990    :::*        LISTEN     42502/docker-proxy，but request like "Http://[nignx host address]:9990" will be refused to access.  check with telnet , this port is accessble (Firewall  has been shutdown before)

**Comment by thresheek** [comment]
check if nginx listens inside the container, not on the host.
