### ISSUE TITLE
nginx won't start on alpine stable image

### ISSUE THREAD

**Issue by yahavb** [nginxinc/docker-nginx#302]
The bug: nginx image form docker-nginx/stable/alpine/ is not starting 

**To Reproduce**
* git clone 
* docker build .
* docker run -it image /bin/sh

**Expected behavior**
nginx process runs as indicated by the command in the Dockerfile `CMD ["nginx", "-g", "daemon off;"]`
Also, no `/etc/init.d/nginx` exists

`nginx -t` is successful 
```
/ # nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by yahavb** [comment]
I ended using the Debian version

**Comment by thresheek** [comment]
When you run 
docker run -it image /bin/sh
you're running /bin/sh inside the image, not nginx.  It's a wrong way to do it.
