### ISSUE TITLE
Use alpine linux 3.9.0

### ISSUE THREAD

**Issue by mrcasablr** [nginxinc/docker-nginx#305]
Alpine linux 3.9.0 is just released - https://alpinelinux.org/posts/Alpine-3.9.0-released.html

**Comment by gdzien** [comment]
There are no official docker images for alpine:3.9 at the moment.

**Comment by code-chris** [comment]
When https://github.com/docker-library/official-images/pull/5367 is merged, they should be available short after that.

**Comment by thresheek** [comment]
Alpine 3.9 is used in mainline/stable builds now.
