### ISSUE TITLE
no ssl_early_data in nginx:1.15.8 because of missing TLS 1.3 support in OpenSSL 1.1.0

### ISSUE THREAD

**Issue by drwetter** [nginxinc/docker-nginx#309]
Hello,

did a ``docker pull nginx:1.15.8`` because I wanted to do some experiments with 0-RTT. 
If I start nginx it's telling me ``nginx: [warn] "ssl_early_data" is not supported on this platform, ignored``.

Nginx documentation (https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_early_data) states ``This directive appeared in version 1.15.3. ``. 

Does _appeared_ mean _supported_ and the container's nginx is just missing a piece?

Cheers, Dirk

**Comment by Ran-snow** [comment]
TLS1.3 is not enabled by default

**Comment by drwetter** [comment]
I should have added that per default I enable this like:

```
root@95eed784a081:/etc/nginx/conf.d# cat 443.conf

server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        server_name _;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_early_data on;
        #
        ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
```

**Comment by drwetter** [comment]
You have a point though. From the outside it looks like it's being not offered:

```
./testssl.sh -q -p 172.17.0.2
 
 Start 2019-02-15 16:26:00        -->> 172.17.0.2:443 (172.17.0.2) <<--

 rDNS (172.17.0.2):      --
 Service detected:       HTTP


 Testing protocols via sockets except NPN+ALPN

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    not offered
 NPN/SPDY   http/1.1 (advertised)
 ALPN/HTTP2 http/1.1 (offered)

 Done 2019-02-15 16:26:03 [   6s] -->> 172.17.0.2:443 (172.17.0.2) <<--
```
```
root@95eed784a081:/etc/nginx/modules# nginx -V 
nginx version: nginx/1.15.8
built by gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
built with OpenSSL 1.1.0j  20 Nov 2018
[..]
````
So, no wonder. I didn't install OpenSSL 1.1.0, it was just automatically pulled. Besides TLS 1.3. it's also missing X448.

**Comment by Ran-snow** [comment]
You can try https://github.com/Ran-snow/docker-nginx

**Comment by drwetter** [comment]
thanks, will try. 

Maybe the maintainers here upgrade their nginx image to Debian buster which has TLS 1.3 in openssl 1.1.1. (Strange enough: Debian sid has still nginx 1.14.)

**Comment by drwetter** [comment]
@Ran-snow: Got your image working, thank you!

**Comment by thresheek** [comment]
Stretch ships 1.1.0 which doesnt have TLS 1.3, hence the error.

When Debian releases buster, we'll switch the images to use it, but not before an official release.

**Comment by drwetter** [comment]
It has freezed already https://wiki.debian.org/DebianBuster, so maybe the impact of switching soon on the little amount of binaries provided is not that big.

While I appreciate that this container has been offered: can the documentation add what's not possible at the moment?
