### ISSUE TITLE
Nginx dockerfile

### ISSUE THREAD

**Issue by chanikyakarnati4008** [nginxinc/docker-nginx#311]
What are the commands to use nginx docker file in mac 

# Usage : nginx
FROM nginx

#RUN apt-get install -y nginx

#RUN apt-get update

RUN nginx

#EXPOSE:80

**Comment by gdzien** [comment]
Hello @chanikyakarnati4008

Please refer to docker build documentation on how to work with Dockerfile 
https://docs.docker.com/engine/reference/commandline/build/

You can also find some extra resources on how to use built image by accessing documentation mentioned in a README of this repository:
https://github.com/docker-library/docs/tree/master/nginx#how-to-use-this-image

Sincerely,
Grzegorz

**Comment by thresheek** [comment]
@chanikyakarnati4008 please see https://hub.docker.com/_/nginx/ on how to use this image.  Thank you.
