### ISSUE TITLE
How to reduce the nginx image size for mac

### ISSUE THREAD

**Issue by chanikyakarnati4008** [nginxinc/docker-nginx#315]
How to reduce the nginx image size for mac

**Comment by thresheek** [comment]
Use nginx:alpine image.

**Comment by chanikyakarnati4008** [comment]
Thanks for the update..

My docker file instructions.

FROM nginx:alpine
RUN apt update 
RUN apt install -y nano wget dialog net-tools 
RUN apt install -y nginx
WORKDIR /
EXPOSE 80
CMD /usr/sbin/nginx -g "daemon off;"


I am getting error message for the above docker file .

Step 2/7 : RUN apt update
 ---> Running in cd12744d9ec5
/bin/sh: apt: not found
The command '/bin/sh -c apt update' returned a non-zero code: 127

Please help me to resolve the issue

**Comment by thresheek** [comment]
nginx is already installed in the image, you don't need to install it afterwards.
