### ISSUE TITLE
COPY nginx.conf not working correctly

### ISSUE THREAD

**Issue by tstivers1990** [nginxinc/docker-nginx#316]
I'm running the mainline/stretch docker image.

Here is my Dockerfile:

```
FROM nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
```

I built an image using this. I'm running this image. If I run `docker exec nginx nginx -T` it dumps the correct version of the file.

If I start an instance with -it and then `cat /etc/nginx/nginx.conf` from that instance, it shows me the correct nginx.conf.

If I run `docker run --rm nginx cat /etc/nginx/nginx.conf` though, it shows me an outdated nginx.conf.

If I do some testing, such as commenting out a line, restarting the container, and then testing to see if the comment takes effect, it doesn't work. For example, comment out a server, rebuild, pull, restart, then try to open that domain name in a browser. The domain name still loads as though it was never commented out.

I've removed the container multiple times, restarted it multiple times. No matter what I do, I can't seem to get my configuration to actually take update.

For clarity, the nginx.conf successfully copied over at least a few times. It *appears* to be the most up to date version depending on what command you run. But it *acts* like the configuration is old. At some point, it was updating the nginx.conf. But at some point, it stopped working.

**Comment by tstivers1990** [comment]
So the problem isn't on the build end. This is probably an issue with docker itself. I managed to resolve the problem by removing the container and running `docker system prune`, which removed the cached images. Still odd that it appeared to be up to date, yet wasn't actually.

**Comment by tstivers1990** [comment]
And upon doing a new build, the image fails to update again.

**Comment by tstivers1990** [comment]
Note to self: latest is not actually latest.

**Comment by tstivers1990** [comment]
Nevermind. This is still a problem when using a different tag, like `production`. It's not a problem I have with any other container...

**Comment by yosifkit** [comment]
> For example, comment out a server, rebuild, pull, restart, then try to open that domain name in a browser.

Was there a `docker push` from the building server before you did that `pull` on the one running it? Ideally you'd use a version or build number `docker build -t my-user/nginx:1.0.2 .` and then `docker push my-user/nginx:1.0.2`, then after an new update it would be `docker build -t my-user/nginx:1.0.3` with its respective `push`.

It seems some of your commands are using the default `nginx` image, while others are using `docker exec` on a container created from your Dockerfile. Are you perhaps naming your local image `nginx` and then doing a `docker pull nginx` (or `docker build --pull`)?

**Comment by tstivers1990** [comment]
@yosifkit The problem was I was trying to update a container created with `docker create` and apparently you can't do that. You have to recreate the container.

**Comment by aishtiaq7** [comment]
This facing this issue on June 5th 2023. 
Anyone with a fix?
