### ISSUE TITLE
Add njs module in the alpine image

### ISSUE THREAD

**Issue by drasko** [nginxinc/docker-nginx#317]
I have noticed that `njs` module is present in the [official `1.15.9` verion based on `debian-stretch-slim`](https://github.com/nginxinc/docker-nginx/blob/7890fc2342613e6669ad83ceead9c81136d2cc0a/mainline/stretch/Dockerfile#L6) , but it is missing in the [`alpine` version](https://github.com/nginxinc/docker-nginx/blob/7890fc2342613e6669ad83ceead9c81136d2cc0a/mainline/alpine/Dockerfile).

Will it be added to `alpine` docker soon?

**Comment by thresheek** [comment]
Hello @drasko.

Indeed, we need to add it to the alpine docker image and this is something I've planned to do since the availability of alpine packages from nginx.org a few weeks ago.  I'd prioritize this one, but no ETA for now.

**Comment by thresheek** [comment]
Hey @drasko it would be very nice if you could test building the images & running your stuff on from the https://github.com/nginxinc/docker-nginx/tree/alpine-nginxorg branch -- thanks in advance.

**Comment by lesv** [comment]
I was successfully able to use it.

**Comment by thresheek** [comment]
That's great @lesv! Thank you.

I'm planning to merge the branch today, for nginx+njs alpine builds to be available via docker hub in a next couple of days.

**Comment by thresheek** [comment]
The njs module is available in :stable tags.  I'll close the issue once we have a 1.17.0 release for the mainline and they'll also pick it up.

**Comment by thresheek** [comment]
All done.
