### ISSUE TITLE
Can't change root password to ssh

### ISSUE THREAD

**Issue by sculptsoft-devs** [nginxinc/docker-nginx#318]
I am using the latest nginx image (nginx:latest). I want to get into the container with ssh which is running on a remote machine. 

I tried    RUN echo 'root:mypass' | chpasswd. 

But when I am trying to ssh into the container with username: root and password: mypass, it gives me Access denied.

I tried this with Ubuntu:latest image and it worked fine there.

Any advise how I can achieve ssh into the container with root. Also, I tried by creating a new user but I require root as I want to change files in there.

**Comment by thresheek** [comment]
nginx:latest doesnt ship a ssh server.  We don't provide support for any modifications to the image, sorry.
