### ISSUE TITLE
version 1.14.2 of nginx.pm is required, but 1.15.12 was found

### ISSUE THREAD

**Issue by mwlczk** [nginxinc/docker-nginx#325]
image: nginx:alpine-perl (5e55d328750c)
trying to load the module ngx_http_perl_module.so is not possible either from nginx.conf nor as a parameter of CMD in the Dockerfile.

I get either this error:
`module "/usr/lib/nginx/modules/ngx_http_perl_module.so" version 1015012 instead of 1014002`  
or this one, which seems the same:
`version 1.14.2 of nginx.pm is required, but 1.15.12 was found.`

**Comment by mwlczk** [comment]
the nginx:stable-alpine-perl image has the same version 1.14.2-r0 as the alpine 3.9 packages.
additionally to ngx_http_perl_module I am installing the ngx_stream_module via apk add from the official alpine repositories.
i guess this overwrites some binaries build in the image building process.

is there a way to be able to use both modules:
`ngx_stream_module` and `ngx_http_perl_module` at the same time?

**Comment by thresheek** [comment]
You don't need to install the ngx_stream_module via apk, if you're using nginx:alpine-perl image, it's already built-in in the main binary.

See `nginx -V`, --with-stream is there.

**Comment by stevenroose** [comment]
I keep getting this error:

```
nginx_1          | 2019-04-29T14:35:56.897519000Z nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_perl_module.so" failed (Error loading shared library /etc/nginx/modules/ngx_http_perl_module.so: No such file or directory) in /etc/nginx/nginx.conf:1
```

**Comment by mwlczk** [comment]
@stevenroose if you are on nginx:alpine-perl, then you should use in your nginx.conf:
load_module /usr/lib/nginx/modules/ngx_http_perl_module.so;
