### ISSUE TITLE
How to enable ldap_server ?

### ISSUE THREAD

**Issue by danielsss** [nginxinc/docker-nginx#326]
- Is the docker-nginx supported to enable it?
- How can I open it if ldap supported

##### Image version
```shell
# docker image ls nginx
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               1.15.12             27a188018e18        8 days ago          109MB
```

**Comment by thresheek** [comment]
If you refer to https://github.com/kvspb/nginx-auth-ldap, then no, it's not possible to use it with this image.

It's possible to use https://github.com/nginxinc/nginx-ldap-auth though.

**Comment by danielsss** [comment]
@thresheek thanks

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
