### ISSUE TITLE
apk not found error during compilation on armhf

### ISSUE THREAD

**Issue by encodeering** [nginxinc/docker-nginx#327]
Hi, 

it seems that the environment is either cleared to greedy with [su -](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L63), especially the `$PATH` variable, or that the path of `apk` has changed in the meantime, which is `/sbin/apk` now.

I receive the following error when building on arm.

```
/usr/bin/abuild: line 1233: apk: not found
>>> ERROR: nginx*: create_apks failed
>>> ERROR: nginx: rootpkg failed
```

I fixed this temporarily by dropping `-` from the command and won't expect any problems with the parental environment here -- the `$HOME` variable is also set the beginning.

Hope that this info can help. Cheers

**Comment by thresheek** [comment]
Hi @encodeering.  I don't think we hit that issue with the official images otherwise I'd be notified when it broke.  Can you please elaborate on how you're building things? Thank you.

**Comment by encodeering** [comment]
Hi @thresheek, yes that's also a good point. 

I am using an alpine image that has been generated with [mkimage-alpine](https://github.com/moby/moby/blob/master/contrib/mkimage-alpine.sh) from moby. I had to call `RUN apk fix` afterwards. A typical build log looks like [this](https://api.travis-ci.org/v3/job/530872333/log.txt)
That image contains `qemu-arm-static` in version `2.6.0` in order to build this on public CI servers, but I do this for many images and haven't seen any bigger issue with qemu so far - besides some go topics from time to time.

However, you are right, that the offical alpine image from the docker hub behaves different to the image that I described above in terms of the `su` command. I tested a few commands inside of each container, but don't get to the point where they differ and am not sure where `su` is configured on alpine at all.

Would you be willing to accept a PR regarding the slash? I would otherwise keep it as a patch internally.

Cheers

**Comment by thresheek** [comment]
Please do a PR.

**Comment by encodeering** [comment]
Thank you @alessfg and @thresheek for taking the time to bring this into master.
