### ISSUE TITLE
Nginx Mainline is lower version than stable (need 1.17)

### ISSUE THREAD

**Issue by ducttapecoder-vt** [nginxinc/docker-nginx#331]
I know 1.17 was just released yesterday (so I don't blame that it's not up yet) but I see that the current mainline image is still 1.15.12 while stable is now 1.16. Shouldn't the mainline package always be at least the same version or higher as stable?

Also, has the null root password issue been fixed for alpine builds?

**Comment by tianon** [comment]
> Also, has the null root password issue been fixed for alpine builds?

https://github.com/nginxinc/docker-nginx/issues/328#issuecomment-491418908

**Comment by thresheek** [comment]
>  Shouldn't the mainline package always be at least the same version or higher as stable?

No, stable/mainline reflect actual nginx versions, and once a year (when the version bump comes) stable can be higher.

That being said, I do need to update the mainline to 1.17.0 anyway.
