### ISSUE TITLE
How do you write logs into log files rather than STDOUT?

### ISSUE THREAD

**Issue by blueabysm** [nginxinc/docker-nginx#333]
Hi there,

I have a set of configuration copied from our production environment which was used by host installed nginx rather than docker one. Now I'd like to use the config with ```docker-nginx```. Everything works fine except logging. My config originally made nginx saving access log files separately by each ```$server_name```, but ```docker-nginx``` ignore it and print access log directly into STDOUT. I've tried to mount log directory on my host to ```docker-nginx``` but nothing changed. Any help would be appreciated, Thanks!

**Comment by thresheek** [comment]
You can replace /etc/nginx/nginx.conf with a version that doesnt have access_log directive in it and only use your $server_name configurations.

**Comment by blueabysm** [comment]
> You can replace /etc/nginx/nginx.conf with a version that doesnt have access_log directive in it and only use your $server_name configurations.

Thank you thresheek and sorry for replying you in lag. 

Actually, my /etc/nginx/nginx.conf does have access_log directive pointing to /var/log/nginx/access.log, but it was overridden by access_log from vhosts config in my production. I've tried to comment it out, nothing new happened.

**Comment by blueabysm** [comment]
BTW, my config was originally used by nginx 1.10.3 on Ubuntu 16.04. I copied the whole /etc/nginx directory to docker-nginx, is it OK?

**Comment by blueabysm** [comment]
Oh, I get the problem solved!

It's weird that there is always an error message in the beginning of each line of access log in STDOUT, saying:
```
[error] 28#28: *51 testing "/etc/nginx/html" existence failed (2: No such file or directory) while logging request <the rest of the log>
```
I ignored them even though they had never been in my production. After I run command ```mkdir /etc/nginx/html```, logging works fine.

But I grep the whole /etc/nginx with keyword "html" and get nothing abnormal.
