### ISSUE TITLE
nginx container exit code is 0 when killed, interrupted or terminated

### ISSUE THREAD

**Issue by zq-david-wang** [nginxinc/docker-nginx#341]
1. docker run -d nginx
2. kill the container via a) docker stop. b) kill -2 1 c) kill -15 1
3. check exit code via docker inspect, it is always 0
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-06-21T06:40:45.887001615Z",
            "FinishedAt": "2019-06-21T06:41:12.377997022Z"
        },

It is better to return non-zero code when killed by signals

**Comment by thresheek** [comment]
> It is better to return non-zero code when killed by signals

Why?

**Comment by zq-david-wang** [comment]
close it since "member" asking "why"

**Comment by thresheek** [comment]
Well, I didnt want to discourage you, I genuinely wonder why that's better.

**Comment by yosifkit** [comment]
I think most users are just used to applications that error or don't stop fast enough when killed by INT or TERM. The difference is that nginx can gracefully stop on TERM and fast stop on INT and thus shouldn't need to exit non-zero since it was a successful shutdown.

See also #46.

**Comment by zq-david-wang** [comment]
@yosifkit  thanks for the information.
 I would like to known why nginx is shutdown by simply checking its exiting code. And some system would make decision base on this exit code, e.g. whether to restart the container.

**Comment by artem-zinnatullin** [comment]
I agree with @zq-david-wang's point here, example of this is k8s environment
