### ISSUE TITLE
Configuration files are not generated

### ISSUE THREAD

**Issue by Phyremaster** [nginxinc/docker-nginx#345]
I am attempting to create an Nginx container with the `/etc/nginx/` and `/usr/share/nginx/html/` folders mounted on the host filesystem and ports 80 and 443 forwarded straight through to the container. Other than that, the container is a default setup. The problem is, no matter how many times I clear everything and pull the latest image, Nginx never generates its default configuration files in `/etc/nginx/`. Instead, it just whines about them not being there in the logs. Adding the default `nginx.conf` file doesn't help; the container doesn't vomit logs anymore, but it doesn't do anything either.

The error:
```
[emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)


nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
```

**Comment by thresheek** [comment]
It would be helpful if you provide detailed step-by-step instructions on how to reproduce the issue. Thanks!

**Comment by Phyremaster** [comment]
I am running my fully up-to-date Docker installation on a Dell PowerEdge 2900 running the latest version of OpenSUSE. I am using Portainer to manage my Docker installation, so I have been trying to create the container through Portainer. As stated in the initial post, all that I did to the container (aside from naming it) was forward TCP ports 80 and 443 (equivalent of `-p`) and mount `/etc/nginx/` and `/usr/share/nginx/html/` to folders within my main (and only) user's home folder (equivalent of `-v`, using a path rather than a volume name). Also, the mounted folders are definitely writable. So, in step format:
1. Use Portainer (on a PowerEdge 2900 running OpenSUSE)
2. Add a container from the `nginx:latest` image with the previously mentioned port and volume configuration
3. View the logs vomiting the error from my first comment over and over again

**Comment by tianon** [comment]
If you mount `/etc/nginx` from the host (or even an already existing volume) neither Docker nor this image will fill it up, hence your error message about missing configuration.  You'll need to copy the files from the image to your directory yourself.

I typically just mount `/etc/nginx/conf.d` for my own usage since that's included from the default configuration.

**Comment by Phyremaster** [comment]
Oh, OK. I assume this is a relatively recent change, as I had a working container in the past with `/etc/nginx/` mounted to a regular volume. Either that, or I somehow created the volume with the container (which is not currently possible in Portainer). Anyway, I guess the issue is resolved now. Thanks!
