### ISSUE TITLE
nginx unable to read files from other container using the volume from feature

### ISSUE THREAD

**Issue by mwaaas** [nginxinc/docker-nginx#35]
So this is part of my nginx configuration

nginx:
  image: quay.io/jumo/sms_nginx:0.0.2
  links:
    - web:web
  volumes_from:
    - web
  ports:
    - 80:80

web:
  image: quay.io/jumo/sms_packages:0.0.2
  volumes:
    - web_container:/root/code
    - /root/code/sms_platform/static
  command: ./app_server.sh
  environment:
    - DJANGO_SETTINGS_MODULE=sms_platform.settings.development
  ports:
    - 8000:3000
  links:
    - db:db
    - rabbitmq:rabbitmq
    - loggy:loggy

The image is from the official nginx   
So when try to get the static files  I get 403 Forbidden

**Comment by mildred** [comment]
The same thing happens when mounting a directory of the host into a volume

**Comment by thresheek** [comment]
@mwaaas can you provide a step-by-step howto to reproduce your error?

@mildred the lack of index file would not cause 403 forbidden if you fetch the files directly, which I believe what @mwaaas problem is.

**Comment by mwaaas** [comment]
I have reproduce the error in this project https://github.com/mwaaas/django_docker_sample

Do make deploy to run the app 

click on this link to acess admin interface http://localhost/admin

You will notice the static files are missing . 
one of the static file that is missing is base css . try to access it with this link http://localhost/static/admin/css/base.css and you will get 403

**Comment by mwaaas** [comment]
@thresheek 
Step of how to produce my error. 
have one container that has static files
then try accessing the static files to that container via nginx container
you get a 403.

Is it possible for the nginx container to serve files in another container

**Comment by thresheek** [comment]
It works fine here provided the unix permissions are correct.

Here's how I tested:

1/ create a container with static files mounted from the host:
deb8-docker% cat static-data/Dockerfile
FROM nginx:latest

VOLUME ["/data/"]
deb8-docker% ls -la /data
total 16
drwxr-xr-x  3 root    root    4096 Sep  3 14:54 .
drwxr-xr-x 23 root    root    4096 Sep  3 13:55 ..
-rw-r--r--  1 root    root      10 Sep  3 14:54 file.txt
deb8-docker% cat /data/file.txt
It works!

deb8-docker% docker build -t static-data:v1 .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon
Step 0 : FROM nginx:latest
 ---> cd3cf76a61ee
Step 1 : VOLUME /data/
 ---> Using cache
 ---> 48c394a22f70
Successfully built 48c394a22f70
deb8-docker% docker run -v /data:/data -d static-data:v1
f4bc190adfe289d923d9fa5b488a7d6dcb7aca6e554ca1784c6b73a2de14656a

2/ created a nginx container with the following:
deb8-docker% cat Dockerfile
FROM nginx:latest

COPY volumes.conf /etc/nginx/conf.d/volumes.conf
deb8-docker% cat volumes.conf
server {
   listen 8080;
   root /data;
}
deb8-docker% docker build -t nginx-403-test:v1 .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon
Step 0 : FROM nginx:latest
 ---> cd3cf76a61ee
Step 1 : COPY volumes.conf /etc/nginx/conf.d/volumes.conf
 ---> Using cache
 ---> 7d5eb622e499
Successfully built 7d5eb622e499

3/ run the nginx container and test it with curl:

deb8-docker % docker run --volumes-from f4bc190adfe289d923d9fa5b488a7d6dcb7aca6e554ca1784c6b73a2de14656a nginx-403-test:v1

... run a few curl fetches results in the following in stdout:

172.17.42.1 - - [03/Sep/2015:14:59:15 +0000] "GET /file.txt HTTP/1.1" 200 10 "-" "curl/7.38.0" "-"
172.17.42.1 - - [03/Sep/2015:14:59:16 +0000] "GET /file.txt HTTP/1.1" 200 10 "-" "curl/7.38.0" "-"
172.17.42.1 - - [03/Sep/2015:14:59:16 +0000] "GET /file.txt HTTP/1.1" 200 10 "-" "curl/7.38.0" "-"

So, it works fine.

**Comment by imaia** [comment]
I have a similar problem
