### ISSUE TITLE
Upgrade to Debian 10

### ISSUE THREAD

**Issue by ftatard** [nginxinc/docker-nginx#350]
Hello, Debian Buster has been released on 2019-07-06. Do you have plans to upgrade mainline to [buster-slim](https://github.com/debuerreotype/docker-debian-artifacts/blob/d13bce7fbde24c2070f48957c65eaa7d8d91fd11/buster/slim/Dockerfile) ?

Thank you all or your hard work 👍

**Comment by thresheek** [comment]
Yes, the plan is to release buster-based images on July 23.
