### ISSUE TITLE
Tzdata upgrade Brazil

### ISSUE THREAD

**Issue by estevammrodrigues** [nginxinc/docker-nginx#352]
Hello!

In Brazil, summer time was abolished in 2019.
Do you have any plans to update the nginx: latest image?

Thanks

**Comment by thresheek** [comment]
We'd need to wait for the distributions to pick up tzdata 2019b: http://mm.icann.org/pipermail/tz-announce/2019-July/000056.html

Debian ships 2019a as of now, as well as alpine linux.

**Comment by estevammrodrigues** [comment]
Tks @thresheek
