### ISSUE TITLE
Do not update base in patch releases

### ISSUE THREAD

**Issue by ostrolucky** [nginxinc/docker-nginx#353]
You switched from debian stretch to debian buster in nginx 1.17.2. This breaks lot of stuff, which should not happen in patch release. For example, there is no `google-cloud-monitoring-buster` yet, so monitoring agent install script at https://dl.google.com/cloudagents/install-monitoring-agent.sh fails

**Comment by ostrolucky** [comment]
Compromise would be to wait at least for minor nginx version update, that wouldn't be a year

**Comment by thresheek** [comment]
But it was a minor nginx version update, 1.17.1 to 1.17.2.  The 1.18/1.19 change will happen in April 2020.

**Comment by ostrolucky** [comment]
I assumed it's `major.minor.patch`. If 1.17.1 -> 1.17.2 is minor, what would be a patch?

**Comment by thresheek** [comment]
That's not how nginx versioning works, you can read more about that on https://www.nginx.com/blog/nginx-1-16-1-17-released/

**Comment by Morriz** [comment]
Our 1.17 build also broke when 1.17.2 came out.

Is this intended behaviour? I assumed building from a minor release that a patch would not break our build. IMO `nginx:1.17` should never break...and I don't think I am alone in this.

And I dont think semver should be used if it's not followed....too confusing...can you not use your own explicit method?

**Comment by thresheek** [comment]
NGINX never used semver. What should not break is an exact tag, e.g. nginx:1.17.1.  If you rely on non-specific tags for your infrastructure, you're doing it wrong, IMO.

**Comment by ostrolucky** [comment]
So I want to address this problem

> If we don't update and wait for another year on stretch (the mainline/stable change happens in April), our users will lack important features e.g. TLSv1.3.

Seems this is not true, there were workarounds for some time https://blobfolio.com/2018/07/enable-tls-1-3-in-nginx-on-debian-stretch/ and nowadays we can use sury repo to install newer openssl. Are there some other features missing on nginx stretch which prompted to immediate update to buster during insignificant 1.12.1->1.12.2 release?

**Comment by thresheek** [comment]
> Seems this is not true, there were workarounds for some time https://blobfolio.com/2018/07/enable-tls-1-3-in-nginx-on-debian-stretch/ and nowadays we can use sury repo to install newer openssl.

Using a third-party repository for critical security things like openssl is a disaster waiting to happen, especially on a scale of nginx images on docker.  This is not something we'd ever do.

And that being said, even if we'd use that repo (or same-security-unsupported debian backports), we'd still need to recompile nginx against that new openssl version, and it still might break third-party software that people use on top of this image. openssl is sadly not fully compatible between versions and you can not just drop it and expect everything to work smoothly and it will break in subtle ways, as proven by Ubuntu 18.04 recent openssl bump.

There are no other major changes between stretch and buster that I considered for an upgrade for the image, no.

**Comment by ostrolucky** [comment]
Thanks for your answer, I can agree with that. Could we consider to at least warn about changes like this in release notes? Some people like me do read it before upgrading.

**Comment by thresheek** [comment]
Indeed, I should document that to be visible on Docker hub, not sure where else.. Would that work?

**Comment by ostrolucky** [comment]
Oh my idea was in GH changelog. We use `dependabot` for these upgrades and I think it grabs GH release notes and show them in commit.

**Comment by thresheek** [comment]
Aha, thanks for the feedback!

I've now edited https://github.com/nginxinc/docker-nginx/releases/tag/1.17.2 to include the information that this is a breaking change.

**Comment by ostrolucky** [comment]
Cool, I don't see more actions necessary to be done here for now, so let's close
