### ISSUE TITLE
Error response from daemon: error processing tar file: docker-tar: relocation error

### ISSUE THREAD

**Issue by chosen1cwp** [nginxinc/docker-nginx#354]
when Execute the following

docker cp nginx:/etc/nginx/conf.d/default.conf /root/www/default.conf

i got follow error :

Error response from daemon: error processing tar file: docker-tar: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
: exit status 127

**Comment by thresheek** [comment]
Looks like a case of https://github.com/moby/moby/issues/39449, so not nginx-related.

**Comment by kevinsingapore** [comment]
1 i got the same error, and how to soled it finally? thank u
