### ISSUE TITLE
Does the nginx:latest image support ssl ? 

### ISSUE THREAD

**Issue by caowencomeon** [nginxinc/docker-nginx#356]
Hi dear:
    I tried to server https with nginx:latest image, but it failed.
    I ran a container with the image and viewed directory '/usr/lib/nginx/modules'.
    I couldn't find the module "ngx_http_ssl_module"
`---------------------------------------------------------------------------------------------------------------
# pwd
/usr/lib/nginx/modules
# ls
ngx_http_geoip_module-debug.so	       ngx_http_js_module-debug.so	     ngx_stream_geoip_module-debug.so
ngx_http_geoip_module.so	       ngx_http_js_module.so		     ngx_stream_geoip_module.so
ngx_http_image_filter_module-debug.so  ngx_http_xslt_filter_module-debug.so  ngx_stream_js_module-debug.so
ngx_http_image_filter_module.so        ngx_http_xslt_filter_module.so	     ngx_stream_js_module.so
# `

**Comment by thresheek** [comment]
Yes it does, see `nginx -V` output.
