### ISSUE TITLE
Nginx 1.16.1 image with proper tag

### ISSUE THREAD

**Issue by a-shink** [nginxinc/docker-nginx#359]
In nginx 1.16.1  fixed some CVEs but still no docker image with proper tag: https://hub.docker.com/_/nginx?tab=tags
I see 1.16 updated day ago it probably this. Can you create image with  "1.16.1" tag? Some peoples used precise tags for images and it will be useful.

**Comment by larsha** [comment]
Same goes for `1.17.3`.

**Comment by defanator** [comment]
@a-shink @larsha yes, we're going to prepare and update images for both 1.16.1 and 1.17.3 shortly. More details here: https://github.com/nginxinc/docker-nginx/pull/358#issuecomment-521574445

**Comment by defanator** [comment]
@a-shink @larsha both images are now available.
