### ISSUE TITLE
1.16.1-alpine image not pullable on aarch64

### ISSUE THREAD

**Issue by gregorkistler** [nginxinc/docker-nginx#361]
`docker pull nginx:1.16.1-alpine` works well on x86 but not on aarch64. Ends in 
```
1.16.1-alpine: Pulling from library/nginx
no matching manifest for unknown in the manifest list entries
```

**Comment by tianon** [comment]
It appears it's been failing to build: https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/nginx/130/execution/node/217/log/?consoleFull :disappointed:
