### ISSUE TITLE
ngx_http_headers_more_filter_module wrong version in nginx:stable-alpine

### ISSUE THREAD

**Issue by jjrdev** [nginxinc/docker-nginx#364]
steps to reproduce
docker file with FROM nginx:stable-alpine
RUN apk update
RUN apk add nginx-mod-http-headers-more

nginx.conf with load_module "modules/ngx_http_headers_more_filter_module.so";
server {
    more_clear_headers Server;
}

expected behavour - nginx starts normally under the latest stable release without the Server: nginx header 

actual result - nginx: [emerg] module "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" version 1014002 instead of 1016000 in /etc/nginx/nginx.conf:2

workaround: replace FROM nginx:stable-alpine with nginx:1.14.2-alpine

this has been ongoing since 14.2 stopped being nginx:stable-alpine

**Comment by thresheek** [comment]
The headers-more module from apk is compiled against a different binary than shipped in the alpine image.  We don't use the alpine repositories for nginx packages, we use the official nginx.org binaries that do not have headers-more compiled in: http://nginx.org/en/linux_packages.html

Your best bet is to recompile the module on your own if you need it in your setup.

**Comment by marty30** [comment]
Since this issue pops up often when you google this problem, I would  like to mention this stackoverflow issue: https://stackoverflow.com/questions/59189311/edit-hide-nginx-server-header-under-alpine-linux/60780597#60780597 This solves the problem in a more generic way that works with the latest versions of nginx.

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
