### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by abbyoomi** [nginxinc/docker-nginx#365]
[ec2-user@bastionserver-0 microproject]$ micro-gw build k8s-project --deployment-config deployment.toml
Compiling source
    src:0.0.0

Running tests
    src:0.0.0
        No tests found

Generating executable
    ./target//opt/microproject/k8s-project/target/k8s-project.balx
        @kubernetes:Service                      - complete 3/3
        @kubernetes:ConfigMap                    - complete 1/1
        @kubernetes:Deployment                   - complete 1/1
error [k8s plugin]: package [src:0.0.0] Unable to connect to server: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
[ec2-user@bastionserver-0 microproject]$

**Comment by abbyoomi** [comment]
I try to add ec2-user to docker usergroup,the command: sudo usermod -aG docker ec2-user. The problem has not been solved。Now，I need help.

**Comment by thresheek** [comment]
This is not kubernetes support channel.
