### ISSUE TITLE
nginx-mod-http-perl not compatible anymore with docker image nginx:alpine

### ISSUE THREAD

**Issue by LuukDeVille** [nginxinc/docker-nginx#366]
We use with the docker image nginx:alpine the module nginx-mod-http-perl. The module was working so far with the image nginx:alpine. But we have recently observed an incompatibility of module nginx-mod-http-perl with the current image. The container fails to start in this case with the following message:

> [emerg] 1#1: module "/etc/nginx/modules/ngx_http_perl_module.so" version 1016001 instead of 1017003 in /etc/nginx/nginx.conf:7
> [emerg] module "/etc/nginx/modules/ngx_http_perl_module.so" version 1016001 instead of 1017003 in /etc/nginx/nginx.conf:7

Below an excerpt from the dockerfile:
```
FROM nginx:alpine

[...]

# Add perl module http.
RUN apk add --no-cache nginx-mod-http-perl

[...]

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

Below an excerpt from nginx.conf:
```
user  nginx;
worker_processes  1;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

load_module "modules/ngx_http_perl_module.so";

[...]
```

If we use image nginx:1.16.1-alpine (as reported in the error “version 1016001”), the container still fails, but with a different error:

> [emerg] 1#1: module "/etc/nginx/modules/ngx_http_perl_module.so" is not binary compatible in /etc/nginx/nginx.conf:7
> nginx: [emerg] module "/etc/nginx/modules/ngx_http_perl_module.so" is not binary compatible in /etc/nginx/nginx.conf:7

If we use image nginx:1.15-alpine, the container successfully starts.

For the moment we don’t understand how the module nginx-mod-http-perl could get incompatible with current nginx:alpine image. Using nginx:1.15-alpine is not a option, as we want to use the most recent version of nginx.

**Comment by thresheek** [comment]
The problem here is you're mixing modules from Alpine linux upstream with nginx-provided alpine binaries.  The best way for you I believe would be just to use nginx:alpine-perl image, which has the proper perl module from the beginning.

**Comment by janisbiz** [comment]
Actually it is not only perl module. It's almost all of them, which are coming from alpine repo, e.g.:
`nginx: [emerg] module "/etc/nginx/modules/ngx_http_cache_purge_module.so" version 1016001 instead of 1017004 in /etc/nginx/modules/http_cache_purge.conf:1`
