### ISSUE TITLE
The image is added ngx_stream_access_module？ 

### ISSUE THREAD

**Issue by chenxushuo** [nginxinc/docker-nginx#368]
why i can set  deny some ip ,but it don't worked for it?
like this:
    upstream back_server{
    server 192.168.1.250:3306;
    server 192.168.1.251:3306 backup;
}
    server{
    listen 3306;
    proxy_pass back_server;
    allow 192.168.1.200;
    deny  all;
  }
But  all host can client the back_server。。。

**Comment by thresheek** [comment]
Yes, the image has the stream_access module, since it cannot be disabled. The allow/deny should work, however you should check that you see real IP addresses.  Access log might help with that: http://nginx.org/en/docs/stream/ngx_stream_log_module.html#access_log

**Comment by chenxushuo** [comment]
I was seted 'deny all'....But  i can access from every ip...

**Comment by thresheek** [comment]
Works fine here:

> 
> thresh@coal ~/tmp/test $ cat nginx.conf
> user  nginx;
> worker_processes  1;
> 
> error_log  /var/log/nginx/error.log warn;
> pid        /var/run/nginx.pid;
> events {
>     worker_connections  1024;
> }
> 
> stream {
> upstream back_server {
>   server 192.168.1.250:3306;
>   server 192.168.1.251:3306 backup;
> }
> 
> server {
>   listen 3306;
>   proxy_pass back_server;
>   allow 192.168.1.1;
>   deny all;
> }
> }
> thresh@coal ~/tmp/test $ docker run -p 3309:3306 -d -v /home/thresh/tmp/test/nginx.conf:/etc/nginx/nginx.conf nginx:latest
> 3d7f7c8d2db916859e233e7bdf793190e6a06045f40c0acf989c6aebe2d0de6e
> thresh@coal ~/tmp/test $ docker logs 3d7f7c8d2db916859e233e7bdf793190e6a06045f40c0acf989c6aebe2d0de6e
> thresh@coal ~/tmp/test $ curl http://127.0.0.1:3309
> curl: (52) Empty reply from server
> thresh@coal ~/tmp/test $ docker logs 3d7f7c8d2db916859e233e7bdf793190e6a06045f40c0acf989c6aebe2d0de6e
> 2019/09/23 12:01:02 [error] 6#6: *1 access forbidden by rule while initializing session, client: 172.17.0.1, server: 0.0.0.0:3306
> thresh@coal ~/tmp/test $

 Please supply full configuration, and steps to reproduce if you still experience the issue.

**Comment by jamaluddinfikri** [comment]
try to double-check the network and destination proxy on your nginx there may be a problem or allow the ip in your nginx config. You can try without IP restrictions first for checking config.

**Comment by chenxushuo** [comment]
OK ，i'm try
