### ISSUE TITLE
Nginx switch remote address with local container ip

### ISSUE THREAD

**Issue by aleksandar78** [nginxinc/docker-nginx#369]
Hi,

I've used Nginx in the past for single-page applications. Nothing new about generic usage but now I have some specific requirements related to application configuration. I need to put some JSON files in the root of the webserver that will be parsed by js when it's needed. 
The problem is that I need to permit access to Json files only for the given domain name and to deny to all others. This can be done with the location directive.  The problem is that Nginx inside docker container receives all incoming requests from the client that has the local container ip ( ex. 172.20.0.2 ). That way I'm not able to restrict access on domain or ip address. 

I've tried to put:
```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
but without success. I know that proxy_set_header is intended to be used for reverse-proxy and not for simple web server instance. 

Full config example
```

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            try_files $uri /index.html;
        }

        location = /config.json {
            allow app.mycompany.com;
            deny all;
            root   /usr/share/nginx/html;
            try_files $uri /config.json;
        }

        #error_page  404              /404.html;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
}

```

Any suggestion or tip is welcome. 

Environment:
* Mac OS 10.14.6
* Docker 2.1.0.3
* Nginx 1.17.4

Thanks in advance

**Comment by thresheek** [comment]
IIRC that's the limitation of docker for mac.  Drop it and test on a real linux server?

**Comment by thresheek** [comment]
See https://github.com/docker/for-mac/issues/180 and https://github.com/moby/moby/issues/15086 for more details.

**Comment by aleksandar78** [comment]
I had a thought that docker for mac could be the reason but I didn't try to run it on our CI server. 
The big problem, for sure, missing some basic functionality on Mac or Windows.  
Anyway, as @thresheek suggested I'll try it tomorrow on the real machine -> Linux.

**Comment by aleksandar78** [comment]
Ad @thresheek suggested I've tried on Linux and everything worked fine. No issue here for Nginx docker.
