### ISSUE TITLE
How do I find out what other modules (if) are available?

### ISSUE THREAD

**Issue by DomKrulak** [nginxinc/docker-nginx#370]
I'm sorry for posting here even if this isn't an issue. I'm new to all this stuff and I can't find a way through except asking questions.

I've installed this image and browsing in container's filesystem to check whether some other modules were installed by default. 

I couldn't find any other modules except the ones defined in [Dockerfile](https://github.com/nginxinc/docker-nginx/blob/master/mainline/buster/Dockerfile).

I've read some blogs How to enable [optional modules](https://packages.debian.org/buster/nginx-full) like HTTP/2 but it didn't mentioned  anything about the module present in filesystem.

**Comment by thresheek** [comment]
The docker image we ship uses official binaries from http://nginx.org/en/linux_packages.html

nginx built there was configured with the following modules: http://hg.nginx.org/pkg-oss/file/tip/debian/Makefile#l203

we also ship the following modules: https://github.com/nginxinc/docker-nginx/blob/master/mainline/buster/Dockerfile#L32

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
