### ISSUE TITLE
can't run the container - existed (132) without any log.

### ISSUE THREAD

**Issue by Habens** [nginxinc/docker-nginx#372]
Hi,

when I run the `docker run nginx:latest` in my AWS ECS instance, works fine in my local, I got the below issue:
![image](https://user-images.githubusercontent.com/6989183/66638057-d95b0e80-ec46-11e9-87e1-2afc8dacffb4.png)

always Exited (132), and there is no any log printed. 

please help to figure out how to fix/investigate the issue.

Thanks,

### [root@xxx]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#### [root@xxx]# uname -r
3.10.0-957.5.1.el7.x86_64

**Comment by thresheek** [comment]
Try docker logs a25d8.

**Comment by Habens** [comment]
@thresheek I tried before.  not any logs :-<

**Comment by Habens** [comment]
The root cause is not found so far.

help below info help:
132 means: Illegal Instruction (refer on: [Exit Codes With Special Meanings](http://www.tldp.org/LDP/abs/html/exitcodes.html) &&  [Unix Signals](http://people.cs.pitt.edu/~alanjawi/cs449/code/shell/UnixSignals.htm))

and I can get the Nginx core dump file in the Docker Container by the way:
1. ulimit -c unlimited
2. echo '/tmp/core.%h.%e.%t' > /proc/sys/kernel/core_pattern
3. docker run --ulimit core=-1 --security-opt seccomp=unconfined -v /tmp:/tmp nginx:latest

current looking for how to analyze the Nginx (running in the Docker Container) Core Dump info via GDB.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
