### ISSUE TITLE
Add curl dependency for consul registration.

### ISSUE THREAD

**Issue by axeon** [nginxinc/docker-nginx#378]
When deploy a UI project with nginx:alpine image, it often use curl to register on consul.
if the nginx:alpine image support curl, can save lot of times to execute "apk add curl".
thanks very much!

**Comment by thresheek** [comment]
Hello @axeon and thank you for your suggestion.

What kind of URL is being hit on consul registration?  Is that plain http or https?

I mean, we probably need to add ca-certificates to the image as well if it's https.

**Comment by axeon** [comment]
3ks!
HTTP is used in most cases.

**Comment by thresheek** [comment]
So https can also be hit, right?  So I assume we would need CAs there too.  I'll take a look on how that would bloat the images and report back.

**Comment by axeon** [comment]
support http may be in advance.
