### ISSUE TITLE
How to build custom image or add a config to disable show server name and version

### ISSUE THREAD

**Issue by wideweide** [nginxinc/docker-nginx#379]
for security reason,I must disable the http headers to show web server 's name and version, to do this it seems must modify the code and recompile, I can't do it my self ...
（1）vim src/http/ngx_http_header_filter_module.c 　　　　　　　　　　    
static u_char ngx_http_server_string[] = "Server: Please guess it!" CRLF;    
（2）vim src/http/ngx_http_special_response.c　　    
"<hr><center>Please guess it!</center>" CRLF

**Comment by thresheek** [comment]
It is not possible to disable server name in the opensource version without modifying the sources.

**Comment by wideweide** [comment]
> It is not possible to disable server name in the opensource version without modifying the sources.

So my question is : If I modified the sources,how to build the image with docker file

has a docker image can do this easily?

**Comment by thresheek** [comment]
No, it can not.
