### ISSUE TITLE
nginx port exposure on Windows

### ISSUE THREAD

**Issue by altsheets** [nginxinc/docker-nginx#38]
Whatever I do, my docker ports do not get exposed to the host machine on Windows.

To me it looks as if it is not an nginx issue, but a general Docker problem.
But perhaps you are able to find the problem most quickly?

Have a look at this issue here:
https://github.com/docker/docker/issues/15740

Thanks!

**Comment by thaJeztah** [comment]
This is not a bug, I've explained the reasons why here; https://github.com/docker/docker/issues/15740#issuecomment-133208641

**Comment by altsheets** [comment]
thanks. Let's discuss it there then.
