### ISSUE TITLE
problem with nginx config file variables

### ISSUE THREAD

**Issue by hancok62** [nginxinc/docker-nginx#381]
hello,
i'm using nginx stable with docker-compose and docker-compose.yml file with basic .yml file specified in https://hub.docker.com/_/nginx?tab=description

my nginx config file have http to https redirect:
server {
    listen ${NGINX_PORT_HTTP};
    server_name ${NGINX_HOST};
    return 301 https://$host$request_uri;
}

but when i start the docker the section of return 301 
it is shown without variables, since envsubst deletes and replaces them
return 301 https://;

i have this startup script to solve this (spageti code)
sed '/\${/!  s/\$/()%/g' /etc/nginx/conf.d/whitehost.es.template > /tmp/YmYpNArGDB9kw9ykiYJrA.yuR934hW+CtDD2TnsXPHGw; /bin/bash -c "envsubst < /tmp/YmYpNArGDB9kw9ykiYJrA.yuR934hW+CtDD2TnsXPHGw | sed '/\${/!  s/()%/\$/g' > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

is there any way to add docker env variables and nginx server variables with default command?

**Comment by thresheek** [comment]
With docker-compose you need to specify those variables in the "environment" section.

With plain docker, you specify them with docker run --env.
