### ISSUE TITLE
Update to 1.17.7

### ISSUE THREAD

**Issue by brentybh** [nginxinc/docker-nginx#383]
2019-12-24 nginx-1.17.7 mainline version has been released.

**Comment by brentybh** [comment]
And #380

**Comment by sknight80** [comment]
Do we have any updates on this?

**Comment by brentybh** [comment]
@sknight80 Maybe the maintainers from NGINX, Inc. still don't have time to update this...

Also, 1.17.7 has a known issue which is fixed right after it was released: https://github.com/nginx/nginx/commit/fb34316d68511bd0986d3153dfea93d21363016d

See: https://github.com/nginx/nginx/commits/master

**Comment by sknight80** [comment]
@brentybh oh, that make sense! Thank you!

**Comment by thresheek** [comment]
Sorry about lack of replies, we're just recovering from the holiday season and travels.  The images will arrive shortly.

Thank you!

**Comment by thresheek** [comment]
Should be live when https://github.com/docker-library/official-images/pull/7249 is merged & acted upon.

**Comment by thresheek** [comment]
Fixed, thank you.
