### ISSUE TITLE
Build and push debian based images to docker hub

### ISSUE THREAD

**Issue by dooblem** [nginxinc/docker-nginx#387]
Hello,

I'm looking for Nginx Debian based images and I do not find them.

However, the docker hub readme seem to mention them : https://hub.docker.com/_/nginx

And I see the Dockerfile in the repo.

Is it normal ? Otherwise I will have to build those images myself.

Thanks in advance,
Marc

**Comment by thresheek** [comment]
Hi Marc,

Hope all is well.

Can you please describe the way you're checking for the debian-based images?  Note that the -mainline/-stable images are indeed built on top of Debian OS, however they don't mention it as in the tags.

Thanks!

**Comment by dooblem** [comment]
Hi thresheek,

My bad. Thanks and sorry for the noise.

I would suggest a line in the README.
