### ISSUE TITLE
Image with ngx_http_opentracing_module

### ISSUE THREAD

**Issue by s1rc** [nginxinc/docker-nginx#391]
Just wondering if there is a maintained image with opentracing modules and libraries included or if I need to make a custom one and maintain it myself?

**Comment by thresheek** [comment]
Hi @s1rc, hope all is well in those uncertain times.

Unfortunately this image will have to be maintained on your side, since opentracing isnt something included in official nginx.

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
