### ISSUE TITLE
nginx not starting

### ISSUE THREAD

**Issue by Tvde1** [nginxinc/docker-nginx#393]
When I run any nginx version like this:

    docker run --name nginx-test nginx

Nothing happens. No log is created and noting is visible on port 80.
`docker ps` does list the container:

    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
    11eb75c445af        nginx               "nginx -g 'daemon of…"   31 hours ago        Up 49 seconds       80/tcp              nginx-test3

Is this because of permissions or something?

**Comment by Tvde1** [comment]
It's just stuck like this forever
![image](https://user-images.githubusercontent.com/11540531/78018869-f26b8f00-734e-11ea-8048-6bc823aaa31d.png)

**Comment by Tvde1** [comment]
This is also happening on a raspberry pi 4 (armv7) with `nginx:1.17.9-alpine`.

**Comment by thresheek** [comment]
It's starting and working as expected.  You need to query the IP address of container and port 80 to get output from nginx.
