### ISSUE TITLE
nginx image doesn't work on IPv6 only kubernetes

### ISSUE THREAD

**Issue by Frankkkkk** [nginxinc/docker-nginx#394]
Hi,
`nginx:latest` doesn't seem to listen on IPv6 addresses. This is a problem on v6 only kubernetes/docker as they thus have no connectivity.

## Steps to reproduce
Create a deployment with
```
$ kubectl create deployment d-nginx --image=nginx
deployment.apps/d-nginx created
```
Then, we can check that the container doesn't reply on IPv6:
```
$ kubectl get pod -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP                                   NODE             NOMINATED NODE   READINESS GATES
d-nginx-b94ddb98b-b9hgx    1/1     Running   0          16s   xxxx:xxxx:cafe:1002:27:ffff:0:bcee   pik-c1-33-vm-3   <none>           <none>

$ curl http://[xxxx:xxxx:cafe:1002:27:ffff:0:bcee]
curl: (7) Failed to connect to xxxx:xxxx:cafe:1002:27:ffff:0:bcee port 80: Connection refused
```

Logging in on the pod, I can indeed see that it listens on IPv4 only:
```
root@d-nginx-b94ddb98b-b9hgx:/# ss -lnt  
State                    Recv-Q                    Send-Q                                       Local Address:Port                                       Peer Address:Port                   
LISTEN                   0                         128                                                0.0.0.0:80                                              0.0.0.0:*                      
```

And its connectivity:
```root@d-nginx-b94ddb98b-b9hgx:/# ip -6 a sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
174: eth0@if175: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP 
    inet6 xxxx:xxxx:cafe:1002:27:ffff:0:bcee/128 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::f048:dfff:fe05:1e74/64 scope link 
       valid_lft forever preferred_lft forever
```

## Expected results
however, it works with `httpd` for example:
```
$ kubectl create deployment d-httpd --image=httpd
deployment.apps/d-httpd created

$ kubectl get pod -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP                                   NODE             NOMINATED NODE   READINESS GATES
d-httpd-549ff79598-5s2xd   1/1     Running   0          10s   xxxx:xxxx:cafe:1002:7:ffff:0:b3cd    pik-c1-13-vm-1   <none>           <none>

$ curl http://[xxxx:xxxx:cafe:1002:7:ffff:0:b3cd]
<html><body><h1>It works!</h1></body></html>
```

Should we listen by default on v6 addresses too ?

Cheers

**Comment by thresheek** [comment]
Yeah, the defaults shipped as "listen 80;" in default.conf only listens on ipv4 address; changing the default configuration is possible, but I'd rather avoid doing that for no big reason.

I mean, most of the times people do not just ship the default image and drop files to docroot to be served, but also provide their own configuration in conf.d, or replace nginx.conf completely.  I don't see a problem in adding "listen [::]:80;" too.

**Comment by Frankkkkk** [comment]
Hi,
Thanks for your reply.
But then, if most of the time people do not use the default image, what's wrong on changing the default configuration to listen on v6 too ?

The problem now is that it's "impossible" to use default nginx containers on v6 only clusters. Granted, they're the minority for now, but times are changing .. ;-)

**Comment by ludovicm67** [comment]
Hi!
I have the same problem and need to patch some Docker images that are built on top of `nginx:latest` like [Riot web](https://github.com/vector-im/riot-web/blob/8122c62f24c418af3680510bf1c93a3dd3cf42b0/Dockerfile#L29).
Adding IPv6 support by default can be really helpful in this kind of cases.

**Comment by thresheek** [comment]
It seems like this change broke ipv4-only setups as per https://github.com/nginxinc/docker-nginx-unprivileged/issues/35 -- I have tested on a machine with a sysctl-disabled ipv6 and didnt notice the issue.  If nobody got better suggestions, I'll have to revert https://github.com/nginxinc/docker-nginx/commit/abef566d0a619721144d59f7a8dd482669250276 and restore the previous behavour.

**Comment by starcraft66** [comment]
I don't think people who purposely disable IPv6 on their systems should be hindering IPv6 adoption by getting this change reverted. Could an environment variable be added to disable listening on IPv6?

**Comment by thresheek** [comment]
Even if it would have been added, how would that work?  That would be a breaking change for all setups that don't have ipv6 enabled, and they will need to explicitely set a variable to revert to the previous state?

**Comment by starcraft66** [comment]
Alternately, the entrypoint of the image could be changed to a shell script that performs a simple test to check if the inet6 address family is available or not and runs `sed` to adjust the default configuration. It should also probably run a checksum on the default config first and not perform any changes against a configuration that isn't the default (i.e. if someone mounted a custom config over it).

**Comment by Frankkkkk** [comment]
From a usability standpoint, falling back to "not supporting IPv6" because some people, in 2020, decide not to support it at all (i.e. `ipv6.disable=true`) seems crazy to me.

@starcraft66 Solution seems a good work-around for now.

**Comment by thresheek** [comment]
Indeed, please do a PR to fix that.
