### ISSUE TITLE
unable to pull docker plus image

### ISSUE THREAD

**Issue by cmpmohan** [nginxinc/docker-nginx#395]
docker pull nginx-plus-ingress:1.6.3
Error response from daemon: pull access denied for nginx-plus-ingress, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

please help. unable to pull image

**Comment by thresheek** [comment]
There is no nginx-plus image publically available. You may want to consult the documentation on how to build one for yourself on https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/
