### ISSUE TITLE
Image for 1.18.0 is currently missing linux/amd64 manifest

### ISSUE THREAD

**Issue by MorrisonCole** [nginxinc/docker-nginx#401]
Seems like a similar problem to #397 that we saw before.

It's a multi-arch image, but the release process only seems to push a few manifests initially. Maybe they should be pushed at once to avoid tools like [Renovate](https://renovate.whitesourcesoftware.com/) picking up the change and failing to build 💭 .

The image has been pushed and [appears to be available](https://hub.docker.com/layers/nginx/library/nginx/1.18.0/images/sha256-93a6d90f828fc2358d7f8e37d5f07225d3d685cffd9e85b0023d661247dc0407?context=explore), but only has manifest for `linux/s390x` and `linux/arm/v7` at the time of writing. Compared to the final image for [1.17.10](https://hub.docker.com/layers/nginx/library/nginx/1.17.10/images/sha256-06e2a1fa4c8be156dc2c05d2123d7876f504f73d64f88cb3f79410d7c5ccb193?context=explore), there are many fewer architectures currently available.

---

```
$ docker pull nginx:1.18.0
1.18.0: Pulling from library/nginx
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by thresheek** [comment]
AFAIU it's still in a build queue on docker-library side of things. Unfortunately there is nothing we can do but wait.

**Comment by tianon** [comment]
This is fixed now, thanks for your patience:

```console
$ manifest-tool inspect nginx:1.18.0 | grep amd64
1           -    Arch: amd64
```

**Comment by thresheek** [comment]
Thanks @tianon!
