### ISSUE TITLE
Where is located the 1.18 version for CentOS 8?

### ISSUE THREAD

**Issue by pedrofurtado** [nginxinc/docker-nginx#402]
I am sorry, but I do not know where to ask this.

The version 1.18.0 will be also available in this URL ( http://nginx.org/packages/mainline/centos/8/x86_64/RPMS/ ) ?

I am asking because I use this script to install/upgrade nginx in CentOS 8:

```bash
touch /etc/yum.repos.d/nginx.repo
cat >> /etc/yum.repos.d/nginx.repo << 'EOL'
[nginx]
name=nginx mainline repo
baseurl=http://nginx.org/packages/mainline/centos/$releasever/$basearch/
gpgcheck=1
enabled=0
gpgkey=https://nginx.org/keys/nginx_signing.key
module_hotfixes=true
EOL
yum-config-manager --enable nginx
yum install -y nginx
systemctl start nginx
```

But it not install nginx 1.18.0, because there is no rpm package there 👍 

Thanks!

**Comment by thresheek** [comment]
Use the stable repository from http://nginx.org/en/linux_packages.html#RHEL-CentOS
