### ISSUE TITLE
About third-party modules

### ISSUE THREAD

**Issue by RobertoHuang** [nginxinc/docker-nginx#404]
Is there any documentation here that tells me how to install third-party modules

**Comment by Bigezno** [comment]
I also want to know it!

**Comment by cetver** [comment]
It would be great to add tools for `configure` and `install` like here
https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions

**Comment by Azer90** [comment]
确实应该搞一个可以添加第三方模块的工具

**Comment by nmaas87** [comment]
I would love to add the rtmp module...

**Comment by chpiter** [comment]
同问

**Comment by brentybh** [comment]
https://github.com/brentybh/docker-nginx/blob/master/Dockerfile

Building dynamic modules

**Comment by scyto** [comment]
i just had this issue, my stupid workaround was to apt install nginx-full - which downgraded the nginx in the container but gave me the following modules via `/include /etc/nginx/modules-enabled/*.conf;`:
```
ngx_http_auth_pam_module.so                                                                                                                      
ngx_http_dav_ext_module.so                                                                                                                       
ngx_http_echo_module.so                                                                                                                          
ngx_http_geoip_module.so                                                                                                                         
ngx_http_image_filter_module.so                                                                                                                  
ngx_http_subs_filter_module.so                                                                                                                   
ngx_http_upstream_fair_module.so                                                                                                                 
ngx_http_xslt_filter_module.so                                                                                                                   
ngx_mail_module.so                                                                                                                               
 ngx_stream_module.so  
```
@nmaas87 after doing that you could then use `apt install libnginx-mod-rtmp` to get what you want (alternately assuming you are on the debian derived container you could use nginx-common or nginx-lite etc as you see fit.

What would be better IMO is if they just produced tags equivalent to these
https://github.com/nginxinc/docker-nginx/issues/451

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
