### ISSUE TITLE
Cannot use hash $request_uri in upstream

### ISSUE THREAD

**Issue by nststanev** [nginxinc/docker-nginx#410]
My config is this:
```    user nginx;
    worker_processes  3;
    #error_log  /var/log/nginx/error.log;
    error_log /dev/stdout info;
    events {
      worker_connections  10240;
    }
    stream {
    upstream stream_backend {
        hash $request_uri;
        server 192.168.1.200:30100;
        server 192.168.1.200:30100;
    }
    server {
        listen        30101;
        proxy_pass    stream_backend;
    }
    }
```
The error I receive is: 

> nginx: [emerg] unknown "request_uri" variable

**Comment by thresheek** [comment]
the $request_uri variable is only defined on http level, not stream, hence you cant use it here.

addiotionally, please use http://nginx.org/en/support.html for getting support since this is not a docker-related issue.

thank you!
