### ISSUE TITLE
dockerfile编译时nginx提示error

### ISSUE THREAD

**Issue by zkyy66** [nginxinc/docker-nginx#413]
E: Version '1.18.0-1~buster' for 'nginx' was not found
E: Version '1.18.0-1~buster' for 'nginx-module-xslt' was not found
E: Version '1.18.0-1~buster' for 'nginx-module-geoip' was not found
E: Version '1.18.0-1~buster' for 'nginx-module-image-filter' was not found
E: Version '1.18.0.0.4.0-1~buster' for 'nginx-module-njs' was not found

请问如何解决

**Comment by zkyy66** [comment]
E: Version 1.18.0-1~buster for 'nginx' was not found
E: Version 1.18.0-1~buster for 'nginx-module-xslt' was not found
E: Version 1.18.0-1~buster for 'nginx-module-geoip' was not found
E: Version 1.18.0-1~buster for 'nginx-module-image-filter' was not found
E: Version 1.18.0.0.4.0-1~buster for 'nginx-module-njs' was not found

**Comment by thresheek** [comment]
Please report bugs in English, thank you.
