### ISSUE TITLE
Needn Help with a docker problem 

### ISSUE THREAD

**Issue by Ncjustus123** [nginxinc/docker-nginx#415]
Sending build context to Docker daemon  40.51MB
Step 1/7 : FROM node:12
12: Pulling from library/node
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

i keep on getting this message any time i try to build an image really frustrating need help this is my dockerfile 
FROM node:12
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
CMD ["node", "app.js"]
EXPOSE 3001

**Comment by thresheek** [comment]
Even if that's a node image mentioned, the same will happen on nginx too.  There is no nginx docker image for windows/amd64.
