### ISSUE TITLE
nginx:alpine cannot be run as nginx user

### ISSUE THREAD

**Issue by garethbdavis** [nginxinc/docker-nginx#417]
Currently, trying to run the container as user 101 (nginx) results in an error:

```docker run --user 101:101 -it nginx:alpine
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
sed: can't create temp file '/etc/nginx/conf.d/default.confXXXXXX': Permission denied
```

It seems that the recent change to `10-listen-on-ipv6-by-default.sh` uses sed, which requires write access to /etc/nginx/conf.d when creating a temporary file.  the `nginx` user does not have this permission.

**Comment by thresheek** [comment]
Please update the image - this was fixed in https://github.com/nginxinc/docker-nginx/commit/2ef3fa66f2a434cd5e44e35a02f4ac502cf50808

**Comment by garethbdavis** [comment]
Thanks for the response.

**Comment by amerni-sami** [comment]
can you explain pleas.how can update my image i have the same problem.i use the last nginx.

**Comment by thresheek** [comment]
@amerni-sami docker pull nginx:latest

**Comment by AkramDhiabi** [comment]
> docker pull nginx:latest

I tried it and I could not I am having troubles as well:
**$ docker build -t mynginx_image2 .
Sending build context to Docker daemon  1.094GB
Step 1/4 : FROM nginx:latest
 ---> daee903b4e43
Step 2/4 : RUN /etc/nginx/conf.d/default.conf
 ---> Running in ea4e51414c3b
/bin/sh: 1: /etc/nginx/conf.d/default.conf: Permission denied
The command '/bin/sh -c /etc/nginx/conf.d/default.conf' returned a non-zero code: 126**

the Dockerfile content is the following:

FROM nginx:latest
RUN /etc/nginx/conf.d/default.conf
COPY drupal-data /var/www/html
COPY nginx-conf /etc/nginx/conf.d

Thanks in advance for help.
