### ISSUE TITLE
nginx:1.19 - /docker-entrypoint.d/ is not empty

### ISSUE THREAD

**Issue by jrdavenport** [nginxinc/docker-nginx#418]
Hi,

I have been using the nginx docker image in my application, however have been getting some interesting messages since 1.19 was released.

My Dockerfile is simple, and just does this:
`FROM nginx:1.19`
The console gives:
`
server_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
server_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
server_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
server_1  | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
server_1  | 10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
server_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
server_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
` 

I do not get any of the docker-entrypoint.sh messages when using `FROM nginx:1.18`.

Is this an issue with the 1.19 image?

**Comment by thresheek** [comment]
No, that's not an issue.  1.19 introduced an entrypoint and a few scripts to alter the configuration on the start of the container.

**Comment by jrdavenport** [comment]
@thresheek thanks for confirming :)
