### ISSUE TITLE
Mapping of /dev/stdout to log file no longer works

### ISSUE THREAD

**Issue by kudos** [nginxinc/docker-nginx#42]
Logs are no longer being piped to stdout and stderr, this has been happening since at least 1.8.0. I suspect it maybe has something to do with this line in the [changelog](https://github.com/docker/docker/blob/master/CHANGELOG.md), but I'm not using the `--read-only` flag.

> Make /proc, /sys, & /dev readonly for readonly containers

**Comment by kudos** [comment]
It seems the fix is to force allocating a tty to the container. I guess a docs update is needed, and maybe it should be mentioned in the Dockerfile?

**Comment by sherter** [comment]
I cannot reproduce this. When I run `docker run --rm -p 127.0.0.1:8080:80 nginx:1.9.4` and hit http://localhost:8080 with a browser it prints the access logs in the console as I would expect. What version of docker do you use?

**Comment by kudos** [comment]
Ok, I think there's actually a bug in Kitematic, `docker logs -f <container-name>` behaves as expected, Kitematic sometimes claims there are no logs (toggling tty seemed to fix it, but it was just a coincidence). No bug here anyway, sorry for the noise!
