### ISSUE TITLE
HIGH vulnerability found in os package type sqlite 3.30.1-r2 and are fixed in 3.32.1-r0

### ISSUE THREAD

**Issue by kalpesh6641** [nginxinc/docker-nginx#420]
HIGH Vulnerability found in os package type sqlite 3.30.1-r2 and are fixed in 3.32.1-r0 for the alpine based nginx images.

Currently available in alpine v3.12: https://pkgs.alpinelinux.org/packages?name=sqlite&branch=v3.12&repo=main

Current alpine version of nginx images are v3.11.

Are there any plans to update to use alpine 3.12 which is released https://alpinelinux.org/posts/Alpine-3.12.0-released.html?

Could anyone help check and fix it? Thanks.

**Comment by tianon** [comment]
Regarding `sqlite` specifically, the vulnerabilities you're referring to should be fixed in 3.30.1-r2 because the Alpine maintainers backported them (see https://github.com/nodejs/docker-node/issues/1274#issuecomment-638363771 and following comments for a discussion of the same).

**Comment by thresheek** [comment]
Indeed, doing `apk add sqlite` on top of nginx:1.19.0-alpine results in 3.30.1-r2 being installed, which holds the fixes for the CVE in question.
