### ISSUE TITLE
Verbose entrypoint

### ISSUE THREAD

**Issue by alexandresalome** [nginxinc/docker-nginx#421]
Since a last month, verbosity was added to the container, making it log on output some information when it starts:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

While it's great to have this information in development, I prefer to have information hidden in production, to keep my production logs for only warning/error messages.

Would you agree if I add a `ENTRYPOINT_SHOW_INFO` environment variable or some other mechanism (indicate me) to reduce this verbosity when everything goes as planned?

Default would be to show, as it is now, but allow users to hide it when they want.

**Comment by thresheek** [comment]
That sounds like a good feature to have, indeed.  An environment variable should be fine.

**Comment by tianon** [comment]
There are quite a few `echo` statements to cover -- instead of making them all conditional, what do you think about something like this in `docker-entrypoint.sh`?

```sh
if [ -z "${NGINX_ENTRYPOINT_QUIET_LOGS:-}" ]; then
    exec 3>&1
else
    exec 3>/dev/null
fi
```

Then, doing `>&3` on all the "logging" `echo`s:

```sh
        echo >&3 "$0: Configuration complete; ready for start up"
```

**Comment by alexandresalome** [comment]
I've sent the pull-request modifying the scripts.

Regarding tests, I've verified default and quiet for static file serving. Did not test error cases.

I've verified also the checksum of every `*.sh` files, and they are all kept identical.

Regarding the documentation, I did not found where and/or how to contribute. Is there a way for me to document this variable?

**Comment by thresheek** [comment]
Thanks @alexandresalome for the PR, I will check it out.

Regarding the docs, you can make a PR on https://github.com/docker-library/docs/tree/master/nginx

**Comment by alexandresalome** [comment]
Documentation pull-request prepared, too.

Thank you for your guidance

**Comment by thresheek** [comment]
Thanks a lot!
