### ISSUE TITLE
TLS Pass through is not working even after enabling it while deploying the Nginx controller.

### ISSUE THREAD

**Issue by vperi1730** [nginxinc/docker-nginx#425]
Hi Team,

We have installed the Nginx controller with TLS pass-through enabled by using the following helm chart. However, while trying to perform any operation, it is expecting a TLS handshake instead of passing it. 

helm install nginx stable/nginx-ingress --set "rbac.create=true" --set "controller.service.type=LoadBalancer" --set "controller.extraArgs.annotations-prefix=nginx.ingress.kubernetes.io" --set "controller.extraArgs.enable-ssl-passthrough="

I need help here.

**Comment by thresheek** [comment]
Hello,

This is the repository for nginx docker images, not nginx-based kubernetes ingress controller.

Please file a bug on https://github.com/nginxinc/kubernetes-ingress/ instead, thank you.

**Comment by vperi1730** [comment]
Sure, thank you.
