### ISSUE TITLE
Add ngx_http_realip_module

### ISSUE THREAD

**Issue by felixsanz** [nginxinc/docker-nginx#433]
I'm using traefik as my ingress / load balancer, and nginx as a frontend to a wordpress image. But nginx container can't get the real ip from the user (`set_real_ip_from: traefik_ip`) because this module is not enabled.

Can we get it enabled please? it's almost a requirement on this workflow (using nginx as a web server behind some other reverse proxy)

**Comment by thresheek** [comment]
The module is enabled in nginx: images, see docker run nginx:latest nginx -V output.
