### ISSUE TITLE
ipv6 not supported always throws errors 10-listen-on-ipv6-by-default.sh

### ISSUE THREAD

**Issue by DotNetRockStar** [nginxinc/docker-nginx#437]
Hi there.  I am using PKS (Kubernetes) and the clusters do not support ipv6.  Because of this, the [10-listen-on-ipv6-by-default.sh] script does not execute and always logs something to STDERR.  
https://github.com/nginxinc/docker-nginx/blob/3dcf654f100182075f01dcb5f0c1e42c3fa402f2/mainline/alpine/10-listen-on-ipv6-by-default.sh#L11

My system is set up using PagerDuty.  Any time I get STDERR, my team gets notified.  However, this notification is something I cannot fix because there is no way for me to enable ipv6 and no way to tell the script DON'T LOG TO STDERR.

Is there any way we could just log to STDOUT instead of STDERR?  This obviously is not required for docker image to successfully containerize and work so why log STDERR anyways?

Thanks in advance!

**Comment by thresheek** [comment]
Maybe we should change it to respect NGINX_ENTRYPOINT_QUIET_LOGS too, thoughts?

**Comment by DotNetRockStar** [comment]
> Maybe we should change it to respect NGINX_ENTRYPOINT_QUIET_LOGS too, thoughts?

That would work perfectly.
