### ISSUE TITLE
How to enable FIPS to the nginx server?

### ISSUE THREAD

**Issue by Santosh-13** [nginxinc/docker-nginx#443]

**Comment by thresheek** [comment]
You might find this documentation relevant: https://docs.nginx.com/nginx/fips-compliance-nginx-plus/

It applies to nginx opensource as well and is orthogonal to running nginx in docker.

**Comment by Santosh-13** [comment]
But thats for nginx plus and if i am using nginx:alpine what to do?

**Comment by thresheek** [comment]
You need to check if alpine provides FIPS-compliant openssl library.  If it does, everything in that post will apply just fine to nginx opensource in alpine.
