### ISSUE TITLE
Unable to bind mount file to `/etc/nginx/default.conf`

### ISSUE THREAD

**Issue by awhan** [nginxinc/docker-nginx#444]
I am not able to mount a local `default.conf` to overwrite the one in the image. However mounting `nginx.conf` to `/etc/nginx/nginx.conf` works without any issues.

The following command will reproduce the problem:

```
docker run -v ${PWD}/default.conf:/etc/nginx/conf.d/default.conf nginx:1.19.2
```

Following are the logs and error trace from the container:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
sed: cannot rename /etc/nginx/conf.d/sedIe64r2: Device or resource busy
```

*OS Info*:  archlinux running kernel 5.6.15-arch1-1
*docker version*: `Docker version 19.03.12-ce, build 48a66213fe`

I have also tried it with `nginx:latest` and found the same issue. However I was NOT able to reproduce this issue with `nginx:1.13` image.

**Comment by thresheek** [comment]
nginx:1.13 does not use entrypoints, so that's the reason it works.

in current images, sed will replace the file contents, and it probably lacks permissions to do that when a file is mounted.

Looking at the logs output, it looks like you're mounting the default.conf unchanged to a container?  What is the reason for that?  10-listen-on-ipv6-by-default.sh will not sed the file if it's changed from outside (e.g. a different version is mounted from a host as a volume).

**Comment by Tsingshen** [comment]
@awhan this is what I do to salve your problem,  wish it can help. Use the dockerfile below generate new image and then run "docker run -v `pwd`/default:/etc/nginx/conf.d/default.conf nginx:<your-tag>"

FROM nginx:1.18

LABEL app=nginx

ENV TZ=Asia/Shanghai LANG=zh_CN.UTF-8

ADD nginx.conf /etc/nginx/nginx.conf

RUN apt update; apt install vim curl wget telnet dnsutils locales -y \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8 \
    && rm -f /etc/nginx/conf.d/default.conf \
    && rm -f /10-listen-on-ipv6-by-default.sh

**Comment by thresheek** [comment]
Closing due to feedback timeout.

**Comment by winkee01** [comment]
If I don't provide a default.conf, then the container will use a default one, but how can I manage that /etc/nginx/conf.d/default.conf if I can't make a volume mapping to it?
