### ISSUE TITLE
3: Bad file descriptor from echo >&3

### ISSUE THREAD

**Issue by ANGkeith** [nginxinc/docker-nginx#445]
Can anyone enlighten me what is echo >&3?
https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/20-envsubst-on-templates.sh#L25
![image](https://user-images.githubusercontent.com/28011783/91182662-07d9bf00-e71d-11ea-9f82-b9849990ac7c.png)

**Comment by Seb-C** [comment]
Same here. I am trying to run this script manually to reload the configuration without restarting the container.

**Comment by BartlomiejSkwira** [comment]
It's either a file descriptor for stdout (`&1`) or `/dev/null` - depending on `NGINX_ENTRYPOINT_QUIET_LOGS` var. It is set in:
```
if [ -z "${NGINX_ENTRYPOINT_QUIET_LOGS:-}" ]; then
    exec 3>&1
else
    exec 3>/dev/null
fi
```

I'm trying to run those scripts in `/docker-entrypoint.d/` inside my Dockerfile like this:
```
RUN chmod +x /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
RUN /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
```
But I get `/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh: 16: /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh: 3: Bad file descriptor` - is it possible to somehow pass file descriptor `&3` to an executed like that shell script?

**Comment by kaangoksal** [comment]
I execute `exec 3>&1` and then `./20-envsubst-on-templates.sh` the script worked. However I'm  failing to execute `./docker-entrypoint.sh` script manually, it doesn't output anything
