### ISSUE TITLE
Entrypoint - run envsubst before ip6

### ISSUE THREAD

**Issue by kshishkin** [nginxinc/docker-nginx#446]
Envsubst overwrites changes made by prior script

**Comment by dekobon** [comment]
I would like to add a bit more context to this issue.

`10-listen-on-ipv6-by-default.sh` runs first and modifies the file at the path `etc/nginx/conf.d/default.conf`. Theoretically, this sets the configuration such that it uses IPv6 if it is supported.
Then `etc/nginx/conf.d/default.conf` comes along and can also potentially modify `etc/nginx/conf.d/default.conf` if you have written the file `/etc/nginx/templates/default.conf.template`. The templated output will overwrite any of the changes made by the IPv6 script.

Perhaps, the ordering of these two scripts should be reversed? Templating and then doing the IPv6 rewrite seems to make sense.

**Comment by thresheek** [comment]
If the templates kick in before ipv6 scripts, how do we check the file is unmodified then? The whole reason for ipv6 fix was to provide an easy way to enable ipv6 if supported on a *default* configuration.  Templating default.conf implies it's already non default and it's up for the administrator to decide whether they want ipv6 on or not .

**Comment by dekobon** [comment]
That trade-off makes sense.

I'm thinking from the perspective of a Dockerfile author that is making an image from generic consumption based on NGINX. Ideally, I would like to preserve the ipv6 auto-detect behaviour for the benefit of the users of the image.

I think I get it - as an extender of the `nginx` Docker image, I'm free to implement a similar script to `10-listen-on-ipv6-by-default.sh` to change the listener behaviour to ipv6 for the nginx configuration that I've offered.

With the above understood, I would vote to close this issue.

@kshishkin - does this discussion reflect the issue that you reported?

**Comment by kshishkin** [comment]
I understand the premise & vote to close this one; I'll continue discussion on this thread as I'm not sure this is the right way to wire the setup:
https://github.com/nginxinc/docker-nginx/issues/447
