### ISSUE TITLE
changes are reflecting on filesystem but not via http when using volumes

### ISSUE THREAD

**Issue by timaschew** [nginxinc/docker-nginx#45]
We found a weird behaviour after changing a file which is mounted as volume.
If you connect to the container via bash and print out the changed file it's okay, but opening the file via http (browser or curl) shows still the old content. It has to do with the volume, because it's working with other files.

You can reproduce it:

```
git clone https://github.com/timaschew/loadbalancer
cd loadbalancer
docker build -t actano/haproxy .
docker-compose up
```

- open http://192.168.99.100:81/indexA.html
- change the file `indexA.html` and then refresh the browser (you see the old content)
- `docker exec -it  /bin/bash serverA` and then `cat /usr/share/nginx/html/indexA.html` 
- WTF!

__env setup__
 Virtualbox 5.0.4 + docker-machine + OSX 10.10

**Comment by thresheek** [comment]
That's a bug in VirtualBox.  See https://github.com/nginxinc/docker-nginx/issues/24 and https://github.com/boot2docker/boot2docker/issues/652 and https://www.virtualbox.org/ticket/9069

**Comment by timaschew** [comment]
thanks
