### ISSUE TITLE
Official docker tag equivalent to nginx-full? 

### ISSUE THREAD

**Issue by scyto** [nginxinc/docker-nginx#451]
I see the :latest is Debian based, however it seems to use own package base instead of debian.

This means if I want to include a common 3rd party modules such as http_subs_filter i can't simply apt install libnginx-mod-http-subs-filter because nginx-common is not installed, this is a different nginx package (i get why).

Please consider making official nginx containers that are on latest and equivalent to nginx-common, nginx-lite, nginx-full in functionality as the current docker is great - until you want to expand it, it makes no sense for me to use nginx:latest as base for my own nginx container due to this limitation.

Thanks for your consideration!

**Comment by thresheek** [comment]
No, there will not be any, since we can not guarantee the quality of code that is shipped with third-party modules (as seen in nginx-full and similar packages coming from Debian proper).

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
