### ISSUE TITLE
Entrypoint became a breaking change

### ISSUE THREAD

**Issue by hakuno** [nginxinc/docker-nginx#460]
I can't run my Docker because it got some trouble with the new version.

```
hub-dev-webserver | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
hub-dev-webserver | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
hub-dev-webserver | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
hub-dev-webserver | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
hub-dev-webserver | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf differs from the packages version
hub-dev-webserver | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
hub-dev-webserver | /docker-entrypoint.sh: Configuration complete; ready for start up
```

I can't access my HTTPS on

```
ss -nultp
Netid   State     Recv-Q     Send-Q          Local Address:Port          Peer Address:Port                                       
tcp     LISTEN    0          128                         *:44933                    *:*        users:(("node",pid=247,fd=18))    
tcp     LISTEN    0          128                         *:8080                     *:*                                          
tcp     LISTEN    0          128                         *:9200                     *:*                                          
tcp     LISTEN    0          128                         *:9300                     *:*            
```

The Docker routed `8080` to `80` and `8443` to `443`. But, there isn't on my network.

---

"Turning on" the IPv6...  why?

"Envsubst" the conf... why?

Why do those things came out automatically?

Wasn't it on demand? Per setting?

I don't understand how to overcome this.

My default.conf is custom. I have many entries in that.

How can I skip these undesired scripts?

Thanks in advance.

**Comment by yosifkit** [comment]
> "Turning on" the IPv6... why?

Only has an effect if you are using the default conf file.

> "Envsubst" the conf... why?

Only has an effect if you have `.template` files in `/etc/nginx/templates` (default values, both configurable)

> How can I skip these undesired scripts?

They shouldn't be doing anything, but an empty `/docker-entrypoint.d/` or just skipping the entrypoint entirely should work.

**Comment by hakuno** [comment]
Thanks.

**Comment by frebib** [comment]
This also broke several of my containers.

**Comment by thresheek** [comment]
Hi @frebib care to share the logs of breakage?

Thanks,

**Comment by hakuno** [comment]
@frebib @thresheek 
In the end I had to post that on https://github.com/docker/compose/issues/7852
