### ISSUE TITLE
Stable alpine images installs modules with old version

### ISSUE THREAD

**Issue by csupi** [nginxinc/docker-nginx#463]
I am trying to install the 'nginx-mod-http-headers-more' package in the stable-alpine version of nginx, but cannot start it because is installs the module for nginx 1.16

Reproduce:

docker run -it --rm nginx:stable-alpine sh

`/ # nginx -v`
`nginx version: nginx/1.18.0`
`/ # apk update`
`/ # apk search nginx-mod-http-headers*`
`nginx-mod-http-headers-more-1.16.1-r6`

**Comment by csupi** [comment]
alpine:3.12 should be used as base image in stable just like for the mainline

**Comment by thresheek** [comment]
The modules from alpine-own repos are incompatible with the modules provided by nginx.org which we use withing those images.

**Comment by thresheek** [comment]
Hi. I've added a way to make it easier to add modules on top of the official image, please check https://github.com/nginxinc/docker-nginx/tree/master/modules for more information.
