### ISSUE TITLE
Why `sticky` directive not working?

### ISSUE THREAD

**Issue by bobfang1992** [nginxinc/docker-nginx#464]
Hi, I have added the `sticky` directive to my config like this:
```
sticky route $route_cookie $route_uri;
```
and I got this error:
```
2020/10/30 17:32:25 [emerg] 1#1: unknown directive "sticky" in /etc/nginx/nginx.conf:12
nginx: [emerg] unknown directive "sticky" in /etc/nginx/nginx.conf:12
```
Looking at the doc here I think it should be supported: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#sticky

What am I missing here?

**Comment by thresheek** [comment]
'Sticky' directive is only available as a part of our commercial subscription: http://nginx.com/products/, as stated at the very end of the paragraph of documentation you posted.
