### ISSUE TITLE
Nginx with PHP-FPM and Traefik - Blank Page

### ISSUE THREAD

**Issue by Caaruzo** [nginxinc/docker-nginx#465]
Greetings, 

Today i runned into an issue and hope someone could help me please.
An while ago i set up a stack with docker-compose, including php-fpm, traefik and nginx. 
When i try to load my website it shows me a blank page with the word "error" printed on.

![image](https://user-images.githubusercontent.com/39491096/97790319-efc46700-1bc7-11eb-8fe9-ff5cd3ba3e54.png)

The Log of nginx tells me nothing. 

php-fpm.log:
`172.1.4.2 -  31/Oct/2020:21:22:20 +0000 "GET /index.php" 500`

Before i clean installed my machine, the stack worked like charm.
I dont run an swarm, its an standalone machine.
Cause i don't know anymore nor whats the cause of it, i hope someone can help me here please.
when i create an new file like phpinfo.php and access it, that works.

docker-compose-file

[docker-compose.yml.txt](https://github.com/nginxinc/docker-nginx/files/5469848/docker-compose.yml.txt)

Nginx conf of mydomain.de

[mydomain.de.conf.txt](https://github.com/nginxinc/docker-nginx/files/5469845/mydomain.de.conf.txt)

**Comment by thresheek** [comment]
That means your PHP code generates 500 (internal server error).  I suggest looking at your application logs for possible errors.

**Comment by Caaruzo** [comment]
Nothing in this log. It also happens to other of my pages, and it worked before i moved. Nothing has changed in the code.

**Comment by Caaruzo** [comment]
added nginx log. this happens to all applications. they worked before move server. No code changes have been made
