### ISSUE TITLE
Incorrect latest release on GitHub UI

### ISSUE THREAD

**Issue by rokf** [nginxinc/docker-nginx#469]
The latest release under the Releases section on https://github.com/nginxinc/docker-nginx is incorrect. Is this something that can be fixed?

![Screenshot 2020-11-10 at 13 03 57](https://user-images.githubusercontent.com/2836852/98671962-53cbf580-2355-11eb-80c4-f81f38eab09f.png)

**Comment by thresheek** [comment]
Thanks @rokf.

I've now removed the Releases tab altogether from the main page. Tags should be used instead, but I don't see how to get rid of Releases in the other parts of UI.  Any idea?

**Comment by rokf** [comment]
What are those other parts? I can't seem to find anything 😅

**Comment by thresheek** [comment]
E.g. when going to "tags", https://github.com/nginxinc/docker-nginx/tags one can switch to Releases...

**Comment by rokf** [comment]
Oh, I see. I guess that can't be affected.

From my perspective this issue can be resolved.

**Comment by thresheek** [comment]
Thanks!
