### ISSUE TITLE
Document how to use SSL ?

### ISSUE THREAD

**Issue by lrhazi** [nginxinc/docker-nginx#47]
The Dockerfile exposes 443, so ssl support is available? Could you please add how to add certs and enable ssl ?

**Comment by thresheek** [comment]
I don't see the point of re-documenting what's already documented.  See http://nginx.org/en/docs/http/ngx_http_ssl_module.html for details.

**Comment by sunshineo** [comment]
Hello. I think this is actually a pain point when running nginx in docker. Would be great if there are some documentation. It's a little difficult to get the cert files into the docker image. And even harder if you don't want to build the file into a docker image which will expose the cert and is a security risk.

**Comment by xkisu** [comment]
+1 there should be some documentation on the best practices for getting a cert into the docker image without including it in the build. This is especially important if your using a Lets Encrypt certificate which needs to be renewed every 90 days
