### ISSUE TITLE
Provide a way to specify the hash map size in the default conf

### ISSUE THREAD

**Issue by Gui13** [nginxinc/docker-nginx#473]
Using the nginx docker image in qemu-based VMs seems to trigger the infamous [map_hash_bucket_size issue](https://serverfault.com/questions/853102/nginx-could-not-build-map-hash-you-should-increase-map-hash-bucket-size-64).

From my understanding, it is left to the user to setup a valid value for this, the default possibly triggering nginx to halt without rescue.

The only way to fix this as of today is to replace the entire nginx.conf with a conf file where the `map_hash_bucket_size` is adapted to the actual CPU running the docker container (!). 

This implies reading the last image nginx.conf, copying it in your own docker folder, including it in your Dockerfile, and rebuild an image based on that.

This is impractical for anybody that wans to follow stable versions (i.e. `nginx:1.19` for instance), because each new version of the image requires a rebuild.

Considering that without this, the docker image will fail to start on any KVM based VM, would it be possible to make the map_hash_bucket_size modifiable through environment variable? Or like the ipv6 activation script, insert a sensible default in the nginx.conf at the entrypoint?

Another solution would be that nginx actually discovered a sensible value itself when the size is not defined in nginx.conf, but I would be happy with an easy way to override it.

**Comment by thresheek** [comment]
An easy way to override it is to put a `map.conf` file in `/etc/nginx/conf.d/` with the following contents:

`
map_hash_bucket_size 256;
`
