### ISSUE TITLE
How to config with nginx config of h5bp?

### ISSUE THREAD

**Issue by quyleanh** [nginxinc/docker-nginx#477]
I would like to use docker with [h5bp config](https://github.com/h5bp/server-configs-nginx).
How can I config this docker file to use with this? Thank you.

**Comment by thresheek** [comment]
Hi @quyleanh, you can mount the resulting nginx.conf or conf.d directly onto the image as a volume, or create a Dockerfile based on this image with the configuraion inside of it.  Check "How to use this image" section on https://hub.docker.com/_/nginx.
