### ISSUE TITLE
site-available and sites-enabled don't work

### ISSUE THREAD

**Issue by jdmarshall** [nginxinc/docker-nginx#48]
I thought the 'Debian' style nginx configuration was to use sites-available and sites-config

The nginx.conf included in this (debian-based) image contains

>     include /etc/nginx/conf.d/*.conf;
and not 

>     include /etc/nginx/sites-available/*;

as I anticipated.  This could result in problems for a lot of people.

**Comment by thresheek** [comment]
They arent there as nginx.org packages do not follow the apache-sque configuration scheme chosen by debian maintainers of a different package.  Not sure why this will result in any problems - it's quite clear from the brief overlook of the provided nginx.conf file that this won't work.

**Comment by peoplemerge** [comment]
It did cause problem for me.  Since Dockerfile/nginx isn't maintained it's a headache.  I think what's needed is a smattering of documentation... will send a PR.

**Comment by peoplemerge** [comment]
@thresheek please review https://github.com/docker-library/docs/pull/443.  More thought is needed.
