### ISSUE TITLE
SIGQUIT with recent nginx version on windows server core

### ISSUE THREAD

**Issue by SebastienHo** [nginxinc/docker-nginx#482]
Hi, 

Since 3 weeks, we have an issue on windows server 1903 and docker EE with NGINX container

Here is our configuration

```
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        0c38b2d
 Built:             11/12/2020 21:33:08
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       5b5efb2d49
  Built:            11/12/2020 21:31:44
  OS/Arch:          windows/amd64
  Experimental:     true
```

Whenever we do an dokcer build command we get an "Invalid signal: SIGQUIT" error.

Here is the docker file we test : 

```
# Image source
FROM nginx
LABEL maintainer=TraceParts
```
Here the result : 
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM nginx-alpine
pull access denied for nginx-alpine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
PS C:\agents\dev-traceparts-com\_work\26\s\project\.cicd\docfx> docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM nginx
latest: Pulling from library/nginx
Digest: sha256:31de7d2fd0e751685e57339d2b4a4aa175aea922e592d36a7078d72db0a45639
Status: Downloaded newer image for nginx:latest
 ---> 7baf28ea91eb
Step 2/2 : LABEL maintainer=TraceParts
Invalid signal: SIGQUIT
```
This happens with all version on nginx 1.9.5.

To solve our issue, we have created an base image which is based from a previous nginx working version from our registry. THis version is based on 1.9.1 nginx version.

Can you check why this happens?

**Comment by thresheek** [comment]
I never used docker on windows, so that's my wild guess: the runtime you're using doesnt support it fully?  

Quick searching shows a similar issue reportedly solved by upgrading to newer docker version on windows: https://github.com/docker-library/php/issues/887#issuecomment-530478852

Can you check that?

**Comment by SebastienHo** [comment]
Hi, 

Thanks for your reply.
I am not able to test on our server because it is not available in the current microsoft repo (defaultdocker). I guess we need to wait for MS to update the version they distribute.

Regards,

**Comment by chrisjd20** [comment]
I'm having this exact same issue.

**Comment by SebastienHo** [comment]
The problem comes from the LCOW component that is used by our windows server 1903 machine.
LCOW has been deprecated since last summer due to the arrival of WSL2, thus this version is not available on 1903.

If you have windows server 1903, You need to install a more recent version that supports WSL2 and this will solve the issue.

Regarding our needs, we decided to move to a windows 10 pro version to make sure all updates are available on this version and we don't have to reinstall our network machines, W10 version is fair enough for what we do with these machines (CICD) in terms of ressources.

Hope this help,

Regards,

Sébastien
