### ISSUE TITLE
Default entrypoint hides config error output

### ISSUE THREAD

**Issue by neben** [nginxinc/docker-nginx#488]
With the current docker image, there is no error logged if the configuration is bad. Apparently the config is checked somewhere in the entrypoint processing, and the container silently restarts if there's an error. This makes debugging the config unnecessarily complicated.

Output
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
[repeats]
```

With disabled entrypoint in docker-compose/stack:
```
  nginx:
    image: nginx
    entrypoint:
      - nginx 
      - -g 
      - daemon off;
```
the output contains the error as expected:
```
nginx: [emerg] "set" directive is not allowed here in /etc/nginx/sites-enabled/foo:2
2021/01/04 11:50:47 [emerg] 1#1: "set" directive is not allowed here in /etc/nginx/sites-enabled/foo:2
```

**Comment by yosifkit** [comment]
Perhaps there is a bug/conflict with [`20-envsubst-on-templates.sh`](https://github.com/nginxinc/docker-nginx/blob/fc5d895ad72b9d91162a8075197d0f7cadbbb197/mainline/debian/20-envsubst-on-templates.sh) and your configuration files since it never got to the "complete" line, but I don't see anything "checking" the config files for correctness.

https://github.com/nginxinc/docker-nginx/blob/fc5d895ad72b9d91162a8075197d0f7cadbbb197/mainline/debian/docker-entrypoint.sh#L32

**Comment by thresheek** [comment]
afaics it logs things pretty well:
```
thresh@coal nginx/docker-nginx/tmp $ docker run -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf -d nginx:1.19.6
0c17645fc74fa1e01aad6f2bc2ef6681057ee51272d82d7cedba13e20ce93843
thresh@coal nginx/docker-nginx/tmp $ docker logs 0c17
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/01/12 14:29:55 [emerg] 1#1: unknown directive "ruser" in /etc/nginx/nginx.conf:2
nginx: [emerg] unknown directive "ruser" in /etc/nginx/nginx.conf:2
```

Can you pls share your full configuration so we can reproduce the issue maybe?

Thanks

**Comment by neben** [comment]
Sorry for the delay. I couldn't reproduce this now, maybe it was related to errors with our docker swarm setup. I'll reopen the issue if it reoccurs, with a test case.
