### ISSUE TITLE
user id 101 is already mapped on debian (to systemd-network user)

### ISSUE THREAD

**Issue by mhow2** [nginxinc/docker-nginx#490]
Hi,
What is the reason behind the choice of uid=101 for nginx ? I mean, the processes bound to that user would borrow the systemd-network user on the host, it could possibly go wrong if an attacker is able to escape the container isn't ?

**Comment by thresheek** [comment]
The reason is simple: it was a first available uid that was historically used by the daemon on a clean machine.

And yes, if an attacker is able to escape the container, it would be mapped to whatever user is available on the machine and their privileges.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
