### ISSUE TITLE
Add link to changelog (release notes)

### ISSUE THREAD

**Issue by l3ender** [nginxinc/docker-nginx#491]
It would be nice if this repo had a link to the [nginx changes page](https://nginx.org/en/CHANGES), so people could easily see the updates between versions.

Thanks!

**Comment by thresheek** [comment]
Hi @l3ender, I'm not sure this would be helpful, but I don't mind.

Would something like:

The changelog for NGINX releases is available at upstream [changes page](https://nginx.org/en/CHANGES)

be OK in a README.md?

Thanks!

**Comment by l3ender** [comment]
Yes, I think that would be helpful for searchability/visibility.

Outside of that, aren't there also new releases due to an updated Alpine/Debian version, and/or features and enhancements for nginx compatibility in the image? These types of things would be nice to see in a changelog.

Thanks!

**Comment by thresheek** [comment]
The changes that applied on this image (e.g. new entrypoints features) are typically described at https://hub.docker.com/_/nginx, but we indeed lack the proper changelog between tags.  This is something we can improve upon indeed.
