### ISSUE TITLE
facing open() "/app/logs/access.log" failed (2: No such file or directory) issue

### ISSUE THREAD

**Issue by bilalmalik777** [nginxinc/docker-nginx#495]
Hello i am facing the following error. It was working fine on my local machine in docker but over the production server it is throwing the following error
```
021/01/19 08:43:48 [emerg] 1#1: open() "/app/logs/access.log" failed (2: No such file or directory)
nginx: [emerg] open() "/app/logs/access.log" failed (2: No such file or directory)
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
```
nginx.config
```server {

  listen 80;
  listen 443 default ssl;

  ssl_certificate /etc/ssl/certs/server.crt;
  ssl_certificate_key /etc/ssl/certs/server.key;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   /usr/share/nginx/html;
  }

  access_log /app/logs/access.log;
  error_log /app/logs/error.log;

}```

**Comment by thresheek** [comment]
/app/logs/ needs to be created, nginx will not create one for you. Can you check it exists inside the container?

**Comment by bilalmalik777** [comment]
thanks, @thresheek issue has been fixed. i just changed the

**Comment by drbeanut** [comment]
changed the what?!?!?!?

**Comment by bilalmalik777** [comment]
I made changes  under **/etc/nginx/sites-available** to configure Nginx as a reverse proxy

`server {
    listen 80;
    server_name test.abcd.com www.test.abcd.com;
    return 301 https://test.abcd.com$request_uri;
}

server {
  listen 443 ssl;
  server_name  test.abcd.com  www.test.abcd.com;

  ssl_certificate /etc/ssl/abcd-cert/abcd.com_ssl_certificate.cer;
  ssl_certificate_key /etc/ssl/abcd-cert/_.abcd.com_private_key.key;

  location / {
    	proxy_pass https://192.168.88.130:44377;
  }
}
`

I do not know why I left my answer uncompleted
