### ISSUE TITLE
application is not accessible, this site cannot be reached

### ISSUE THREAD

**Issue by bilalmalik777** [nginxinc/docker-nginx#496]
over system ip address, the application is accessible but when i try to access via domain name which is provided in nginx.config, browser says the site cannot be reached.I also make entries in the hosts file. Please help me to sort out this issue

```
server {
  # listen 80;
  listen 443 ssl;
  server_name  lahoreoffice.thingtrax.com  www.lahoreoffice.thingtrax.com;

  ssl_certificate /etc/ssl/certs/thingtrax.com_ssl_certificate.cer;
  ssl_certificate_key /etc/ssl/certs/_.thingtrax.com_private_key.key;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  error_page   500 502 503 504  /50x.html;

  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
```
![2021-01-19 14_05_27-938163349 - AnyDesk](https://user-images.githubusercontent.com/23011613/105045483-dd87f580-5a5f-11eb-8682-3014e7da1211.png)

**Comment by thresheek** [comment]
Try checking the nginx logs for requests and issues.  If there is nothing in there, means nginx didnt receive the request and you need to look somewhere else.
