### ISSUE TITLE
How can I build nginx images without http_dav_module and http_gzip_static_module?

### ISSUE THREAD

**Issue by wzg0131** [nginxinc/docker-nginx#497]
I need a nginx that doesn't open http_gzip_static_module and http_dav_module.Which file should I modify?

**Comment by thresheek** [comment]
It's not possible with an easy modification of the Dockerfiles, since they are using prebuilt packages.

**Comment by wzg0131** [comment]
> It's not possible with an easy modification of the Dockerfiles, since they are using prebuilt packages.

thanks,I've successfully compiled it using the old repository’s Dockerfile:https://github.com/docker-library/nginx/blob/master/1.7/Dockerfile
