### ISSUE TITLE
Switch to Alpine 3.13

### ISSUE THREAD

**Issue by michael-k** [nginxinc/docker-nginx#498]
See https://alpinelinux.org/posts/Alpine-3.13.0-released.html

Nginx packages for Alpine 3.13 are not yet available at https://nginx.org/packages/mainline/alpine/ and I don't know what's necessary for them to appear there.

**Comment by thresheek** [comment]
Thanks,

We need to build some infrastructure on nginx.org first to have alpine 3.13 packages available. I don't have a strict ETA, but it's in the works.

**Comment by thresheek** [comment]
Done for mainline.

**Comment by tarikbenammar** [comment]
Is it possible to get  the new image from docker hub directly ?  It's more convenient than having to built it locally 

Thank you !

**Comment by thresheek** [comment]
Hi @tarikbenammar, the image with Alpine 3.13 will be on Docker Hub next tuesday, with the release of 1.19.7 (as planned).

**Comment by pfleigo** [comment]
Hey @thresheek , seems like not uploaded yet (https://hub.docker.com/_/nginx). Is there any new timeline for it?

**Comment by thresheek** [comment]
Hi @pfleigo please check https://github.com/docker-library/official-images/pull/9635 for progress

**Comment by Shocktrooper** [comment]
I am assuming this ticket can probably be closed out, correct? Since 1.19.7 is on dockerhub or has alpine 3.13 not been shipped with the 1.19.7 update

**Comment by thresheek** [comment]
Hi @Shocktrooper you're correct it's shipped with 1.19.7 - however I'm keeping it open until stable version also gets it.

**Comment by thresheek** [comment]
All done.
