### ISSUE TITLE
nginx with ngx_http_stub_status_module

### ISSUE THREAD

**Issue by ffroliva** [nginxinc/docker-nginx#499]
Hi I am trying to monitor nginx with Prometheus but it is not clear to me if the offical image has this monitoring module enabled by default.

http://nginx.org/en/docs/http/ngx_http_stub_status_module.html

Do I need to extend the official image and add this module?

If that's not necessary, what is the best practice to enable it using the oficial docker image?

For example, would it be sufficiente to add the below nginx.conf as a volume when running the image?
```
server {
    listen 8080;
    stub_status;
    
}
```

Thank you in advance.

**Comment by thresheek** [comment]
Indeed, the official image is built with stub status module enabled, you can check with:
```docker run -ti --rm nginx:latest nginx -V```
and look for stub_status

**Comment by ffroliva** [comment]
Thank you. I was able to make it work!

**Comment by ffroliva** [comment]
Another question: 
What if I want to expose the metrics to prometheus, what would be the best approach. What if I have multiple instances of my nginx, what would be the official nginx advice?

This project seems not to support multiple instances of a nginx: https://github.com/nginxinc/nginx-prometheus-exporter

**Comment by thresheek** [comment]
We don't provide support for other projects here, sorry.

Please consider either opening an issue in the prometheus exporter project, or a thread under nginx mailing list over at http://mailman.nginx.org/mailman/listinfo/nginx.
