### ISSUE TITLE
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)

### ISSUE THREAD

**Issue by dagda1** [nginxinc/docker-nginx#50]
My host is OS X El Captain version 10.11.1

Docker version 1.9.0.

When I run the following command:

```docker run --name mynginx1 -P -d nginx```

And I attempt to connect to the port listed in ```docker ps -a``` with 

```curl -v http://localhost:32791```

I get:

>* Rebuilt URL to: http://localhost:32791/
*   Trying ::1...
* connect to ::1 port 32791 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 32791 failed: Connection refused
* Failed to connect to localhost port 32791: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 32791: Connection refused

If I connect to the docker container with ```docker exec -it mynginx1 bash``` and run ```nginx``` I get the following output:

> 2015/11/14 17:29:52 [emerg] 12#12: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/11/14 17:29:52 [emerg] 12#12: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/11/14 17:29:52 [emerg] 12#12: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/11/14 17:29:52 [emerg] 12#12: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/11/14 17:29:52 [emerg] 12#12: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/11/14 17:29:52 [emerg] 12#12: still could not bind()
nginx: [emerg] still could not bind()

**Comment by thresheek** [comment]
On OSX, docker runs inside a virtual machine in VirtualBox that does not map ports automatically to localhost.  ssh into that VM and use curl there.

**Comment by dagda1** [comment]
But the bind error is coming from the container.  I mentioned I opened a bash session in the container.

**Comment by md5** [comment]
@dagda1 The bind error is happening because you're trying to start `nginx` inside a container that's already running `nginx`.

**Comment by md5** [comment]
Also, since you've published the port with `-P`, you should use `$(docker-machine ip default)` to get the IP address you need to use instead of `localhost`.
