### ISSUE TITLE
Unable to secure page using docker-compose

### ISSUE THREAD

**Issue by MateoLa** [nginxinc/docker-nginx#501]
Hi.
I can't secure the page I'm working on when I load it using docker-compose. If I load it using docker command it works.
I read any post I found related to my problem but they doesn't help.
To ilustrate the problem I have I created a small repo here: https://github.com/MateoLa/hola-plex
It loads a pelx server. There you will find the steps to reproduce the issue.
I did many (many) tests. The containers pings each other. Theres no nginx logs of the failure neither docker logs nor console outputs.
I'm stuck. Please help. Thanks, Mateo.

**Comment by MateoLa** [comment]
Hello. I would like to know I you has found time to verify the issue?
The example above use only 2 files docker-compose.yml and nginx.conf.
Thanks.

**Comment by thresheek** [comment]
Hi @MateoLa ,

I have tried following your instructions, but I get during the following step:
```
Navigate to: https://localhost

You won't be connect to the secured page.
```:

ip-10-1-18-180% curl  https://localhost
curl: (7) Failed to connect to localhost port 443: Connection refused
```
In `docker-compose.yml` I can see that' you're publishing the following ports:
```
    ports:
      - '80:80'
      - '433:433'
```

You probably meant to publish port 443, as it's the one used for TLS.

**Comment by MateoLa** [comment]
Hi Thresheek.
I'm a fool, sorry for bother you. But most important, many, many, thanks.
