### ISSUE TITLE
NGINX not starting with Portainer stack

### ISSUE THREAD

**Issue by svandoe** [nginxinc/docker-nginx#507]
It appears that my issue is very similar to issue #360. I have followed the fix to copy files into my path as described however I still can't get NGINX to start.
Here is the portion of the stack for NGINX:

 nginx:
    image: nginx:1.15-alpine
    container_name: nginx_bitwarden
    ports:
      - "84:80"
      - "446:443"
    volumes:
      - /srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/nginx:/etc/nginx
      - /srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/ssl:/etc/ssl

I copied the files nginx.conf and default.conf to the first volume above and I still get the following error:

open() "/etc/nginx/nginx.conf" failed (2: No such file or directory).

Any help would be appreciated.

**Comment by thresheek** [comment]
Can you show the output of:
```
$ ls -la /srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/nginx
```
and
```
$ docker run -ti --rm -v /srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/nginx:/etc/nginx nginx:1.15-alpine ls -la /etc/nginx
```
?

**Comment by svandoe** [comment]
Output of first item:
drwxr-sr-x 3 root root  4096 Feb 18 17:07 .
drwxr-sr-x 6 pi   users 4096 Feb 18 15:29 ..
drwxr-sr-x 3 root root  4096 Feb 18 15:50 etc

Output of second item:
ls: /etc/nginix: No such file or directory

**Comment by thresheek** [comment]
Try mounting `/srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/nginx/etc/nginx` to `/etc/nginx` in your volume definitions.

**Comment by svandoe** [comment]
This is the volume I have currently

 - /srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/nginx:/etc/nginx

I'm not sure how you want me to change it? Do you mean this?
 - /srv/dev-disk-by-uuid-1c0dc0b4-d37c-4a43-b9ed-597a8dd4f64f/Primary/AppData/nginx/etc/nginx:/etc/nginx

It seems like this path just has unnecessary folders. On closer inspection it looks like I have the nginx.conf file in the path above and this might be my problem. Can I also just relocate this file to the original path? I think I may not fully understand the : in the path.

**Comment by thresheek** [comment]
You need not only one nginx.conf file, but a number of other files it might include, but it's up to you what you provide and what you mount inside of an image.

NGINX needs /etc/nginx/ and /etc/nginx/nginx.conf to work.

**Comment by svandoe** [comment]
I understand that but the problem seems to be that the image is not writing any of the necessary files to the defined volumes so I have tried to manually copy some files into the correct folders but this has not worked either. Why do these files not get written when the stack is deployed?

**Comment by thresheek** [comment]
The image doesnt write anything to a container, it's the job of your management system (docker, or docker-compose, or similar).  In your case, I see that you're mounting a wrong path to a container, which means that it wouldnt get a file it needs.  You need to sort it out and mount what is expected. I suppose copying /etc/nginx/ contents from a container to your host should be fine, and when mounted accordingly it should work fine.

**Comment by ansred** [comment]
Here is a simple stack I am using with a static page and it's working fine using my Synology DSM as Docker hosted and Portainer as Docker Compose GUI

```
web:
  image: nginx
  container_name: lab-redmedia-bootstrap
  volumes:
   - /volume1/docker/Bootstrap/redrice/:/usr/share/nginx/html:ro
  ports:
   - "8228:80"
```

**Comment by thresheek** [comment]
Closing due to feedback timeout.
