### ISSUE TITLE
E: Version '1.9.7-1~jessie' for 'nginx' was not found

### ISSUE THREAD

**Issue by earnaway** [nginxinc/docker-nginx#51]
After the update to 1.9.7, when I try an fresh build of nginx docker container, I get:
`E: Version '1.9.7-1~jessie' for 'nginx' was not found`

The command is:
```
ENV NGINX_VERSION 1.9.7~jessie
RUN apt-get update && \
    apt-get install -y ca-certificates nginx=${NGINX_VERSION} && \
    rm -rf /var/lib/apt/lists/*
```

The same happened when updating to 1.9.6 and took a couple of days before I could apt-get . Is there any specific reason why I can't install the ca-certificates for that nginx version straight away?

**Comment by tianon** [comment]
Just curious, why are you building from source instead of just doing a simple `Dockerfile` on top?

ie:
```Dockerfile
FROM nginx
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with extra packages/setup. :smile:

**Comment by thresheek** [comment]
@earnaway check if you have http caches in front of your docker builder.

**Comment by earnaway** [comment]
Thanks - this is more just for testing certain systems and I build a single box with PHP and NGINX inside, which I use the PHP base docker image and then install nginx. I just can't see why "Version '1.9.7-1~jessie' for 'nginx' was not found" happens when the official nginx version was just released, and i'm building with no-cache as well.

**Comment by thresheek** [comment]
As I've said, check if you have http caches or proxies in front of your systems that might cache requests to nginx.org repositories. This is the only thing that might result in such an error.

**Comment by earnaway** [comment]
:+1:
