### ISSUE TITLE
Improve documentation on adding third-party modules

### ISSUE THREAD

**Issue by nicbou** [nginxinc/docker-nginx#511]
My scenario is pretty standard: I have a docker-compose project that uses nginx. I want to add a module (ngx_cache_purge). How do I do this?

I have read [the page on third-party modules](https://github.com/nginxinc/docker-nginx/tree/master/modules) multiple times, but I just can't understand it. It seems like it was written as a reference for the maintainers, not as a guide for the users. It makes too many assumptions about our understanding of this image's build process.

I have an nginx reverse proxy with some custom configs in a docker-compose.yml file. This is my starting point. I don't know how to work from there using the instructions I am given.

Here's my attempt at understanding those instructions, and explaining them back to you. The "???" are the parts I don't understand.

---

You can build your own version of the official nginx image with third-party nginx modules. There are two ways to do this.

## Install packages from hg.nginx.org/pkg-oss

If your module is in [this list](https://hg.nginx.org/pkg-oss/file/tip/contrib/src) (the `Makefile.module-*` files), you just need to add the module to the `ENABLED_MODULES` build arg:

```
# docker-compose.yml
my-nginx-image:
  build:
    context: my-nginx-image  # ??? Which image ???
    args:
      - "ENABLED_MODULES=ndk lua"
```

??? Which image am I supposed to use? It's clearly not nginx:alpine ???

## Install local packages

If your module is not on hg.nginx.org/pkg-oss, you must install it yourself. 

1. Place your modules in the same directory as your `Dockerfile` (??? Which Dockerfile ???). The module directories must follow this structure:
   ```
   test
   ```
2. ???

??? How do I do this in a regular docker-compose setup ???

**Comment by nicbou** [comment]
I found a bit more assistance here: https://gist.github.com/hermanbanken/96f0ff298c162a522ddbba44cad31081

**Comment by thresheek** [comment]
Hi @nicbou, thanks for raising a very valid point. Sometimes we assume the knowledge of how things work and this is something that can definitely be improved.

The document you linked to explains how to build an image which you can later either define in your docker-compose file as an image to run (if you built it manually), or how to build it before starting up the containe using the build phase of docker-compose.

You can use something like the following to automate things and make them manageable:
```
thresh@coal ~/tmp/myapp $ tree
.
├── docker-compose.yml
└── my-nginx
    ├── cachepurge
    │   └── source
    └── Dockerfile

2 directories, 3 files
```
Where `docker-compose.yml` is:
```
version: "3.3"
services:
  web:
    build:
      context: ./my-nginx/
      args:
        ENABLED_MODULES: cachepurge
    image: my-nginx-with-cache-purge:v1
    ports:
      - "8666:8666"
  redis:
    image: "redis:alpine"
```
`my-nginx/cachepurge/source` is:
```
https://github.com/FRiCKLE/ngx_cache_purge/archive/2.3.tar.gz
```
And `Dockerfile` is a copy of https://github.com/nginxinc/docker-nginx/blob/master/modules/Dockerfile

Now, running `docker-compose up --build -d` will build the image and run the application for you.  I hope that's good enough to understand, let me know if other clarifications are needed.

**Comment by nicbou** [comment]
Hi @thresheek. I'm trying this again today. This morning's attempt went really smoothly. Your instructions were crystal clear. They should appear verbatim in the README.

Here are a few notes that might simplify things for other users:

* There is also https://github.com/nginxinc/docker-nginx/blob/master/modules/Dockerfile.alpine
* The *contents* of `my-nginx/cachepurge/source` are the URL to the desired package. This is somewhat obvious from the given commands, but still easy to miss.
* If your docker build context is not the default one, you will need to change the COPY instruction to match the correct path to your modules.
* Don't forget to enable the module with load_module.

Thank you for taking the time to write the previous comment. It was immensely helpful.
