### ISSUE TITLE
Why can only install third-party modules in the mainline image?

### ISSUE THREAD

**Issue by ADD-SP** [nginxinc/docker-nginx#512]
> It's possible to extend a **mainline image** with third-party modules either from your own instuctions following a simple filesystem layout/syntax using `build_module.sh` helper script, or failing back to package sources from `https://hg.nginx.org/pkg-oss`.

For what reason did the decision not to provide a way to install third-party modules in the stable image? Is the current method not stable enough?

**Comment by defanator** [comment]
@ADD-SP my guess here is that a new stable is about to arrive later in April, so we haven't dilated recent changes in the mainline package branch to the recent `stable-1.18` branch. This should be relatively easy though if there is a demand.

**Comment by ADD-SP** [comment]
Thanks for your answer. @defanator
