### ISSUE TITLE
Easier installation of third-party modules.

### ISSUE THREAD

**Issue by ADD-SP** [nginxinc/docker-nginx#513]
```
/pkg-oss $ LC_ALL=C make -C debian list-all-modules
make: Entering directory '/pkg-oss/debian'
brotli                  1.0.0-1
encrypted-session       0.08-1
geoip                   1.19.6-1
geoip2                  3.3-1
headers-more            0.33-1
image-filter            1.19.6-1
lua                     0.10.19-1
modsecurity             1.0.1-1
ndk                     0.3.1-1
njs                     0.5.0-1
opentracing             0.10.0-1
passenger               6.0.6-1
perl                    1.19.6-1
rtmp                    1.2.1-1
set-misc                0.32-1
subs-filter             0.6.4-1
xslt                    1.19.6-1
make: Leaving directory '/pkg-oss/debian'
```

This list is a bit short of modules and the steps to install modules not mentioned above are a bit tedious as it requires knowing the download link of the module and the dependencies of the module, I think this should be improved.

Could the list of third-party modules supported by default be extended in some way, for example the author of a third-party module could create a pull request and provide the necessary information (such as download links and dependencies) to add this module.

**Comment by defanator** [comment]
@ADD-SP all required information could be found in the `contrib/src` subdirectory within the `pkg-oss` repo, e.g. download link:

http://hg.nginx.org/pkg-oss/file/tip/contrib/src/nginx-opentracing/Makefile#l4 (direct link)
http://hg.nginx.org/pkg-oss/file/tip/contrib/src/ngx_http_substitutions_filter_module/Makefile#l4 (GIT url)

Dependencies:

http://hg.nginx.org/pkg-oss/file/tip/contrib/src/nginx-opentracing/Makefile#l13
http://hg.nginx.org/pkg-oss/file/tip/contrib/src/lua-nginx-module/Makefile#l18

etc.

Corresponding parts of the package subdirs (apk/debian/rpm) are supposed to use the information from contrib to obtain module sources, patches, etc. The entire structure has been made in a way that allows to extend initial list of modules easily.

**Comment by ADD-SP** [comment]
> @ADD-SP all required information could be found in the `contrib/src` subdirectory within the `pkg-oss` repo, e.g. download link:
> 
> http://hg.nginx.org/pkg-oss/file/tip/contrib/src/nginx-opentracing/Makefile#l4 (direct link)
> http://hg.nginx.org/pkg-oss/file/tip/contrib/src/ngx_http_substitutions_filter_module/Makefile#l4 (GIT url)
> 
> Dependencies:
> 
> http://hg.nginx.org/pkg-oss/file/tip/contrib/src/nginx-opentracing/Makefile#l13
> http://hg.nginx.org/pkg-oss/file/tip/contrib/src/lua-nginx-module/Makefile#l18
> 
> etc.
> 
> Corresponding parts of the package subdirs (apk/debian/rpm) are supposed to use the information from contrib to obtain module sources, patches, etc. The entire structure has been made in a way that allows to extend initial list of modules easily.

@defanator 

Looks good, how should I add a third party module to `pkg-oss`? For example, which email to send the patch to, is there any formatting requirements for the commit message, etc.
