### ISSUE TITLE
NGINX_PORT is being ignored

### ISSUE THREAD

**Issue by tcurdt** [nginxinc/docker-nginx#514]
Based on the documentation here https://hub.docker.com/_/nginx/ I would expect that setting `NGINX_PORT` should change the port that nginx is listening on. But that does not seem to be the case.

This should work:

`docker run -it -e NGINX_PORT=1234 -p 1234:1234 nginx:alpine`

but instead this works

`docker run -it -e NGINX_PORT=1234 -p 1234:80 nginx:alpine`

which shows that `NGINX_PORT` is being ignore as it's the same as:

`docker run -it -p 1234:80 nginx:alpine`

**Comment by thresheek** [comment]
Hi @tcurdt,

You also need to provide a template file referencing that variable so it would be replaced.  It's not in the default configuration, you need to provide it yourself.

**Comment by tcurdt** [comment]
@thresheek thanks for the quick response.

I didn't expected that from reading the docs. 

> Out-of-the-box, nginx doesn't support environment variables inside most configuration blocks. But this image has a function, which will extract environment variables before nginx starts.

So it would be nice to update the docs to make this more explicit.
Or even better - have the default configuration support it.

**Comment by thresheek** [comment]
The quoted phrase is right there in the example on how to achieve it, so I'm not sure how to be more explicit. I'm open to suggestions on how to improve it. The default will not change, though.

**Comment by tcurdt** [comment]
The phrase "most configuration blocks" is unclear and "will extract environment variables" is a detail not really relevant to the users of the image. I would suggest to replace that paragraph more along the lines of

> The default configuration provided with the image **does not** contain any references to environment variables. But if you provide your own configuration that references environment variables they will be expanded as follows:

**Comment by tcurdt** [comment]
Not really sure I understand the idea of having such a mechanism but not offering it with the default configuration. But fair enough.

**Comment by thresheek** [comment]
> The phrase "most configuration blocks" is unclear 

That's because nginx (not this docker image) has limited support for using environment variables in the configuration file: https://nginx.org/r/env

Thanks for your suggestion!
