### ISSUE TITLE
enable ipv6 for arm64v8/nginx

### ISSUE THREAD

**Issue by joe-sch** [nginxinc/docker-nginx#515]
Hi there,
i was trying to use nginx on my raspberry on my home network to serve as a forward proxy.
My raspberry is only reachable via ipv6 from the outside world.

In this description: https://www.cyberciti.biz/faq/nginx-ipv6-configuration/ i saw that ipv6 support is disabled by default and that i need to compile nginx with `–with-ipv6` flag.
There is also description how i can verify if nginx was built to support ipv6

````
nginx -V 2>&1 >/dev/null | grep --color -o with-ipv6
````

At least for the  `arm64v8/nginx` image  it seems that it is not enabled.

**Comment by thresheek** [comment]
Hi @joe-sch, ipv6 is enabled by default in all nginx builds starting from 1.11.5 (see http://nginx.org/en/CHANGES):
```
Changes with nginx 1.11.5                                        11 Oct 2016

    *) Change: the --with-ipv6 configure option was removed, now IPv6
       support is configured automatically.
```

So all builds newer tags in this docker image should work fine with ipv6.

**Comment by joe-sch** [comment]
oh sorry that was my mistake.
I thought it was because of that, but now I have found out that docker network was not ipv6 enabled
