### ISSUE TITLE
arm32v7/nginx:1.19.7-alpine fails to fully start up

### ISSUE THREAD

**Issue by nanowireUK** [nginxinc/docker-nginx#517]
The latest arm32v7/nginx:1.19.7-alpine fails to start up on my arm32v7 Debian 9 based machine. The whole container just stops straight after it says ready for start up. There are no error messages that occur and this problem does not appear in the arm32v7/nginx:1.19.6-alpine release.

```
sudo docker run arm32v7/nginx:1.19.7-alpine
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

System info:
```
cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 996.14
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc08
CPU revision    : 2

Hardware        : Generic AM33XX (Flattened Device Tree)
Revision        : 0000
Serial          : 0000000000000000
````

**Comment by nanowireUK** [comment]
@huguesBouvier fyi

**Comment by nanowireUK** [comment]
This is reproducible on two identical Moxa UC-8100A-ME industry gateways running Debian 9. Container engine is the Azure IoT Edge Moby runtime `Docker version 3.0.13+azure, build dd360c7c0de8d9132a3965db6a59d3ae74f43ba7`

**Comment by thresheek** [comment]
Hi @nanowireUK,

Can you pelase try:
`docker run -ti --rm arm32v7/alpine:3.13 /bin/sh -c 'date && uname -m'?

I suspect it's similar to https://github.com/nginxinc/docker-nginx/issues/510, https://github.com/alpinelinux/docker-alpine/issues/150 and https://github.com/alpinelinux/docker-alpine/issues/135.

Thank you!

**Comment by nanowireUK** [comment]
@thresheek @huguesBovier that is exactly the issue. The way I understand the Alpine issue, this is effectively a known breaking change and requires additional libraries on the host.

```
Status: Downloaded newer image for arm32v7/alpine:3.13
Sun Jan  0 00:100:571606  1900
armv7l
failed to resize tty, using default size
```

**Comment by thresheek** [comment]
Correct, @nanowireUK, so you need to update your docker environment on a host for newer images to work.  Meanwhile you can use a debian variant of an image.
