### ISSUE TITLE
Dockerfile is buggy: modules/Dockerfile.alpine 

### ISSUE THREAD

**Issue by AnubhavUjjawal** [nginxinc/docker-nginx#518]
In the line https://github.com/nginxinc/docker-nginx/blob/dcaaf66e4464037b1a887541f39acf8182233ab8/modules/Dockerfile.alpine#L21 we are cloning https://hg.nginx.org/pkg-oss/ . But updates to that repository such as updating Nginx to [1.19.8](https://hg.nginx.org/pkg-oss/rev/9fc3031c13ce) fail the docker build for earlier versions. 

For example, If I use the current mainline-alpine (1.19.7-alpine) as builder, build fails.

To mitigate this, we can checkout to a specific revision using `hg update -r <rev>` after clone.

**Comment by thresheek** [comment]
Hi @AnubhavUjjawal,

Can you try the following patch on top of Dockerfile.alpine:
```
diff --git a/modules/Dockerfile.alpine b/modules/Dockerfile.alpine
index b2b8b3e..ec64282 100644
--- a/modules/Dockerfile.alpine
+++ b/modules/Dockerfile.alpine
@@ -47,9 +47,9 @@ RUN set -ex \
         elif make -C /pkg-oss/alpine list | grep -E "^$module\s+\d+" > /dev/null; then \
             echo "Building $module from pkg-oss sources"; \
             cd /pkg-oss/alpine; \
-            make abuild-module-$module BASE_VERSION=$NGINX_VERSION; \
+            make abuild-module-$module BASE_VERSION=$NGINX_VERSION NGINX_VERSION=$NGINX_VERSION; \
             apk add $(. ./abuild-module-$module/APKBUILD; echo $makedepends;); \
-            make module-$module BASE_VERSION=$NGINX_VERSION; \
+            make module-$module BASE_VERSION=$NGINX_VERSION NGINX_VERSION=$NGINX_VERSION; \
             find ~/packages -type f -name "*.apk" -exec mv -v {} /tmp/packages/ \;; \
         else \
             echo "Don't know how to build $module module, exiting"; \
```

With your proposal, checking out a correct revision is also a good option;  the reason it's not there is I wanted to have "latest and greatest" modules versions available, and not specifically tied to a specific release.  Maybe we should make it configurable somehow.

**Comment by AnubhavUjjawal** [comment]
@thresheek I am using a custom version of /modules/Dockerfile.alpine.

However, according to me, docker images built using `Dockerfile` should be reproducible if we provide the same `ARG` and `ENV` every time we build an image, that's why I came up with an initial approach of updating the revision. Packages break compatibility all the time, hence having "latest and greatest" modules versions available isn't the best approach a/c to me.

**Comment by thresheek** [comment]
Many thanks for your feedback!

I agree, I'll fix the Dockerfiles to be reproducible.

**Comment by gnought** [comment]
The root clause is `NGINX_VERSION` is hard-coded to 1.19.8 in `pkg-oss/contrib/src/nginx/version`
