### ISSUE TITLE
30-tune-worker-processes.sh does not work on Windows Docker Desktop

### ISSUE THREAD

**Issue by Herr-Sepp** [nginxinc/docker-nginx#520]
The Nginx container cannot start under docker for windows (WSL 2 Backend) when providing NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE as environment variable.
It exits with error code 1.

last output with sh -x 30-tune-worker-processes.sh

```
+ controller=cpuset
+ IFS= read -r line
+ foundroot=/sys/fs/cgroup/cpuacct
+ echo /sys/fs/cgroup/cpuacct
+ cpu=/sys/fs/cgroup/cpuacct
+ '[' /sys/fs/cgroup/cpuacct ]
+ get_quota /sys/fs/cgroup/cpuacct
+ cpuroot=/sys/fs/cgroup/cpuacct
+ ncpu=0
+ '[' -f /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us ]
+ return
+ ncpu_quota=
```
I don't know why it fails at [line 175](https://github.com/nginxinc/docker-nginx/blob/dcaaf66e4464037b1a887541f39acf8182233ab8/entrypoint/30-tune-worker-processes.sh#L175)

Files inside /sys/fs/cgroup/cpuacct
![image](https://user-images.githubusercontent.com/10489458/110769750-d52a8a80-8258-11eb-9fd5-a8dbb488340c.png)

Tested with Docker Desktop Version 3.2.1 | Engine 20.10.5 | WSL2 Backend

**Comment by thresheek** [comment]
Hi @Herr-Sepp,

Thanks for the letting us know.  Indeed, I didnt test on WSL2. I will and adapt the script accordingly.

**Comment by thresheek** [comment]
Hi @Herr-Sepp can you build an image from https://github.com/nginxinc/docker-nginx/tree/520-fix-wsl and let me know if that fixes the issue for you?  I've checked it on my WSL2 setup and it seems it works, but I'd rather double check before pushing into master.

Thank you!

**Comment by Herr-Sepp** [comment]
@thresheek 
wow that was fast thank you!
It also works for me. Both without limit and with limit resources of WSL2.  
In both cases, the script correctly detected the CPU cores available to the WSL2.

Thank you for these entrypoint-scripts that make all our lives a little easier.👍
