### ISSUE TITLE
Not able to pull image

### ISSUE THREAD

**Issue by pradipdockerhub** [nginxinc/docker-nginx#522]
getting below error, can someone help me?
PS C:\> docker pull nginx 
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: read udp 192.168.65.3:49159->192.168.65.1:53: i/o timeout

**Comment by thresheek** [comment]
Hi @pradipdockerhub it looks like a general issue with your docker set up. Sadly we cant help here. Try https://forums.docker.com/ maybe.
