### ISSUE TITLE
Package Release Not Found

### ISSUE THREAD

**Issue by Writtscher** [nginxinc/docker-nginx#527]
Hi. I hope you can help me with this. When I run your build command I get the the following error

```
+ hg clone -r 1.18.0-2~buster https://hg.nginx.org/pkg-oss/
destination directory: pkg-oss
abort: unknown revision '1.18.0-2~buster'!
```
(I tried stable instead of mainline but no luck)

I have used your Dockerfile and added the module `ngx_http_sub_module`.

**Comment by thresheek** [comment]
Hi @Writtscher !

Indeed, the Dockerfile needs to strip the ~buster part before checking out sources - I didnt check that with Debian. Will fix!

**Comment by Writtscher** [comment]
@thresheek Nice, thank you!
