### ISSUE TITLE
envsubst conflicts with internal variables

### ISSUE THREAD

**Issue by Roffild** [nginxinc/docker-nginx#529]
envsubst is a very bad solution because variables in Nginx also start with $
```
    set $MAGE_ROOT ${MAGENTO_ROOT}; # Variable: MAGENTO_ROOT
    set $MAGE_MODE ${MAGENTO_RUN_MODE}; # Variable: MAGENTO_RUN_MODE
    set $MFTF_UTILS ${MFTF_UTILS}; # Variable: MFTF_UTILS
    set $WITH_XDEBUG ${WITH_XDEBUG}; # Variable: WITH_XDEBUG

    set $my_fastcgi_pass "fastcgi_backend";
    if ($cookie_XDEBUG_SESSION) {
        set $my_fastcgi_pass "fastcgi_backend_xdebug";
    }

    # Support for SSL termination.
    set $my_http "http";
    set $my_ssl "off";
    set $my_port "80";
    if ($http_x_forwarded_proto = "https") {
        set $my_http "https";
        set $my_ssl "on";
        set $my_port "443";
    }
```

**Comment by Roffild** [comment]
You can create a script on Perl to replace between `%var&` to avoid conflicts.

Why is the dead Perl included in the image, but not Python?

**Comment by thresheek** [comment]
Hi @Roffild, can you explain a bit more about how `envsubst` conflicts with internal configuratoin variables? `envsubst` will not touch anything you are not defining in your docker environment, so it's up to you to configure what's best.

In your case I believe the correct way to use it is to rename the vars passed from environment like `MFTF_UTILS` and `WITH_XDEBUG`, since `envsubst` will replace both entries.

Also, `perl` is included in a Debian-based image since it is a part of a base system, and we cant easily get rid of it.  If you wish to use an image without perl, consider switching to `nginx:alpine` Alpine based-variants.

**Comment by Roffild** [comment]
envsubst simply replaces one text with another without parsing the syntax.

The replacement pattern is the same as the syntax for variables. The chances of replacing the wrong thing and not getting an error is huge. This is a security hole! (Vulnerability)

The replacement pattern MUST NOT be part of the config syntax.

**Comment by thresheek** [comment]
I don't think I agree that it's a vulnerability nor a security hole.

First of all, no replacement is done by default.  You're free to provide your static configuration and it will not be touched by `envsubst`.

Second, `envsubst` won't replace variables it doesn't know of as you have to manually specify them in the environment.

Third, and most important, it's an administrator job to ensure the correctness of configuration input, even if it's templated, and environment variables if they affect your configuration.

However we can improve the documentation so the users will be aware of a possible issue.  Can you provide a configuration snippet with envsubst-based substitution that will pass nginx configuration check and be problematic?

Thanks!

**Comment by Roffild** [comment]
There are a lot of environment variables to accidentally (or deliberately) use a name. NO ONE CONTROLS THEIR QUANTITY.

I am sure that many people use $HOME and $PATH for regular expressions.

Even the error message:
` "Check the contents of $PATH in config.php" `
Now it will show a lot of interesting information for hacking.

**Comment by thresheek** [comment]
I dont think I understand how the regular expression and the error message are linked, can you provide a configuration snippet that exposes this problem, when used with envsubst?

Thanks!

**Comment by Roffild** [comment]
```
server {
    server_name   ~^(www\.)?(?<HOME>.+)$;

    location / {
        root   /sites/$HOME;
    }
}
```

**Comment by thresheek** [comment]
So what's the problem with it?

If you set HOME in your environment to some path that exists under /sites/ and run envsubst as per entrypoints, nginx will serve the files just like it did with a non-edited configuration without envsubst.

If you set HOME in your environment to some path that does not exist under /sites/ and run envsubst as per entrypoint script, nginx will do a 404.

Where is the security issue?

**Comment by Roffild** [comment]
envsubst is executed BEFORE starting Nginx. Therefore, Nginx will ALWAYS execute this config:
```
server {
    server_name   ~^(www\.)?(?<HOME>.+)$;

    location / {
        root   /sites/root;
    }
}```

**Comment by thresheek** [comment]
Correct, and it will use the same configuration when a client executes a call to "Host: www.root", in an non-envsubst configuration.

**Comment by Roffild** [comment]
Wrong! The /sites/example.com, not the /sites/root, must be used when requesting www.example.com

http://nginx.org/en/docs/http/server_names.html

**Comment by thresheek** [comment]
OK, so the proposition is to add a clause like:
```
Be careful when using envsubst-based substitution of environment variables in templates! Check if they dont overlap with internal variables possibly used in your configuration, or that might result in unexpected configuration changes
```

How does that sound?

**Comment by Roffild** [comment]
...and leave that security hole?

You need to rewrite the script to replace the template. The template should not allow Nginx to start due to a syntax error if not all variables have been replaced:
```
sed / %var% / value
or
sed / #var# / value
```

The decision to use envsubst was wrong! All configs must be checked. Keeping compatible is stupid.

**Comment by thresheek** [comment]
There are many ways to write insecure configuration in nginx, and `envsubst`-based templating is possibly just another way to do it.  We don't take precautions on what is supposed to be human-checked and understood by a system administrator.  Anyone who's templating their configuration should understand that - and hence I propose to write a clause in the documentation to explicitely state it.

Regarding the variable names, what if a user has e.g. sub_filter in their configuration, replacing literal non-templated '%var%' in the responses?  Should templating engine fail to start then?  I think not, it's up for an administrator to decide their configuration, and we should not bail out on that.

And I disagree, keeping backwards compatibility is not stupid for a widely used project like `nginx`.

**Comment by tianon** [comment]
The extreme measures of backwards compat are one of the main reasons I love NGINX so much (my config written today will likely work many versions from now). :heart:

To even get the `envsubst` behavior, it requires the configuration to be explicitly placed in `/etc/nginx/templates/` with a `.template` filename suffix (as opposed to `.conf` files in `/etc/nginx/conf.d`), so it's hard to see how the configurator explicitly opting into this behavior wouldn't be expected to understand their configuration and the implications of opting in?  It's not like this is being unexpectedly applied to existing configuration files. :confused:
