### ISSUE TITLE
How to add modules ?

### ISSUE THREAD

**Issue by valm13** [nginxinc/docker-nginx#531]
Hello,

Is there a way to add modules to this official Nginx Docker image?
I've made a post on StackOverflow: https://stackoverflow.com/q/67005594/9914294

Have a nice day,

Valentin M.

**Comment by thresheek** [comment]
Hi @valm13,

the `autoindex` module is provided with this image, since it's enabled by default it nginx.

If you would like to add some other modules (e.g. third party ones, not included in nginx), please check https://github.com/nginxinc/docker-nginx/tree/master/modules#readme

**Comment by valm13** [comment]
Hi `@thresheek,`

Thank you for the fast and clear answer!
I had misconfigured my Nginx conf that's why the autoindex instruction wasn't processed, just forgot a semi-colon...
