### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by QJpd** [nginxinc/docker-nginx#532]
Hello, when I use nginx:latest When the container deploys the application of Vue, the stylesheet type file of Vue is always considered as text / HTML, resulting in CSS unable to load.

I try to solve this problem by:

http {

include /etc/nginx/ mime.types ;

default_ type application/octet-stream;

Related configuration solution, but has failed to work, experienced boss to help solve the puzzle, thank you.

 -----------------------
user  root;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    # gzip  on;
    
    include /etc/nginx/conf.d/*.conf;
    
    server { 
        listen       9000;
        server_name  localhost;

        #include /etc/nginx/*.conf

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
        root   /map/vue/demo;

        location / {
           try_files $uri $uri/ @router;#需要指向下面的@router否则会出现vue的路由在nginx中刷新出现404
           index  index.html index.htm;
        }
        
        #对应上面的@router，主要原因是路由的路径资源并不是一个真实的路径，所以无法找到具体的文件
        #因此需要rewrite到index.html中，然后交给路由在处理请求资源
        location @router {
            rewrite ^.*$ /index.html last;
        }

**Comment by thresheek** [comment]
What is the filename that is requested that has the `text/html` content type?  Can you provide the output `curl -v http://host/filename` to show the issue?

Thanks

**Comment by youyazhuwuya** [comment]
Use COPY
I ran into the same problem
![image](https://user-images.githubusercontent.com/29652276/120447827-8d318480-c3bd-11eb-8ade-72d440627f96.png)

Dockerfile
```
FROM nginx:latest
ENV TIME_ZONE=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone
COPY dist/* /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
```
Use -v
The program works normally😂
```
docker run -d -p 80:80 -v /usr/app/nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v /usr/app/nginx/html:/usr/share/nginx/html --name=ruoyi-ui --network=ruoyi-network nginx:latest
```

**Comment by thresheek** [comment]
Hi @niaucz can you share nginx.conf as well?

**Comment by niaucz** [comment]
@thresheek 

```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

		location / {
            root   /usr/share/nginx/html;
			try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }
		
		location /prod-api/{
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_pass http://gateway-server:8080/;
		}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
```

**Comment by nielsuit227** [comment]
Does anybody know when this started? Can we downgrade for a temporary solve? Seems I got the same problem.

**Comment by nielsuit227** [comment]
For me, problem never was with nginx, was with routing.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
