### ISSUE TITLE
Not able to see anything in error_log

### ISSUE THREAD

**Issue by siddjain** [nginxinc/docker-nginx#538]
we are using `nginx:1.17` Docker image. In our server config block we have this line:

```
error_log /var/log/nginx/error.log debug;
```

But the file is empty and just a symlink to `/dev/stderr`. Reading [this](https://docs.nginx.com/nginx/admin-guide/monitoring/debugging/) link it seems the NGINX binary needs to be compiled with `--with-debug` flag for the debug info to show up in `error_log`. 

- Is the NGINX binary that comes with `nginx:1.17` not compiled with `--with-debug` flag?
- Is there an image we can use which will provide us the debugging information we want?

**Comment by siddjain** [comment]
[This](https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile-alpine.template#L100) link says:

```
# forward request and error logs to docker log collector
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log \
```

but this also does not behave as expected (bug). we tried echoing to `/dev/stderr` and it does NOT output to docker log. docker log only shows `/proc/1/fd/1`.

**Comment by thresheek** [comment]
You need to explicitely launch a binary under the name of "nginx-debug", it has debug logging enabled (compiled with `--with-debug`).
