### ISSUE TITLE
nginx: invalid option: "off;'"

### ISSUE THREAD

**Issue by siddjain** [nginxinc/docker-nginx#539]
Using [this](https://github.com/docker-library/docs/tree/master/nginx#running-nginx-in-debug-mode) link we are trying to create a docker container like this:

```
docker container create \
        --name $CONTAINER_NAME \
        --network $NETWORK \
        --log-opt max-file=3 \
        --log-opt max-size=10m \
        $HTTP_PORT \
        $HTTPS_PORT \
        nginx:1.19 \
        nginx-debug -g 'daemon off;'
```

but when we start this container we see following in the logs:

```
nginx: invalid option: "off;'"
```

it could be a bash issue because in reality what we do is this in a shell script:

```
CMD="docker container create \
	--name $CONTAINER_NAME \
	--network $NETWORK \
	$HTTP_PORT \
	$HTTPS_PORT \
	nginx:1.17 \
	nginx-debug -g 'daemon off;'"
$CMD
```

and then execute the script. how can we fix this?

**Comment by thresheek** [comment]
You probably need to escape quotes.

**Comment by phebing** [comment]
Just in case anyone stumbles over this:
Took me a long time to figure the escaping out for a task.json in vscode:

`"command": "nginx -g \"daemon off;\""`

Single quotes or even escaped single quotes there just didnt do the trick for me
