### ISSUE TITLE
"nginx -g 'daemon off" --> http://localhost:8080/ --> This webpage is not available

### ISSUE THREAD

**Issue by tenzan** [nginxinc/docker-nginx#54]
I've followed the instructions https://hub.docker.com/_/nginx/

My `Dockerfile`:

```
FROM nginx
COPY sites-available-default /etc/nginx/sites-available/default
COPY app-dir /usr/share/nginx/html
```

I started container `docker run --name nginx-cont -d -p 8080:80 nginx-cont`

And able to confirm it's running
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
c2e5d5cd08ad        nginx-cont          "nginx -g 'daemon off"   12 minutes ago      Up 12 minutes       443/tcp, 0.0.0.0:8080->80/tcp   nginx-cont
```

But when access http://localhost:8080 it says, `This webpage is not available`

**Comment by uglyog** [comment]
I'm having the same issue. Following the docs, I run: `docker run -d -p 8080:80 nginx`

docker ps reports:

    CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                           NAMES
    0dc74ee9e308        nginx:latest        "nginx -g 'daemon of   3 seconds ago       Up 2 seconds        443/tcp, 0.0.0.0:8080->80/tcp   pensive_heisenberg

    $ ps -ef | grep nginx
    root      8200  4361  0 15:14 ?        00:00:00 nginx: master process nginx -g daemon off;
    syslog    8248  8200  0 15:14 ?        00:00:00 nginx: worker process

    $ curl -v http://localhost:8080
    * Rebuilt URL to: http://localhost:8080/
    *   Trying 127.0.0.1...
    * Connected to localhost (127.0.0.1) port 8080 (#0)
    > GET / HTTP/1.1
    > Host: localhost:8080
    > User-Agent: curl/7.43.0
    > Accept: */*
    > 
    * Recv failure: Connection reset by peer
    * Closing connection 0
    curl: (56) Recv failure: Connection reset by peer

This is on Ubuntu 15.10 with docker 1.6.2

**Comment by uglyog** [comment]
Adding -i fixes the issue for me: `docker run -p 8080:80 -id nginx`

**Comment by tenzan** [comment]
@uglyog cool! Just wondering if this is going to be an official fix. Let's see.

**Comment by tenzan** [comment]
@uglyog For me, `docker run -d -p 8080:80 -id nginx` didn't work. :disappointed: 

Accessing `localhost:8080` still showing up
> This webpage is not available

and `docker ps` outputs as follows:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
903923b67a8a        nginx               "nginx -g 'daemon off"   5 seconds ago       Up 5 seconds        443/tcp, 0.0.0.0:8080->80/tcp   reverent_wing
```

**Comment by hacfi** [comment]
@tenzan Are you using docker-machine or boot2docker on OS X by any change? For docker-machine you can try running `open "http://$(docker-machine ip default):8080"` or whatever your docker machine name is.

**Comment by tenzan** [comment]
Hi @hacfi 
Thanks a lot.

```
$ docker-machine ip default
192.168.99.100
```

so, accessing `http://192.168.99.100:8080` showed me the page.

Great! :+1:
