### ISSUE TITLE
Performance implications of running nginx-debug with log-level error

### ISSUE THREAD

**Issue by siddjain** [nginxinc/docker-nginx#540]
Is there any difference in terms of performance between the following:

- run `nginx` binary
- run `nginx-debug` binary with log-level set to error. [ref](https://nginx.org/en/docs/ngx_core_module.html?&_ga=2.21057467.1063027611.1618940830-1413749159.1618940830#error_log)

**Comment by thresheek** [comment]
Yes, there is a few percent penalty gap when running a `nginx-debug` binary.
