### ISSUE TITLE
[Feature request] Red Hat Universal Base Image

### ISSUE THREAD

**Issue by lucacome** [nginxinc/docker-nginx#542]
Hello,

it would be great to have official images with Red Hat [UBI](https://developers.redhat.com/products/rhel/ubi) as a base image.

**Comment by lucacome** [comment]
@thresheek just saw this https://www.redhat.com/en/about/press-releases/red-hat-brings-red-hat-universal-base-image-docker-hub 🎉

**Comment by pratapagiri** [comment]
Any update on this?

**Comment by thresheek** [comment]
Hi @pratapagiri. There are no updates since there is no official UBI image in the docker library yet.

**Comment by pratapagiri** [comment]
Hi @thresheek , Thanks for update. UBI official images are available at https://hub.docker.com/u/redhat

**Comment by thresheek** [comment]
Hi @pratapagiri, unfortunately those are not Docker Library official ones.  See the bug 9445 I linked earlier.

**Comment by lucacome** [comment]
Since it's not possible to have an official image (at least for now), I've created https://github.com/lucacome/nginx-ubi to build images as close as possible to what I think the official ones would look like. They're pushed to https://hub.docker.com/r/nginxcontrib/nginx-ubi. 

Contributions are welcome 🙂

**Comment by thresheek** [comment]
Seems like UBI images are now a part of official docker library, so this can be checked again! Hooray and great job @yosifkit and @tianon!

Good news is that we provide prebuilt nginx packages for EL8/EL9 so the builds will be quick for `amd64`, `arm64` and `s390x` architectures.  I'm not too sure if it's worth building for both EL versions (`and for ppc64le`) - however opinions are welcome.

Refs: https://github.com/docker-library/official-images/issues/9445

**Comment by lucacome** [comment]
I noticed that too @thresheek 🎉 IMHO we should build for UBI9 and all the architectures, including `ppc64le`, to align with the other images as much as we can.
