### ISSUE TITLE
Third party module build fails if the directory name has `-`

### ISSUE THREAD

**Issue by pshanoop** [nginxinc/docker-nginx#550]
I tried to build [nginx-module-vts](https://github.com/vozlt/nginx-module-vts) using  command
`sudo docker build --build-arg ENABLED_MODULES="nginx-module-vts" . -f Dockerfile.alpine -t nginx:vts` in `/modules` directory. 

This fails with this error
```
>>> nginx-module-nginx-module-vts-dbg: Running split function dbg...
>>> nginx-module-nginx-module-vts-dbg: Preparing subpackage nginx-module-nginx-module-vts-dbg...
>>> ERROR: nginx-module-nginx-module-vts-dbg: Missing /tmp/build_module.sh.18/pkg-oss/alpine/abuild-module-nginx-module-vts/pkg/nginx-module-nginx-module-vts-dbg
>>> ERROR: nginx-module-nginx-module-vts: prepare_subpackages failed
>>> ERROR: nginx-module-nginx-module-vts: rootpkg failed
Command exited with non-zero status 1
real 12.93
user 9.61
sys 3.65
make: *** [Makefile:179: module-nginx-module-vts] Error 1
build_module.sh: ERROR: Build failed
```
The same works fine if I remove `-` from the module directory and change the `ENABLED_MODULES`. 

I'm not certain if this bug is in this repo. It might be in **NGINX packaging tool**. Don't know how to file issue for it.

**Comment by thresheek** [comment]
Hi @pshanoop can you check if https://github.com/nginxinc/docker-nginx/pull/549 fixes the issue for you?

**Comment by pshanoop** [comment]
> Hi @pshanoop can you check if #549 fixes the issue for you?

This works only if replaced `-` with `_`.

**Comment by pshanoop** [comment]
Btw, This affects both Alpine and Debian images.
