### ISSUE TITLE
Change of default.conf file location after release 2021-06-29njs-0.6.1 bugfix and 1.20.1-r3 version 

### ISSUE THREAD

**Issue by kaiqueprazeres** [nginxinc/docker-nginx#558]
Dear ones, I'm reporting a problem that happened recently with several distributed applications that I work with.

After updating nginx and fixing the bugfix all the microservices we had in production environment were unavailable showing the error "not found 404".

After days of trying to figure out the cause, I identified that these errors coincidentally occurred after the updates that were recently released.

To be sure, I ran the same applications in a previous version, and everything worked fine. But it took me a while to identify that what caused the problem was the change of the "default.conf" file path in the docker container.

Which before version 1.20.1-r3 was located in `/etc/nginx/conf.d/default.conf` and/or `/etc/nginx/sites-available/default.conf` `/etc/nginx/sites-enabled/default. conf`
it works only in` /etc/nginx/http.d/default.conf` .

And besides, the content of the file "/etc/nginx/http.d/default.conf " was:

```
# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost

server {
    listen 80 default_server;
    listen [::] 80 default_server

    # Everything is a 404
    location / {
        return 404;
    }

    # You may need this to prevent return 404 recursion.
    location = /404.html {
        internal;
    }
}
```

This caused access to my applications to always return 404.

And only after changing this file with my applications settings in the new location `/etc/nginx/http.d/default.conf`  things started working again.

I bring this report as a possible solution for other people who had a similar problem. I hope this helps them save time and the huge headache I had until I found out what had happened. 

Important info: I didn't find in the nginx changelog or official documentation any information about this change or in any other community. So that was the solution I found to solve the problem in my scenario. And the problem started to occur instantly on 6/25/2021 

Docker image used: `FROM php:7.4-fpm-alpine3.14` and `RUN set -xe && apk add --no-cache --update && apk add nginx `

**Comment by thresheek** [comment]
Hi @kaiqueprazeres, this is a tracker for `nginx:`-based images, not `php:*` ones.  Also, `nginx-1.20.1-r3` is not something we build on nginx.org, which `nginx:alpine` images use.  That's why it's not mentioned in the official docs - it's not built by us, so it's shouldnt be there.

It's likely that alpine linux upstream binaries changed something, but we have no control over it nor we use it in `nginx:alpine` images. Please report this issue on Alpine Linux sites.

Thanks!
