### ISSUE TITLE
Container with proxy: curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by Yamakasi** [nginxinc/docker-nginx#559]
I'm facing the issue that my proxy, Caddy, is not capable of connecting from node1 to a container on node2 following it's logs and end up in timeouts in my browser.

When I exec into the caddy container I can curl to that container and get the nginx headers so connection is fine.

I see the following errors when it happens:

`{"level":"error","ts":1625137947.7337053,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"read tcp 10.1.65.3:49276->10.1.65.6:80: read: connection reset by peer"}`

and these a lot as well:

`{"level":"error","ts":1625138171.8006687,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}`

```
Caddy (proxy) command: 
# curl http://10.1.65.6 -H "Accept: application/html" -H "Host: domain.tld"
Nginx reponse:
10.1.65.3 - - [01/Jul/2021:18:45:00 +0000] "GET / HTTP/1.1" 200 2629 "-" "curl/7.67.0" "-"
Caddy response after long waithing:
curl: (56) Recv failure: Connection reset by peer
```

The issue seems to occur more and always with proxies (and containers)

[https://stackoverflow.com/questions/68144421/when-i-access-nginx-in-container-i-got-curl-56-recv-failure-connection-rese/68215622](url)

Any idea what I'm doing wrong ?

**Comment by thresheek** [comment]
The fact that nginx logged the request means it's finished from nginx POV
The fact that curl sees a "(56) Recv failure: Connection reset by peer" means there is an issue in your docker networking/ip stack. and there is nothing can be done by nginx to prevent it.
