### ISSUE TITLE
Need image filter module

### ISSUE THREAD

**Issue by netroby** [nginxinc/docker-nginx#56]
But do not want recompile it 

--with-http_image_filter_module

**Comment by thresheek** [comment]
Duplicate of #2 and #14.

**Comment by netroby** [comment]
What the hell?
You just close this ? Good idea, close issue is the good way to resolve problems. Good job

**Comment by thresheek** [comment]
Well if it makes you less grumpy, I can duplicate what have been said in #14, let me quote:
"The current idea in packaging official nginx is to enable as many optional modules as long they do not require anything external, like language interpreter or a shared library. "

This will likely change when the support for dynamic modules is introduced, but so far the point still stands.
