### ISSUE TITLE
`1.21.1-alpine` invalid manifest

### ISSUE THREAD

**Issue by Fossan** [nginxinc/docker-nginx#562]
So far I was using the `1.21.0-alpine` as a base image of my Dockerfile that I'm pushing to my own artifactory (JFrog) and it worked like a charm. However, after an update to `1.21.1-alpine` I'm unable to push my image since I'm getting `manifest invalid: manifest invalid` error all the time.

To ensure that the issue was not with my particular image, I pulled `1.21.1-alpine`, retagged it and tried to push it again - however this fails with the exact same message.

```
> docker pull nginx:1.21.1-alpine                                                                                    
1.21.1-alpine: Pulling from library/nginx
5843afab3874: Pull complete 
0dc18a5274f2: Pull complete 
48a0ee941dcd: Pull complete 
2446243a1a3f: Pull complete 
cbf0756b41fb: Pull complete 
c72750a979b9: Pull complete 
Digest: sha256:2c2dfbb9814318bc50578b5c60a1e3305f2ac217879a1c87a84418f5d9418ff6
Status: Downloaded newer image for nginx:1.21.1-alpine
docker.io/library/nginx:1.21.1-alpine
> docker tag nginx:1.21.1-alpine <artifactory_url>:1.21.1-TEST
> docker push <artifactory_url>:1.21.1-TEST                                                       
The push refers to repository [<artifactory_url>]
7ebe47ef59e5: Layer already exists 
a40efec40891: Layer already exists 
d3a37e5dc9b6: Layer already exists 
2524a71e1218: Layer already exists 
b74fa78b1528: Layer already exists 
72e830a4dff5: Layer already exists 
manifest invalid: manifest invalid
```

**Comment by thresheek** [comment]
Maybe there are some logs on artifactory side?

We've been doing exactly the same pulling images from docker hub and pushing them to AWS ECR Public, and no issues there.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
