### ISSUE TITLE
(root) Additional property nginx is not allowed

### ISSUE THREAD

**Issue by lireupt** [nginxinc/docker-nginx#568]
Hello folks, when I try to run a container in my cli windows machine I receive this message, "(root) Additional property nginx is not allowed", how can solve this issue? I've allready install docker and sign up, but I really don´t understand what's happenend when I access and try run the container, please help. 
thanks

**Comment by thresheek** [comment]
Something is wrong in your docker-compose file, like indentation. You need to check it.

**Comment by lireupt** [comment]
ok, thanks I will see if that you say is the problem, thanks ; )
