### ISSUE TITLE
Adding --with-http_gzip_static_module

### ISSUE THREAD

**Issue by PierrickV** [nginxinc/docker-nginx#57]
Hi,

Can you please add [Module ngx_http_gzip_static_module](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) to this image?

Thank you :-) !

**Comment by thresheek** [comment]
Did you actually check the image?  It is there.

**Comment by booyaa** [comment]
@PierrickV see this comment in another issue https://github.com/nginxinc/docker-nginx/issues/14#issuecomment-134935522
