### ISSUE TITLE
bind port 80 permission denied on eks v1.20

### ISSUE THREAD

**Issue by emcay** [nginxinc/docker-nginx#571]
After upgrading from EKS v1.19 to v1.20 (with no other changes) nginx containers suddenly fail to start due to an issue with binding to port 80.

2021/08/26 23:09:45 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)

The only workaround I have found is to run the container as root (0), which obviously isn't ideal.

v1.20.7-eks-d88609
amazon-eks-node-1.20-v20210722
nginx:stable-alpine build image

**Comment by namevic** [comment]
when you running unprivileged, you can't use ports less than 1000 (if I remember correctly), change the 80 to 8080 and redirect traffic to this port

**Comment by emcay** [comment]
> when you running unprivileged, you can't use ports less than 1000 (if I remember correctly), change the 80 to 8080 and redirect traffic to this port

This was the resolution thanks!
