### ISSUE TITLE
the image nginx:1.21.0-alpine , it seems does not work well on centos7.3

### ISSUE THREAD

**Issue by nuaazt** [nginxinc/docker-nginx#572]
my host:
centos 7.3,
step1: docker pull nginx:1.21.0-alpine 
step2: create container frm the image
step3: docker stop <container-name>
step4: docker start <container-name>
step5: docker logs <container-name>
then:
 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)

**Comment by nuaazt** [comment]
It is mentioned on the official website that nginx only supports version centos 7.4+.
                 http://nginx.org/en/linux_packages.html#Alpine
Does it also mean that the host also must be 7.4+ when it is deployed from docker image?
![image](https://user-images.githubusercontent.com/42135380/131298520-df1d5e5a-0b00-481b-9440-78f8838c9046.png)

**Comment by nuaazt** [comment]
It seems that the file /etc/nginx/mime.types has been removed  by docker stop **

**Comment by thresheek** [comment]
Please provide full steps of how you're testing this.  The packages section is irrelevant in this case since you're using docker.

**Comment by nuaazt** [comment]
> Please provide full steps of how you're testing this. The packages section is irrelevant in this case since you're using docker.
1. get the image: docker pull nginx:1.21.0-alpine
2.  create a file named docker-compose.yml and then
![image](https://user-images.githubusercontent.com/42135380/131791480-625250c5-4382-482e-852e-1bf119491635.png)

the docker log will show that err

**Comment by nuaazt** [comment]
[root@localhost my_nginx]# cat docker-compose.yml
version: "3"

services:
  mynginx:
    container_name: mynginx
    image: nginx:1.21.0-alpine
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

**Comment by thresheek** [comment]
Can not reproduce. Works fine here.  Try updating your docker install and operating system to something current.

**Comment by nuaazt** [comment]
> Can not reproduce. Works fine here. Try updating your docker install and operating system to something current.

it is ok on centos 7.2 or 7.4, but does not work well on centos7.3.1611
![image](https://user-images.githubusercontent.com/42135380/131818042-f2921e9b-f66f-4d29-a606-f663692fe8e9.png)

**Comment by thresheek** [comment]
So it's not an nginx issue, but rather a Docker/CentOS one. We cant help with that here.
