### ISSUE TITLE
Security vulnerability in stable-alpine (1.20.1)

### ISSUE THREAD

**Issue by SIPR-octo** [nginxinc/docker-nginx#589]
Hello there! :wave: 

There are 2 CVE for `curl` & `libcurl` version `7.78.0-r0` in the docker image `stable-alpine` (or `1.20.1-alpine`).

These are the same vulnerabilities than for the `mainline` image (issue here: https://github.com/nginxinc/docker-nginx/issues/577) but unlike this one, the vulnerabilities are fixed in the parent image `alpine:3.13`.

The stable alpine image is not updated for 2 months now, would it be possible to rebuild it (as is) so that the vulnerability is fixed?

Thanks a lot! :pray:

**Comment by thresheek** [comment]
Fixed in `nginx:1.20.2` by moving to alpine 3.14 as a base.
