### ISSUE TITLE
Cannot manually install nginx-extras

### ISSUE THREAD

**Issue by akash1810** [nginxinc/docker-nginx#60]
I've seen https://github.com/nginxinc/docker-nginx/issues/14 and https://github.com/nginxinc/docker-nginx/issues/56 so thought I could build an image from the following Dockerfile:

```dockerfile
FROM nginx:latest
RUN apt-get -y update && apt-get -y install nginx-extras
```

However, building the image fails with the following (trimmed) output:

```console
Selecting previously unselected package nginx-common.
Preparing to unpack .../nginx-common_1.6.2-5_all.deb ...
Unpacking nginx-common (1.6.2-5) ...
dpkg: error processing archive /var/cache/apt/archives/nginx-common_1.6.2-5_all.deb (--unpack):
 trying to overwrite '/usr/share/nginx/html/index.html', which is also in package nginx 1.9.9-1~jessie
Selecting previously unselected package rename.
Preparing to unpack .../archives/rename_0.20-3_all.deb ...
Unpacking rename (0.20-3) ...
Selecting previously unselected package xml-core.
Preparing to unpack .../xml-core_0.13+nmu2_all.deb ...
Unpacking xml-core (0.13+nmu2) ...
Selecting previously unselected package nginx-extras.
Preparing to unpack .../nginx-extras_1.6.2-5_amd64.deb ...
Unpacking nginx-extras (1.6.2-5) ...
dpkg: error processing archive /var/cache/apt/archives/nginx-extras_1.6.2-5_amd64.deb (--unpack):
 trying to overwrite '/usr/sbin/nginx', which is also in package nginx 1.9.9-1~jessie
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nginx-common_1.6.2-5_all.deb
 /var/cache/apt/archives/nginx-extras_1.6.2-5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get -y update && apt-get -y install nginx-extras' returned a non-zero code: 100
```

As an alternative, I'm now using ubuntu as the base image:

```dockerfile
FROM ubuntu:14.04

RUN apt-get -y update && apt-get -y install \
  nginx \
  nginx-extras \
  ca-certificates

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

VOLUME ["/var/cache/nginx"]

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
```

This works well, however was wondering if/how I can get the first Dockerfile working as its more intention revealing.

**Comment by thresheek** [comment]
nginx-extras is not something we build/provide under nginx.org binaries, which are used in the official Dockerfile.  I'm not sure why do you want to do FROM: nginx:latest if you need to use a different binary.  In any case, I guess you need to remove nginx first and then install nginx-extras.

**Comment by akash1810** [comment]
>  In any case, I guess you need to remove nginx first and then install nginx-extras.

Yeah, that's what I thought I'd have to do if I wanted to use the nginx image... which seems like a very odd thing to do!

> nginx-extras is not something we build/provide under nginx.org binaries, which are used in the official Dockerfile.

From the issues linked, I gather this is because nginx-extras has third party dependancies?

I'll keep to using the ubuntu based Dockerfile - closing.

**Comment by fosskers** [comment]
I just hit this issue, trying to install `nginx-extras` to get access to the `perl_modules` pragma.

**Comment by thresheek** [comment]
@fosskers, install nginx-module-perl instead.

**Comment by fosskers** [comment]
Strange, that package is already installed in the `nginx:1.10.3` image, yet I'm getting `nginx: [emerg] unknown directive "perl_modules" in /etc/nginx/nginx.conf:15` as my nginx-based image boots.

**Comment by fosskers** [comment]
This does the trick:
```
FROM ubuntu:16.04

# For the `perl_modules` extension.                                                                       
RUN apt-get update && apt-get install -y nginx nginx-extras

COPY _site/ /var/www/

# Overwrite default nginx configuration                                                                   
COPY nginx.conf /etc/nginx/
 
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
```

**Comment by thresheek** [comment]
don't forget to load the module: http://nginx.org/r/load_module, http://hg.nginx.org/pkg-oss/file/tip/debian/Makefile#l132
