### ISSUE TITLE
The reverse proxy cannot obtain the correct IP address

### ISSUE THREAD

**Issue by Kry1702** [nginxinc/docker-nginx#600]
NGINX and backend containers (JAVA) are managed through docker-compose.
They are all connected to the same bridged network.

When the JAVA container is restarted, the port exposed outside of Nginx cannot be accessed and an error 404 is displayed. In fact, the resource actually exists.

Nginx reverse proxy is requesting the wrong IP address, not the actual IP address of the current backend (JAVA) container.
The IP address of the Nginx reverse proxy is always obtained as the expired address last used by the JAVA container.
My stupid solution, restarting the JAVA container together with Nginx, is obviously not the best solution.

More：
The Ping command （ping java-05-server） in the Nginx container returns the correct IP address of the JAVA container.
Nginx Config：proxy_pass http://java-05-server:43021
Docker network custom creation （docker network create app-network）.
docker-compose network specified to join the extended network（external: true）.
Nginx log： [error] 22#22: *47 connect() failed (111: Connection refused) while connecting to upstream.

Experts, have you encountered similar problems, can you tell me your solution? Thank you!

**Comment by yosifkit** [comment]
Nginx caches the DNS lookup; to make it look it up all the time, you can put it in a variable or adjust the TTL of the cache: https://serverfault.com/a/593003

**Comment by Kry1702** [comment]
> Nginx 缓存 DNS 查找；为了让它一直查找，你可以把它放在一个变量中或调整缓存的TTL：[https](https://serverfault.com/a/593003) : [//serverfault.com/a/593003](https://serverfault.com/a/593003)

Thank you!  Based on the solution you provided, I tried it and the problem still exists.
Nginx  config changed to 
server {
    ...
    resolver 127.0.0.11;   #The IP address comes from the nameserver value of the Nginx container /etc/resolv.conf file
    set $backend "http://java-05-server:43021";
    proxy_pass $backend;
    ...
}

Thanks again for your reply！

**Comment by Kry1702** [comment]
> Nginx caches the DNS lookup; to make it look it up all the time, you can put it in a variable or adjust the TTL of the cache: https://serverfault.com/a/593003

Thank you! Based on the ideas you provided, I have successfully solved the problem.
