### ISSUE TITLE
Nginx stable and latest lost networking after the latest container release

### ISSUE THREAD

**Issue by clickbg** [nginxinc/docker-nginx#601]
After the container upgrade in the past few days all our previously working containers suddenly lost network connectivity. This seems to affect both latest and stable, for which the container was upgraded a few days ago. Alpine, for which the image is a bit older is working fine.

Host: Raspbian
Arch: ARM - RPI4

root@juno:~# docker images
REPOSITORY        TAG       IMAGE ID       CREATED        SIZE
nginx             stable    b806e477d1cc   5 hours ago    109MB
nginx             latest    4aa417b5bbfb   5 hours ago    109MB
nginx             alpine    062e12983452   4 days ago     16MB
nginx             1.21.0    a2e43f88ed53   4 months ago   103MB

root@juno:~# docker run -it --rm nginx:latest /bin/bash
root@b950816588c8:/# curl google.com
curl: (28) Resolving timed out after 1094587810065 milliseconds

root@juno:~# docker run -it --rm nginx:stable /bin/bash
root@8efd17fa6cae:/# curl google.com
curl: (28) Resolving timed out after 1091446178065 milliseconds

root@juno:~# docker run -it --rm nginx:1.21.0 /bin/bash
root@2c75bf87a97b:/# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

**Comment by thresheek** [comment]
What is the docker version you run on the host?  I cant seem to reproduce on docker 19.03.15 on my rpi4 running raspbian.

**Comment by clickbg** [comment]
Hi, seems to be a bit newer, I am also using the Docker package from docker.com 

root@juno:~# docker --version
Docker version 20.10.10, build b485636
root@juno:~# dpkg -l | grep docker
ii  docker-ce                        5:20.10.10~3-0~debian-buster        armhf        Docker: the open-source application container engine
ii  docker-ce-cli                    5:20.10.10~3-0~debian-buster        armhf        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras        5:20.10.10~3-0~debian-buster        armhf        Rootless support for Docker.
ii  docker-compose                   1.21.0-3                            all          Punctual, lightweight development environments using Docker
root@juno:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

Thanks for the fast reply!

**Comment by thresheek** [comment]
What's the libseccomp version you have? Can you try updating it?

https://github.com/debuerreotype/docker-debian-artifacts/issues/106
and https://github.com/debuerreotype/docker-debian-artifacts/issues/97 might be related.

**Comment by thresheek** [comment]
Perfect. Glad this helped.
