### ISSUE TITLE
nginx-nr-agent installation does not work with the latest version 1.21.4

### ISSUE THREAD

**Issue by symplr-rshakya** [nginxinc/docker-nginx#602]
Running this command in docker file with base as the nginx:latest gives error
`RUN apt-get update &&     apt-get install -y --no-install-recommends     nginx-nr-agent ca-certificates jq curl iproute2     && rm -rf /var/lib/apt/lists/*`

gives  error 
![image](https://user-images.githubusercontent.com/83594579/142439303-286e5bd4-ee81-4f77-8441-6393c64bd71a.png)

This  worked when we switched to a previous version (1.21.3)

**Comment by jimas14** [comment]
FWIW, our build using `1.20` just started failing due to python-pip package missing from apt repo. Still haven't been able to resolve, after switching to `python3-pip`, then we have gem installations failing

**Comment by thresheek** [comment]
`nginx:1.21.4` moved to Debian 11 Bullseye, which is probably not compatible with the package you're installing.  Note that `nginx-nr-agent` is not supported by F5/NGINX anymore.

**Comment by thresheek** [comment]
Closing since we will not fix that.

**Comment by kklicmhenya** [comment]
Hi all, how can I install and use new-relic agent for nginx on debial:bullseye now?
