### ISSUE TITLE
Failed to build nginx with ndk and lua

### ISSUE THREAD

**Issue by sarfaraz-alam-md** [nginxinc/docker-nginx#605]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gettext/autopoint_0.21-4_all.deb  Connection failed [IP: 146.75.30.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c set -ex     && apt-get update     && apt install -y --no-install-suggests --no-install-recommends                 patch make wget mercurial devscripts debhelper dpkg-dev                 quilt lsb-release build-essential libxml2-utils xsltproc                 equivs git g++     && hg clone -r ${NGINX_VERSION}-${PKG_RELEASE%%~*} https://hg.nginx.org/pkg-oss/     && cd pkg-oss     && mkdir /tmp/packages     && for module in $ENABLED_MODULES; do         echo "Building $module for nginx-$NGINX_VERSION";         if [ -d /modules/$module ]; then             echo "Building $module from user-supplied sources";             if [ ! -s /modules/$module/source ]; then                 echo "No source file for $module in modules/$module/source, exiting";                 exit 1;             fi;             if [ -f /modules/$module/build-deps ]; then                 echo "Installing $module build dependencies";                 apt update && apt install -y --no-install-suggests --no-install-recommends $(cat /modules/$module/build-deps | xargs);             fi;             if [ -x /modules/$module/prebuild ]; then                 echo "Running prebuild script for $module";                 /modules/$module/prebuild;             fi;             /pkg-oss/build_module.sh -v $NGINX_VERSION -f -y -o /tmp/packages -n $module $(cat /modules/$module/source);             BUILT_MODULES="$BUILT_MODULES $(echo $module | tr '[A-Z]' '[a-z]' | tr -d '[/_\-\.\t ]')";         elif make -C /pkg-oss/debian list | grep -P "^$module\s+\d" > /dev/null; then             echo "Building $module from pkg-oss sources";             cd /pkg-oss/debian;             make rules-module-$module BASE_VERSION=$NGINX_VERSION NGINX_VERSION=$NGINX_VERSION;             mk-build-deps --install --tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes" debuild-module-$module/nginx-$NGINX_VERSION/debian/control;             make module-$module BASE_VERSION=$NGINX_VERSION NGINX_VERSION=$NGINX_VERSION;             find ../../ -maxdepth 1 -mindepth 1 -type f -name "*.deb" -exec mv -v {} /tmp/packages/ \;;             BUILT_MODULES="$BUILT_MODULES $module";         else             echo "Don't know how to build $module module, exiting";             exit 1;         fi;     done     && echo "BUILT_MODULES=\"$BUILT_MODULES\"" > /tmp/packages/modules.env' returned a non-zero code: 100

**Comment by thresheek** [comment]
You need to fix your connection, as there is an issue with fetching a package. Nothing we can help with.
