### ISSUE TITLE
missing tags for official nginx docker image

### ISSUE THREAD

**Issue by vvitayau** [nginxinc/docker-nginx#61]
Currently this repo has no tag. The publish process should enforce tagging.

Per https://hub.docker.com/_/nginx/ I have no clue what 1.9.9 is nor how it differs from latest HEAD.
Which SHA from https://github.com/nginxinc/docker-nginx/commits/master was used to publish nginx:1.9.9 ?

**Comment by yosifkit** [comment]
Just click the link to the Dockerfile in the "Supported Tags and Respective `Dockerfile` links" list. It will take you [here](https://github.com/nginxinc/docker-nginx/blob/a8b6da8425c4a41a5dedb1fb52e429232a55ad41/Dockerfile).

**Comment by tianon** [comment]
Additionally, if you click the link to [the relevant manifest file (`library/nginx`)](https://github.com/docker-library/official-images/blob/master/library/nginx) below there, that's the official place the "Docker tag" <-> Git commit is codified.

**Comment by thresheek** [comment]
I kinda agree with @vvitayau on this one.  It would be quite cool to use tags for that.

**Comment by md5** [comment]
@thresheek There's nothing to stop you from adding these tags as part of your own process. However, I think the Official Images policy of not accepting tags is a good once since tags are mutable and SHA references are not.

**Comment by thresheek** [comment]
Fair enought, thanks.

**Comment by thresheek** [comment]
Added the tags for releases accepted by docker official images library.
