### ISSUE TITLE
raspberry pi 4 problems with docker and nginx:1.21.4 vs nginx:1.21.3 using as a reverse proxy

### ISSUE THREAD

**Issue by zenhighzer** [nginxinc/docker-nginx#610]
Hi there, 
today after "upgrading" my container from nginx:1.21.3 to nginx:1.21.4 I experienced some strange behavior 
My browser throws errors like: 
- 504 Gateway Time-out
- PR_END_OF_FILE_ERROR

In the nginx-logs there are errors like: 
1931/02/16 03:06:35 [error] 24#24: *660 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.100.202, server: gitlab.mydomain.test, request: "GET / HTTP/2.0", upstream: "http://192.168.100.55:8877/", host: "gitlab.mydomain.test"

But if I use nginx:1.21.3 with the same configuration everything is absolutely fine, no errors

- I build an own image with Dockerfile and the only difference is "FROM nginx:1.21.3" and "FROM nginx:1.21.4"
- And for testing I just change the docker run command like docker run [bind some mounts and ports]  nginx:1.21.3   vs   docker run [bind some mounts and ports]  nginx:1.21.4

Are there any breaking changes, do I make something wrong or what could be the problem? Thank you for your help :)

In general I use a really "basic" configuration like: 
```
#VIRTUALHOSTS

     server {
        #listen 80;
        listen 443;
        listen [::]:443;

        ssl on;
        ssl_certificate /etc/nginx/wildcard_cert.crt;
        ssl_certificate_key /etc/nginx/wildcard_cert.pem;

        server_name www.mydomain.test;

        index index.htm index.html /index.htm;

        location / {
        proxy_pass http://www.mydomain.test:8888/;
        }
}


server {
    #listen 80;
    listen 443;
    #listen [::]:443;

    ssl on;
    ssl_certificate /etc/nginx/wildcard_cert.crt;
    ssl_certificate_key /etc/nginx/wildcard_cert.pem;
    server_name gitlab.mydomain.test;


    index index.htm index.html /index.htm;

    location / {
       proxy_pass http://gitlab.mydomain.test:8877;
       proxy_redirect https://gitlab.mydomain.test:8877 https://gitlab.mydomain.test;
    }

}
```

Thanks and Best Regards
zenhighzer

**Comment by thresheek** [comment]
hi @zenhighzer !

The change between 1.21.3 and 1.21.4 is move to a newer Debian version, 11.

Overall it looks similar to https://github.com/nginxinc/docker-nginx/issues/601 - can you please check if updating libseccomp and docker fixes the issue for you, similar to https://github.com/nginxinc/docker-nginx/issues/601#issuecomment-971609391 ?

Thanks!

**Comment by thresheek** [comment]
Closing due to feedback timeout.
