### ISSUE TITLE
Alpine flavor on AWS ECR Gallery?

### ISSUE THREAD

**Issue by bkuhl** [nginxinc/docker-nginx#611]
Currently `alpine` images are only available on [Dockerhub](https://hub.docker.com/_/nginx/) and not [AWS ECR Gallery](https://gallery.ecr.aws/nginx/nginx).  Can Alpine images also be mirrored to ECR?

**Comment by bkuhl** [comment]
To elaborate more clearly, `1.20-alpine` is available, but not `1.21-alpine`

**Comment by thresheek** [comment]
Thanks for opening this issue @bkuhl!

They are mirrored, although the web interface doesnt seem to show them for some reason.

Or do you have an actual pull issue from that repo?

**Comment by thresheek** [comment]
Ah, the tag filter on AWS ECR isnt exactly smart - you need to iterate over pages, or set the output limit to 100 to see those tags. Bah.

**Comment by bkuhl** [comment]
Doh, you're right - it is pullable.  Thanks!
