### ISSUE TITLE
ngx_http_js_module not loading in 1.21.5

### ISSUE THREAD

**Issue by SamDuvall** [nginxinc/docker-nginx#615]
I'm getting a `unknown directive "js_include" in /etc/nginx/nginx.conf` error when I upgrade from 1.21.4 to 1.21.5.

Do I need to do something differently to load ngx_http_js_module other than `load_module /usr/lib/nginx/modules/ngx_http_js_module.so` in PCRE2?

**Comment by thresheek** [comment]
Hi @SamDuvall ! It's not related to PCRE2.

`js_include` was deprecated and is now removed in njs 0.7.1 which is a part of `nginx:1.21.5` image:, see http://nginx.org/en/docs/njs/changes.html#njs0.7.1 .

Please use http://nginx.org/en/docs/http/ngx_http_js_module.html#js_import instead.

**Comment by SamDuvall** [comment]
Ah, okay. Thank you for the (quick) clarification.
