### ISSUE TITLE
[Help] Set up mirror for GitHub

### ISSUE THREAD

**Issue by wordlesswind** [nginxinc/docker-nginx#616]
Hello,

This is an issue for help. In the Chinese mainland, we have problems connecting to GitHub. So we need to set the mirror address, such as [FastGit](https://doc.fastgit.org/).

When using [docker-nginx/modules/Dockerfile](https://github.com/nginxinc/docker-nginx/blob/master/modules/Dockerfile) to build modules, some module source codes are downloaded from GitHub.

I want to replace the GitHub URL to FastGit, but I checked the Dockerfile and pkg-oss, and I did not find the `brotli` repository URL.

Could you tell me where the URL is? Thanks!

Best Regards,
wordlesswind

**Comment by Ran-snow** [comment]
It's official repo. 
The fastgit is reverse proxy only. 
The 'brotli' from goggle, this repo haven't brotli
So you'd better build by yourself.

You can also consider my repo from this . My repo contain brotli
[https://github.com/Ran-snow/docker-nginx](https://github.com/Ran-snow/docker-nginx)

**Comment by wordlesswind** [comment]
> It's official repo. The fastgit is reverse proxy only. The 'brotli' from goggle, this repo haven't brotli So you'd better build by yourself.
> 
> You can also consider my repo from this . My repo contain brotli https://github.com/Ran-snow/docker-nginx

I am referencing the Dockerfile used to add modules in the repository.

**Comment by Ran-snow** [comment]
Is [https://github.com/google/ngx_brotli](https://github.com/google/ngx_brotli) ?

**Comment by thresheek** [comment]
Hi @wordlesswind !

The brotli dockerfile is referenced in https://hg.nginx.org/pkg-oss, https://hg.nginx.org/pkg-oss/file/tip/contrib/src/ngx_brotli/Makefile

**Comment by wordlesswind** [comment]
> Hi @wordlesswind !
> 
> The brotli dockerfile is referenced in https://hg.nginx.org/pkg-oss, https://hg.nginx.org/pkg-oss/file/tip/contrib/src/ngx_brotli/Makefile

Thank you very much, this helped me a lot.
have a pleasant workday!
