### ISSUE TITLE
how can I use proxy_pass to pass rtmp link through nginx?

### ISSUE THREAD

**Issue by siavashfazli** [nginxinc/docker-nginx#617]
how can I use proxy_pass directive for a RTMP link(rtmp://...)? I have a main-Nginx container and a RTMP server container, Now I need to pass the RTMP link(with port:1935) through main-nginx to access RTMP container. can someone help me how to write proxy_pass directive to pass RTMP link?

**Comment by thresheek** [comment]
Hi @siavashfazli , please use https://mailman.nginx.org/mailman/listinfo/nginx for questions unrelated to docker usage.

Thanks!
