### ISSUE TITLE
image of nginx with pcre3

### ISSUE THREAD

**Issue by yangzhaofeng** [nginxinc/docker-nginx#618]
From Nginx 1.21.5 it is built with pcre2 by default. However, there are a number of modules built with pcre3. Directly building them with default options will lead to error like `[emerg] dlopen() "/path/to/ngx_http_lua_module.so" failed (/path/to/ngx_http_lua_module.so: undefined symbol: pcre_dfa_exec) in /path/to/ngx_http_lua_module.conf:1`

Certainly, it can be workarounded by adding `-lpcre` in `with-ld-opt`, but it can frustrate a lot of beginners of nginx modules. It will be helpful if you can consider adding images built with pcre3.

**Comment by daveteu** [comment]
@yangzhaofeng  beginner of nginx modules here. Where do we add the -pcre with-ld-opts option?

**Comment by yangzhaofeng** [comment]
@daveteu 

https://github.com/yangzhaofeng/docker-nginx/blob/3411022c380ec4e37e1777d2042fcad6304bd0fe/Dockerfile

Reference here.

The core command is 
```
./configure --with-compat <--modules-path=/usr/lib/nginx/modules> --with-ld-opt='<-Wl,--as-needed,-O1,--sort-common -L/usr/lib> -lpcre' --add-dynamic-module=../ngx_devel_kit-${DEVEL_KIT_VERSION} --add-dynamic-module=../lua-nginx-module-${LUA_MODULE_VERSION}
```
Options in `<>` is optional

**Comment by thresheek** [comment]
No, please fix the modules instead.

**Comment by thresheek** [comment]
FWIW, it's fixed for lua module built from this repos' modules/ directory.
