### ISSUE TITLE
recent change from pcre to pcre2 breaks ngx_http_lua_module.so

### ISSUE THREAD

**Issue by ben-xo** [nginxinc/docker-nginx#619]
If i use [the officially sanctioned way to build an image with modules](https://github.com/nginxinc/docker-nginx/blob/master/modules/Dockerfile), and specify `ENABLED_MODULES="ndk lua"`, the image will build just fine, but the module does not load at runtime and the container crashes.

```
2022/01/04 12:26:27 [emerg] 1#1: dlopen() "/usr/lib/nginx/modules/ngx_http_lua_module.so" failed (Error relocating /usr/lib/nginx/modules/ngx_http_lua_module.so: pcre_compile: symbol not found) in /etc/nginx/nginx.conf:6
nginx: [emerg] dlopen() "/usr/lib/nginx/modules/ngx_http_lua_module.so" failed (Error relocating /usr/lib/nginx/modules/ngx_http_lua_module.so: pcre_compile: symbol not found) in /etc/nginx/nginx.conf:6
```

The workaround is to edit the modules Dockerfile from nginx:mainline to nginx:stable, which is the version before the change, but I imagine that workaround won't be valid forever.

**Comment by daveteu** [comment]
nginx:stable didn't work for me. I get same error message when I run the docker.

**Comment by thresheek** [comment]
This needs to be fixed by Lua module authors: https://github.com/openresty/lua-nginx-module/issues/1984

**Comment by thresheek** [comment]
As a workaround I've added http://hg.nginx.org/pkg-oss/rev/5f69f306c090.

It should fix the issue you're getting.
