### ISSUE TITLE
add alpine variant

### ISSUE THREAD

**Issue by ncopa** [nginxinc/docker-nginx#62]
It would be nice with an nginx:alpine variant:

````
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               alpine              adfc4335a989        15 seconds ago      6.245 MB
nginx               latest              fb7fe53bd952        2 weeks ago         133.8 MB
````

The image above uses the distro provided nginx package:
````Dockerfile
FROM alpine:3.3

MAINTAINER NGINX Docker Maintainers "docker-maint@nginx.com"

ENV NGINX_VERSION 1.8.0

RUN apk add --no-cache nginx

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
````

I can probably help with either building an official nginx repository for alpine and use that as base for a docker image, or I can help you with building it from sources if you can point me to where I can find the compile options used for `deb http://nginx.org/packages/mainline/debian/ jessie nginx`

**Comment by thresheek** [comment]
What is the point of maintaining a build for a small obscure linux distro?  I really do not understand.

The packaging sources are available on http://hg.nginx.org/pkg-oss/.

**Comment by ncopa** [comment]
The point would be to provide a significantly smaller alternative for docker users. As you see the alpine docker image is 95% smaller (6.2MB vs 133.8MB). For users who roll out more than 20 nginx instances using docker this _may_ mean:

- 20 times more instances on same hardware
- storage cost reduced with 95%
- bandwidth cost for deployment reduced with 95%
- reployment time reduced with 95%
- better security due to attack surface reduced with 95%

But of course, all of this is completely pointless if you only deploy 1 instance or if you don't use docker in the first place.

Maintaining a nginx build against musl libc will also confirm that the code quality is high when it comes to portability - which it is. nginx has built on alpine linux without any issues since 2010.

Where can i find the compile options that you use for the maintained builds for the big non-obscure distros?

Thanks!

**Comment by thresheek** [comment]
Oh ok, that sounds great indeed.

I'm fine with introducing those builds provided that would not add much maintenance burden.  If you could provide Dockerfiles and needed changes for that repo and docker-library, that would be awesome.

I've linked the compile options (as packaging sources) in the previous comment.

Thanks!

**Comment by md5** [comment]
@ncopa Here is the `./configure` call for the Debian package: http://hg.nginx.org/pkg-oss/file/tip/debian/rules#l21

**Comment by ncopa** [comment]
Thanks!

**Comment by stephennancekivell** [comment]
+1 Thanks @ncopa, I love the idea.

**Comment by hbrls** [comment]
@thresheek What is the Docker Hub link? I did not find the new tags.

**Comment by thresheek** [comment]
@hbrls does not look like the PR is merged yet: https://github.com/docker-library/official-images/pull/1462

I guess maintainers are quite busy with the libc6 CVE fallout, so cant blame really. Let's be patient. :-)

**Comment by hbrls** [comment]
@thresheek I thought this was the official repo. Now I know it's the child repo. :clap:

**Comment by thresheek** [comment]
It is official by means that the actual development is going on here.  docker-library/official-images is the way to propagate the tags to docker registry / hub.
