### ISSUE TITLE
docker image error messages can be improved

### ISSUE THREAD

**Issue by vivekKodira** [nginxinc/docker-nginx#621]
Background: 

I was trying to setup the container as a reverse proxy and specified a custom conf.d folder to be used. This folder did not contain neither nginx.conf nor default.conf. I had instead included a file wrongly named as `nginx-conf` (hyphen instead of dot).

The container came up successfully. It displayed the `info` message "`10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist`." but was not otherwise responding to requests on the ports I expected.  I was even able to exec into the container and verify that the nginx service was indeed running.

The only suspicious msg had the word: 'info' and was then followed by a few other lines which will make novice users like me wrongly ignore it.  

Suggestions:
* Could the container error be clearer? If neither file is found, it should say so instead of only `default.conf`

**Comment by vivekKodira** [comment]
Sorry. Please ignore this issue. I had a typo in the file name `nginx.conf`

**Comment by thresheek** [comment]
`10-listen-on-ipv6-by-default.sh` does not touch or modify `/etc/nginx/nginx.conf`, so it should not check or notify user about it.

If you're not providing your own main configuration file, a default one is used, too.

**Comment by vivekKodira** [comment]
@thresheek thank you for the clarification. 

In that case do consider adding *another* message indicating that the container did not find either nginx.conf or default.conf.

**Comment by thresheek** [comment]
Those files are always in there, since they are coming in the image.  If you remove `nginx.conf`, nginx (and the container) will not start at all.

**Comment by vivekKodira** [comment]
Sorry, I've not been very clear with my description. I will edit it. 

I was trying to setup the container as a reverse proxy and specified a custom conf.d folder to be used. This folder did not contain neither nginx.conf nor default.conf. I had instead included a file labelled `nginx-conf`.

The container did come up successfully. It displayed the `info` message above but was not otherwise responsive to requests on the ports I expected.

**Comment by thresheek** [comment]
That's because the default `nginx.conf` file (which is not in a conf.d folder, but in /etc/nginx/) includes `conf.d/*.conf` files.  That's not something we can easily instrument with warning messages, since it's perfectly fine to start if there are no files like that to be included.

**Comment by vivekKodira** [comment]
Thanks for taking the time to respond @thresheek. I've gone past the issue I was facing and this was only feedback I hoped would help someone who faced a similar issue. 

I understand if it is not practical or a priority to implement. Will close the ticket. 

Thanks again for your contributions.
