### ISSUE TITLE
High vulnerability with underlying alpine://3.15:freetype:2.11.0-r0

### ISSUE THREAD

**Issue by pavel-moskotin-db** [nginxinc/docker-nginx#622]
Hi team,
can this library be upgraded please?
freetype:2.11.0-r0 to the version higher than 2.11.0-r0

**Comment by thresheek** [comment]
It's not in the `alpine:3.15` yet: https://pkgs.alpinelinux.org/packages?name=freetype&branch=v3.15 .

**Comment by thresheek** [comment]
Alpine 3.15 now ships freetype 2.11.1-r0 and 3.15-based nginx images have that as well, so closing this now.
