### ISSUE TITLE
cant build Nginx 1.21.5 for Alpine docker

### ISSUE THREAD

**Issue by cyrax13** [nginxinc/docker-nginx#624]
Hi All)

nginx 1.21.5 mainline, link from https://hub.docker.com/_/nginx
using dockerfile for alpine from here [https://github.com/nginxinc/docker-nginx/blob/01561128671d4e33c039a654fe198c6259a2514c/mainline/alpine/Dockerfile](https://github.com/nginxinc/docker-nginx/blob/01561128671d4e33c039a654fe198c6259a2514c/mainline/alpine/Dockerfile)

So, problem is - build failed, when try to build docker image...

Why? Looking at source code, line 69 and above:
```
....................................
                && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
                && PKGOSSCHECKSUM=\"b0ed109a820a2e8921f313d653032b8e70d3020138d634039ebb9194dc3968493f6eb4d85bdbf18d2aea7229deddb98ca0f1d9825defcc5af45f68ee37845232 *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
                && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
                    echo \"pkg-oss tarball checksum verification succeeded!\"; \
                else \
                    echo \"pkg-oss tarball checksum verification failed!\"; \
                    exit 1; \
                fi \
....................................
```

Expected ckecksum is _b0ed109a820a2e8921f313d653032b8e70d3020138d634039ebb9194dc3968493f6eb4d85bdbf18d2aea7229deddb98ca0f1d9825defcc5af45f68ee37845232_

But when docker build download archive from here "https://hg.nginx.org/pkg-oss/archive/1.21.5-1.tar.gz" and check sums "openssl sha512 -r 1.21.5-1.tar.gz", the real ckekcsum is _01e788d3eed17f072aab2b17d5cb83879fea9a360027ae8dc279557d9b149462a363f31b3b672d07efef472fceeb0d1705e26f83376da4b34f4d7c7cf60960b0_

They didnt much(

What's happened? Why is the downloaded archive different? Can you fix this issue?

PS: look in the my build logs before January 1, 2022 - the build was successful )
PSPS: change ckecksum from b0ed10... to 01e788... in Dockerfile - docker image build with no errros ))

**Comment by thresheek** [comment]
Hi @cyrax13 ! Thanks for filling out the issue.  The tag on hg.nginx.org got moved, so the checksum changed indeed. It should be fixed with the current master and 1.21.5 tag here: https://github.com/nginxinc/docker-nginx/commit/135978e032a4db66ca6bde03978107102065f406.
