### ISSUE TITLE
SSL_do_handshake() failed (SSL: error:14201044:SSL routines:tls_choose_sigalg:internal error)

### ISSUE THREAD

**Issue by agdevsu** [nginxinc/docker-nginx#625]
I have created a Nginx server with proxy configuration in a docker container.

* Nginx Docker Container Version: nginx:1.20.2

* From Nginx server error log:

192.168.3.218 - - [24/Jan/2022:15:39:15 +0000] "POST /auth/realms/Toyota/protocol/openid-connect/token HTTP/1.1" 200 2161 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

2022/01/24 15:39:15 [crit] 24#24: *110 SSL_do_handshake() failed (SSL: error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL handshaking, client: 192.168.3.218, server: 0.0.0.0:443

2022/01/24 15:39:15 [crit] 24#24: *111 SSL_do_handshake() failed (SSL: error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL handshaking, client: 192.168.3.218, server: 0.0.0.0:443
We are able to send the hello packet from the server to the client, but when the client sends the response, SSL Handshake is failing here.

This is my nginx.conf file. Please let me know any changes needed.

user  nginx;

events {
    worker_connections   1000;
}

http {

    proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          90m;
    send_timeout                600;
    
    resolver 10.89.1.1 valid=30s ipv6=off;
    resolver_timeout 10s;
    
    server {
        listen 80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/tde.com.ec.crt;
        ssl_certificate_key /etc/nginx/certs/tde.com.ec.key;

        server_name auth-py.tde.com.ec;

		location / {

            set $auth_url repuestos_auth_1;

            proxy_pass http://$auth_url:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/tde.com.ec.crt;
        ssl_certificate_key /etc/nginx/certs/tde.com.ec.key;

        server_name tems-api-py.tde.com.ec;

		location / {

            set $api_url repuestos_api_1;

            proxy_pass http://$api_url:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
	}

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/tde.com.ec.crt;
        ssl_certificate_key /etc/nginx/certs/tde.com.ec.key;

        server_name tems-py.tde.com.ec;

		location / {

            set $client_url repuestos_client_1;

            proxy_pass http://$client_url;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
	}
}

**Comment by thresheek** [comment]
Looks like there is no overlap between supported signature algorithms between your client and nginx.
Adjusting openssl security level on either client side or nginx side might help with that issue. On nginx adding '@SECLEVEL=0' to `ssl_ciphers` might help.

Relevant reading:
-  https://serverfault.com/questions/1089684/nginx-cant-accept-tls-handshake-when-client-is-not-sending-tls-extensions

**Comment by thresheek** [comment]
Closing due to feedback timeout.

**Comment by liuchi209** [comment]
I had the same problem, after debuging multiple locations, I found that the backend address forwarded by nginx forwarding should be https requests, and I wrote http. Hope that helps.

**Comment by HumbertoBernal** [comment]
> I had the same problem, after debuging multiple locations, I found that the backend address forwarded by nginx forwarding should be https requests, and I wrote http. Hope that helps.

Did you change http -> https in which part? 
In proxy_pass or in the beginning of the whole nginx.conf file?
