### ISSUE TITLE
how to build without some default modules?

### ISSUE THREAD

**Issue by kuznetcoff777** [nginxinc/docker-nginx#628]
Cannot find where i can declare what modules i need or not (for example i dont need --with-mail)

**Comment by thresheek** [comment]
Hi @kuznetcoff777!

That is not possible without modifying the packaging sources on https://hg.nginx.org/pkg-oss.  The easiest way is probably to modify the Alpine-based Dockerfiles to include a patch on top of a pkg-oss checkout that fixes that for you.

**Comment by kuznetcoff777** [comment]
Downloaded https://hg.nginx.org/pkg-oss/archive/1.20.2-1.tar.gz to see what is in there. But i dont see mail module in apline folder. I was thinking to delete some from that folder (describe it in Dockerfile)

**Comment by thresheek** [comment]
It's in the `alpine/Makefile`, under `BASE_CONFIGURE_ARGS`, see http://hg.nginx.org/pkg-oss/file/stable-1.20/alpine/Makefile#l89

**Comment by kuznetcoff777** [comment]
In /stable/alpine/Dockerfile added this string 

`                && cat Makefile | grep -viE "with-mail|with-http_mp4_module|with-http_flv_module|with-mail_ssl_module|with-stream|with-stream_realip_module|with-stream_ssl_module|with-stream_ssl_preread_module" > Makefile.tmp && yes|mv Makefile.tmp Makefile.tmp \`


total part:

```
&& su nobody -s /bin/sh -c " \
                export HOME=${tempDir} \
                && cd ${tempDir} \
                && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
                && PKGOSSCHECKSUM=\"af6e7eb25594dffe2903358f7a2c5c956f5b67b8df3f4e8237c30b63e50ce28e6eada3ed453687409beef8f3afa8f551cb20df2f06bd5e235eb66df212ece2ed *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
                && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
                    echo \"pkg-oss tarball checksum verification succeeded!\"; \
                else \
                    echo \"pkg-oss tarball checksum verification failed!\"; \
                    exit 1; \
                fi \
                && tar xzvf ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
                && cd pkg-oss-${NGINX_VERSION}-${PKG_RELEASE} \
                && cd alpine \
                && cat Makefile | grep -viE "with-mail|with-http_mp4_module|with-http_flv_module|with-mail_ssl_module|with-stream|with-stream_realip_module|with-stream_ssl_module|with-stream_ssl_preread_module" > Makefile.tmp && yes|mv Makefile.tmp Makefile.tmp \
                && make all \
                && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
                && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
                " \

```
But still no luck, seems to be wrong place i chosen...

**Comment by kuznetcoff777** [comment]
My fault
mv Makefile.tmp Makefile.tmp
but need this
mv Makefile.tmp Makefile

Checking...

**Comment by kuznetcoff777** [comment]
Nope, still with modules

`nginx version: nginx/1.20.2
built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
built with OpenSSL 1.1.1k  25 Mar 2021 (running with OpenSSL 1.1.1l  24 Aug 2021)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --with-perl_modules_path=/usr/lib/perl5/vendor_perl --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-Os -fomit-frame-pointer -g' --with-ld-opt=-Wl,--as-needed,-O1,--sort-common`

Dont get it

**Comment by thresheek** [comment]
Are the packages built or installed from nginx.org repos?  There is a switch for common architectures that would use prebuilt packages over at: https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile#L30

**Comment by kuznetcoff777** [comment]
I just used all default files from git, just added dynamic modules:

`docker build --build-arg ENABLED_MODULES="ndk lua nginx-vod-module nginx-dav-ext-module" -f Dockerfile.alpine -t my-stable-only-needed-nginx-with-lua-webdav-kaltura .
`

**Comment by thresheek** [comment]
You still need to build the base image without the default modules that Dockerfile.alpine references in FROM, the one in `stable/alpine/Dockerfile` with your edits mentioned https://github.com/nginxinc/docker-nginx/issues/628#issuecomment-1023909261. And then, based on that image, add the third-paryt modules on top of it via `modules/Dockerfile.alpine`.

**Comment by kuznetcoff777** [comment]
Yes, and i attempted to do it already, in /stable/alpine/Dockerfile a made those grep|mv edits...
Or you mean that i should launch first docker build on /stable/alpine/Dockerfile and only after that i should build with file /modules/Dockerfile.alpine?

But i was sure that when i build /modules/Dockerfile.alpine it triggers to build first /stable/alpine/Dockerfile
is not it?

**Comment by thresheek** [comment]
The first sentence is correct, you first need to build a base image with `stable/alpine/Dockerfile`, and then reference that tag under `modules/Dockerfile.alpine` in both FROM places (by default the modules/ one would use `nginx:mainline-alpine`).

**Comment by kuznetcoff777** [comment]
Sorry, forget to mention it before, i already changed it in modules/Dockerfile.alpine in both FROM places, and built modules/Dockerfile.alpine, was sure it triggers to build stable version automatically...

**Comment by thresheek** [comment]
There is no automation in this part.  For `modules/` builds we're reusing what is already available.

**Comment by kuznetcoff777** [comment]
Attempted.
`docker build -f Dockerfile . -t nginx:stable-alpine`
in Dockerfile a hack with grep and mv
also added     `&& nginx -V \`
after
```
&& ln -sf /dev/stdout /var/log/nginx/access.log \
&& ln -sf /dev/stderr /var/log/nginx/error.log \
```

And still shows all that modules

**Comment by thresheek** [comment]
Check the image build logs whether your changes have any effect then.

**Comment by kuznetcoff777** [comment]
made a tee output while building
[123.txt](https://github.com/nginxinc/docker-nginx/files/7958341/123.txt)
 
and i see my grep/mv operations

**Comment by thresheek** [comment]
That's just the dump of Dockerfile, and it never gets executed. I believe you need to change the architectures part as mentioned in https://github.com/nginxinc/docker-nginx/issues/628#issuecomment-1023975577 for your changes to have affect.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
