### ISSUE TITLE
local variable does not work

### ISSUE THREAD

**Issue by kuznetcoff777** [nginxinc/docker-nginx#629]
Wanted to use log_by_lua script to monitor different counters.

Added this to location
`set $location_name "webdav";`

In main log access area added 
`"LOCATION_NAME=$location_name"'`

Restarted container and see as in access logs empty variable LOCATION_NAME=

**Comment by kuznetcoff777** [comment]
Also in logs i see 
`using uninitialized "location_name" variable while logging request`

**Comment by kuznetcoff777** [comment]
Strange, config was this one

```
server {
        listen  81;
        root /storage/webdav;
        client_body_buffer_size 10m;
        client_max_body_size    10G;
#        upload_max_file_size    10G;


        location / {
            set $location_name "webdav";
            dav_methods PUT DELETE MKCOL COPY MOVE;
            dav_ext_methods PROPFIND OPTIONS;
            autoindex on;
            create_full_put_path   on;
            dav_access user:rw group:rw all:r;

            limit_except  GET {
                allow  172.20.0.1;
                deny   all;
            }
        }

    }
```

When i moved             
`set $location_name "webdav"; `
on a server layer, it started to work. Cannot get if it is ok

**Comment by thresheek** [comment]
I would try to reproduce without third party modules, and just using normal nginx logging via acess_log first.

**Comment by kuznetcoff777** [comment]
At the begining i was sure that it was docker issue...
And yes, i used normal logging via acess_log...
