### ISSUE TITLE
Fail due to $PORT not passing to Heroku via Dockerfile

### ISSUE THREAD

**Issue by SmarticoApps** [nginxinc/docker-nginx#634]
Fail due to $PORT not passing to Heroku via Dockerfile

In another docker/heroku repo this command in Dockerfile works by passing the randomly assigned PORT to nginx.

How to implement this into docker-nginx ?

`COPY default.conf.template /etc/nginx/conf.d/default.conf.template`

`CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'`

Contents of default.conf.template

`server {`
`  listen $PORT default_server;`
`  root   /usr/share/nginx/html;`
`  index  index.html index.htm;`
`}`

**Comment by jrtitus** [comment]
Are you setting `PORT` as an environment variable when running your container?

```
docker run --rm -e PORT=8080 -p 8080:8080 your-image-name
```

Alternatively you could just map the default port 80 defined by nginx to another port using Docker without the variable substitution

```
docker run --rm -p 8080:80 nginx
```

**Comment by SmarticoApps** [comment]
Heroku assigns a random port during build, thus a $PORT variable is required to capture the random port

**Comment by selurvedu** [comment]
Works for me out of the box with `listen       ${PORT};` and the default `/docker-entrypoint.d/20-envsubst-on-templates.sh`.

**Comment by thresheek** [comment]
It definitely works passing a $PORT variable as described in "Using environment variables in nginx configuration" section of https://hub.docker.com/_/nginx.
