### ISSUE TITLE
Can't copy files into nginx alpine container

### ISSUE THREAD

**Issue by adamSecureAILabs** [nginxinc/docker-nginx#635]
```
FROM node:16.14.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN apk update && apk add python3 g++ make && rm -rf /var/cache/apk/*

RUN yarn install
COPY . ./
RUN yarn run build

# production environment
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html/
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Default port exposure
EXPOSE 80

# Copy .env file and shell script to container
COPY ./env.sh /usr/share/nginx/html

# Start Nginx server
CMD ["/bin/sh", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]

```
The code above will return the following error: /bin/sh: /usr/share/nginx/html/env.sh: not found

However, simply getting rid of the alpine tag fixes it. No idea why

**Comment by jrtitus** [comment]
I've seen that error message before - it's very misleading. If your `env.sh` script starts with `#!/bin/bash` (or something equivalent) then you need to `apk add bash` because alpine does not come with it.

**Comment by thresheek** [comment]
Correct, you'll need to install bash if you're using it inside alpine containers.
