### ISSUE TITLE
Vulnerability DSA-5085-2 is found for docker nginx latest image

### ISSUE THREAD

**Issue by Dipenduroy** [nginxinc/docker-nginx#639]
Vulnerability [Link](https://linuxsecurity.com/advisories/debian/debian-dsa-5085-2-expat-regression-update-11-15-49)

Vulnerability ID  Policy Status  Affected Packages  How to Resolve
DSA-5085-2        Active         libexpat1          Upgrade libexpat1 to >= 2.2.10-2+deb11u3

**Comment by thresheek** [comment]
Both `nginx:latest` and `nginx:stable` have libexpat1 2.2.10-2+deb11u3 now. Fixed.
