### ISSUE TITLE
"Configure" is not defined when trying to install other modules

### ISSUE THREAD

**Issue by zacharynevin** [nginxinc/docker-nginx#64]
I am trying to install the echo nginx module (https://github.com/openresty/echo-nginx-module). I have the following steps:

````
FROM nginx:1.9.7
MAINTAINER Zachary <zachary@thegraduate.asia>

ADD https://github.com/openresty/echo-nginx-module/archive/v0.58.tar.gz /nginx-modules/

# install Make and the nginx module
RUN tar -xzvf /nginx-modules/v0.58.tar.gz \
    && ./configure --prefix=/etc/nginx --add-module=/nginx-modules/echo-nginx-module-0.58 \
    && make -j2 \
    && make install \
    && rm /etc/nginx/conf.d/default.conf
````

I get the error `/bin/sh: 1: ./configure: not found` when I do this.

**Comment by hacfi** [comment]
@zacharynevin Using this repository as the base image doesn’t help you if you want to add a custom module. You have to compile nginx yourself. Have a look at this [Dockerfile](https://gist.github.com/hacfi/3ea3fe84251aebaa83be) to see how that looks like. Didn’t test it but should work with some minor modifications.

**Comment by thresheek** [comment]
nginx official image does not ship the source code.
