### ISSUE TITLE
Building up of Memory usage when the udpRequests are increased.

### ISSUE THREAD

**Issue by bkannadassan** [nginxinc/docker-nginx#643]
Hi All,

   With below configuration we see a gradual buildup of memory..    
```
 proxy_requests 10;
 proxy_responses 1;
```
When we change it to 
```
 proxy_requests 1;
 proxy_responses 1;
```
Memory usage drops down drastically. Please let us know if this is expected. When I logged into the pod and checked the process memory I don't see increasing but still at pod level in k8s its showing a gradual increase. Could this be because of shared memory ?.

rgds
Balaji

**Comment by thresheek** [comment]
Hello @bkannadassan!

Can you please clarify what do you mean by memory increasing in the pod level?  If NGINX inside the container does not report the increased memory usage (e.g. via top/htop or similar commands), then it's definitely not using more and more.

Regarding the proxy_requests, maybe what you're seeing is actual kernel memory usage per container?  Leaving sessions active for a longer time might mean more RAM usage on the kernel side too.
