### ISSUE TITLE
Apple M1: nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:47

### ISSUE THREAD

**Issue by tiefenb** [nginxinc/docker-nginx#656]
I have problems with docker nginx on Apple M1 Pro Silicon Chip (ARM64)

```
bto-docker-nginx-1    | nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:47
bto-docker-nginx-1    | patching file /etc/nginx/conf.d/10-upstreams.conf
bto-docker-nginx-1    | Reversed (or previously applied) patch detected!  Skipping patch.
bto-docker-nginx-1    | 1 out of 1 hunk ignored -- saving rejects to file /etc/nginx/conf.d/10-upstreams.conf.rej
```

I have tried to add platform: "linux/amd64" to my docker-compose.yml to emulate it wit Rosetta 2 but it doesn't work.

**Comment by thresheek** [comment]
Hi @tiefenb !

What image are you using?  We don't ship LUA as a part of official images.

**Comment by tiefenb** [comment]
Hi @thresheek,

I use nginx:latest.

When I add `platform: linux/arm64/v8` I get the error `Error response from daemon: image with reference [registry.gitlab.com/netconomy/bto/bto-docker/bto/nginx:latest](http://registry.gitlab.com/netconomy/bto/bto-docker/bto/nginx:latest) was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd6`

Current Image id: fef2f51d297b

**Comment by thresheek** [comment]
It seems you're not using docker official images registries, but something that was built on top of it.  Looks like the defaults for unresolved images for you go to netconomy on gitlab, while for nginx:latest they should be in the docker.io namespace.

Also, with the official images we do provide images built for armv8/aarch64 (the architecture M1 uses), so it should be automatic in your case.

**Comment by tiefenb** [comment]
Yes sorry - I forget that this image comes from the internal regestry.

**Comment by neelsingh98** [comment]
I am also facing the same issue on my M1 pro, I am using openresty below is the docker image
docker build is successfull but when running the image getting error "failed to initialize Lua VM"

FROM openresty/openresty:1.13.6.1-alpine

RUN apk -Uuv add sed python py-pip && \
	pip install awscli && \
	apk --purge -v del py-pip && \
	rm /var/cache/apk/* && \
    addgroup nginx && \
    adduser -s /bin/false -H -S -G nginx nginx && \
    rm -rf /etc/nginx/conf.d/* && \
    mkdir /etc/nginx/api.conf.d && \
    touch /usr/local/openresty/nginx/conf/env.conf

COPY conf/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY conf/spa.conf /etc/nginx/conf.d/
COPY bootstrap.sh .

CMD sh bootstrap.sh

**Comment by thresheek** [comment]
Hi @neelsingh98, we don't support this image here. Please consult openresty.

**Comment by cilf** [comment]
@neelsingh98 I had the same but fixed it using newer docker image - `openresty/openresty:1.21.4.1-0-alpine`
