### ISSUE TITLE
How to disable IPv6?

### ISSUE THREAD

**Issue by nmajin** [nginxinc/docker-nginx#659]
Is there any way to disable IPv6 via an environment variable or any other way than to comment out the `[::]:8080` listener?

**Comment by thresheek** [comment]
You can just remove the default.conf file.

**Comment by nmajin** [comment]
Would that work though if `nginx.conf` is in use? That is what is actually configured with the listen `[::]:8080` directive

**Comment by thresheek** [comment]
No, there is no configuration with `listen [::]:8080` in `nginx.conf` shipped with this image.

**Comment by nmajin** [comment]
Well looks like we are actually using this image: https://catalog.redhat.com/software/containers/rhscl/nginx-120-rhel7/612f5a4fc61b370d4fd4c7f3...do you see this being the same config for this image?

**Comment by thresheek** [comment]
Sorry, we can't provide support for other images than official nginx images.
