### ISSUE TITLE
No 1.8.x?

### ISSUE THREAD

**Issue by lrkwz** [nginxinc/docker-nginx#66]
Why there is no 1.8.x tag available?

**Comment by thresheek** [comment]
See #3 and #21.

**Comment by lrkwz** [comment]
Sorry I didn't understand as from http://nginx.org/en/download.html

- 1.9.x mainline version
- 1.8.x stable version

My opinion (as much it counts) is: docker is commonly used for dev environments and it is quite useful to develop your apps in the SAME environment you have in production: likely 1.8 (or older).

Am I wrong?
