### ISSUE TITLE
Nginx Docker Image Security Hardening Based CIS Benchmark

### ISSUE THREAD

**Issue by raja4dev** [nginxinc/docker-nginx#661]
Is your feature request related to a problem? Please describe.
I'm looking at CIS Benchmark [documents](https://www.cisecurity.org/benchmark/nginx) for hardening Nginx.
I found most of the CIS Benchmark security findings are still [present](https://hub.docker.com/r/nginxinc/nginx-unprivileged) and its not remediation are not implemented

Example: like directory permissions, user accounts, network configuration, nginx modules enable/disable and default nginx configuration changes still are present

Describe the solution you'd like
Can we expect the docker image from your side as that supported by CIS Benchmark at nginx level to the sec

Describe alternatives you've considered
I tried to follow the CIS document on the Nginx, but it will be difficult to fix the problem at container/pod level.

Additional context
CIS Bench mark reference: https://www.cisecurity.org/benchmark/nginx

**Comment by thresheek** [comment]
No, there are no plans to introduce images like that.
