### ISSUE TITLE
Update version to latest 

### ISSUE THREAD

**Issue by Gyula-Toth** [nginxinc/docker-nginx#668]
Yesterday we had a release for both nginx and njs.

https://nginx.org/en/docs/njs/changes.html
https://nginx.org/en/CHANGES-1.22

We should probably update the versions and the sha checksum digest in update.sh, and probably create a new tag for 1.22 / 1.22.0
I wouldn't mind making a PR to do so, but I'm unsure about the ideal less painful way to grab the new digest for this.

**Comment by thresheek** [comment]
I'm working on it, thanks!

**Comment by thresheek** [comment]
Done for `stable` images.
