### ISSUE TITLE
Add flag to disable DNS resolution check of upstreams on nginx statup and nginx test

### ISSUE THREAD

**Issue by hegerdes** [nginxinc/docker-nginx#669]
Problem:
Nginx refuses to start if it has `proxy_pass` statments containing a domain-name that can not be resoved at statup or at test time.

*Conf*
```conf
upstream site1.my-domain.com_default {
    server my_service1:5050;
    server my_service2:5050;
}

server {
    server_name site1.my-domain.com;
    location / {
        proxy_pass http://site1.my-domain.com_default/;
    }
}
```

*Error*
```bash
#11 6.009 2022/05/25 22:00:12 [emerg] 12#12: host not found in upstream "my_service1:5050" in /etc/nginx/conf.d/my_service.com.conf:7
#11 6.009 nginx: [emerg] host not found in upstream "my_service1:5050" in /etc/nginx/conf.d/my_service.com.conf:7
#11 6.009 nginx: configuration file /etc/nginx/nginx.conf test failed
```

Imagin a case where you have 100's of upstreams. If one upstream can not be resolved due to a DNS issue, all 99 other services become unavailable too on a nginx restart.  
Also in the container world, where internal container IPs are often unpredictable and the container communicate over their service names  it must be possible to start/restart nginx when one service name can not be resolved or a service is down.

Proposal:
Add a flag to disable DNS resolution on nginx startup and nginx test (`nginx -t`)

This allows to start nginx even if one upstream is not available, but others are. It also allows to check if the configuration is valid at `docker build` time where DNS resolution is definitely not available.

**Comment by thresheek** [comment]
Hi @hegerdes!

That is a well known behaviour of nginx - please refer to https://www.nginx.com/blog/dns-service-discovery-nginx-plus/ for possible solutions.

Thanks!

**Comment by hegerdes** [comment]
Thanks for the replay!

The process described in the article is a workaround, not a solution. It is a 6 year old article and the importance of that use case has nothing but increased. Maybe there should be a discussion to change the current sate to adapt to the current use cases to keep up with competing software. 

Keeping a functionality like that preserved to the paid version is not contemporary anymore or an artificial limitation to force users to nginx plus.
