### ISSUE TITLE
Plan to tag other distros mainline images on Docker Hub?

### ISSUE THREAD

**Issue by ujovlado** [nginxinc/docker-nginx#67]
Hi, since there are Dockerfiles for other Linux distributions, do you plan to build and tag those images on Docker Hub?

Thanks

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/1462 is probably the best place to see the current status of that :+1:

**Comment by ujovlado** [comment]
@tianon thanks, I will look there. :wink:
