### ISSUE TITLE
ECR scanner doesn't support alpine 3.16 

### ISSUE THREAD

**Issue by renperez-cpi** [nginxinc/docker-nginx#670]
Hi Guys,

Looks like ECR scanner doesn't support alpine3.16. I am using nginx:stable-alpine image which uses alpine3.16 is there an nginx image that i can use that uses alpine3.12?

https://github.com/aws/containers-roadmap/issues/1753

**Comment by thresheek** [comment]
Alpine 3.12 is EOL upstream, so there are no images for that OS that we provide.  You may use `nginx:mainline-alpine` which is now alpine 3.15-based - but that will change in a month or so.

**Comment by thresheek** [comment]
All alpine-based images are now moved to 3.16.  Fix your scanners if they don't support it yet.
