### ISSUE TITLE
[Help] How to modify the source configuration file?

### ISSUE THREAD

**Issue by wordlesswind** [nginxinc/docker-nginx#676]
Hello,

I read this article: [Improving NGINX Performance with Kernel TLS and SSL_sendfile( )](https://www.nginx.com/blog/improving-nginx-performance-with-kernel-tls/)

So I wanted to modify your Debian Dockerfile and port it to Ubuntu Docker with OpenSSL 3.

But embarrassingly, I don't know how the apt-get source file should be modified, I didn't find much instructions on Google.

Can they be modified? And if you decide to start using OpenSSL 3, now Debian doesn't support kTLS, is it possible to add Ubuntu Docker?

Best Regards,
wordlesswind

**Comment by thresheek** [comment]
Hello @wordlesswind !

Keep in mind that for KTLS to work, you also need a supported kernel - so make sure host machine is up to date.

Regarding the changes, I think you just need to change all occurences of `debian` to `ubuntu`, and `bullseye` to e.g. `jammy`.  I didnt test if it builds, so it was just a quick glance.

We don't have plans to support Ubuntu on this image - it's more likely that Alpine moves to openssl 3.0 earlier than Debian would .

**Comment by wordlesswind** [comment]
> Hello @wordlesswind !
> 
> Keep in mind that for KTLS to work, you also need a supported kernel - so make sure host machine is up to date.
> 
> Regarding the changes, I think you just need to change all occurences of `debian` to `ubuntu`, and `bullseye` to e.g. `jammy`. I didnt test if it builds, so it was just a quick glance.
> 
> We don't have plans to support Ubuntu on this image - it's more likely that Alpine moves to openssl 3.0 earlier than Debian would .

thank you for your reply. I'll keep an eye on this, maybe migrating to Alpine is a good option. Thanks again
