### ISSUE TITLE
Not able to build the geoip2 module with Nginx

### ISSUE THREAD

**Issue by bqbn** [nginxinc/docker-nginx#677]
We cloned this repo and ran the following command

```
docker build --platform linux/amd64 --build-arg ENABLED_MODULES="geoip2" -t my-nginx-with-geoip2 .
```

and we got this error:

```
------
#10 13.79 E: Unsupported file /tmp/packages/nginx-module-geoip2_1.23.0*.deb given on commandline
------
```

After adding a few breakpoints in the Dockerfile, we found that there was an error that was silently ignored before the above error,

```
#9 109.4 make[1]: Entering directory '/pkg-oss/docs'
#9 109.4 xslscript.pl -o changes.xslt changes.xsls
#9 109.4 make[1]: xslscript.pl: No such file or directory
#9 109.4 make[1]: *** [Makefile:66: changes.xslt] Error 127
#9 109.4 make[1]: Leaving directory '/pkg-oss/docs'
#9 109.4 make: *** [Makefile:245: nginx-module-geoip2.deb-changelog] Error 2
#9 109.4 + mk-build-deps --install --tool=apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes debuild-module-geoip2/nginx-1.23.0/debian/control
#9 110.0 E: You must put some 'deb-src' URIs in your sources.list
#9 110.0 mk-build-deps: Unable to find package name in `apt-cache showsrc debuild-module-geoip2/nginx-1.23.0/debian/control'
#9 110.0 + make module-geoip2 BASE_VERSION=1.23.0 NGINX_VERSION=1.23.0
#9 110.2 ===> Generating nginx-module-geoip2.deb-changelog
#9 110.2 make[1]: Entering directory '/pkg-oss/docs'
#9 110.2 xslscript.pl -o changes.xslt changes.xsls
#9 110.2 make[1]: xslscript.pl: No such file or directory
#9 110.2 make[1]: *** [Makefile:66: changes.xslt] Error 127
#9 110.2 make[1]: Leaving directory '/pkg-oss/docs'
#9 110.2 make: *** [Makefile:245: nginx-module-geoip2.deb-changelog] Error 2
```

So basically no deb file was generated. We're not sure why `xslscript.pl` isn't there though.

**Comment by thresheek** [comment]
Thanks @bqbn - that's interesting.  I ocasionally see the same issue on our builders but didnt get to the bottom of it yet.

xslscript.pl shouldnt be needed to build for sure, I'll work on fixing that.

**Comment by bqbn** [comment]
Thank you @thresheek.

I wonder if this issue has to do with cached images because when I cleaned up all the intermediary images and ran the command again, it was able to finish successfully. I don't have direct proof though. I couldn't even find where `xslscript.pl` was called.

Also I'm not sure it matters, but I have had no success running the command on my M1 MacBook, but was able to build the image on a Linux machine.

**Comment by thresheek** [comment]
No, I don't think it's related to cached images. xslscript.pl gets called when changes.xsls is modified (http://hg.nginx.org/pkg-oss/file/default/docs/Makefile), but I'm not yet sure why this is happening.
