### ISSUE TITLE
OpenSSL security update

### ISSUE THREAD

**Issue by ginkel** [nginxinc/docker-nginx#69]
AFAICS the current nginx 1.9.11 docker image published at Docker Hub (sha256:363672ec4204fa58f60c80cc157adce725e8cd65e5b34cb4ae89adb38927956a) is based on a base image, which is vulnerable to the OpenSSL CVEs listed at: http://openssl.org/news/secadv/20160301.txt

As the relevant Debian base image has been updated in the meantime, I would appreciate if you could publish an updated nginx image based on that.

**Comment by tianon** [comment]
The fix for this should be pushed now.

**Comment by ginkel** [comment]
Excellent, thanks a lot! :+1:

**Comment by dgoujard** [comment]
Hi,

I created an container based on nginx:1.9.11 downloaded this morning and when i inspect the openssl version i got "OpenSSL 1.0.1k 8 Jan 2015".

My nginx:1.9.11 image id is sha256:fd19524415dc0e3ea56cd8fe9400400d47aacef1d05c2f503638525794d30fec 

It's the latest version ?

Thank you

**Comment by ginkel** [comment]
On a fully patched Debian Jessie system:

    $ openssl version
    OpenSSL 1.0.1k 8 Jan 2015

So the output provides no indication about the included patches.

**Comment by thresheek** [comment]
root# docker images nginx:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               latest              fd19524415dc        2 days ago          134.6 MB

root# docker run nginx:latest dpkg -l libssl1.0.0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version         Architecture Description
+++-=================-===============-============-===============================================
ii  libssl1.0.0:amd64 1.0.1k-3+deb8u4 amd64        Secure Sockets Layer toolkit - shared libraries


You can check http://anonscm.debian.org/viewvc/pkg-openssl/openssl/branches/jessie/debian/changelog?view=markup for which patches are included in this version.
