### ISSUE TITLE
How to disable ipv6 on latest nginx:alpine ?

### ISSUE THREAD

**Issue by 1xtr** [nginxinc/docker-nginx#690]
Test machine win10 with docker desktop latest

Dockerfile is simple
```
FROM nginx:alpine

COPY ./src /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
```

Container start log:
```
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
2022-07-27T10:22:22.550057276Z 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
2022-07-27T10:22:22.560317013Z 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
```
Because 
```
ls /proc/net | grep inet6
if_inet6
```
After container started:
```
sysctl -a 2>/dev/null | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.sit0.disable_ipv6 = 1
```

I tried use sed to comment or delete string in Dockerfile like this
```
RUN sed -i.bak '/\(listen.*::.*\)/d' /etc/nginx/conf.d/default.conf
or
RUN sed -i.bak 's/\(listen.*::.*\)/#\1/' /etc/nginx/conf.d/default.conf
```
But container still start with `listen  [::]:80;` and on prod machine container immediately stop with error 
`nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)`

I know that I can use templates, but still... may be there is a better solution to disable ipv6

**Comment by thresheek** [comment]
You can remove the `10-listen-on-ipv6-by-default.sh` in your Dockerfile if you don't want it to be executed.

**Comment by 1xtr** [comment]
> 10-listen-on-ipv6-by-default.sh

Thx so much
I didn't think of it myself ))) LOL
