### ISSUE TITLE
recipe for target 'objs/addon/ngx_http_geoip2_module-master/ngx_http_geoip2_module.o' failed

### ISSUE THREAD

**Issue by techalexx** [nginxinc/docker-nginx#691]
Version 1.23.1

/usr/src/geo/ngx_http_geoip2_module-master/ngx_http_geoip2_module.c: In function ‘ngx_http_geoip2_variable’:
/usr/src/geo/ngx_http_geoip2_module-master/ngx_http_geoip2_module.c:172:14: error: assignment from incompatible pointer type [-Werror]
         xfwd = &r->headers_in.x_forwarded_for;
              ^
/usr/src/geo/ngx_http_geoip2_module-master/ngx_http_geoip2_module.c:175:58: error: passing argument 3 of ‘ngx_http_get_forwarded_addr’ from incompatible pointer type [-Werror]
             (void) ngx_http_get_forwarded_addr(r, &addr, xfwd, NULL,
                                                          ^
In file included from src/http/ngx_http.h:36:0,
                 from /usr/src/geo/ngx_http_geoip2_module-master/ngx_http_geoip2_module.c:10:
src/http/ngx_http_core_module.h:531:11: note: expected ‘struct ngx_table_elt_t *’ but argument is of type ‘struct ngx_array_t *’
 ngx_int_t ngx_http_get_forwarded_addr(ngx_http_request_t *r, ngx_addr_t *addr,
           ^

**Comment by thresheek** [comment]
Hi @techalexx, this particular issue is fixed for 1.23.1, so I think the underlying image you're using is on a older tag. Can you please check?

**Comment by thresheek** [comment]
So maybe your geoip2 module isnt up to date?  It's fixed in 3.4: https://github.com/leev/ngx_http_geoip2_module/releases/tag/3.4

**Comment by techalexx** [comment]
Yeeee, thanx bro. I didn't think about it :|
