### ISSUE TITLE
IPv6 entrypoint addon script unused code branch

### ISSUE THREAD

**Issue by tspearconquest** [nginxinc/docker-nginx#693]
Hello,

I was working to make a fork of the stable Dockerfile for internal builds for my org and we run `shellcheck` via `pre-commit`

Shellcheck noticed that https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/10-listen-on-ipv6-by-default.sh contains the below block starting at line 35:

```
case "$ID" in
    "debian")
        CHECKSUM=$(dpkg-query --show --showformat='${Conffiles}\n' nginx | grep $DEFAULT_CONF_FILE | cut -d' ' -f 3)
        echo "$CHECKSUM  /$DEFAULT_CONF_FILE" | md5sum -c - >/dev/null 2>&1 || {
            echo >&3 "$ME: info: /$DEFAULT_CONF_FILE differs from the packaged version"
            exit 0
        }
        ;;
    "alpine")
        CHECKSUM=$(apk manifest nginx 2>/dev/null| grep $DEFAULT_CONF_FILE | cut -d' ' -f 1 | cut -d ':' -f 2)
        echo "$CHECKSUM  /$DEFAULT_CONF_FILE" | sha1sum -c - >/dev/null 2>&1 || {
            echo >&3 "$ME: info: /$DEFAULT_CONF_FILE differs from the packaged version"
            exit 0
        }
        ;;
    *)
        echo >&3 "$ME: info: Unsupported distribution"
        exit 0
        ;;
esac
```

It flagged this with:
```
In 1.22.0/10-listen-on-ipv6-by-default.sh line 35:
case "$ID" in
      ^-^ SC2154 (warning): ID is referenced but not assigned.
```

Upon checking, I'm not seeing this variable defined anywhere, so I'm unable to determine if it's possibly being populated by Github actions or something else in the public build, but wanted to check if shell check is correct or not, so that I can account for this finding in my build.

Thank you in advance!

**Comment by yosifkit** [comment]
That comes from line 27, so it is entirely expected to not be defined in the script. 

https://github.com/nginxinc/docker-nginx/blob/f3d86e99ba2db5d9918ede7b094fcad7b9128cd8/stable/alpine/10-listen-on-ipv6-by-default.sh#L27

**Comment by tspearconquest** [comment]
Thanks, I appreciate the pointer!
