### ISSUE TITLE
Provide OpenSSL >3.0.0 kTLS build

### ISSUE THREAD

**Issue by StrangePeanut** [nginxinc/docker-nginx#698]

**Comment by thresheek** [comment]
That would be possible whenever any of the OS variants we support (alpine, Debian) gets OpenSSL 3.0.0.

**Comment by jnoordsij** [comment]
Update: Alpine 3.17 ships with [OpenSSL 3.0 as default version](https://alpinelinux.org/posts/Alpine-3.17.0-released.html#significant_changes), so #720 would provide this for the alpine tags.

**Comment by thresheek** [comment]
We now ship mainline tags with Alpine 3.17, which has openssl 3.0 and ktls should work on those OSes.
