### ISSUE TITLE
Files served are not being updated

### ISSUE THREAD

**Issue by spectralsun** [nginxinc/docker-nginx#70]
We were trying to use this nginx container as to serve static HTML and Javascript. It was essentially supposed to emulate a CDN. We fired up the container with the following command:

    docker run -d -v ~/git/my_project/client/:/usr/share/nginx/html -p 8080:80 nginx

We'd see ``~/git/my_project/client/index.html`` served up correctly when we hit the exposed nginx container, as expected. However, when we made a change to ``index.html`` (or any other file served), nginx would not update what it was serving. We tried logging into the nginx container, installing curl, and seeing that inside the container it was also serving up a stale copy of ``index.html`` via ``curl localhost``. The only way we could get nginx to serve the up to date contents of the ``~/git/my_project/client/`` directory was to restart the docker process on the host OS. This meant that every time we made a change to the mapped directory we'd have to do a full restart of the host OS docker process to see nginx serve the up to date files.

**Comment by thresheek** [comment]
Are you using VirtualBox?
