### ISSUE TITLE
long execution for envsubst

### ISSUE THREAD

**Issue by karlderkaefer** [nginxinc/docker-nginx#704]
Related to this change #560 I noticed there is huge performance degradation by factor `50x` when having +1000 environment variables.

You can easily that reach that number of environment variables in kubernetes when you have **a lot of services within one namespace** `~40` and running **Istio with mTLS**. The Istio proxy will inject multiple environment variables for each service.

This will have impact on startup time of container

**How to reproduce**
running on ubuntu

```
cat <<EOT > test.sh
#!/bin/bash

for INDEX in {1..2000}
do
  export VAR_\$INDEX=\$INDEX
done
defined_envs=\$(printf '\${%s} ' \$(env | cut -d= -f1))
env | grep "VAR_" | wc -l
envsubst "\$defined_envs" < "./template.yaml"
EOT

cat <<EOT > template.yaml
data:
  \${VAR_1}: bla
EOT

chmod +x ./test.sh
./tesh.sh
```
result before change with 2000 EnvVars
```
time ./test.sh
2000
./test.sh  0,09s user 0,01s system 172% cpu 0,058 total
```
result after
```
time ./test.sh                                                               
2000
./test.sh  4,47s user 10,04s system 102% cpu 14,113 total
```

**Comment by karlderkaefer** [comment]
there is a workaround if we are able to whitelist environment variable explicitly #705

**Comment by thresheek** [comment]
Provided a workaround in https://github.com/nginxinc/docker-nginx/commit/34f8babd45eba2b3c4b001b7aac41882aae3b17a
