### ISSUE TITLE
Remove server response header on docker-nginx

### ISSUE THREAD

**Issue by rajasekar-mu** [nginxinc/docker-nginx#709]
Hi ,

We need to remove nginx response header **_server:_** , any possible way is there docker-nginx? Thanks

![image](https://user-images.githubusercontent.com/12061783/194029958-f34af23d-533a-4a10-a29d-04bed5247417.png)

Regards,
Rajasekar

**Comment by thresheek** [comment]
Hi @rajasekar-mu.  It's not possible with `docker-nginx`.

**Comment by rajasekar-mu** [comment]
Thanks @thresheek , Most of the applications expecting to remove server for security purpose, So kindly add this feature?

**Comment by thresheek** [comment]
The feature is only available in NGINX Plus, commercial version: https://nginx.org/r/server_tokens .
It will not be implemented in the free version.
