### ISSUE TITLE
Unable to connect docker nginx with docker ubuntu

### ISSUE THREAD

**Issue by eualin** [nginxinc/docker-nginx#71]
I have noticed an issue with docker nginx which is not the case when nginx is running on the host machine (`apt-get install`). Here is how to reproduce my issue:

# solution A: 'nc' on container 1, 'nginx' on container 2, 'curl' on host

    docker stop $(docker ps -aq)
    docker rm $(docker ps -aq)

### 'nc' on container 1

    docker run -ti --name agitated_stallman ubuntu:14.04 bash
    nc -l 4545

### 'nginx' on container 2

    LOLPATH=$HOME/testdocker
    echo $LOLPATH
    
    mkdir -p $LOLPATH
    cd $LOLPATH
    
    subl mple.conf

 .

    server {
    
    	listen 80;
    	root /var/www/html;
    
    	location /roz {
    		proxy_pass http://neocontainer:4545;
    		proxy_set_header Host $host;
    	}
    
    }

 .

    docker run --link agitated_stallman:neocontainer -v $LOLPATH/mple.conf:/etc/nginx/sites-available/default -p 12345:80 nginx:1.9

### 'curl' on host

    sudo apt-get install curl
    curl http://localhost:12345/roz

**ERROR** response from 'nginx':

    2016/03/04 19:59:18 [error] 8#8: *3 open() "/usr/share/nginx/html/roz" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /roz HTTP/1.1", host: "localhost:12345"
    172.17.0.1 - - [04/Mar/2016:19:59:18 +0000] "GET /roz HTTP/1.1" 404 169 "-" "curl/7.45.0" "-"

# solution B: 'nginx' on host, 'nc' on host, 'curl' on host

### 'nginx' on host

    sudo apt-get install nginx
    sudo subl /etc/nginx/sites-available/default

. 

    server {
    
    	listen 80;
    	root /var/www/html;
    
    	location /roz {
    		proxy_pass http://localhost:4646;
    		proxy_set_header Host $host;
    	}
    
    }

 .

     sudo service nginx restart

### 'nc' on host

    nc -l 4646

### 'curl' on host

    sudo apt-get install curl
    curl http://localhost:80/roz

**SUCCESS** response from 'nc':

    GET /roz HTTP/1.0
    Host: localhost
    Connection: close
    User-Agent: curl/7.45.0
    Accept: */*

Any ideas why 'solution 1' does not work? Is this is a bug?

**Comment by thresheek** [comment]
There is no sites-available on the nginx official image.

The docs are available on https://hub.docker.com/_/nginx/

**Comment by eualin** [comment]
oh. I see. you're right. thank you very much.
