### ISSUE TITLE
COPY static-html-directory --> COPY static-html-directory/

### ISSUE THREAD

**Issue by ValorNaram** [nginxinc/docker-nginx#711]
```dockerfile
FROM nginx
COPY static-html-directory /usr/share/nginx/html
```

should be

```dockerfile
FROM nginx
COPY static-html-directory/ /usr/share/nginx/html
```

in order to have the content of `static-html-directory` copied over to the docker container filesystem location at `/usr/share/nginx/html`.

**Comment by yosifkit** [comment]
In a Dockerfile, the trailing slashes don't really matter on the source side :disappointed::

>  If `<src>` is a directory, the entire contents of the directory are copied, including filesystem metadata.
>
> https://docs.docker.com/engine/reference/builder/#copy

**Comment by thresheek** [comment]
Closing due to feedback timeout.
