### ISSUE TITLE
Why does compiling Brotli from sources generate an extra .so file by build_module.sh?

### ISSUE THREAD

**Issue by Bisstocuz** [nginxinc/docker-nginx#713]
I used [build_module.sh](https://github.com/nginxinc/docker-nginx/tree/master/modules) to compile Brotli from sources of master branch (https://github.com/google/ngx_brotli.git), not from pkg-oss:
```shell
build_module.sh: INFO: Module binaries created
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/src/nginx-1.22.1/objs/ngx_http_brotli_filter_module-debug.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/src/nginx-1.22.1/objs/ngx_http_brotli_static_module.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/src/nginx-1.22.1/objs/ngx_brotli.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/src/nginx-1.22.1/objs/ngx_http_brotli_static_module-debug.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/src/nginx-1.22.1/objs/ngx_http_brotli_filter_module.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/src/nginx-1.22.1/objs/ngx_brotli-debug.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/pkg/nginx-module-brotli/usr/lib/nginx/modules/ngx_http_brotli_filter_module-debug.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/pkg/nginx-module-brotli/usr/lib/nginx/modules/ngx_http_brotli_static_module.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/pkg/nginx-module-brotli/usr/lib/nginx/modules/ngx_brotli.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/pkg/nginx-module-brotli/usr/lib/nginx/modules/ngx_http_brotli_static_module-debug.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/pkg/nginx-module-brotli/usr/lib/nginx/modules/ngx_http_brotli_filter_module.so
/tmp/build_module.sh.30/pkg-oss/alpine/abuild-module-brotli/pkg/nginx-module-brotli/usr/lib/nginx/modules/ngx_brotli-debug.so
build_module.sh: INFO: Module packages created
'/root/packages/alpine/x86_64/nginx-module-brotli-1.22.1.1.0-r1.apk' -> '/tmp/packages/nginx-module-brotli-1.22.1.1.0-r1.apk'
'/root/packages/alpine/x86_64/nginx-module-brotli-dbg-1.22.1.1.0-r1.apk' -> '/tmp/packages/nginx-module-brotli-dbg-1.22.1.1.0-r1.apk'
build_module.sh: INFO: Removing /tmp/build_module.sh.30
```

It generated `ngx_http_brotli_static_module.so`, `ngx_http_brotli_filter_module.so` and `ngx_brotli.so`. But if I follow [google's tutorials](https://github.com/google/ngx_brotli#installation), only generated `ngx_http_brotli_static_module.so` and `ngx_http_brotli_filter_module.so`.

If I follow this below, the `load_module` will work improperly with "No symbolic links".
```shell
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/1) Installing nginx-module-brotli (1.22.1.1.0-r1)
Executing nginx-module-brotli-1.22.1.1.0-r1.post-install
----------------------------------------------------------------------

The brotli dynamic module for nginx has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ngx_brotli.so;

----------------------------------------------------------------------
OK: 27 MiB in 43 packages
```

Use this then works properly:
```
load_module modules/ngx_http_brotli_filter_module.so;
load_module modules/ngx_http_brotli_static_module.so;
```

**Comment by thresheek** [comment]
Hello @Bisstocuz !

It looks like `build_module.sh` built-in heuristics to determine what .so files are installed are wrong in this case.
Brotli module seems to have a bit unconventional `config` file: https://github.com/google/ngx_brotli/blob/master/config and `build_module.sh` expects `ngx_module_name` defined in the top-level config to figure out the names of resulting plugins.

**Comment by Bisstocuz** [comment]
If I use pkg-oss source to compile Brotli, only generated `ngx_http_brotli_static_module.so` and `ngx_http_brotli_filter_module.so`.

**Comment by thresheek** [comment]
The incorrect thing here is the post-install banner which is generated by `build_module.sh`: https://hg.nginx.org/pkg-oss/file/tip/build_module.sh#l334 (lines 334+).

Both `ngx_http_brotli_static_module.so` and `ngx_http_brotli_filter_module.so` are generated just fine and should be used instead of `ngx_brotli.so`.

I guess this happens because brotli module is actually two modules packaged in one repo.

**Comment by Bisstocuz** [comment]
Hi, @thresheek !

Excuse me, I have another one question.

How to prevent `ngx_brotli.so` from generating, it wastes disk space.

**Comment by thresheek** [comment]
Hi @Bisstocuz. It's not currently possible with`build_module.sh`.  I suggest using the contrib's target of `make module-brotli` for a cleaner build.
