### ISSUE TITLE
Process environment variables in included files

### ISSUE THREAD

**Issue by Cyanat** [nginxinc/docker-nginx#718]
Hello,
I'm using these two conf files to declare servers listening on port 80 and 443:

nginx.conf
```
server {
    server_name ...;
    listen 80 default;
    [...]
    include app/locations.conf;
}
```

nginx-ssl.conf
```
server {
    server_name ...;
    listen 443 ssl;
    [...]
    include app/locations.conf;
}
```
Because my locations are the same for both servers, as you can see I have exported them in file `app/locations.conf`.
(Note: locations can be accessed either in http or https, except some of them which are redirected to https, that's why I use two server).

Problem, with this configuration, environment variables are not processed in file locations.conf.
If I store my locations in `templates/locations.conf.template`, output file goes to `/etc/nginx/conf.d/locations.conf`, and so is directly read by nginx, so raising error because my locations are not expected outside of a server context.

What would be the best solution here?
I was thinking to use NGINX_ENVSUBST_OUTPUT_DIR to store processed configuration outside `conf.d`, then store a script in `/docker-entrypoint.d/` to move only `nginx.conf` and `nginx-ssl.conf` in conf.d... But maybe is there an easier way to do that?

**Comment by thresheek** [comment]
Hi @Cyanat!

That'll work. 

You can also have something like `99-move-stuff-in-place.sh` (make sure it to be last to be executed) to move `location.conf` to an appropriate location out of template dir.

**Comment by Cyanat** [comment]
Thanks for you response @thresheek,

I was thinking, maybe I could store my locations in `app/locations.conf` and replace all environment variables by variable inluded with the ngx_http_rewrite_module.
In that cast my nginx.conf would look like that:
```
server {
    server_name ...;
    listen 80 default;
    [...]
    set $subnet_admin ${SUBNET_ADMIN};
    include app/locations.conf;
}
```
However, it seems my variable $subnet_admin isn't traduced in the following location, and so, raised as an `invalid parameter "$subnet_admin"`:
```
location /admin {
    allow $subnet_admin;
    deny all;
    try_files $uri /index.php$is_args$args;
}
```
It seems variable defined in nginx.conf have no effect in the included file locations.conf... Does nginx allow a way to do that?
If not, then I will switch to you the solution you propose.

**Comment by thresheek** [comment]
The problem with that approach is you can not just use variables anywhere in the nginx configuration, but only in specific directives where it's explicitely documented.

**Comment by Cyanat** [comment]
Ok, in that case I will use, as you propose, a script `99-move-stuff-in-place.sh`, seems to be the best option here.
Many thank for your help!
