### ISSUE TITLE
[Question] How to add ModSecurity-nginx module

### ISSUE THREAD

**Issue by InoryS** [nginxinc/docker-nginx#726]
I have written a similar command as described in https://github.com/nginxinc/docker-nginx/blob/master/modules/README.md

`buildctl build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --opt build-arg:ENABLED_MODULES="brotli ndk lua modsecurity modsecurity-nginx" --output type=oci,name=nginx:v1,dest=nginx_v1.tar`

But i got this error :
```
#0 314.7 >>> nginx-module-modsecurity-dbg: Create nginx-module-modsecurity-dbg-1.23.2.1.0.3-r2.apk
#0 314.7 >>> nginx-module-modsecurity: Tracing dependencies...
#0 314.7        nginx-r1.23.2
#0 314.7        /bin/sh
#0 314.7        so:libc.musl-x86_64.so.1
#0 314.7        so:libcurl.so.4
#0 314.7        so:libgcc_s.so.1
#0 314.7        so:libpcre.so.1
#0 314.7        so:libstdc++.so.6
#0 314.7        so:libxml2.so.2
#0 314.7        so:libyajl.so.2
#0 314.7 >>> nginx-module-modsecurity: Package size: 1.9 MB
#0 314.7 >>> nginx-module-modsecurity: Compressing data...
#0 315.0 >>> nginx-module-modsecurity: Create checksum...
#0 315.0 >>> nginx-module-modsecurity: Create nginx-module-modsecurity-1.23.2.1.0.3-r2.apk
#0 315.0 real 73.56
#0 315.0 user 626.66
#0 315.0 sys 57.89
#0 315.0 renamed '/root/packages/alpine/x86_64/nginx-module-modsecurity-dbg-1.23.2.1.0.3-r2.apk' -> '/tmp/packages/nginx-module-modsecurity-dbg-1.23.2.1.0.3-r2.apk'
#0 315.0 renamed '/root/packages/alpine/x86_64/nginx-module-modsecurity-1.23.2.1.0.3-r2.apk' -> '/tmp/packages/nginx-module-modsecurity-1.23.2.1.0.3-r2.apk'
#0 315.0 Building modsecurity-nginx for nginx-1.23.2
#0 315.1 Don't know how to build modsecurity-nginx module, exiting
```

Full log here (github complains about being too long) : https://paste.gg/p/anonymous/4dbc0b33b872437894065f4be1530cf3

**Comment by thresheek** [comment]
Hi @InoryS, you should just use "modsecurity", as "modsecurity-nginx" is a library dependancy of modsecurity module, and will be automatically pulled into the build.

**Comment by InoryS** [comment]
> Hi @InoryS, you should just use "modsecurity", as "modsecurity-nginx" is a library dependancy of modsecurity module, and will be automatically pulled into the build.

Thank you for your reply, it would be better if there is an explanation somewhere.

**Comment by thresheek** [comment]
It is documented in https://github.com/nginxinc/docker-nginx/blob/master/modules/README.md#usage - right under the "As of the time of writing this README, the following modules and their versions are available from pkg-oss repository:" phrase.
