### ISSUE TITLE
nginx:alpine is unsigned

### ISSUE THREAD

**Issue by leromarinvit** [nginxinc/docker-nginx#73]
The Debian-based variant of the nginx image is signed and can be used with docker content trust enabled. The Alpine-based image is unsigned and can only be used with content trust disabled. Please consider signing nginx:alpine as well, since signed images are much better suited for production servers.

**Comment by yosifkit** [comment]
Thanks for reporting.  Docker Inc are the ones controlling the signing of images.  cc @toli

**Comment by toli** [comment]
apologies for the delay - `nginx:alpine` has been signed

**Comment by leromarinvit** [comment]
Thanks for taking care of this so quickly!

I must have misunderstood the concept of signed images - I thought the idea was to remove the implied trust from the middle man, so you could be sure the image you downloaded wasn't tampered with after the original author created it.
