### ISSUE TITLE
segment fault from alpine:latest

### ISSUE THREAD

**Issue by bklooste** [nginxinc/docker-nginx#732]
Rebuild our master which was working fine and its giving segment faults started 3 days ago, anyone else seent this ?   Reverted to .2 and its fine

load_module modules/ngx_http_js_module.so;

http {
    gzip on;
    gzip_min_length 128;
    gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css application/json  application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;
    include mime.types;
    default_type  application/octet-stream;
    js_import oauth.js; # Location of JavaScript code

    server {

        listen 80;
        add_header Cache-Control no-cache;
        access_log /dev/stdout;
        error_log /dev/stdout debug;
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;

        location /policybuy/ {
          include cors_support;
          auth_request /authcheck;
          auth_request_set $scopes $sent_http_token_scopes;
          auth_request_set $name $sent_http_token_name;
          auth_request_set $email $sent_http_token_email;
          proxy_pass https://dev-viewservice-policybuy.api.au.npd.bizcover.io/;
          proxy_set_header scopes $scopes;  
          proxy_set_header name $name;  
          proxy_set_header email $email;  
          proxy_set_header auth-claim-scopes $scopes;  
          proxy_set_header auth-claim-name $name;  
          proxy_set_header auth-claim-email $email;  
          proxy_http_version 1.1;
          proxy_set_header "Connection" "";          
        }

**Comment by thresheek** [comment]
Hi @bklooste !

Can you provide more details on how to trigger the issue?

**Comment by thresheek** [comment]
Closing due to feedback timeout.
