### ISSUE TITLE
Unable to build the lua module with Nginx

### ISSUE THREAD

**Issue by AndreyPnm** [nginxinc/docker-nginx#737]
Trying to build nginx with lua module according to the instruction

`docker build --build-arg ENABLED_MODULES="lua" -t nginx_lua:latest .`

But the process fails with such error:

`The following packages have unmet dependencies:
 nginx-module-lua : Depends: nginx-module-ndk-r1.23.3 but it is not installable
E: Unable to correct problems, you have held broken packages.`

Tried to change nginx base image from mainline to 1.23.1 but the error doesn't dissapear

<img width="1728" alt="Screenshot 2022-12-27 at 17 19 59" src="https://user-images.githubusercontent.com/48521033/209680006-7477f5d2-f648-43e2-86c6-d30db394f7a7.png">

**Comment by thresheek** [comment]
Hi @AndreyPnm, you'll need to specify dependencies manually, so e.g. for lua it would be `ENABLED_MODULES="ndk lua"`

**Comment by AndreyPnm** [comment]
Many thanks. Now it works
