### ISSUE TITLE
Files not created in bind mount volume

### ISSUE THREAD

**Issue by MatsG23** [nginxinc/docker-nginx#741]
I try to use the nginx docker image (with Alpine Linux) with a bind mounted directory outside of the container. But the initial creation of the config files seem to fail. The directory is currently empty, the podman user has the permissions to it. There are no issues in the log without bind mounting /etc/nginx.

```
$ podman run --name=nginx-server --volume=/opt/nginx/configs:/etc/nginx:Z docker.io/library/nginx:mainline-alpine

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/01/11 11:03:34 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
```

**Comment by thresheek** [comment]
Hi @MatsG23, you should check with podman why this happens. It's outside of scope for this image.

**Comment by rw-django-fan-2020** [comment]
I experienced the same problem. Is this nginx docker specific issue?

**Comment by thresheek** [comment]
Hi @rw-django-fan-2020, it's probably your runtime-specific, e.g. podman or a similar tool.

There is no control over mounts or anything external in the images.
