### ISSUE TITLE
How to automatically generate a certificate when nginx reloads

### ISSUE THREAD

**Issue by laopaoer-wallet** [nginxinc/docker-nginx#755]
How to automatically generate a certificate when nginx reloads

**Comment by thresheek** [comment]
Hi @laopaoer-wallet.

nginx does not support generating a TLS certificate, you'd need to use some other tooling to achieve that.

Typically with LetsEncrypt people seem to utilize certbot or similar: https://mindsers.blog/post/https-using-nginx-certbot-docker/
