### ISSUE TITLE
Mounted volume is hiding the directories

### ISSUE THREAD

**Issue by GhaziTriki** [nginxinc/docker-nginx#759]
Hello I am adding the following volume with the custom built image but as the screenshot shows the directories for `location /` are never shown.

https://github.com/riadvice/hivelvet/blob/develop/docker-compose.yml

![image](https://user-images.githubusercontent.com/4991088/223562123-6de0d29d-bbd9-40a7-88a0-4cdc878cfacd.png)

**Comment by GhaziTriki** [comment]
I fixed the issue. Is it a convention to mount sites code on `/var/www/html`?

**Comment by thresheek** [comment]
Hi @GhaziTriki,

The default directory to host static content is `/usr/share/nginx/html`.
