### ISSUE TITLE
Volumes `-v` seemingly not working

### ISSUE THREAD

**Issue by OAguinagalde** [nginxinc/docker-nginx#762]
This command, pretty much taken from the `ngingx` docker readme file at https://hub.docker.com/_/nginx, is not working as expected:

```powershell
docker run --name container -v nginx.conf:/etc/nginx/:ro -v files:/usr/share/nginx/html/:ro -p 80:80 -d nginx
```

I expect it to...
* use the local `nginx.conf` instead of the default one, and...
* put the host's folder `files` with its contents (only one file `clientInfo.json`) in the container's `/usr/share/nginx/html/` folder.

But it does none of those. No error is shown (full log down below).

Further testing with the `-v` flag, it seems to behave in very bizarre ways. Take this for example.

```powershell
PS C:\Users\user\git_projects\nginx> ls .\files\
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        13/03/2023     16:32             18 clientInfo.json

PS C:\Users\user\git_projects\nginx> docker run --name container -v files:/test -d nginx
eb80defccfff78e8f2ab9521307c80fb088f21d1b33fea67a64ff09972f9b3d5

PS C:\Users\user\git_projects\nginx> docker exec container ls /test
50x.html
index.html
```

I'm asking docker to mount a folder which contains a json file, and instead its randomly creating some html files. What is going on here, what am I missing?

-----------------------------

Here is the full log showing all the files and the unexpected outcome:
```powershell
PS C:\Users\user\git_projects\nginx> docker run --name container -v nginx.conf:/etc/nginx/:ro -v files:/usr/share/nginx/html/:ro -p 80:80 -d nginx

PS C:\Users\user\git_projects\nginx> docker exec container cat /etc/nginx/nginx.conf

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

PS C:\Users\user\git_projects\nginx> cat .\nginx.conf
server {
        location / {
                root /files;
    }
}

PS C:\Users\user\git_projects\nginx> ls files
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        13/03/2023     16:32             18 clientInfo.json

PS C:\Users\user\git_projects\nginx> docker exec container ls /usr/share/nginx/html/
50x.html
index.html
```

**Comment by thresheek** [comment]
Does it work if you use full path to specify volume source?

**Comment by yosifkit** [comment]
Those need to be absolute paths and if it is a file on the left, then it must be a file on the right (not a folder to put it in):

(`$PWD` should give you the current directory, even in powershell)
```powershell
-v $PWD/nginx.conf:/etc/nginx/nginx.conf:ro -v $PWD/files/:/usr/share/nginx/html/:ro
```

By not using a full path, docker is treating them as a named volume (and so creating a volume for the name). You can see them with `docker volume ls` (and delete with `docker volume rm [name]`).

**Comment by OAguinagalde** [comment]
You are both right, it works now.

For reference if someone ends up here, this works:
```powershell
> cd some/path # The path with where the file `nginx.conf` and the folder `files` is
> docker run --name container -v $pwd/nginx.conf:/etc/nginx/nginx.conf:ro -v $pwd/files:/usr/share/nginx/html/files/:ro -p 80:80 -d nginx
```

I'll be closing this then, thanks for the help!
