### ISSUE TITLE
How to disable all possible control characters (0x00 – 0x1f, 0x7f) in the URL path in nginx.conf?

### ISSUE THREAD

**Issue by jing-tyagi** [nginxinc/docker-nginx#763]
I'm using nginx:1.23.3-alpine-slim,  and trying to disable all possible control characters (0x00 – 0x1f, 0x7f) in the URL path.

I tried add the following in the nginx.conf file, it works with * and ~.  It's really hard to while list all the special control characters.  Could you please help with this?

this works,
 if ($request_uri ~ ^(/.*)([\^]|[\~])(.*)$) {
    return 435;
  }

these don't work,

   if ($request_uri ~* ^(/.*)([\x09] (.*)$) {
     return 435;
  }

   if ($request_uri ~* ^(/.*)([\x00-\0x1f] (.*)$) {
     return 435;
  }

   if ($request_uri ~* ^(/.*)([0x00-0x1f] | [0x7f])(.*)$) {
     return 435;
  }

Thanks for your time and help!

Jing

**Comment by thresheek** [comment]
Hi @jing-tyagi.

This is a issue tracker for docker nginx images and not nginx in general.  I suggest you ask for help in the nginx users mailing list instead: https://mailman.nginx.org/mailman/listinfo/nginx
