### ISSUE TITLE
alpine - libjpeg-turbo 2.1.4-r0 - possible denial of service

### ISSUE THREAD

**Issue by falk-atos** [nginxinc/docker-nginx#764]
Any chance we can get a new alpine image (https://registry.hub.docker.com/layers/library/nginx/alpine/images/sha256-3eb380b81387e9f2a49cb6e5e18db016e33d62c37ea0e9be2339e9f0b3e26170?context=explore) with https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.1.5 ? 

In the current version we have a bug which might allow a denial of service: https://github.com/libjpeg-turbo/libjpeg-turbo/issues/633

**Comment by yosifkit** [comment]
There is no newer package available in Alpine 3.17 than [2.1.4-r0	](https://pkgs.alpinelinux.org/packages?name=libjpeg-turbo&branch=v3.17). So even a rebuild wouldn't change anything.

**Comment by falk-atos** [comment]
@yosifkit sorry for me maybe not understanding but I get the following output on

```
~ sudo docker run -it alpine:3.17 apk list  

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/community: No such file or directory
musl-1.2.3-r4 x86_64 {musl} (MIT) [installed]
zlib-1.2.13-r0 x86_64 {zlib} (Zlib) [installed]
apk-tools-2.12.10-r1 x86_64 {apk-tools} (GPL-2.0-only) [installed]
busybox-binsh-1.35.0-r29 x86_64 {busybox} (GPL-2.0-only) [installed]
musl-utils-1.2.3-r4 x86_64 {musl} (MIT AND BSD-2-Clause AND GPL-2.0-or-later) [installed]
alpine-baselayout-3.4.0-r0 x86_64 {alpine-baselayout} (GPL-2.0-only) [installed]
alpine-keys-2.4-r1 x86_64 {alpine-keys} (MIT) [installed]
libcrypto3-3.0.8-r0 x86_64 {openssl} (Apache-2.0) [installed]
busybox-1.35.0-r29 x86_64 {busybox} (GPL-2.0-only) [installed]
scanelf-1.3.5-r1 x86_64 {pax-utils} (GPL-2.0-only) [installed]
ca-certificates-bundle-20220614-r4 x86_64 {ca-certificates} (MPL-2.0 AND MIT) [installed]
libc-utils-0.7.2-r3 x86_64 {libc-dev} (BSD-2-Clause AND BSD-3-Clause) [installed]
ssl_client-1.35.0-r29 x86_64 {busybox} (GPL-2.0-only) [installed]
alpine-baselayout-data-3.4.0-r0 x86_64 {alpine-baselayout} (GPL-2.0-only) [installed]
libssl3-3.0.8-r0 x86_64 {openssl} (Apache-2.0) [installed]
```

while nginx gives me:
```
~ sudo docker run -it nginx:1.23.3-alpine -- apk list

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/community: No such file or directory
nginx-1.23.3-r1 x86_64 {nginx} (2-clause BSD-like license) [installed]
nginx-module-xslt-1.23.3-r1 x86_64 {nginx-module-xslt} (2-clause BSD-like license) [installed]
libxext-1.3.5-r0 x86_64 {libxext} (MIT) [installed]
....
libjpeg-turbo-2.1.4-r0 x86_64 {libjpeg-turbo} (BSD-3-Clause AND IJG AND Zlib) [installed]
...
tiff-4.4.0-r1 x86_64 {tiff} (libtiff) [installed]
pcre2-10.42-r0 x86_64 {pcre2} (BSD-3-Clause) [installed]
libdav1d-1.0.0-r2 x86_64 {dav1d} (BSD-2-Clause) [installed]
```

So I assumed "libjpeg-turbo" was introduced during your build process.

**Comment by yosifkit** [comment]
Yes, the `libjpeg-turbo` package is installed during the `nginx:1.23-alpine` build but it is as up to date as is available in Alpine's packages (`apk`).

There are other package updates available, but no updates for `libjpeg-turbo`:
```console
$ docker run -it --rm nginx:1.23.4-alpine sh
Unable to find image 'nginx:1.23.4-alpine' locally
1.23.4-alpine: Pulling from library/nginx
63b65145d645: Already exists
51f129e7c3f1: Pull complete
f32490ce40c5: Pull complete
d18f1b67600c: Pull complete
b793aaf052d0: Pull complete
10b0102e5979: Pull complete
ec50f2776186: Pull complete
Digest: sha256:ff07dba791a114f5d944c8455e8236ca4b184bfd8d21d90b7755a4ba0a119b06
Status: Downloaded newer image for nginx:1.23.4-alpine
/ # apk upgrade --no-cache
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/2) Upgrading libcrypto3 (3.0.8-r0 -> 3.0.8-r2)
(2/2) Upgrading libssl3 (3.0.8-r0 -> 3.0.8-r2)
Executing ca-certificates-20220614-r4.trigger
OK: 43 MiB in 62 packages
/ #
```

The other packages will be automatically updated the next time the `alpine` image is updated or at the next `nginx` version bump. If you need updates earlier, you could just `apk upgrade --no-cache` in a new image.

---

Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link
