### ISSUE TITLE
NGINX 1.24 Alpine Docker image not able to be built, SHA mismatch from https://nginx.org/keys/nginx_signing.rsa.pub

### ISSUE THREAD

**Issue by isuftin** [nginxinc/docker-nginx#769]
https://github.com/nginxinc/docker-nginx/blob/1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c/stable/alpine-slim/Dockerfile#L28-L29

The pub key coming from https://nginx.org/keys/nginx_signing.rsa.pub is `e7fa8303923d9b95db37a77ad46c68fd4755ff935d0a534d26eba83de193c76166c68bfe7f65471bf8881004ef4aa6df3e34689c305662750c0172fca5d8552a` not `e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655`, so trying to build this image fails.

**Comment by isuftin** [comment]
```sh
❯ wget https://nginx.org/keys/nginx_signing.rsa.pub
--2023-04-17 11:26:15--  https://nginx.org/keys/nginx_signing.rsa.pub
Resolving nginx.org (nginx.org)... 52.58.199.22, 3.125.197.172
Connecting to nginx.org (nginx.org)|52.58.199.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 451 [application/octet-stream]
Saving to: ‘nginx_signing.rsa.pub’

nginx_signing.rsa.pub                                                                                      100%[=====================================================================================================================================================================================================================================================================================>]     451  --.-KB/s    in 0s

2023-04-17 11:26:16 (53.8 MB/s) - ‘nginx_signing.rsa.pub’ saved [451/451]

❯ openssl rsa -pubin -in nginx_signing.rsa.pub -text -noout | openssl sha512 -r
e7fa8303923d9b95db37a77ad46c68fd4755ff935d0a534d26eba83de193c76166c68bfe7f65471bf8881004ef4aa6df3e34689c305662750c0172fca5d8552a *stdin
```

**Comment by thresheek** [comment]
Hi @isuftin!

I'm not sure where the openssl rsa command is coming from in your tests since we've moved to a different method in https://github.com/nginxinc/docker-nginx/commit/f27368329ff9f02b9973bc3a23d7a643e2485d7d

And as far as I see it reports with a proper checksum.
