### ISSUE TITLE
mainline-alpine size increased

### ISSUE THREAD

**Issue by wernight** [nginxinc/docker-nginx#77]
I found that `nginx:stable-alpine` is only 15 MB (as expected) but `nginx:mainline-alpine` is 60 MB. It looks as if something was left that should be removed.

    $ docker pull nginx:mainline-alpine
    $ docker images nginx:mainline-alpine
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    nginx               mainline-alpine     25ea644a8c4c        3 days ago          60.61 MB

**Comment by thresheek** [comment]
No, there were numerous changes to the image since 1.9.12, please see the changelog.

**Comment by wernight** [comment]
OK. That's a huge leap. Well if nothing can be done about it... :)
