### ISSUE TITLE
Allow even more advanced template configuration

### ISSUE THREAD

**Issue by LeviPesin** [nginxinc/docker-nginx#770]
I suggest to allow in templates some kind of conditional (also based on environment variables) execution and loops.

My use-case: I develop a NGINX-based proxy that among other parameters (in environment variables) takes in a list of websocket URLs and a list of backends to which it should proxy them. Allowing to write something like `#for (($url, $backend) in ($URLS.split(), $BACKENDS.split())) {location $url {include websocket.conf; proxy_pass $backend}}` will be extremely useful.

**Comment by thresheek** [comment]
I think that's reinventing a proper templating system and templating language with it, but poorly.  There are tools to generate complex configuration and frankly, I don't think we need to reinvent them just for nginx.

**Comment by LeviPesin** [comment]
> There are tools to generate complex configuration and frankly, I don't think we need to reinvent them just for nginx.

Can you suggest some? Or maybe an entrypoint script could be added to run one on the configuration.

**Comment by LeviPesin** [comment]
So I tried to use them and I think they are just too bloated for this relatively simple task...
I did some search and found [an unmaintained repo](https://github.com/saghul/njk) and [this StackOverflow question](https://stackoverflow.com/questions/7491352/looking-for-a-standalone-command-line-code-generator-script)... From them I think I will use [gomplate](https://docs.gomplate.ca/).
