### ISSUE TITLE
Error relocating /usr/sbin/nginx: SSL_CTX_set_options: symbol not foun

### ISSUE THREAD

**Issue by jastlw** [nginxinc/docker-nginx#771]
Hello folks,
I am stuck in the same problem. Do you have any idea what I can do?

I use NGINX_VERSION=1.24 on Docker CE 23.0.4 (API: 1.42) and this on linux x86_64 AlmaLinux 9.1 (Lime Lynx).

`Error relocating /usr/sbin/nginx: SSL_CTX_set_options: symbol not found
Error relocating /usr/sbin/nginx: BIO_new_file: symbol not found
Error relocating /usr/sbin/nginx: X509_check_issued: symbol not found
Error relocating /usr/sbin/nginx: BIO_s_mem: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_error: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_ex_data: symbol not found
Error relocating /usr/sbin/nginx: X509_digest: symbol not found
Error relocating /usr/sbin/nginx: OCSP_BASICRESP_free: symbol not found
Error relocating /usr/sbin/nginx: EVP_DigestUpdate: symbol not found
Error relocating /usr/sbin/nginx: SSL_set_options: symbol not found
Error relocating /usr/sbin/nginx: X509_verify_cert_error_string: symbol not found
Error relocating /usr/sbin/nginx: ASN1_d2i_bio: symbol not found
Error relocating /usr/sbin/nginx: X509_set_ex_data: symbol not found
Error relocating /usr/sbin/nginx: d2i_SSL_SESSION: symbol not found
Error relocating /usr/sbin/nginx: ERR_peek_last_error: symbol not found
Error relocating /usr/sbin/nginx: SSL_CIPHER_find: symbol not found
Error relocating /usr/sbin/nginx: X509_STORE_set_flags: symbol not found
Error relocating /usr/sbin/nginx: SSL_session_reused: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_new: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_wbio: symbol not found
Error relocating /usr/sbin/nginx: HMAC_Init_ex: symbol not found
Error relocating /usr/sbin/nginx: X509_get_subject_name: symbol not found
Error relocating /usr/sbin/nginx: OCSP_response_status_str: symbol not found
Error relocating /usr/sbin/nginx: ERR_peek_error_data: symbol not found
Error relocating /usr/sbin/nginx: PEM_read_bio_DHparams: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_sess_set_get_cb: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_verify_result: symbol not found
Error relocating /usr/sbin/nginx: EVP_MD_CTX_free: symbol not found
Error relocating /usr/sbin/nginx: SSL_set_verify_depth: symbol not found
Error relocating /usr/sbin/nginx: ENGINE_free: symbol not found
Error relocating /usr/sbin/nginx: X509_NAME_digest: symbol not found
Error relocating /usr/sbin/nginx: ERR_peek_error: symbol not found
Error relocating /usr/sbin/nginx: SSL_get0_alpn_selected: symbol not found
Error relocating /usr/sbin/nginx: PEM_read_bio_PrivateKey: symbol not found
Error relocating /usr/sbin/nginx: X509_STORE_add_lookup: symbol not found
Error relocating /usr/sbin/nginx: SSL_sendfile: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_get_cert_store: symbol not found
Error relocating /usr/sbin/nginx: ASN1_TIME_print: symbol not found
Error relocating /usr/sbin/nginx: RAND_bytes: symbol not found
Error relocating /usr/sbin/nginx: SSL_write: symbol not found
Error relocating /usr/sbin/nginx: SSL_CIPHER_get_name: symbol not found
Error relocating /usr/sbin/nginx: SSL_version: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_session: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_load_verify_locations: symbol not found
Error relocating /usr/sbin/nginx: X509_NAME_oneline: symbol not found
Error relocating /usr/sbin/nginx: EVP_DecryptInit_ex: symbol not found
Error relocating /usr/sbin/nginx: OCSP_REQUEST_free: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_set_alpn_protos: symbol not found
Error relocating /usr/sbin/nginx: ERR_clear_error: symbol not found
Error relocating /usr/sbin/nginx: X509_get_issuer_name: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_get_client_CA_list: symbol not found
Error relocating /usr/sbin/nginx: EVP_aes_256_cbc: symbol not found
Error relocating /usr/sbin/nginx: X509_LOOKUP_ctrl: symbol not found
Error relocating /usr/sbin/nginx: X509_get0_notAfter: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_callback_ctrl: symbol not found
Error relocating /usr/sbin/nginx: OCSP_check_validity: symbol not found
Error relocating /usr/sbin/nginx: OCSP_CERTID_free: symbol not found
Error relocating /usr/sbin/nginx: SSL_CONF_CTX_free: symbol not found
Error relocating /usr/sbin/nginx: OCSP_RESPONSE_free: symbol not found
Error relocating /usr/sbin/nginx: EVP_DigestInit_ex: symbol not found
Error relocating /usr/sbin/nginx: OCSP_REQUEST_new: symbol not found
Error relocating /usr/sbin/nginx: X509_chain_up_ref: symbol not found
Error relocating /usr/sbin/nginx: SSL_CONF_CTX_set_ssl_ctx: symbol not found
Error relocating /usr/sbin/nginx: SSL_read: symbol not found
Error relocating /usr/sbin/nginx: PEM_read_bio_X509_AUX: symbol not found
Error relocating /usr/sbin/nginx: BIO_int_ctrl: symbol not found
Error relocating /usr/sbin/nginx: X509_STORE_CTX_free: symbol not found
Error relocating /usr/sbin/nginx: BIO_free: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_certificate: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_peer_cert_chain: symbol not found
Error relocating /usr/sbin/nginx: X509_STORE_CTX_get1_chain: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_version: symbol not found
Error relocating /usr/sbin/nginx: BIO_ctrl: symbol not found
Error relocating /usr/sbin/nginx: OPENSSL_sk_push: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_set_client_CA_list: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_clear_options: symbol not found
Error relocating /usr/sbin/nginx: SSL_in_init: symbol not found
Error relocating /usr/sbin/nginx: ENGINE_load_private_key: symbol not found
Error relocating /usr/sbin/nginx: EVP_EncryptInit_ex: symbol not found
Error relocating /usr/sbin/nginx: X509_verify_cert: symbol not found
Error relocating /usr/sbin/nginx: SSL_get1_session: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_ctrl: symbol not found
Error relocating /usr/sbin/nginx: SSL_set_ex_data: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_set_alpn_select_cb: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_sess_set_new_cb: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_get_timeout: symbol not found
Error relocating /usr/sbin/nginx: EVP_DigestFinal_ex: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_options: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_get_ex_data: symbol not found
Error relocating /usr/sbin/nginx: ERR_get_error: symbol not found
Error relocating /usr/sbin/nginx: SSL_CTX_get_verify_depth: symbol not found
Error relocating /usr/sbin/nginx: SSL_get0_verified_chain: symbol not found
Error relocating /usr/sbin/nginx: SSL_get_current_cipher: symbol not found
Error relocating /usr/sbin/nginx: ENGINE_by_id: symbol not found
Error relocating /usr/sbin/nginx: SSL_load_client_CA_file: symbol not found
Error relocating /usr/sbin/nginx: PEM_read_bio_X509: symbol not found
Error relocating /usr/sbin/nginx: OCSP_cert_status_str: symbol not found
Error relocating /usr/sbin/nginx: OCSP_RESPONSE_new: symbol not found
Error relocating /usr/sbin/nginx: d2i_OCSP_RESPONSE: symbol not found
Error relocating /usr/sbin/nginx: X509_free: symbol not found`

Thank you a lot!

_Originally posted by @jastlw in https://github.com/nginxinc/docker-nginx/issues/506#issuecomment-1519067930_

**Comment by thresheek** [comment]
Hi @jastlw

Which nginx image is that?

What is the output of `docker version`?

**Comment by jastlw** [comment]
Hi @thresheek!

I am using `nginx:1.24-alpine` as base and the output is
`$ docker version
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:34:35 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:31:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`


My Dockerfile looks like that:
`# -------------- Build-time variables --------------
ARG PHP_VERSION=7.4
ARG NGINX_VERSION=1.24


ARG ALPINE_VERSION=3.15
ARG HARDENED_MALLOC_VERSION=11
ARG SNUFFLEUPAGUS_VERSION=0.8.3

ARG UID=1000
ARG GID=1000
# ---------------------------------------------------

### Build PHP base
FROM php:${PHP_VERSION}-fpm-alpine${ALPINE_VERSION} as base

ARG SNUFFLEUPAGUS_VERSION

RUN apk -U upgrade \
 && apk add -t build-deps \
        $PHPIZE_DEPS \
        freetype-dev \
        git \
        gmp-dev \
        icu-dev \
        libjpeg-turbo-dev \
        libpng-dev \
        libwebp-dev \
        libzip-dev \
        zlib-dev \
 && apk --no-cache add \
        freetype \
        gmp \
        icu \
        libjpeg-turbo \
        libpq \
        libpq \
        libwebp \
        libzip \
        zlib \
 && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
 && docker-php-ext-install -j "$(nproc)" \
        exif \
        gd \
        intl \
        opcache \
        mysqli \
        zip \
        calendar \
 && pecl install APCu \
 && pecl install redis \
 && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini \
 && cd /tmp && git clone --depth 1 --branch v${SNUFFLEUPAGUS_VERSION} https://github.com/jvoisin/snuffleupagus \
 && cd snuffleupagus/src && phpize && ./configure --enable-snuffleupagus && make && make install \
 && apk del build-deps \ 
 && rm -rf /var/cache/apk/* /tmp/*

### Build Hardened Malloc
ARG ALPINE_VERSION
FROM alpine:${ALPINE_VERSION} as build-malloc

ARG HARDENED_MALLOC_VERSION
ARG CONFIG_NATIVE=false
ARG VARIANT=light

RUN apk --no-cache add build-base git gnupg && cd /tmp \
 && wget -q https://github.com/thestinger.gpg && gpg --import thestinger.gpg \
 && git clone --depth 1 --branch ${HARDENED_MALLOC_VERSION} https://github.com/GrapheneOS/hardened_malloc \
 && cd hardened_malloc && git verify-tag $(git describe --tags) \
 && make CONFIG_NATIVE=${CONFIG_NATIVE} VARIANT=${VARIANT}


### Fetch Source from SVN
FROM alpine:${ALPINE_VERSION} as source


RUN apk --no-cache add subversion curl
WORKDIR /tmp
# [...]

### Fetch nginx
FROM nginx:${NGINX_VERSION}-alpine as nginx

### Build imagename (production environemnt)
FROM base as imagename

COPY --from=nginx /usr/sbin/nginx /usr/sbin/nginx
COPY --from=nginx /etc/nginx /etc/nginx
COPY --from=build-malloc /tmp/hardened_malloc/out-light/libhardened_malloc-light.so /usr/local/lib/


ARG UID
ARG GID

# [...]
    PHP_HARDENING=false \
    LD_PRELOAD="/usr/local/lib/libhardened_malloc-light.so /usr/lib/preloadable_libiconv.so"

RUN mkdir /imagename
COPY --from=source /tmp/imagename

RUN apk --no-cache add \
        gnupg \
        pcre2 \
        s6 \
        coreutils \
        mariadb-client \
 && adduser -g ${GID} -u ${UID} --disabled-password --gecos "" imagename \
 && chown -R imagename:imagename /imagename

COPY --chown=imagename:imagename rootfs /

RUN chmod +x /usr/local/bin/* /etc/s6.d/*/* /etc/s6.d/.s6-svscan/*

USER imagename

WORKDIR /imagename

VOLUME /imagename`

I would be really grateful if you could give me a little hint on how to solve the problem. Thx a lot!

**Comment by thresheek** [comment]
I would suggest copying all nginx dependencies and not only one binary and configuration.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
