### ISSUE TITLE
envsubst is skipped if using a custom command

### ISSUE THREAD

**Issue by leonidumanskiy** [nginxinc/docker-nginx#784]
It appears that the environment variable substitution does not work if using custom command that does not start with "nginx". 

For instance, if someone was to modify command and do something like `/bin/sh -c 'something & nginx -g \"daemon off;\"'` the environment variable substitution does not work.

Not sure why it is required to [check](https://github.com/nginxinc/docker-nginx/blob/73a5acae6945b75b433cafd0c9318e4378e72cbb/mainline/debian/docker-entrypoint.sh#LL12C52-L12C52) if first argument is nginx or not.

**Comment by thresheek** [comment]
Hi @leonidumanskiy,

See https://github.com/nginxinc/docker-nginx/pull/752 for explanation.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
