### ISSUE TITLE
Failed to get public gpg key

### ISSUE THREAD

**Issue by sri85** [nginxinc/docker-nginx#79]
`RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 \` fails to retrieve the key 

This code seems to be failing ,is there any other alternate key servers which i could use

**Comment by thresheek** [comment]
Try hkps://hkps.pool.sks-keyservers.net.

**Comment by sri85** [comment]
I see this error now @thresheek with the code `apt-key adv --keyserver hkps://hkps.pool.sks-keyservers.net`

I see the following error `gpgkeys: HTTP fetch error 1: unsupported protocol`

**Comment by sri85** [comment]
Seems the server is up and running again . 
Cheers
