### ISSUE TITLE
SMTP proxy

### ISSUE THREAD

**Issue by jastlw** [nginxinc/docker-nginx#795]
Hi!

on the nginx page it says:
_Nginx (pronounced "engine-x") is an open source reverse proxy server for HTTP, HTTPS, **SMTP**, POP3, and IMAP protocols, as well as a load balancer, HTTP cache, and a web server (origin server)._

But I can not find any other information on https://registry.hub.docker.com/_/nginx/ or in the docs regarding proxing smtp.

**Is it even possible to do that with your docker image?** 
Or do I need to compile my own with the option  "--with-mail"? 
Are you planning to add a docker image which supports that?

Thank you.

Jacob

**Comment by thresheek** [comment]
Hi @jastlw 

This image is built with mail support.  You can use it as documented with https://docs.nginx.com/nginx/admin-guide/mail-proxy/mail-proxy/

Hope this helps

**Comment by jastlw** [comment]
@thresheek Yes, it helps a lot! 
Thank you. :)

**Comment by jastlw** [comment]
@thresheek Yes, it helps a lot! 
Thank you. :)
