### ISSUE TITLE
Provide a Mainline Docker Image based on bullseye

### ISSUE THREAD

**Issue by logopk** [nginxinc/docker-nginx#799]
With the minor change from 1.25.0 to 1.25.1 all my Docker builds based on bullseye are breaking.

Please provide a version 1.25-bullseye to keep efforts for other users as low as possible.

Thank you!

**Comment by maxproske** [comment]
+1

Some modules are unable to build with `nginx:mainline`. Temporarily fixed by downgrading to `nginx:1.24-bullseye`.

<img width="1169" alt="Screen Shot 2023-06-14 at 8 18 57 AM" src="https://github.com/nginxinc/docker-nginx/assets/14317828/798133b7-b2b7-417c-b9ec-bd004adb4dfc">

**Comment by thresheek** [comment]
Hello @logopk,

We will not migrate back to bullseye, let's focus on fixing issue with this image if there are any.  What is the exact problem you're seeing?

@maxproske mixing nginx-extras with this image is not supported, as this package is not something we ship via nginx.org (which this image uses).

**Comment by logopk** [comment]
I'm building modsecurity and php7.4 to the image and I need to fix versions that are no longer existing in bookworm (openssl 1.1.1 and php7.4) and dependencies - plus a full test of the ci/cd chain.

i assume that could be again a hassle if the underlying host is bullseye and dependencies like libc can get messy as it happened on the last migration from buster to bullseye.

I don't really understand why you can't maintain the 1.25.0 image on bullseye as a starting point?

Plus why be an early adopter for a brand new debian version for a key component in a lot of people's infrastructure?

My 2cts...

Peter

**Comment by thresheek** [comment]
> I'm building modsecurity and add php7.4 to the image and I need to fix versions that are no longer existing in bookworm (openssl 1.1.1 and php7.4) and dependencies - plus a full test of the ci/cd chain.

That's fine.

> i assume that could be again a hassle if the underlying host is bullseye and dependencies like libc can get messy as it happened on the last migration from buster to bullseye.
> 
> I don't really understand why you can't maintain the 1.25.0 image on bullseye as a starting point?

I assume you mean 1.25.1 image on bullseye - but to answer the question: because 1.25.0 image on bullseye is still available and can be used just fine until you fix your modsecurity / php 7.4 issues.

> Plus why be an early adopter for a brand new debian version for a key component in a lot of people's infrastructure?

It's better to fix things early.  Again, It's not that images for previous nginx releases are not usable anymore.

**Comment by omriezra** [comment]
Hi guys, any ETA for that fix?

**Comment by thresheek** [comment]
Hi @omriezra, fix for what exact problem?

**Comment by omriezra** [comment]
> Hi @omriezra, fix for what exact problem?

Hi @thresheek ,
We have the same problem since 1.25, we did resolve temporarily by going back to 1.24. The fix I'm talking about is a new release resolving the issue mentioned by @maxproske

**Comment by thresheek** [comment]
There will be no fix for issue reported by @maxproske since we don't support and never did support mixing Debian packages (nginx-extras) and nginx from this image.

**Comment by omriezra** [comment]
> There will be no fix for issue reported by @maxproske since we don't support and never did support mixing Debian packages (nginx-extras) and nginx from this image.  If you're installing nginx-extras, you shouldnt use this image, but rather write a separate Dockerfile for it.

Thanks for the answer. So a better way for me would be to create a Dockerfile based debian like alpine/ubuntu and then install the nginx and nginx-extras ?

**Comment by thresheek** [comment]
> Thanks for the answer. So a better way for me would be to create a Dockerfile based debian like alpine/ubuntu and then install the nginx and nginx-extras ?

Yes, that's correct.

**Comment by thresheek** [comment]
Closing this since we will not provide new images based on bullseye.
