### ISSUE TITLE
Under what license is the stuff in this repo available?

### ISSUE THREAD

**Issue by kajmagnus** [nginxinc/docker-nginx#80]
I'm copy-editing the Alpine Dockerfile and would like to include a copyright and license notice, so I wonder, to whom should I attribute copyright and under which license? Right now I've written "nginxinc" and "unknown open source license".

Best regards, KajMangnus

**Comment by kajmagnus** [comment]
Aha now I followed the link in the readme, and came to https://github.com/docker-library/docs, and in that repo there's a LICENSE file, MIT it seems to me, + apparently the stuff in this repo is included in docker-library, so that license file should apply. Therefore one answer to my question could be:

Copyright (c) 2014-2015 Docker, Inc.
MIT

I guess you (nginxinc) have copyright too ...

**Comment by thresheek** [comment]
Those files are available under the same License as NGINX itself, 2-clause BSD.
Copyright is NGINX Inc.
