### ISSUE TITLE
x perm missing on startup scripts on latest

### ISSUE THREAD

**Issue by juliencognito** [nginxinc/docker-nginx#803]
Hello;

It seems that the execution bit on every sh files in /docker-entrypoint.d/ is now missing on :latest (debian:12.0-slim).

```
15/06/2023 16:37:05/docker-entrypoint.sh: Ignoring /docker-entrypoint.d/20-envsubst-on-templates.sh, not executable
```

I have to admit that i'm using an deprecated rancher version (1.6)  and docker (1.12.6)
```
root@1b87e4cea72d:/# if [ -x /docker-entrypoint.d/20-envsubst-on-templates.sh ];then echo "OK"; else echo 'KO';fi
KO
```

However, on my desktop, it correctly use 0775 and the `if`  is OK inside the container.
```
root@b6f12612beb4:/# if [ -x docker-entrypoint.d/20-envsubst-on-templates.sh ];then echo "OK";fi
OK
```

Thanks for all your helpful work.

**Comment by thresheek** [comment]
Hi @juliencognito,

That's interesting to know but I don't think we can do anything to fix that.  Docker 1.12.6 is from early 2017, and I would be surprised if the image is fully functional there - see e.g. https://github.com/nginxinc/docker-nginx/issues/800 for apt update issues.

**Comment by yosifkit** [comment]
> I'd suggest updating docker and libseccomp on the host. Newer base OS's use newer system calls and an older libseccomp can block them since they are unknown to it. You can verify that it is libseccomp by running the bookworm image with `--security-opt seccomp=unconfined`.

**Comment by nikomi86** [comment]
I have the same issue with docker version  19.03.13. Also interesting that all of these files have x flag:
`-rwxrwxr-x 1 root root 3008 Jun 14 07:16 20-envsubst-on-templates.sh
`
but
`if [ -x /docker-entrypoint.d/20-envsubst-on-templates.sh ];then echo "OK"; else echo 'KO';fi
KO
`

**Comment by thresheek** [comment]
hi @nikomi86!

That's expected on older container runtimes due to failing system calls used now in the image binaries.  The only solution would be to update docker, seccomp et al.

**Comment by michal-michalak** [comment]
Updating docker version from `19` to `24` solved the problem for me.
