### ISSUE TITLE
nginx container is not working in EKS 1.25 cluster

### ISSUE THREAD

**Issue by Teju-chitara** [nginxinc/docker-nginx#806]
Hi there,

I have deployed nginx:stable in 1.25 and its failing with below error message

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.d/20-envsubst-on-templates.sh: 20: awk: not found
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/06/26 18:00:55 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)

The same container was working fine in 1.23

**Comment by thresheek** [comment]
Hi @Teju-chitara,

Which nginx image is that exactly?

How do you launch the container?  Any volume mounts or similar?

**Comment by Teju-chitara** [comment]
hi @thresheek 

Thanks for your response.

Below is the docker image and Dockerfile

### STAGE 1: Build ###
FROM node:16.14.2 AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install && npm install -g @angular/cli
COPY . .
RUN ng version && ng build --prod  && ls -lrt
RUN ls -lrt /usr/src/app/dist/


### STAGE 2: Run ###
FROM nginx:stable
ARG NPM_BUILD_VAL
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/$NPM_BUILD_VAL/* /usr/share/nginx/html/
RUN mkdir /home/nginx \
&& chown -R nginx:nginx /home/nginx \    
&& chown -R nginx:nginx /usr/share/nginx/html \	    
&& chmod -R 775 /home/nginx \
&& cat /etc/nginx/nginx.conf
ENV HOME /home/nginx
USER nginx
WORKDIR /home/nginx
EXPOSE 8080

Deployment yaml file
  name: ib-orc-tmf-order-001
spec:
  selector:
    matchLabels:
      app: tmforder
      service: dish-microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 454cad13828942cf244ecf3ba5cbb8966f9976750dfa46be8ee548d55347b15f
      creationTimestamp: null
      labels:
        app: tmforder
        service: dish-microservice
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ib-orc-tmf-order-001
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - image: 147415857303.dkr.ecr.us-east-2.amazonaws.com/dish-tmf-order-ubi:2023-06-26.15.42.29.cd561c8e
        imagePullPolicy: IfNotPresent
        name: ib-orc-tmf-order-001
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html/envapp/assets/app.config.json
          name: ib-orc-tmf-order-001-config
          subPath: app.config.json
        - mountPath: /etc/
          name: tmpfs-1
      dnsPolicy: ClusterFirst
      nodeSelector:
        name: na4d
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 101
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ib-orc-tmf-order-001-config
        name: ib-orc-tmf-order-001-config
      - emptyDir: {}
        name: tmpfs-1

**Comment by Teju-chitara** [comment]
I have mounted the emptyDir to fix this issue

2023/06/26 18:00:55 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)

- mountPath: /etc/
name: tmpfs-1

Nothing changed though in nginx behavior

**Comment by thresheek** [comment]
If the `/etc/nginx/nginx.conf` file indeed exists in the image you created on top `nginx:latest`, then something is wrong in the container startup config.

**Comment by Teju-chitara** [comment]
I have updated the container port to use 8080 instead of default 80 as I am running this pod now on 1.25 cluster.

Also I have removed the /etc volumeMount with that the pod is up and running now.

Thank you @thresheek for your time and support
