### ISSUE TITLE
fcgiwrap cannot be started

### ISSUE THREAD

**Issue by KodaiWaki** [nginxinc/docker-nginx#807]
### Summary

I have noticed that in the latest nginx image (possibly after version 1.25), the fcgiwrap service does not start even after installing the package using `apt-get install -y fcgiwrap`.
However, when I specify the base nginx image as 
`FROM nginx:1.24.0`
 in the Dockerfile, fcgiwrap works correctly.

Could someone please clarify if this is a known issue and provide information on the source of this difference?

Thank you.
Sincerely

**Comment by thresheek** [comment]
Hi @KodaiWaki!

Starting additional services is not something we support with this image.  What changed in 1.25.1 is we moved to Debian Bookworm (12) instead of Bullseye (11), so you might want to check what changed in fcgiwrap packaging between those distros.
