### ISSUE TITLE
Base image name broken in Alpine Dockerfile

### ISSUE THREAD

**Issue by victorstanciu** [nginxinc/docker-nginx#814]
Since 4d700b97e48ccf981cdaf865b59bb3d7a827ff7c the `-alpine` suffix of the base Alpine image name gets duplicated, resulting in a build error:

```
ERROR: failed to solve: nginx:mainline-alpine-alpine: docker.io/library/nginx:mainline-alpine-alpine: not found
```

**Comment by thresheek** [comment]
Thanks @victorstanciu indeed, I'll fix it today (as well as some CI goodness to actually check if those Dockerfiles work).

**Comment by thresheek** [comment]
Fixed in https://github.com/nginxinc/docker-nginx/pull/815
