### ISSUE TITLE
Dynamic Perl module is missing

### ISSUE THREAD

**Issue by svagi** [nginxinc/docker-nginx#82]
Hello, 
[nginx:alpine image](https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile) is built with several dynamic modules

```
--with-http_xslt_module=dynamic \
--with-http_image_filter_module=dynamic \
--with-http_geoip_module=dynamic \
--with-http_perl_module=dynamic \
```

But `/etc/nginx/modules/` directory contains only

```
ngx_http_geoip_module-debug.so
ngx_http_geoip_module.so
ngx_http_image_filter_module-debug.so
ngx_http_image_filter_module.so
ngx_http_xslt_filter_module-debug.so
ngx_http_xslt_filter_module.so
```

Is that so for a reason or am I missing something?

**Comment by thresheek** [comment]
You're likely launching not the latest one.

debian8-docker% docker pull nginx:alpine
alpine: Pulling from library/nginx
420890c9e918: Pull complete
a3ed95caeb02: Pull complete
18ba72bba100: Pull complete
3e8ec0e227d6: Pull complete
255b6d643a93: Pull complete
Digest: sha256:7d4a186f16ec00463ada491d62e12f60755e8aa2ea27ba1e6e0b26a9034347f6
Status: Downloaded newer image for nginx:alpine

debian8-docker% docker run -t -i nginx:alpine /bin/sh
/ # ls -la /etc/nginx/modules/
total 184
drwxr-xr-x    2 root     root          4096 Apr  5 18:59 .
drwxr-xr-x    3 root     root          4096 Apr  5 18:59 ..
-rwxr-xr-x    1 root     root         19952 Apr  5 18:59 ngx_http_geoip_module-debug.so
-rwxr-xr-x    1 root     root         19952 Apr  5 18:59 ngx_http_geoip_module.so
-rwxr-xr-x    1 root     root         23160 Apr  5 18:59 ngx_http_image_filter_module-debug.so
-rwxr-xr-x    1 root     root         23160 Apr  5 18:59 ngx_http_image_filter_module.so
-rwxr-xr-x    1 root     root         23120 Apr  5 18:59 ngx_http_perl_module-debug.so
-rwxr-xr-x    1 root     root         23120 Apr  5 18:59 ngx_http_perl_module.so
-rwxr-xr-x    1 root     root         19176 Apr  5 18:59 ngx_http_xslt_filter_module-debug.so
-rwxr-xr-x    1 root     root         19176 Apr  5 18:59 ngx_http_xslt_filter_module.so
/ # %                                                                                                                                                         debian8-docker%

**Comment by svagi** [comment]
Yup, you're right, it was my mistake - cached build. Thanks @thresheek!
