### ISSUE TITLE
Runtime variables for security headers

### ISSUE THREAD

**Issue by CameronGo** [nginxinc/docker-nginx#825]
### Is your feature request related to a problem? Please describe

Numerous 3rd party official images are based on the official nginx image. (For example: https://github.com/swagger-api/swagger-ui/.) It is often preferable to use these official images rather than building a custom image, but it is impractical for these 3rd party images to harden certain security configuration settings into these official images without knowing the environment into which they'll be deployed.

### Describe the solution you'd like

I'd like to be able to set specific security related configuration settings using runtime environment variables. For example, response headers related to:
- Strict-Transport-Security
- X-Frame-Options
- X-Robots-Tag

Perhaps via a single environment variable that can contain multiple pairs of response headers and values?

### Describe alternatives you've considered

Building and maintaining a custom docker image with a custom nginx.conf file with the settings required. This is less preferred in some cases because I'd be 3 steps removed from the official nginx image.

### Additional context

I've made a similar request on the Swagger UI team's page, but it occurred to me that, if this were supported globally in the nginx image, everyone would benefit from such a feature. See these other requests here:
https://github.com/swagger-api/swagger-ui/issues/8379
https://github.com/swagger-api/swagger-ui/issues/9116

**Comment by thresheek** [comment]
Hi @CameronGo!

I don't think adding such a niche use-case adds significant value for everyone using this image.

We're providing a nice way to extend this image via entrypoint configurations and are committed to supporting it in the future, which is I believe is good enough for customization such as this one.

You don't really need another image for that, too.  Just drop the config file and a script to export the variables you'd need in the templates.
