### ISSUE TITLE
ECS Nginx image can't find the config file, despite it being there.

### ISSUE THREAD

**Issue by igalci** [nginxinc/docker-nginx#829]
### Describe the bug

ECS Nginx image can't find the config file, despite it being there.

### To reproduce

I have set up a docker image for my t4g using the recommended Nginx image as such:

```
    FROM arm64v8/nginx:latest
    COPY ./nginx.conf /etc/nginx/nginx.conf
```

The image is created fine, uploaded into ECR, but then when I run my task, it exits by itself. And in the logs I see:

`open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)`

I went into the EC2 and manually opened the image (using /bin/sh) to check if the nginx.conf file is there, and it is.

It runs up until this `/docker-entrypoint.sh: Configuration complete; ready for start up`, then gives the error above, and exits with code 1.

### Expected behavior

I want to run the Nginx without exiting.

Why won't my task run?

### Your environment

- Version/release of Docker and method of installation (e.g. Docker Desktop / Docker Server): AWS ECS
- Version/tag of the NGINX Docker image: arm64v8/nginx:latest

**Comment by thresheek** [comment]
Hi @igalci!

Can you please provide:
- full logs for the container
- how container is started, e.g. mounts, volumes etc.

Thanks!

**Comment by igalci** [comment]
> Hi @igalci!
> 
> Can you please provide:
> 
>     * full logs for the container
> 
>     * how container is started, e.g. mounts, volumes etc.
> 
> 
> Thanks!

Sorry, silly mistake on my end.

I checked my mounts and it seems like I forgot to remove my previous mount attempting to pull the conf from S3, but now i removed it and it seems fine.

Thanks for your help and telling me to check the mounts.
