### ISSUE TITLE
USER instruction for building secure Docker images

### ISSUE THREAD

**Issue by joelchen** [nginxinc/docker-nginx#83]
Should there be a USER instruction included in the Dockerfile for added security as described in https://www.youtube.com/watch?v=LmUw2H6JgJo?

**Comment by thresheek** [comment]
You're free to use it in a child Dockerfile/image, using FROM nginx:latest and then re-defining everything related in the nginx.conf.

I don't think it makes sense to do that in the official image.  We're still dropping the privileges very early and workers work under non-privileged users.
