### ISSUE TITLE
How-to install new-relic agent for Nginx on Debian:Bullseye?

### ISSUE THREAD

**Issue by kklicmhenya** [nginxinc/docker-nginx#830]
### Describe the bug
Hi all, Got to update an old application that was on debiah:stretch, and was using nginx and nginx-nr-agent. 
It was upgraded to debian:bullseye, nginx installation was done, but there was a problem with nginx-nr-agent. Build crashes due to lack of python dependencies. 
After some searching, I realized it was about Python2 when debian 11 no longer supports it. Then I found an issue in this github repository that nginx-nr-agent is no longer supported. [Issue 602](https://github.com/nginxinc/docker-nginx/issues/602) So here's a question: how can I connect new-relic agent for nginx on debian:bullseye now?
```shell
[2023-08-18T10:05:37.360Z]  nginx-nr-agent : Depends: python-daemon but it is not installable

[2023-08-18T10:05:37.360Z]                   Depends: python-setproctitle but it is not installable
``` 
Thanks in advance!

### Your environment

- Method of installation:
```shell
RUN apt-get update -y && apt-get install -y nginx-nr-agent && \	
    rm -rf /var/lib/apt/lists/*
``` 
- Version/tag of the NGINX Docker image: debian:bullseye

**Comment by thresheek** [comment]
Hi @kklicmhenya!

nginx-nr-agent is not supported since a long time and there will be no development or support for it.

Therefore it's not possible to use it in newer images.

**Comment by kklicmhenya** [comment]
Got it, thanks for the response!
