### ISSUE TITLE
Upgrading from image ID c31fe73098ae to 88db8eea1453 breaks SSL Client Certificates

### ISSUE THREAD

**Issue by eta-orionis** [nginxinc/docker-nginx#832]
### Describe the bug

Upgrading from image with ID c31fe73098ae (an old nginx:stable-alpine version 1.22.1 from 9 months ago) to the current nginx stable-alpine (ID 6dae3976ee05 / nginx 1.24.0) causes SSL client certificates to stop working with a HTTP 400 error (see attachment). No changes were made to the configuration, simply pulled the new image and restarted the container.

Error appears with all browsers I tried: Firefox, Safari, Chrome, curl, and openssl s_client

Upon further verification, the problem is present with older image IDs as well. I verified the following do not work:

nginx:1.22.1-alpine   88db8eea1453
nginx:1.23.4-alpine   8e75cbc5b25c

What could cause this?

### Your environment

Docker version 23.0.6, build ef23cbc4315ae76c744e02d687c09548ede461bd
Deployment: docker-compose

Nginx images from oldest to newest:
c31fe73098ae works
88db8eea1453 does not work
8e75cbc5b25c does not work
6dae3976ee05 does not work

### Additional context
![image](https://github.com/nginxinc/docker-nginx/assets/3466670/31daae5b-1e17-4ca7-be73-2701fd0c95b2)

**Comment by thresheek** [comment]
Hello @eta-orionis!

Can you share the error log from the container when you see the 400 error?

Thanks

**Comment by eta-orionis** [comment]
Thanks @thresheek 

The container output at the default logging settings looks like a completely normal request, rejected with code 400. 

Setting the error log level to `debug` I get: 

`server  | 2023/08/24 13:51:58 [info] 10#10: *3 client SSL certificate verify error: (68:CA signature digest algorithm too weak) while reading client request headers, client: xx.xx.xx.xx, server: example.com, request: "GET / HTTP/2.0", host: "example.com"

It's confusing because the nginx version in both images is the same: 1.22.1.

**Comment by eta-orionis** [comment]
Thanks for the answer!

Fixed the problem. In my case, the CA certificate was fine, but the client certificates were signed with `Signature Algorithm: sha1WithRSAEncryption`. The current openssl will accept `Signature Algorithm: sha256WithRSAEncryption`.

For anybody else having the same problem: 
- change the CA default signature algorithm and reissue client certs: https://itigloo.com/security/change-openssl-default-signature-algorithm/
- OR lower nginx required ciphers: https://stackoverflow.com/questions/54797480/how-can-i-allow-sha1withrsaencryption-during-nginx-ssl-client-verify

If your problem is with the CA cert itself, you may be able to reissue the CA cert without reissuing client certs: https://serverfault.com/questions/306345/certification-authority-root-certificate-expiry-and-renewal/471434
