### ISSUE TITLE
nginx 1.25.2 on alpine - docker image oversize

### ISSUE THREAD

**Issue by cyrax13** [nginxinc/docker-nginx#835]
### Describe

Hello there :)

After building nginx 1.25.2 mainline on alpine using dockerfile released i have got image oversized - 3+Gb. Take a look:

```
~$ docker image ls | grep nginx
nginx         1.25.2-r1-alpine        e533c5b3e9b2   31 minutes ago   3.26GB
nginx         1.25.0-r1-alpine        d6c4b9aefdfb   3 months ago     130MB
nginx         1.24.0-r1-alpine        1c83564ef7bf   4 months ago     124MB
nginx         1.23.4-r1-alpine        b36e9b7d4b6b   4 months ago     124MB
nginx         1.23.3-r2-alpine        a11fcf9efff0   5 months ago     129MB
nginx         1.23.3-r1-alpine        bea5d7b59e5c   8 months ago     122MB
```

Typically my nginx builds are 120-130 megabytes, but nginx version 1.25.2 is 3.26 gigabytes...

### Reproduce

Steps to reproduce:

1. Download alpine nginx-slim dockerfile: https://github.com/nginxinc/docker-nginx/blob/321a13a966eeff945196ddd31a629dad2aa85eda/mainline/alpine-slim/Dockerfile
2. Build:
`docker build -f Dockerfile -t nginx:1.25.2-alpine-slim .`
3. Download alpine nginx dockerfile: https://github.com/nginxinc/docker-nginx/blob/321a13a966eeff945196ddd31a629dad2aa85eda/mainline/alpine/Dockerfile
4. Build:
`docker build -f Dockerfile -t nginx:1.25.2-alpine .`
5. See image size:
`docker image ls | grep nginx`

### Environment

- Docker 24.0.5 on UbuntuServer 22.04 LTS virtual machine

### Additional context

Commit that broke the cleanup logic /tmp folder inside image on build: https://github.com/nginxinc/docker-nginx/commit/2879b26c7dedf1d958b1894a5c1b1dec3c026369

```
fix: address Alpine bug and shell linter warnings
Replace `-n` with `-f` in Alpine Linux conditional check
```

Yep, replace `-n` to `-f` for alpine brokes `/tmp` clean up there:

```
    && if [ -f "$tempDir" ]; then rm -rf "$tempDir"; fi \
    && if [ -f "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
    && if [ -f "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi
```

And `rm -rf /tmp/*` resolve the problem...

Can you fix it? Thank you in advance)

**Comment by yosifkit** [comment]
👍 The `-f ` is the incorrect check since it is only going to be a directory (otherwise an empty string) and never a regular file. This specifically applies to architectures that are not `x86_64` or `aarch64`, since the others have to build and so create/use the temp directory.

**Comment by thresheek** [comment]
Thanks @cyrax13 @yosifkit

Yeah, I'm going to submit patches to fix that today.

I'll also work on figuring out a test case for changes like that - seems like comparison of before/after sizes of the images with some percentage would be a good thing to check.
