### ISSUE TITLE
Unable to build with stream_ssl_preread module

### ISSUE THREAD

**Issue by darkvertex** [nginxinc/docker-nginx#838]
### Is your feature request related to a problem? Please describe

I would like to compile nginx with this module:
http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html

Do I need to reinvent the wheel or is there a straightforward way to customize the dockerfile to include this module when compiling nginx?

### Describe the solution you'd like

Ideally declaring it in ENABLED_MODULES and letting it compile should be enough, but there appears to be no makefile pre-made for it:
https://hg.nginx.org/pkg-oss/file/tip/alpine

**Comment by thresheek** [comment]
Hello @darkvertex,

This module is enabled in the builds, see https://hg.nginx.org/pkg-oss/file/tip/alpine/Makefile#l95
