### ISSUE TITLE
This dockerfile have a Unknown instruction: &&

### ISSUE THREAD

**Issue by pascalandy** [nginxinc/docker-nginx#84]
Hey guys,
When I'm building [this dockerfile](https://github.com/nginxinc/docker-nginx/commit/2b0b2939f52d1bcfc7e4e5be9a49233758e01133), I'm having this issue `Unknown instruction: &&`

see my log here https://gist.github.com/pascalandy/fe9a767ac1b86573c39753b59f3a35d2

**Comment by pascalandy** [comment]
Well, I guess this is a Docker glitch. 

I did remove all containers and all images from my server. 
Build the image again and I'm fine. 

So no issue on this Dockerfile. Sorry for this.

**Comment by albers** [comment]
# forward request and error logs to docker log collector

This comment terminates the multiline command.
So Docker expects the next line `&& ln -sf /dev/stdout /var/log/nginx/access.log \` to be a new dockerfile instruction and fails because the first word is no known command.

**Comment by thresheek** [comment]
Interesting, which docker version are you running?  Is it reproducible on the latest one?

**Comment by thresheek** [comment]
Works fine on Docker version 1.11.1, build 5604cbe.
