### ISSUE TITLE
AWS Guard false positive warning

### ISSUE THREAD

**Issue by BCsabaEngine** [nginxinc/docker-nginx#844]
### Describe the bug

AWS Guard identifies the use of AWK at runtime as a security incident. Couldn't there be a simpler way to resolve the awk command used in https://github.com/nginxinc/docker-nginx/blob/4b0d808b8f320df132c154a974ebe46e9e5f5ffe/mainline/alpine-slim/15-local-resolvers.envsh?

### Expected behavior

Remove, replace awk command with simple echo

### Your environment

- AWS EKS
- nginx:1.25.2-alpine (nginx:1.23.x-alpine works well)

**Comment by thresheek** [comment]
I believe that patches are welcome, but awk is just so conventient to do the parsing for us.
