### ISSUE TITLE
how to build nginx with modules  for alpine image？

### ISSUE THREAD

**Issue by snowdream** [nginxinc/docker-nginx#846]
I try to [Adding third-party modules to nginx official alpine image](https://github.com/nginxinc/docker-nginx/tree/master/modules#adding-third-party-modules-to-nginx-official-image)，but failed.

https://github.com/snowdreamtech/nginx/actions/workflows/mainline-alpine.yml

**Comment by snowdream** [comment]
This is my project.  [https://github.com/snowdreamtech/nginx](https://github.com/snowdreamtech/nginx/actions/workflows/mainline-alpine.yml)

Accroding [Adding third-party modules to nginx official alpine image](https://github.com/nginxinc/docker-nginx/tree/master/modules#adding-third-party-modules-to-nginx-official-image).

I Try to build nginx with modules.

1. debian images : success
2. alpine images: failed

I do not know why.

logs:
https://github.com/snowdreamtech/nginx/actions

**Comment by thresheek** [comment]
I can see "Bus error: core dumped" in your action logs.  You need to figure out why and on what architecture this happens, possibly by shrinking the list of the architectures you build on:

linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390

**Comment by snowdream** [comment]
> I can see "Bus error: core dumped" in your action logs. You need to figure out why and on what architecture this happens, possibly by shrinking the list of the architectures you build on:
> 
> linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390

OK, I will try later.

**Comment by snowdream** [comment]
@thresheek 

linux/arm/v6

https://github.com/snowdreamtech/nginx/actions/runs/6620087423
![image](https://github.com/nginxinc/docker-nginx/assets/737958/cfd16197-ce8e-4513-82dc-1ae7fc4b6121)

**Comment by thresheek** [comment]
Hi @snowdream, have you been able to figure out the build issues?
