### ISSUE TITLE
Host additional module packages in nginx.org repo

### ISSUE THREAD

**Issue by robalexdev** [nginxinc/docker-nginx#849]
I've noticed the official docs recommend [building NGINX from scratch](https://github.com/nginxinc/docker-nginx/tree/a4d9a5c94867f845db761672b9c422f46e0090ef/modules) when custom modules are needed.

As an alternate approach, would it be possible to host additional NGINX module packages at the https://nginx.org/packages/ repos, such that the additional modules can simply be installed?

For example, I was expecting the following would work:

    FROM nginx:1.24.0-alpine
    RUN apk add \
        -X "https://nginx.org/packages/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" \
        --no-cache \
        "nginx-mod-http-lua=${NGINX_VERSION}-r${PKG_RELEASE}"

Note that this uses Docker image version pinning, uses the environmental variables set in the base image to install compatible package versions, and the pinning can be managed with Dependabot (or similar). A similar approach should work for Debian/apt, and others.

This approach mirrors that of [the official build](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L35), which already added a trust relationship to the nginx.org repo. Unfortunately, it doesn't work because `nginx-mod-http-lua` [isn't available](https://nginx.org/packages/alpine/v3.17/main/x86_64/) in the nginx.org package repo. I'm not sure how difficult it would be to build additional modules to that repo, but this feels like a cleaner way to install modules.

**Comment by thresheek** [comment]
Hi @robalexdev!

Our policy is to only host binary versions of software we own and write on nginx.org, and not third-party modules like lua.  We do, however, provide build instructions via `pkg-oss` so we can proactively test if they are compatible with new nginx releases, and they are indeed used in this repo's "custom modules" dockerfiles.

**Comment by robalexdev** [comment]
Hi Konstantin,

The no-third-party-module policy makes sense, thanks for the explaination.
