### ISSUE TITLE
Publish 1.10 please

### ISSUE THREAD

**Issue by alaz** [nginxinc/docker-nginx#85]

**Comment by jlaswell** [comment]
Looks like this was just pushed out: https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile

**Comment by thresheek** [comment]
@jlaswell indeed, I'm waiting for https://github.com/docker-library/official-images/pull/1669 to be merged to close this issue.

**Comment by jlaswell** [comment]
Understood. Really appreciate the update 👍

**Comment by thresheek** [comment]
It's published now.
