### ISSUE TITLE
apk command VERY slow under nginx:1.25.3-alpine

### ISSUE THREAD

**Issue by gom59** [nginxinc/docker-nginx#850]
I recently updated my Docker image from nginx:1.25.2-alpine to nginx:1.25.3-alpine.
Building is nearly impossible, and apk takes way too long.

This is the beginning of my Dockerfile:

```
FROM nginx:1.25.3-alpine AS prod
RUN apk add --update \
               curl \
               bash \
               openssl \
               certbot \
               python3 \
               fail2ban \
               python3-dev \
               py3-pip
```

In nginx:1.25.2-alpine, this is nearly instantaneous.

In nginx:1.25.3-alpine, commands take minutes.
This is using Docker version 24.0.7, build afdd53b, in a docker compose project.
I have gone back and forth quite many times between the two nginx images, the difference is systematic.

Initial download:
![Screenshot from 2023-12-03 12-41-56](https://github.com/nginxinc/docker-nginx/assets/49916817/63478b20-6a40-4f56-a8d7-d5ee39809cd7)

Later on:
![Screenshot from 2023-12-03 12-50-03](https://github.com/nginxinc/docker-nginx/assets/49916817/f85002c2-76d9-483b-88af-9ba5b83943dd)

**Comment by thresheek** [comment]
Hi @gom59!

Out of those 507 seconds, which step takes most of the time?   I cant reproduce here, and I suspect it's either network connectivity or disk access is having issues on your side.
