### ISSUE TITLE
Why is the `latest` behind `stable`?

### ISSUE THREAD

**Issue by wernight** [nginxinc/docker-nginx#86]
mainline is still 1.9 while stable is 1.10 (on Docker Hub). Just from the version number it looks like it should be the inverse.

**Comment by thresheek** [comment]
1.10.0 is identical to 1.9.15 code-wise: http://hg.nginx.org/nginx/shortlog/efbdc2f66901 so it makes no sense to bump just to bump numbers.

Also, latest is always pointing to the latest mainline release.

**Comment by wernight** [comment]
Wouldn't it be cleaner if both were 1.10 then?
