### ISSUE TITLE
unexpected-in-etc-nginx-nginx-conf10

### ISSUE THREAD

**Issue by kapil26021994** [nginxinc/docker-nginx#860]
### To reproduce

1. Deploy the NGINX Docker image using ...
2. View output/logs/configuration on ...
3. See error

### Your environment

- Version/release of Docker and method of installation (e.g. Docker Desktop / Docker Server)
- Version/tag of the NGINX Docker image (e.g. `nginx:alpine`)
- Target deployment platform (e.g. OpenShift / Kubernetes / Docker Compose / etc...)

**Comment by thresheek** [comment]
Closing, duplicate of https://github.com/nginxinc/docker-nginx/issues/861
