### ISSUE TITLE
Limit Req not applied for UDP packet

### ISSUE THREAD

**Issue by bnnk2** [nginxinc/docker-nginx#864]
### Describe the bug

No option to ratelimit UDP packet

### To reproduce

Limit Req is applicable for only for HTTP server and not for UDP

### Expected behavior

Similar option for UDP not applicable /present

### Your environment
docker NGINX

### Additional context

Is there any option to ratelimit udp is there any module in nginx that can be enabled for udp rate limiting I don't find any option in the modules that are present. This chokes our upstream server. Any help on the same.

**Comment by thresheek** [comment]
Hi @bnnk2, there is no way to pace/ratelimit udp streams in nginx.
