### ISSUE TITLE
Image nginx: 1.25.4-alpine3.18 does not have support for HTTPS enabled, and after container startup, an error message is reported using HTTP 3

### ISSUE THREAD

**Issue by chenxudong2020** [nginxinc/docker-nginx#867]
### Describe the bug

Image nginx: 1.25.4-alpine3.18 
does not have support for HTTPS enabled, 
and after container startup, an error message is reported using HTTP 3

My configuration file is as follows:
server {
        listen $HTTP_PORT default_server;
        listen [::]:$HTTP_PORT default_server;
        server_name localhost;
        index index.php index.html index.htm index.nginx-debian.html;
        root  /web;
    }
     server {
        listen $HTTPS_PORT ssl default_server;
        listen $HTTPS_PORT http3 reuseport default_server;
        listen [::]:$HTTPS_PORT ssl default_server;
        listen [::]:$HTTPS_PORT http3 reuseport default_server;
        http2 on;
        ssl_certificate       /cert/$SSL_PUBLIC;
        ssl_certificate_key   /cert/$SSL_KEY;
        ssl_protocols         TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        add_header Alt-Svc 'quic=":$HTTPS_PORT"; h3-27=":$HTTPS_PORT";h3-25=":$HTTPS_PORT"; h3-T050=":$HTTPS_PORT"; h3-Q050=":$HTTPS_PORT";h3-Q049=":$HTTPS_PORT";h3-Q048=":$HTTPS_PORT"; h3-Q046=":$HTTPS_PORT"; h3-Q043=":$HTTPS_PORT"';        server_name           localhost;
        index index.php index.html index.htm index.nginx-debian.html;
        root  /web;
        error_page 400 = /400.html;

        location ~ \\.php$ {
            
        }

        location $TUNNEL_PATH {
            proxy_redirect off;
            proxy_pass http://$OVERTLS_HOST:$OVERTLS_PORT;
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host \$http_host;
        }
    }

Error reported after running:
2024/02/21 09:06:23 [emerg] 12#12: invalid parameter "http3" in /etc/nginx/conf.d/overtls.conf:10

### Your environment

- Version/release of Docker and method of installation (e.g. Docker Desktop / Docker Server)
- Version/tag of the NGINX Docker image (e.g. `nginx:alpine`)
- Target deployment platform (e.g. OpenShift / Kubernetes / Docker Compose / etc...)

**Comment by DJviolin** [comment]
For some reason, http3 also not working for me in my compose project. I'm assuming the error is in my settings, but even when I try a very minimal setup with defaults, always http2 version returning. This haunting me for 2 days already.

**Comment by thresheek** [comment]
@DJviolin, browsers can be picky about enabling `http3` - I'd suggest testing with cli tools like `curl`.

**Comment by DJviolin** [comment]
It works with curl, but not with latest Firefox and Edge. I'm absolutely exhausted, why it's not working... Can be an issue with the local certificate? I created it with this command:

```sh
$ docker run -it --rm -v "./secrets/:/secrets/" alpine/openssl:latest req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /secrets/docker.test.key -out /secrets/docker.test.crt -subj "/C=HU/ST=Pest/L=Budapest/O=Docker Compose Company/CN=docker.test"
```

Here is the curl output for HTTP3 request:

```batch
C:\APPS\curl-8.6.0_1-win64-mingw\bin>curl -ILk http://www.docker.test/benchmark_json --http3
HTTP/1.1 301 Moved Permanently
Date: Wed, 21 Feb 2024 18:20:06 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: http://docker.test/benchmark_json
Content-Security-Policy: upgrade-insecure-requests
Permissions-Policy: autoplay=(), camera=(), microphone=()
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-protocol: HTTP/1.1
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

HTTP/1.1 301 Moved Permanently
Date: Wed, 21 Feb 2024 18:20:06 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://docker.test/benchmark_json
Content-Security-Policy: upgrade-insecure-requests
Permissions-Policy: autoplay=(), camera=(), microphone=()
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-protocol: HTTP/1.1
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

HTTP/3 200
date: Wed, 21 Feb 2024 18:20:06 GMT
content-type: application/json
content-length: 56
content-security-policy: upgrade-insecure-requests
permissions-policy: autoplay=(), camera=(), microphone=()
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
alt-svc: h3=":443"; ma=86400
x-protocol: HTTP/3.0
strict-transport-security: max-age=63072000; includeSubDomains; preload
```

**Comment by DJviolin** [comment]
The problem was caused by the browser's strict policy about locally signed certificates and certificate authorities with HTTP3/QUIC.

Longer explanation and how to whitelist your localhost domains in the browsers can be found [here](https://github.com/kelmenhorst/quic-censorship/blob/main/browsers.md).

**Comment by DJviolin** [comment]
The problem was caused by the browser's strict policy about locally signed certificates and certificate authorities with HTTP3/QUIC. Longer explanation can be found [here](https://www.smashingmagazine.com/2021/09/http3-practical-deployment-options-part3/#additional-issues) why de browsers doing this:

> This is because [non-official TLS certificates are often used by companies to decrypt their employees’ TLS traffic](https://tlseminar.github.io/tls-interception/#how-ssl-tls-interception-works) (so that they can, for example, have their firewalls scan inside encrypted traffic). However, if companies would start doing that with QUIC, we would again have custom middlebox implementations that make their own assumptions about the protocol. This could lead to them potentially breaking protocol support in the future, which is exactly what we tried to prevent by encrypting QUIC so extensively in the first place! As such, Chrome takes a very opinionated stance on this: If you’re not using an official TLS certificate (signed by a certificate authority or root certificate that is trusted by Chrome, such as [Let’s Encrypt](https://letsencrypt.org/)), then you cannot use QUIC. This, sadly, also includes self-signed certificates, which are often used for local test set-ups.

How to whitelist your localhost domains in the browsers can be found [here](https://github.com/kelmenhorst/quic-censorship/blob/main/browsers.md).
