### ISSUE TITLE
hg.nginx.org is unavailable, breaking Dockerfile

### ISSUE THREAD

**Issue by jvanheesch** [nginxinc/docker-nginx#868]
### Is your feature request related to a problem? Please describe

Our build requires an nginx container with lua. Based on [these excellent instructions](https://github.com/nginxinc/docker-nginx/tree/master/modules#docker-compose-with-pre-packaged-modules), we use [this Dockerfile](https://raw.githubusercontent.com/nginxinc/docker-nginx/master/modules/Dockerfile).
Right now, our build is failing because https://hg.nginx.org/xslscript/raw-file/01dc9ba12e1b/xslscript.pl is down.

### Describe the solution you'd like

To reduce the chance of build failures, perhaps a highly available read-only github mirror could be considered (similar to https://github.com/nginx/njs).

**Comment by thresheek** [comment]
Hi @jvanheesch !

Yes, we're considering a mirror or a move of `pkg-oss` to github. No hard ETA for this yet though.

**Comment by thresheek** [comment]
`pkg-oss` is now moved to github.  the change is tracked in https://github.com/nginxinc/docker-nginx/pull/926

**Comment by thresheek** [comment]
Should no longer be an issue, fixed & closing.
