### ISSUE TITLE
Latest version missing from ECR public gallery

### ISSUE THREAD

**Issue by kimmoahokas** [nginxinc/docker-nginx#869]
### Describe the bug

[AWS ECR public gallery](https://gallery.ecr.aws/nginx/nginx) does not have all the latest container versions.

### To reproduce

1. Go to [AWS ECR public gallery](https://gallery.ecr.aws/nginx/nginx) 
2. See that for example tag `bookworm` is missing and tag `mainline` was last updated 3 months ago while in Docker hub it was updated 18 days ago.

### Expected behavior

The same image tags and versions that are in Docker Hub are available in AWS ECR public gallery

### Your environment

not relevant

### Additional context

none

**Comment by thresheek** [comment]
Should be fixed now!

I'm going to set up a sync job here in this repo to offer more visibility into synchronisation and make sure it stays green, too.

**Comment by kimmoahokas** [comment]
Thank you very much for super quick fix!
