### ISSUE TITLE
Docker images for 1.25.5 cannot be pulled from Docker Hub

### ISSUE THREAD

**Issue by rzuckerm** [nginxinc/docker-nginx#880]
### Describe the bug

I cannot seem to pull the 1.25.5 docker image from Docker hub onto my Ubuntu 22.04 system:

```console
$ docker pull nginx:1.25.5
1.25.5: Pulling from library/nginx
no matching manifest for linux/amd64 in the manifest list entries
```

### To reproduce

1. `docker pull nginx:1.25.5`
2. See error mentioned above (or something similar depending upon the machine architecture

### Expected behavior

The docker image is pulled without error.

### Your environment

- Version/release of Docker and method of installation: `Docker version 26.0.1, build d260a54` installed from docker apt repo.
- Version/tag of the NGINX Docker image: 1.25.5
- Target deployment platform: Docker compose

### Additional context

In the [1.25.4](https://hub.docker.com/_/nginx/tags?page=&page_size=&ordering=&name=1.25.4) release, I see a list of architectures for each image, but for [1.25.5](https://hub.docker.com/_/nginx/tags?page=&page_size=&ordering=&name=1.25.5), I do not.

**Comment by JuniorJPDJ** [comment]
Same, renovatebot found the update but CI failed to build image for any arch: https://github.com/JuniorJPDJ/containers/actions/runs/8727029958/job/23943964887?pr=63

**Comment by oxpa** [comment]
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/nginx/

it seems the build was successful but the registry doesn't have proper manifests in place. Not sure why. Will ping guys at official-images

**Comment by oxpa** [comment]
docker-library/official-images#16625

**Comment by oxpa** [comment]
Should be fine now.
