### ISSUE TITLE
can't read /etc/apt/sources.list: No such file or directory

### ISSUE THREAD

**Issue by Edarjak** [nginxinc/docker-nginx#885]
### Describe the bug

Can't read /etc/apt/sources.list in the nginx 1.26

### To reproduce

1. Deploy the NGINX Docker image
2. cat  /etc/apt/sources.list
3. See the output:

```
# cat /etc/apt/sources.list
cat: /etc/apt/sources.list: No such file or directory
# cd /etc/apt
# ls -la
total 36
drwxr-xr-x 1 root root 4096 Apr 23 15:00 .
drwxr-xr-x 1 root root 4096 Apr 29 08:53 ..
drwxr-xr-x 2 root root 4096 Apr 23 15:00 apt.conf.d
drwxr-xr-x 2 root root 4096 May 25  2023 auth.conf.d
drwxr-xr-x 1 root root 4096 Apr 25 07:36 keyrings
drwxr-xr-x 2 root root 4096 May 25  2023 preferences.d
drwxr-xr-x 2 root root 4096 Apr 23 15:00 sources.list.d
drwxr-xr-x 2 root root 4096 Apr 23 15:00 trusted.gpg.d
```

### Expected behavior

sources.list should exist under /etc/apt/

### Your environment

- Docker Desktop on Mac v4.29.0
- nginx:1.26.0
- Target deployment platform: OpenShift / Kubernetes

**Comment by thresheek** [comment]
It seems `/etc/apt/sources.list` is not shipped with the underlying image, `debian:bookworm-slim`.  There is nothing this image can do then.

**Comment by yosifkit** [comment]
In `bookworm` and newer the information is now contained in `/etc/apt/sources.list.d/debian.sources` (note that it is a `.sources` file, not a `.list` since it is using a newer RFC 2822 based format)
```console
root@ac8c9788eda2:/# cat /etc/apt/sources.list.d/debian.sources
Types: deb
# http://snapshot.debian.org/archive/debian/20240408T000000Z
URIs: http://deb.debian.org/debian
Suites: bookworm bookworm-updates
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
# http://snapshot.debian.org/archive/debian-security/20240408T000000Z
URIs: http://deb.debian.org/debian-security
Suites: bookworm-security
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
root@ac8c9788eda2:/#

**Comment by Edarjak** [comment]
Thank you all for replies! :)
