### ISSUE TITLE
Facing issue while running Nginx using docker on riscv 

### ISSUE THREAD

**Issue by divyashree123456** [nginxinc/docker-nginx#888]
I have created a docker file for nginx for riscv using ref of https://github.com/nginxinc/docker-nginx/tree/master/mainline/alpine-slim
installed nginx in base image as it is systemd service and added only paths in docker file.
Docker file is attached.
[Dockerfile.txt](https://github.com/nginxinc/docker-nginx/files/15270660/Dockerfile.txt)

 After creating image using this docker file ,while running a image i m facing issue as :
 
![Screenshot from 2024-05-09 18-20-39](https://github.com/nginxinc/docker-nginx/assets/120623642/9a881ae6-7920-49de-87d8-547cea214b1b)

the dmsg for nginx is not coming and not showing any errors .
please help to me solve this issue.

**Comment by thresheek** [comment]
Also, it looks like container is running, since you see it in `docker ps` - so I'm not sure what the actual error is?

**Comment by divyashree123456** [comment]
Hi @thresheek  "ready to run nginx"  is statement i have added in docker-entrypoint.sh file just for debugging .
need to get nginx logs after execution of this file ,those logs are not  displaying for me .please help me to debug the issue.
used shell scripts and files are attached below.
[files_for_nginx.zip](https://github.com/nginxinc/docker-nginx/files/15343934/files_for_nginx.zip)
Thanks in advance

**Comment by thresheek** [comment]
I believe you should just rebuild the Dockerfiles we provide and use those.  Unfortunately we don't support custom builds of NGINX in this repo.
