### ISSUE TITLE
ARM64v8 no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by kingjerod** [nginxinc/docker-nginx#889]
### Describe the bug

Trying to pull the ARM64v8 image results in the error message "no matching manifest for linux/amd64 in the manifest list entries"

### To reproduce

Issue command `docker pull arm64v8/nginx`

### Expected behavior

It downloads the latest arm64v8 Nginx docker image.

### Your environment

Docker version: Docker version 20.10.23, build 7155243
OS: Windows 10

### Additional context

Pulling the regular (non ARM) version works fine.

**Comment by thresheek** [comment]
Hi @kingjerod if you're running that on amd64 machine, you'd also need to provide a proper --platform option since arm64v8/nginx only publishes arm64 versions of manifests.

**Comment by kingjerod** [comment]
If I do a `docker pull arm64v8/node:18.14.2-slim` it works fine, no need for --platform. Oh well.
