### ISSUE TITLE
[emerg] unknown directive "perl"

### ISSUE THREAD

**Issue by alaz** [nginxinc/docker-nginx#89]
Hi,

I am trying to migrate to Docker container with new Nginx stable 1.10 and having a problem using the Perl module.

The simplest reproducible scenario is to run `docker run --rm -it --entrypoint /bin/sh nginx:stable-alpine`, then create a virtual host configuration w/ Perl directive, like this one:

```
/ # cat /etc/nginx/conf.d/default.conf 
server {
  listen 80 default_server;
  server_name _;
  location / {
    perl 'sub { return HTTP_BAD_REQUEST; }';
  }
}
```

and this is what I have when trying to start nginx:

```
/ # /usr/sbin/nginx -g 'daemon off;' -g 'load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;' -g 'error_log stderr debug;'
2016/05/07 12:17:16 [emerg] 17#17: unknown directive "perl" in /etc/nginx/conf.d/default.conf:5
nginx: [emerg] unknown directive "perl" in /etc/nginx/conf.d/default.conf:5
```

Am I missing something? Is there any other debug information I could provide?

**Comment by alaz** [comment]
My fault. Only the last `-g` command line argument plays.

**Comment by hasancansaral** [comment]
Hi @alaz, How did you start nginx with the Perl module loaded? I am having the exact same [issue](https://github.com/nginxinc/docker-nginx/issues/124).

**Comment by hasancansaral** [comment]
Loading the module with command `nginx -g 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;'` resolved the issue.

**Comment by typoworx-de** [comment]
load_module directive also seems to work, but it must be in the first lines of nginx.conf (=nginx main configuration).
