### ISSUE TITLE
[Question] Prevent `XSS` and `SQL Injection` in `nginx:latest` image

### ISSUE THREAD

**Issue by danieeeld2** [nginxinc/docker-nginx#890]
Hello, I am a Computer Science Student and is my first time using `docker-nginx`. 

My teacher required me to configure `nginx:latest` image to avoid `SQL injection` and `XSS`. I have seen that people use `NAXSI` for this  but  I wasn't able to install it into the image (The problem is that I cannot change the image).

Is it possible to install it or should I try something more?
Thanks you and sorry for the inconvenience.

**Comment by thresheek** [comment]
Hi @danieeeld2, without changing the image it's impossible - nginx does not have tools to prevent XSS and SQL injection out of the box.

**Comment by danieeeld2** [comment]
> Hi @danieeeld2, without changing the image it's impossible - nginx does not have tools to prevent XSS and SQL injection out of the box.

Okayy. Thanks you❤️
