### ISSUE TITLE
support for environment variables in custom configuration

### ISSUE THREAD

**Issue by fgutmann** [nginxinc/docker-nginx#9]
Nginx unfortunately doesn't support using environment variables inside most configuration blocks.

Since this is quite essential when linking with other containers to build a reverse proxy I think this image should provide some mechanism to use environment variables in custom configuration.

Solutions found on the web:

**Pre-processing configuration files**
https://github.com/shepmaster/nginx-template-image

**Using set_by_lua or set_by_perl**
https://docs.apitools.com/blog/2014/07/02/using-environment-variables-in-nginx-conf.html

Both of this don't work out of the box because none of the modules is included.

**Comment by pikeas** [comment]
+1

**Comment by amouat** [comment]
+1

This would allow us to pass in config values at runtime e.g. `docker run -d -e HOST myname.com -e PROXY http://bla nginx`

This would allow users to do a lot of things without needing to subclass the image.

**Comment by jmagnusson** [comment]
The [official postgres image](https://hub.docker.com/_/postgres/) is a good example of how to pass in env variables at runtime and also to run scripts (which in this case would be replacing template vars in the nginx conf.)

**Comment by efouts** [comment]
Linked containers get entries added to the hosts file. So if you link a source container  ```--link source:upstream``` you can then just use http://upstream as your proxy pass param. That should be more resilient than environment variables if the source container gets restarted and changes IPs. 

Got this info [here](https://docs.docker.com/userguide/dockerlinks/) under "Updating the /etc/hosts file"

**Comment by jmmills** [comment]
@efouts Good point, I'm not sure docker updated the hosts file when this ticket was originally opened.

**Comment by aikomastboom** [comment]
:+1: 
or include eg the perl module.. so we can do things like:
```
      perl_set aws_region 'sub { return $ENV{"AWS_REGION"}; }';
      perl_set aws_bucket 'sub { return $ENV{"AWS_BUCKET"}; }';
      proxy_pass http://s3-$aws_region.amazonaws.com/$aws_bucket/$1;
```

**Comment by peXed** [comment]
@efouts it seems your solution is not working (anymore).
I tried linking a container and just used the linked name in a config, but Nginx starts and stops again with the error host not found.
However, if I change the config, so Nginx starts probably, and using a ping command in the nginx container, it pings the linked container correctly.

Did I do something wrong or is it a bug? If I enter the IP of the container manually in the config, it works perfectly.

**Comment by vidarl** [comment]
FYI : I have created PR https://github.com/nginxinc/docker-nginx/pull/59 as an attempt to add this most wanted feature...

**Comment by thresheek** [comment]
Possible since 7085823179fd6eb751cda956e2f91968c8fcefc8.
