### ISSUE TITLE
Default configuration should support IPv6

### ISSUE THREAD

**Issue by mpalmer** [nginxinc/docker-nginx#90]
The configuration that ships with the nginx container (Debian variant, at least) only listens on INADDR_ANY.  It doesn't seem problematic to also listen on IN6ADDR_ANY, to allow feature parity with both protocol versions.

**Comment by thresheek** [comment]
I don't really see the point in providing that in the default configuration.

default.conf, which contains listen 80; is meant to be removed and replaced by something that provides the configuration needed for your use for any non-trivial use-case, so what's the issue with adding listen [::]:80; in the configuration snippet you will be shipping anyway?

**Comment by thresheek** [comment]
There is also another consideration.  Imagine docker ships with ipv6 enabled by default at some point and this change in the default will add another attack scope for a very popular component.

**Comment by mpalmer** [comment]
If everyone is supposed to replace the configuration, why have one at all?  Why not ship without a configuration?  At any rate, this is clearly a "no", so I'll close this issue.
