### ISSUE TITLE
[Question]  [notice] 9#9: signal 17 (SIGCHLD) received from 12, what does it mean?

### ISSUE THREAD

**Issue by gastonborba** [nginxinc/docker-nginx#901]
I have this output in openshift:

2024/06/12 16:31:00 [notice] 9#9: using the "epoll" event method
2024/06/12 16:31:00 [notice] 9#9: nginx/1.27.0
2024/06/12 16:31:00 [notice] 9#9: built by gcc 12.2.0 (Debian 12.2.0-14)
2024/06/12 16:31:00 [notice] 9#9: OS: Linux 4.18.0-305.19.1.el8_4.x86_64
2024/06/12 16:31:00 [notice] 9#9: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/06/12 16:31:00 [notice] 9#9: start worker processes
2024/06/12 16:31:00 [notice] 9#9: start worker process 15
2024/06/12 16:31:02 [notice] 9#9: signal 17 (SIGCHLD) received from 12
2024/06/12 16:31:02 [notice] 9#9: unknown process 12 exited with code 0

Everything seems to work fine, but I don't know what that message means.
When I run the image on my local machine with docker, that notice does not appear.
Should I downplay it?

**Comment by yosifkit** [comment]
> 2024/06/12 16:31:02 [notice] 9#9: unknown process 12 exited with code 0

That sounds like another process was running in the container and exited. Did you `docker exec` something that ran to completion? `nginx` is PID 1 of the container, so it inherits any child processes in the PID namespace and is responsible for reaping processes to clean up "zombies" (i.e., acting on `SIGCHLD`).

**Comment by gastonborba** [comment]
I think you are right.
Searching in the /var/log folder I found the dynatrace/oneagent folder, then I realized that the openshift cluster has Dynatrace installed.
I suspect that notice is Dynatrace doing its thing.
Thank you very much for your help.
