### ISSUE TITLE
update this repository tags to match the container images

### ISSUE THREAD

**Issue by rgl** [nginxinc/docker-nginx#902]
Currently, the latest container image (at https://hub.docker.com/_/nginx/) is 1.27.0 (which seems to correspond to https://github.com/nginxinc/docker-nginx/blob/3180cdbec313dc4a9f6dd1109ae66adaf98f11fb/mainline/alpine/Dockerfile), but this repository does not have that tag, notice that the latest tag in this repository is 1.25.4, and not 1.27.0:

![image](https://github.com/nginxinc/docker-nginx/assets/43356/ed3c411b-59f6-4808-bada-f6c78253c371)

Without the tag here, it seems, we cannot easily cross-referencing things.

**Comment by thresheek** [comment]
Hi @rgl!

I've pushed the tags now -- thanks for prodding!
