### ISSUE TITLE
Adding custom modules is not successful

### ISSUE THREAD

**Issue by YJiangi** [nginxinc/docker-nginx#911]
I want to add nginx VTS module nginx mirror, this is what I use dockerfile address: https://raw.githubusercontent.com/nginxinc/docker-nginx/master/modules/Dockerfile, but I finished building After completion, I found that there was no module I wanted
<img width="1769" alt="image" src="https://github.com/user-attachments/assets/be0eaeaa-f1ad-472e-9f84-fc869a3db078">
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/2503876a-51f5-4118-8976-1a1ed7a53c8b">

**Comment by YJiangi** [comment]
docker build --build-arg ENABLED_MODULES="cachepurge" -t my-nginx-with-cachepurge:v3 .  This is the command I built

**Comment by thresheek** [comment]
Hi @YJiangi !

The module will be built as a package separate to the main nginx binary?  Check /etc/nginx/modules/ if it's there?

**Comment by YJiangi** [comment]
I don't see this module 
![image](https://github.com/user-attachments/assets/fbea0062-20a4-4b11-8235-3b205666506c)

**Comment by thresheek** [comment]
It should be there if the image build had succeeded.  Please provide the full log of a build, e.g.:

`docker build --progress=plain --build-arg ENABLED_MODULES="cachepurge" -t my-nginx-with-cachepurge:v3 .`

**Comment by YJiangi** [comment]
The my log :
root@iZt4nde2ikkc481bxuf6llZ:~/myapp-cache/my-nginx# docker build --progress=plain --build-arg ENABLED_MODULES="cachepurge" -t my-nginx-with-cachepurge:v5 .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 3.80kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/nginx:mainline
#2 DONE 0.9s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/4] FROM docker.io/library/nginx:mainline@sha256:6af79ae5de407283dcea8b00d5c37ace95441fd58a8b1d2aa1ed93f5511bb18c
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 177B done
#5 DONE 0.0s

#6 [3/4] COPY ./ /modules/
#6 CACHED

#7 [2/4] RUN if [ "cachepurge" = "" ]; then         echo "No additional modules enabled, exiting";         exit 1;     fi
#7 CACHED

#8 [4/4] RUN apt-get update     && apt-get install -y --no-install-suggests --no-install-recommends                 patch make wget mercurial devscripts debhelper dpkg-dev                 quilt lsb-release build-essential libxml2-utils xsltproc                 equivs git g++ libparse-recdescent-perl     && XSLSCRIPT_SHA512="f7194c5198daeab9b3b0c3aebf006922c7df1d345d454bd8474489ff2eb6b4bf8e2ffe442489a45d1aab80da6ecebe0097759a1e12cc26b5f0613d05b7c09ffa *stdin"     && wget -O /tmp/xslscript.pl https://hg.nginx.org/xslscript/raw-file/01dc9ba12e1b/xslscript.pl     && if [ "$(cat /tmp/xslscript.pl | openssl sha512 -r)" = "$XSLSCRIPT_SHA512" ]; then         echo "XSLScript checksum verification succeeded!";         chmod +x /tmp/xslscript.pl;         mv /tmp/xslscript.pl /usr/local/bin/;     else         echo "XSLScript checksum verification failed!";         exit 1;     fi     && hg clone -r ${NGINX_VERSION}-${PKG_RELEASE%%~*} https://hg.nginx.org/pkg-oss/     && cd pkg-oss     && mkdir /tmp/packages     && for module in $ENABLED_MODULES; do         echo "Building $module for nginx-$NGINX_VERSION";         if [ -d /modules/$module ]; then             echo "Building $module from user-supplied sources";             if [ ! -s /modules/$module/source ]; then                 echo "No source file for $module in modules/$module/source, exiting";                 exit 1;             fi;             if [ -f /modules/$module/build-deps ]; then                 echo "Installing $module build dependencies";                 apt-get update && apt-get install -y --no-install-suggests --no-install-recommends $(cat /modules/$module/build-deps | xargs);             fi;             if [ -x /modules/$module/prebuild ]; then                 echo "Running prebuild script for $module";                 /modules/$module/prebuild;             fi;             /pkg-oss/build_module.sh -v $NGINX_VERSION -f -y -o /tmp/packages -n $module $(cat /modules/$module/source);             BUILT_MODULES="$BUILT_MODULES $(echo $module | tr '[A-Z]' '[a-z]' | tr -d '[/_\-\.\t ]')";         elif make -C /pkg-oss/debian list | grep -P "^$module\s+\d" > /dev/null; then             echo "Building $module from pkg-oss sources";             cd /pkg-oss/debian;             make rules-module-$module BASE_VERSION=$NGINX_VERSION NGINX_VERSION=$NGINX_VERSION;             mk-build-deps --install --tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes" debuild-module-$module/nginx-$NGINX_VERSION/debian/control;             make module-$module BASE_VERSION=$NGINX_VERSION NGINX_VERSION=$NGINX_VERSION;             find ../../ -maxdepth 1 -mindepth 1 -type f -name "*.deb" -exec mv -v {} /tmp/packages/ \;;             BUILT_MODULES="$BUILT_MODULES $module";         else             echo "Don't know how to build $module module, exiting";             exit 1;         fi;     done     && echo "BUILT_MODULES=\"$BUILT_MODULES\"" > /tmp/packages/modules.env
#8 CACHED

#9 exporting to image
#9 exporting layers done
#9 writing image sha256:9d39dde8370564d8dc84489e4309fa445de2cd3479e9f38bd566d6673eccf6d4 done
#9 naming to docker.io/library/my-nginx-with-cachepurge:v5 done
#9 DONE 0.0s

**Comment by YJiangi** [comment]
This is my file:
![image](https://github.com/user-attachments/assets/24b2ad02-aaf1-4aaf-9db5-9457b198a43e)

**Comment by YJiangi** [comment]
我想我知道什么问题了,感谢你的指导,通过 --progress=plain 这个参数 我发现我需要在/etc/nginx/nginx.conf加载ngx_http_vhost_traffic_status_module.so模块,感谢
