### ISSUE TITLE
Remediate security vulnerabilities on bookworm

### ISSUE THREAD

**Issue by singularjacques** [nginxinc/docker-nginx#923]
Hi Guys,

We are currently running nginx on an AKS cluster using the bookworm-slim image. Our client is using a security scanner called Prisma and it has picked up a lot of vulnerabilites (CVE's) with the **mainline-bookworm** image. We also tried **latest** and version specific images to try and get the list down with no luck.

I can post the CVE numbers if needed.

Are there any plans to patch these before Trixie is released?

**Comment by oxpa** [comment]
@singularjacques you are, probably, using images built by Docker Inc for their https://github.com/docker-library/official-images/ .
Also, it is very common though for security scanners to ignore backported patches in packages. So I would suggest you to make sure debian didn't release fixes for mentioned CVEs and then raise a ticket with official-images repo.

Let me know if I can still help you anyhow.

**Comment by singularjacques** [comment]
Thanks for the response @oxpa, I have raised the issue with Docker and they referred me here. We are using images from here: https://hub.docker.com/_/nginx/

**Comment by oxpa** [comment]
Could you please share the issue you raised with Docker?
We don't really have control over official images (and you are using an official image) or debian provided software. If it's nginx what has a CVE - I can fix that. If that's 3-rd party software - I can only offer you "apt-get upgrade", sadly.

**Comment by thresheek** [comment]
> Are there any plans to patch these before Trixie is released?

The software packages with CVEs in question should be patched in Debian first, and then they will eventually propagate to our images.  There is no other way.
