### ISSUE TITLE
Nginx user unable to run entrypoint

### ISSUE THREAD

**Issue by RajeshwariSubramaniam** [nginxinc/docker-nginx#924]
### Describe the bug

We are extending the nginx:alpine image and attempting to run Nginx as the `nginx` user instead of the `root` user. However, we encounter a permission error when executing the entrypoint.
 
It appears that the home directory for the `nginx` user is set to `/var/cache/nginx`, but the `nginx` user lacks sufficient permissions to create folders within this directory.

![docker-nginx](https://github.com/user-attachments/assets/bbeb57bf-1e40-4c41-8084-b8f173f67eb9)

### To reproduce

1. Create a Dockerfile with the following content:
```
FROM nginx:1.27.1-alpine-slim
USER nginx
```
2. Build an image using the above Dockerfile.
3. Run a container from the created image
4. Observe the error.

### Expected behavior

Since the home directory for the `nginx` user is `/var/cache/nginx`, the user should have the necessary permissions to create folders within this directory.

### Your environment

- Version/release of Docker and method of installation (e.g. Docker Desktop / Docker Server) - `Docker version 26.1.4, build 5650f9b`
- Version/tag of the NGINX Docker image (e.g. `nginx:alpine`) - `nginx:1.27.1-alpine-slim`
- Target deployment platform (e.g. OpenShift / Kubernetes / Docker Compose / etc...) - N/A or Docker

**Comment by thresheek** [comment]
That's normal, please see/use https://github.com/nginxinc/docker-nginx-unprivileged/ for that task.

**Comment by RajeshwariSubramaniam** [comment]
I wasn't aware. 
Thanks for sharing!
