### ISSUE TITLE
cannot change website file

### ISSUE THREAD

**Issue by Petelin** [nginxinc/docker-nginx#93]
i do some thing like 
```
docker run -v /Users/zhangxiaolin/docker/nginx/website_files:/website_files  nginx

location / {
          root   /website_files;
           index  index.html index.htm;
      }
```

1. after i add some .html to my real machine(under  /Users/zhangxiaolin/docker/nginx/website_files),it works.i can see them from Chrome.

2. but when i change content of .html in /Users/zhangxiaolin/docker/nginx/website_files  , no matter how i stop,reload ,create new container , it do not update....

3. (if you `exec` it  ,you will find change in /website_files, but nginx just ignore them)

4. i have try remove old file and create a new same with name file.it works,modify content show in chrome.

so i cannot  just modify html in place?  that too bad.

**Comment by thresheek** [comment]
If that's under VirtualBox, see https://github.com/nginxinc/docker-nginx/issues/45.
