### ISSUE TITLE
libheif1:1.15.1-1 used includes fixable vulnerabilitites

### ISSUE THREAD

**Issue by cueoriginal** [nginxinc/docker-nginx#941]
Please update **libheif1:1.15.1-1** to at least **1.15.1-1+deb12u1**, as this will fix at least some of the known high and critical vulnerabilities.

Find attached the full vunerabilities scan.
[cvs.csv](https://github.com/user-attachments/files/17540890/cvs.csv)

**Comment by oxpa** [comment]
@cueoriginal images are build by Docker Inc themselves through official-images repository.
As the vulnerability itself is not in nginx - it will be fixed in due course as the fix is submitted into the base OS image.
