### ISSUE TITLE
Cannot upgrade from Nginx:1.27.1 to 1.27.3

### ISSUE THREAD

**Issue by stevenpopick** [nginxinc/docker-nginx#946]
### Describe the bug

Cannot upgrade to 1.27.3-perl as is shown on docker hub https://hub.docker.com/_/nginx

### To reproduce

1. Deploy the NGINX Docker image using `FROM nginx:1.27.3-perl AS base`
2. View output/logs/configuration on build logs
3. See error
`The content of stderr is 'failed to solve: nginx:1.27.3-perl: failed to resolve source metadata for docker.io/library/nginx:1.27.3-perl: docker.io/library/nginx:1.27.3-perl: not found`
### Expected behavior

I expect the container to build
### Your environment

- Version/release of Docker and method of installation (e.g. Docker Desktop / Docker Server) `Docker version 27.0.3, build 7d4bcd8`
- Version/tag of the NGINX Docker image (e.g. `nginx:alpine`) `nginx:1.27.3-perl`
- Target deployment platform (e.g. OpenShift / Kubernetes / Docker Compose / etc...)`Docker Compose`

**Comment by thresheek** [comment]
The images are still being built.  It takes some time for all architectures to get built & published.

**Comment by stevenpopick** [comment]
Ah I see, thank you.
