### ISSUE TITLE
docker -u support - run with another uid

### ISSUE THREAD

**Issue by Mahagon** [nginxinc/docker-nginx#95]
i tried to run the docker container with another uid:guid due to security reasons
but it seems that the script doesn't support this yet.

Would it be possible to add this feature? would bne awesome :)

Error i currently get by changing the uid with 

docker run --name webservice -P -u 2000:2000 -d nginx:alpine

2016/06/01 17:24:00 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2016/06/01 17:24:00 [emerg] 1#1: open() "/var/run/nginx.pid" failed (13: Permission denied)
nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied)

**Comment by thresheek** [comment]
It will work if you provide the proper configuration file.  You're already providing at least a vhost, so what stops you from that?

**Comment by thresheek** [comment]
Something like the following works fine:

nginx.conf:

```

worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    client_body_temp_path /tmp/client_body_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;
    server {
	listen 8080;
	location / {
	    return 200 'OK\n';
	}
}
}
```

```
# docker run -P -u 2000:2000 -d -v /root/user/nginx.conf:/etc/nginx/nginx.conf nginx:latest
```

```
root@deb8-docker-ipv6:~/user# ps axwu | grep nginx
2000      5280  0.0  0.4  23176  4272 ?        Ss   16:51   0:00 nginx: master process nginx -g daemon off;
2000      5294  0.0  0.2  23632  2400 ?        S    16:51   0:00 nginx: worker process
```

**Comment by Mahagon** [comment]
seems to work :) thanks a lot
