### ISSUE TITLE
The docker image configuration does not use include /etc/nginx/sites-enabled/*

### ISSUE THREAD

**Issue by oleersoy** [nginxinc/docker-nginx#96]
That causes surprises like this one:
http://unix.stackexchange.com/questions/287030/running-nginx-as-a-reverse-proxy-on-docker

**Comment by thresheek** [comment]
It uses conf.d, which is essentially the same and is documented on https://hub.docker.com/_/nginx/.

**Comment by oleersoy** [comment]
Yes but the issue is that it is not symmetric with other installations.  Ideally we would not have to read documentation twice to perform administration and installations.

**Comment by thresheek** [comment]
The configuration cannot be symmetric to everything in the world.  It needs to be precise.

**Comment by oleersoy** [comment]
I agree with you ... especially WRT the whole world :).  But ideally symmetry is maintained across different installation methods unless there is a really good reason to deviate.
