### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by jalberto** [nginxinc/docker-nginx#99]
Will be great to have an official image for ARM.

Using scaleway/alpine as base image works out of the box

**Comment by thresheek** [comment]
Will not arrive until there is an official support for multiple arches in docker/docker-registry.

**Comment by jalberto** [comment]
@thresheek there is kind of support, just need to create a different tag (that is what other images do)

**Comment by thresheek** [comment]
I don't see arm tags in https://github.com/docker-library/official-images/blob/master/library/debian 

Can you point me to the examples please?

**Comment by md5** [comment]
@thresheek There are no ARM tags for any official images. See here for information about the experimental base images: https://github.com/docker-library/official-images#architectures-other-than-amd64

Since there is a policy of not allowing official images to derive from unofficial images, it's not currently possible to have ARM tags for `nginx` itself, though it would be possible to have them under an `nginxinc/*` namespace or somewhere else.

**Comment by jalberto** [comment]
@md5 is right, non-official images are using arm tags, officilaimages are not using it

**Comment by nsteinmetz** [comment]
It"s quite easy to build them, especially for alpine version.

Just replace:

```
FROM alpine:3.4
```

by

```
FROM armhf/alpine:3.4
```

And you're done :)

**Comment by thresheek** [comment]
Please re-open when/if there are official arm-based images for the distributions we use.

**Comment by nagromc** [comment]
Please reopen the issue.

Docker released [official images for ARM architectures](https://github.com/docker-library/official-images#architectures-other-than-amd64), especially [arm32v6/alpine](https://hub.docker.com/r/arm32v6/alpine/) and [arm64v8/alpine](https://hub.docker.com/r/arm64v8/alpine/) where ARMv6 is the architecture used on the Raspberry Pi 1, and the ARMv8 on the Raspberry Pi 3.

I am sure other architectures will be supported soon as the ARM repos have been created in May 2017, so it is just a beginning.

**Comment by nagromc** [comment]
> Please reopen the issue.

Ping?

**Comment by DanielRamosAcosta** [comment]
I would also love this.

**Comment by nsteinmetz** [comment]
Have a look at the "Supported architecture" of https://hub.docker.com/_/nginx/ -> arm is supported for some months now.

**Comment by DanielRamosAcosta** [comment]
Oh I see, thanks!
